# -*- coding: utf-8 -*-
# Албанская адаптация лендинга травника. Форм-фактор — ГЕЛЬ (в источнике тоже гель).
# Живојин Поповић -> Selim Doda (Gjyshi Selim), 102, bimëtar, fshat pranë Tiranës
# Драган Поповић  -> Arben Doda | Београд -> Tirana | динар -> lekë

AL = {
0: "Selim Doda, bimëtar 102-vjeçar nga fshatrat pranë Tiranës, zbulon formulën për rikuperimin e plotë të nyjeve — një metodë e arritshme për çdo qytetar shqiptar",
1: "NË MOSHËN 102-VJEÇARE, AI ËSHTË BIMËTARI MË I VJETËR NË SHQIPËRI DHE I VETMI NGA BREZI I TIJ QË ECËN PA SHKOP. PËR HERË TË PARË ZBULON FORMULËN QË PËR 40 VJET UA DHA VETËM ATYRE QË VINIT TEK AI.",
2: "Publikuar:",
3: "„Si ia doli Gjyshi Selim Doda, bimëtar nga fshatrat pranë Tiranës, t'i ruajë nyjet e tij në gjendje të përsosur deri në moshën 102-vjeçare, ndërkohë që të gjithë bashkëmoshatarët e tij prej kohësh nuk ecin dot?“",
4: "Në një fshat jo larg Tiranës jeton një njeri që përgënjeshtron gjithçka që dimë për plakjen. Në moshën 102-vjeçare, bimëtari Selim Doda çdo mëngjes ecën nëpër shtigjet mbi fshat, ngjit shkallët pa ndihmë dhe nuk ka përdorur kurrë në jetën e tij një shkop. Bashkëmoshatarët e tij prej kohësh nuk janë më ndër të gjallët ose janë të lidhur pas karriges me rrota — kurse ai edhe sot ngjitet vetëm në kodër për bimë.",
5: "Deri vitin e kaluar, Gjyshi Selim priste njerëz në shtëpinë e tij, në dhomën e vjetër ku prej dhjetëra vjetësh than bimët. Mbi 70 vjet punë me bimët, mbi 40.000 njerëz, dhjetëra shtylla kurrizore dhe gjunjë të kthyer në jetë, të cilat mjekët i kishin shkruar të humbura. Ekzistonte një listë pritjeje gjashtëmujore — vinin njerëz nga i gjithë vendi për ta parë.",
6: "Por misteri i vërtetë nuk janë ata që vinin tek ai. Misteri i vërtetë është ai vetë. Në moshën 102-vjeçare — as artrit, as artrozë, as hernie diskale. Radiografitë e nyjeve të tij duken si të një burri 45-vjeçar. Mjekët që e ekzaminojnë thjesht nuk u besojnë syve të tyre.",
7: "Për dhjetëra vjet e mbajti recetën e tij të fshehtë — e përgatiste vetë, në dhomën e tij, dhe nuk e bëri kurrë publike. Por sot, kur shëndeti nuk i lejon më të presë njerëz personalisht, Gjyshi Selim mori një vendim që ndryshoi gjithçka: ta bëjë formulën e tij të arritshme për çdo qytetar shqiptar.",
8: "Gjyshi Selim Doda: „Gjithë jetën kam parë se si njerëzit plaken para kohe — jo sepse trupi u është i dobët, por sepse askush nuk u ka thënë se si t'i aktivizojnë mekanizmat e tyre të rigjenerimit. Në moshën 102-vjeçare jam dëshmia e gjallë se",
9: "nyjet mund të mbeten të shëndetshme deri në pleqëri të thellë, nëse di si t'i „zgjosh“ qelizat që i ndërtojnë.",
10: "QËLLIMI IM KA QENË GJITHMONË VETËM NJË — TA NDIHMOJ TRUPIN TË PRODHOJË IND TË RI KËRCOR DHE KOCKOR, TAMAM SI NË RINI. TANI DJALI IM ARBEN E KA KTHYER GJITHË KËTË NË NJË PRODUKT",
11: "QË MUND TË MBËRRIJË NË ÇDO SHTËPI NË SHQIPËRI.",
13: "Arben Doda — djali i bimëtarit — u rrit mes bimëve të thara dhe peshoreve të babait të tij dhe e mësoi zanatin që në fëmijëri. Ai nuk u bë mjek. Për vite me radhë e bindi babanë që receta të mos mbetej e mbyllur në një shtëpi të vetme, e më pas gjeti vetë një laborator dhe njerëz që ndihmuan që përvoja dhjetëravjeçare e Gjyshit Selim të kthehej në një produkt të arritshëm për këdo — që të mbërrijë tek të gjithë ata që kanë nevojë për të.",
14: "Rezultati i këtij bashkëpunimi i tejkaloi të gjitha pritshmëritë. Por para se t'ju tregoj për produktin, le të shohim pse gjithçka që dini për trajtimin e nyjeve është, me shumë gjasë, e gabuar.",
15: "Gënjeshtra në të cilën beson gjithë Shqipëria:",
16: "„Qetësuesit e dhimbjes i shërojnë nyjet“ — GABIM, ata i shkatërrojnë edhe më shpejt!",
17: "Gjyshi Selim Doda:",
18: "— Prej shtatëdhjetë vjetësh trajtoj njerëz dhe do t'ju them diçka që farmacitë nuk do ta pranojnë kurrë: asnjë qetësues dhimbjeje në historinë e mjekësisë nuk ka rigjeneruar as edhe një milimetër kërc. Asnjë i vetëm! Ata e mbytin dhimbjen, por ndërkohë kërci vazhdon të shpërbëhet — thjesht ju nuk e ndieni më. Dhe kur ta ndieni sërish, do të jetë tepër vonë.",
19: "Por kjo nuk është më e keqja. Më e keqja është ajo që këto substanca kimike u bëjnë organeve tuaja të brendshme. Në 70 vjet punë kam parë qindra njerëz me mëlçi dhe veshka krejtësisht të shkatërruara — jo nga sëmundja, por nga barnat! Trupi nuk është krijuar të gëlltisë kimikate për dhjetëra vjet. E megjithatë pikërisht këtë „përshkruan“ mjekësia konvencionale.",
20: "Shtylla kurrizore është veçanërisht e cenueshme. Disqet ndërmjet rruazave nuk kanë qarkullim gjaku të vetin — ushqehen me difuzion, që do të thotë se dëmtimi i tyre ndodh në heshtje, pa dhimbje, ndonjëherë me vite. Kur dhimbja më në fund shfaqet, dëmtimi është tashmë i përparuar. Presioni mbi nerv nga hernia diskale e kthen jetën në makth: fillon me një mpirje të lehtë në këmbë dhe përfundon me humbjen e plotë të lëvizshmërisë.",
21: "Shikoni çfarë tregon kjo radiografi. Një grua, vetëm 39 vjeçe, mësuese — kurse shtylla e saj kurrizore është në një gjendje që para 20 vjetësh e shihja vetëm te njerëz 70-vjeçarë. Të ndenjurit në karrige 8 orë në ditë, mungesa e lëvizjes dhe mosnjohja e plotë e trupit të vet — ja çfarë sjell mënyra moderne e jetesës.",
22: "Një pamje nga arkivi që Gjyshi Selim e ruan prej dhjetëra vjetësh: shtylla kurrizore e një mësueseje 39-vjeçare nga Elbasani. Erdhi me „një lodhje të lehtë në mes“ — radiografia zbuloi tre disqe të dëmtuara, një hernie fillestare dhe mikroçarje në mbështjellësin kërcor.",
23: "Nëse ndieni dhimbje, ngurtësim ose kërcitje në nyje pas moshës 40-vjeçare — kërci juaj tashmë po shpërbëhet. Kjo nuk është „nga lodhja“ dhe nuk është „normale“.",
24: "Te shtylla kurrizore procesi është disa herë më i shpejtë dhe më tinëzar — dhimbja shfaqet vetëm atëherë kur dëmtimi është tashmë kritik!",
25: "Gjyshi Selim Doda:",
26: "— Dua të jem krejtësisht i drejtpërdrejtë. Njoh njerëz që e shtynë me muaj. Rezultati? Një nerv i shtypur që nuk funksionoi më kurrë normalisht. Rigjenerimi i disqeve kur nervi tashmë ka vdekur është i kotë —",
27: "DISKU MUND TË KTHEHET, POR NERVI — JO!",
28: "E atëherë çfarë mbetet? SHKOP, KARRIGE ME ROTA DHE VARËSI NGA NDIHMA E TË TJERËVE DERI NË FUND TË JETËS!",
29: "E çfarë ofron kirurgjia moderne? Operacione të shtrenjta dhe të rrezikshme me implante metalike. Kam parë personalisht qindra njerëz që pas operacionit të shtyllës kurrizore ndiheshin MË KEQ se më parë.",
30: "INFEKSIONE, NGJITJE TË DËSHTUARA, DHIMBJE KRONIKE DHE, NË FUND — NJË OPERACION I RI. E NDONJËHERË — DËMTIME TË PAKTHYESHME!",
31: "Gjyshi Selim tregon një pamje që ia solli një burrë pas operacionit me vida metalike: „Ky është rezultati tipik — implanti nuk u prit siç duhet, indet përreth janë të inflamuara, kurse dhimbja është më e fortë se para operacionit. Kam parë qindra raste të ngjashme.“",
32: "Statistika është e pamëshirshme: te 60% e të operuarve, hernia kthehet brenda 2–4 vjetësh. E çmimi? Muaj palëvizshmërie, qindra mijëra lekë dhe një pasiguri e plotë. Shumë veta e pranojnë: po të mund ta kthenin kohën pas, nuk do të shtriheshin kurrë në tryezën e operacionit.",
33: "Këto simptoma do të thonë se kërci juaj tashmë po vdes! E nëse jeni mbi 40–50 vjeç — procesi është i pakthyeshëm pa ndërhyrje!",
34: "— Për 70 vjet nëpër duart e mia kanë kaluar mbi 40.000 njerëz dhe mund të them këtë: çdo dhimbje e shpërfillur në nyje është një hap drejt karriges me rrota. Vetëm në",
35: " në Shqipëri janë regjistruar mbi 125.000 raste të reja sëmundjesh të rënda të nyjeve — nga të cilat 23.000 te persona të moshës 38 deri 48 vjeç. Ky nuk është problem i pleqërisë. Ky është problem i mosveprimit.",
36: "Nëse organizmi juaj ju ka dhënë tashmë ndonjë prej këtyre sinjaleve — mos prisni asnjë ditë të vetme!",
37: "Ja lista që ia thoshja çdo njeriu qysh në prag:",
38: "Ngurtësim i mëngjesit që nuk kalon me lëvizjen;",
39: "Kërcitje, krisje ose çjerrje gjatë lëvizjes;",
40: "Forcim i dhimbjes me ndryshimin e motit;",
41: "Vështirësi në përkuljen ose drejtimin e gjunjëve;",
42: "Ënjtje, skuqje ose nxehtësi rreth nyjes;",
43: "Dhimbje gjatë ngjitjes ose zbritjes së shkallëve;",
44: "Lodhje kronike dhe rëndim në këmbë;",
45: "Dhimbje në mes që „shkrep“ drejt kofshës ose shputës;",
46: "Ngurtësim ose therje në gishta;",
47: "Ndryshim i të ecurit — çalim, paqëndrueshmëri;",
48: "Pamundësi për të qëndruar në këmbë më shumë se 10–15 minuta;",
49: "Nëse e njihni veten qoftë edhe në dy prej këtyre simptomave — kërci juaj tashmë po shkatërrohet. Kurse te shtylla kurrizore procesi është tre deri katër herë më i shpejtë, sepse disqet ndërmjet rruazave janë nën presion të vazhdueshëm.",
50: "REZULTATI: HERNIE, NERV I SHTYPUR, DEFORMIM I RRUAZAVE, HUMBJE E LËVIZSHMËRISË — DHE E GJITHË KJO MUND TË NDODHË BRENDA DISA JAVËSH!",
51: "Mos e shtyni, sepse organizmi nuk ju jep shanse pa fund!",
52: "Shikoni këta njerëz më poshtë. Secili prej tyre ka pasur po ato simptoma që ndoshta i ndieni edhe ju në këtë çast. Secili tha „do të kalojë“. Dhe secili sot do të jepte gjithçka që ta kthente kohën pas dhe të vepronte atëherë kur ende kishte një shans.",
53: "Ish-paciente e një klinike tjetër, 58 vjeçe, Shkodër. Tre rruaza të zhvendosura mbi 8 mm, palca kurrizore nën presion. Dy herë refuzoi të shkonte te Gjyshi Selim — kur më në fund erdhi, ishte një hap larg paralizës.",
54: "Grua 61-vjeçare nga Vlora — gunga i është rritur në 4 cm brenda më pak se një viti. Rruazat e qafës janë deformuar deri në atë pikë sa koka nuk kthehet më anash. Qetësuesit e dhimbjes pushuan së vepruari para 8 muajsh.",
55: "Amvise, 59 vjeçe, Korçë. Nyjet e gjunjëve i janë konsumuar aq shumë sa kërci është hollur nën 1 mm. Çdo hap tingëllon si kërcitja e një dere të vjetër. Tre ortopedë i thanë se zgjidhja e vetme është një protezë e dyfishtë, për mbi 600.000 lekë.",
56: "Ish-minator, 68 vjeç, Bulqizë. Kërci në gjurin e djathtë është shkatërruar krejtësisht, indi kockor ka hyrë në fazën e nekrozës. Shtyrja prej 4 muajsh i kushtoi gjymtyrën — amputim mbi gju dhe varësi e përjetshme nga karrigia me rrota.",
57: "Gjyshi Selim Doda:",
58: "Jam 102 vjeç dhe mund t'ju them nga përvoja ime personale: organizmi është i aftë të rigjenerohet vetë në ÇDO moshë — me kusht që të dini SI ta aktivizoni. Pikërisht kësaj ia kushtova jetën.",
59: "E NËSE JENI TASHMË MBI 50–60 VJEÇ, MOS PRISNI ASNJË SEKONDË!",
60: "Tek ju dëmtimi ka hyrë pothuajse me siguri në fazën kritike — urgjentisht duhet ta ndalni shkatërrimin dhe të aktivizoni rigjenerimin e kërcit të ri, të kockave të reja dhe të indeve të reja!",
61: "Raste që mjekët i kishin shpallur të pashpresa!",
62: "Drande Marku, në moshën 86-vjeçare, ecën sërish pa ndihmë, pasi tre spitale e refuzuan. Ja historia e saj…",
63: "Drande Marku nga Lezha vuante nga artroza e rëndë e gjunjëve dhe nga hernie të shumta diskale. Tre spitale të ndryshme e refuzuan — kudo i thoshin të njëjtën gjë: „Në këtë moshë nuk mund të bëhet më asgjë.“ E bija dëgjoi rastësisht për Gjyshin Selim nga një i njohur prej një fshati jo larg Tiranës dhe vendosi ta kërkonte.",
64: "„Jetoja si në burg — shtëpia ime u bë qelia ime. Nuk arrija dot deri te banjoja, nuk qëndroja dot në këmbë më shumë se një minutë, nuk bëja dot vetë një çaj. Fëmijët punonin dhe nuk vinin dot çdo ditë. Rrija shtrirë dhe shikoja tavanin. Mjekët thanë se nuk ka kuptim operacioni në këtë moshë dhe më dhanë vetëm qetësues dhimbjeje.",
65: "Kur ime bijë më çoi te Gjyshi Selim, ai më pa dhe më tha diçka që asnjë mjek nuk ma kishte thënë: „Zonja Drande, trupi juaj NUK ka pushuar së luftuari. Thjesht askush nuk e ka ndihmuar.“ Më dha atë që përgatit vetë dhe më tha të kem durim. Në javën e tretë, për herë të parë pas një viti e gjysmë, U NGRITA VETË nga shtrati!",
66: "Sot, pesë muaj më vonë, shkoj në dyqan, gatuaj, madje kujdesem edhe për lulishten para pallatit. Në moshën 86-vjeçare! Kur më panë fqinjët në oborr, nuk u besuan syve. Mendonin se nuk do të më shihnin më. Gjyshi Selim ma ktheu jetën — dhe nuk kam fjalë me të cilat t'i falënderohem.“",
67: "Drande Marku, 86 vjeçe, Lezhë",
68: "Një rast tjetër i jashtëzakonshëm është Agron Sula — punëtor ndërtimi 47-vjeçar nga Fieri, i cili pas 20 vjetësh pune të rëndë fizike pësoi një dëmtim të rëndë të shtyllës kurrizore dhe u detyrua të lëvizte me karrige me rrota.",
69: "Agroni provoi metodën e Gjyshit Selim, kurse rezultatet tronditën edhe mjekun e tij të familjes.",
70: "SHTYLLA E TIJ KURRIZORE FILLOI TË RIKUPEROHEJ, DHIMBJA U ZHDUK KRYESISHT, DHE MË E PABESUESHMJA —",
71: "E LA KARRIGEN ME RROTA VETËM PAS 4 JAVËSH!",
72: "Agroni na tregoi:",
73: "„Njëzet vjet ndërtova pallate, por nuk u kujdesa për shtyllën time kurrizore. Një mëngjes u zgjova dhe nuk lëvizja dot mesin. Gruaja thirri urgjencën. Diagnoza — tre hernie dhe presion mbi rrënjën nervore. Mjekët propozuan një operacion prej 350.000 lekësh, por pa garanci.",
74: "Me muaj rrija në shtëpi në karrige me rrota. Fëmijët më shikonin me trishtim, gruaja qante çdo mbrëmje. Ndihesha si barrë. Doja të zhdukesha…",
75: "Atëherë vjehrri im dëgjoi për Gjyshin Selim nga një njeri të cilit i kishte ndihmuar. U lajmërova, dërgova radiografitë dhe plaku tha: „Nuk është vonë.“ Ato tri fjalë më dhanë më shumë shpresë se gjithçka që kisha dëgjuar nga dhjetëra mjekë.",
76: "Ditën e katërt tashmë mund të qëndroja në këmbë. Kursi i plotë zgjati 80 ditë. Sot punoj sërish — jo në kantier, por në zyrë, por ECI. Vrapoj me fëmijët në park. Jetoj. Radiografia tregon se disqet e mia janë rikuperuar 90%. Gjyshi Selim është i vetmi që nuk më refuzoi — dhe i vetmi që më ndihmoi.“",
77: "Historitë e mijëra njerëzve të cilëve u ka ndihmuar Gjyshi Selim janë po aq mahnitëse: njerëz të cilëve mjekët u thoshin „mësohuni me dhimbjen“ ecën sërish, vrapuan sërish, jetuan sërish. Si është e mundur kjo?",
78: "Formula që Gjyshi Selim e përgatiti me duart e tij për më shumë se 40 vjet!",
79: "Sekreti i metodës „Riaktivizimi endogjen i indeve“ — si fillon organizmi vetë të prodhojë kërc të ri, kocka të reja dhe ligamente të reja!",
80: "Gjyshi Selim Doda:",
81: "— Më lejoni t'ju shpjegoj diçka që mjekësia konvencionale nuk pranon ta njohë. Organizmi i çdo njeriu — qoftë edhe i një 90-vjeçari — zotëron qeliza rigjeneruese „të fjetura“. Po ato qeliza që në rini ju ndërtonin lehtësisht kërc, kocka dhe ligamente. Me vitet, ato nuk vdesin — thjesht „bien në gjumë“, sepse organizmi pushon së dërguari atyre sinjalet e duhura.",
82: "Para 40 vjetësh zbulova se një kombinim i caktuar substancash natyrore — në përmasa rreptësisht të përcaktuara — vepron si „çelës ndezjeje“ për këto qeliza të fjetura. Metodën e quajta",
83: "„Riaktivizimi endogjen i indeve“",
84: "— sepse nuk fut asgjë artificiale, por aktivizon burimet e vetë organizmit. Pikërisht prandaj tek unë NUK ka efekte anësore, NUK ka dëmtim organesh dhe NUK ka varësi.",
85: "Katër dekada e zbatova këtë metodë te secili që më trokiste në prag — dhe te secili shënova të njëjtin rezultat: ndalimin e shkatërrimit, uljen e dhimbjes dhe kthimin gradual të funksionit të nyjeve. Qindra njerëz, që vinin tek unë „si shansi i fundit“, largoheshin nga shtëpia ime në këmbët e tyre.",
86: "Vetë formula nuk është e ndërlikuar — por saktësia është gjithçka. Çdo përbërës duhet të jetë në sasi të përpiktë, deri në të qindtën e miligramit. Nëse përmasat nuk respektohen, efekti thjesht zhduket. Pikërisht prandaj për dhjetëra vjet e zbatova metodën personalisht — sepse nuk mund t'ua besoja farmacive.",
87: "Përbërja e xhelit sipas recetës së bimëtarit Doda (substanca aktive për dozë):",
88: "Omega-3",
89: "farë liri: 4500 mg",
90: "Glukozaminë sulfat",
91: "guaskorë: 1100 mg",
92: "Citrat magnezi",
93: "alga deti: 390 mg",
94: "Gingerol",
95: "xhenxhefil: ekstrakt 4200 mg",
96: "AKBA",
97: "rrëshirë temjani (Boswellia): ekstrakt 1100 mg",
98: "Silic",
99: "bishtdhelpra: ekstrakt 320 mg",
100: "Kurkuminë",
101: "shafran i Indisë: ekstrakt 2300 mg",
102: "Këta përbërës duken të thjeshtë, por gjetja e tyre në cilësinë e duhur dhe nga burimi i duhur është jashtëzakonisht e vështirë. Shumica nuk gjenden në farmaci dhe duhen sjellë nga pjesë të ndryshme të botës. Kurse përzierja në shtëpi është praktikisht e pamundur — sepse dozimi duhet të jetë i saktë deri në 0,1 mg.",
103: "Pikërisht prandaj për dhjetëra vjet e përgatita përzierjen personalisht, për secilin njeri veç e veç. Por djali im Arben e pa gjithë pamjen.",
104: "Si e ktheu Arben Doda recetën 40-vjeçare të babait të tij në një xhel të arritshëm për këdo — Nautubone",
105: "Arben Doda:",
106: "— U rrita në dhomën me bimë të babait tim. Çdo ditë shikoja si njerëzit hynin të përkulur nga dhimbja — dhe dilnin duke buzëqeshur. Në moshën 14-vjeçare e dija recetën përmendsh. Unë nuk u bëra mjek — zanatin e mësova prej tij. Por për vite me radhë e binda: baba, kjo recetë nuk duhet të mbetet e mbyllur në një shtëpi të vetme. Mijëra njerëz presin atë që ti e mban në raft.",
107: "Pesë vjet vizitova laboratorë në Tiranë dhe në Mynih derisa gjeta njerëz që donin ta studionin seriozisht recepturën e babait tim. Përgjigjja që mora më entuziazmoi: kombinimi i këtyre përbërësve në përmasa të sakta aktivizon prodhimin e kolagjenit të tipit II dhe të proteoglikaneve — dy elementet kryesore ndërtuese të kërcit. Me fjalë të tjera: organizmi fjalë për fjalë „e kujton“ si të ndërtojë kërc të ri, thjesht i duhet sinjali i duhur.",
108: "Së bashku me laboratorin zhvilluam një procedurë që e quajtëm",
109: "„Teknologjia e nanodifuzionit me biodisponibilitet të avancuar“",
110: "— një metodë me të cilën substancat aktive mbyllen në nanogrimca të veçanta që depërtojnë thellë përmes lëkurës dhe mbërrijnë drejtpërdrejt te indi i dëmtuar i nyjes. Kjo rrit thithjen me rreth 380% krahasuar me xhelet dhe pomadat e zakonshme. Produktin e quajta",
111: "Nautubone",
112: "— një xhel që lyhet mbi lëkurë dhe vepron pikërisht atje ku është e nevojshme. E quajta kështu për nder të babait tim dhe të 40 vjetëve të punës së tij.",
113: "Xheli Nautubone përmban të shtatë përbërësit nga receta origjinale e babait tim, plus 29 ekstrakte dhe vitamina shtesë që i shtuam pas testeve laboratorike në Mynih. Rezultati është një xhel që funksionon PIKËRISHT AQ MIRË sa ajo që përgatiste babai im me duart e veta — por që mund të dërgohet në çdo shtëpi në Shqipëri. Lyeni nyjet dy herë në ditë, kurse substancat aktive depërtojnë përmes lëkurës drejtpërdrejt te nyjet e prekura.",
114: "„Nautubone është trashëgimia e babait tim — 40 vjet përvojë e tij, të mbyllura në një formulë të vetme. Çdo përbërës është zgjedhur me saktësinë me të cilën ai i afrohej çdo njeriu që i trokiste në derë. Ky nuk është produkt masiv nga farmacia — ky është vepra e një jete të tërë kushtuar shërimit.“",
115: "Gjëja më e pabesueshme te Nautubone është se ai jo vetëm e lehtëson dhimbjen — por aktivizon mekanizmin e rigjenerimit që ka rënë në gjumë me vitet. Xheli lyhet mbi lëkurë, kurse nanogrimcat i çojnë substancat aktive thellë në indin e nyjes — atje ku hapat dhe injeksionet e zakonshme nuk mbërrijnë kurrë. Sinergjia mes përbërësve e forcon efektin deri në 20 herë krahasuar me marrjen e tyre veç e veç.",
116: "Katër fazat e rikuperimit me Nautubone — çfarë ndodh në organizmin tuaj hap pas hapi",
117: "Gjyshi Selim Doda:",
118: "— Gjatë gjithë jetës sime si bimëtar kam parë se si njerëzit kalojnë nëpër të njëjtat katër faza. Djali im i dokumentoi dhe i ndërtoi brenda Nautubone-s, në mënyrë që secili të mund t'i kalojë në shtëpi.",
119: "Katër fazat e „Riaktivizimit endogjen të indeve“:",
120: "Faza 1 — Ndalimi i dhimbjes dhe i inflamacionit:",
121: "Qysh nga lyerja e parë e xhelit, nanogrimcat i çojnë substancat aktive përmes lëkurës drejtpërdrejt në indet e dëmtuara, duke bllokuar molekulat inflamatore. Dhimbja zvogëlohet dukshëm brenda 24–48 orësh — pa ngarkuar mëlçinë dhe veshkat, sepse xheli përdor teknologjinë e thithjes së drejtuar përmes lëkurës dhe nuk kalon nëpër metabolizmin tradicional të mëlçisë.",
122: "Faza 2 — Ndalimi i shkatërrimit:",
123: "Mes ditës së tretë dhe të shtatë, organizmi pushon së shpërbëri indin kërcor dhe kockor. Rritet prodhimi i lëngut sinovial — „lubrifikantit“ natyror të nyjeve. Fërkimi zvogëlohet dhe lëvizjet bëhen më të lehta.",
124: "Faza 3 — Zgjimi i qelizave rigjeneruese:",
125: "Kjo është zemra e metodës. Kondrocitet dhe osteoblastet „e fjetura“ marrin një sinjal biokimik dhe fillojnë të prodhojnë kërc të ri dhe ind kockor. Pikërisht kjo fazë e bën Nautubone unik — asnjë produkt tjetër nuk e aktivizon këtë mekanizëm.",
126: "Faza 4 — Barrierë mbrojtëse e qëndrueshme:",
127: "Pas 30–60 ditësh, indet e sapoformuara krijojnë një shtresë të fortë mbrojtëse, çka i bën nyjet rezistente edhe ndaj ngarkesës. Gjyshi Selim e quan këtë „imunitet i nyjeve“ — sapo arrihet, efekti ruhet me vite.",
128: "Secila prej këtyre fazave është rezultat i 40 vjetëve përvojë të një njeriu të vetëm dhe i 5 vjetëve testesh laboratorike. Nautubone nuk ofron një „maskim“ të shpejtë të dhimbjes — por nis një proces të thellë biologjik rigjenerimi, që i kthen nyjet në gjendjen në të cilën ishin para dhjetëra vjetësh.",
129: "Rezultate që befasuan komunitetin mjekësor — ndjekja e 2.340 njerëzve të moshës 38 deri 89 vjeç",
130: "Arben Doda:",
131: "— Kur publikuam rezultatet e para të testeve laboratorike, reagimi ishte i rrufeshëm. Klinika universitare nga Tirana, Berlini dhe Vjena kërkuan të kryenin hulumtimet e tyre. Rezultatet te njerëz realë i tejkaluan edhe pritshmëritë tona — asnjë prej metodave ekzistuese të trajtimit nuk u afrohet këtyre treguesve.",
132: "Njerëz që ishin caktuar për vendosjen e një proteze nyjeje i anuluan operacionet. Njerëz që me muaj nuk ngriheshin nga shtrati ecën sërish. Ortopedët nuk u besonin radiografive të tyre.",
133: "Rezultatet e ndjekjes së „Nautubone“ te 2.340 njerëz të moshës 38 deri 89 vjeç",
134: "Heqja e plotë e dhimbjes dhe e inflamacionit",
136: "Kthimi i vëllimit të plotë të lëvizjes",
138: "Tendinit, bursit, periartrit",
140: "Ndalimi dhe tërheqja e ndryshimeve degjeneruese",
142: "Sinovit, ligamentit",
144: "Osteoartrit (të gjitha stadet)",
146: "Osteoporozë",
148: "Artrit reumatoid, përdhes",
150: "Artrozë, spondiloartrit",
152: "Rigjenerim i dokumentuar i indit kërcor",
154: "Afatet e sakta të rikuperimit me „Nautubone“:",
155: "Ekipe të tjera shkencore në Evropë përpiqen ta riprodhojnë formulën tonë, por rezultatet e deritanishme janë larg tonave. Teknologjia e nanodifuzionit me biodisponibilitet të avancuar, e zhvilluar bashkë me laboratorin tonë, ende nuk mund të përsëritet — pikërisht ajo i mundëson xhelit t'i çojë përbërësit drejtpërdrejt në nyje përmes lëkurës, në vend që thjesht të mbeten në sipërfaqen e lëkurës.",
156: "Sa zgjat rikuperimi i plotë? Gjyshi Selim shpjegon në bazë të 70 vjetëve përvojë",
157: "Gjyshi Selim Doda:",
158: "— Kursi minimal që rekomandoj është 30 ditë. Te dëmtimet më të rënda — 60, e ndonjëherë edhe 90 ditë. Por në gjithë karrierën time NUK KAM PASUR ASNJË RAST TË VETËM në të cilin metoda të mos jepte rezultat. Asnjë të vetëm. E kam trajtuar njerëz 85, 90, madje edhe 94 vjeç.",
159: "Nautubone jo vetëm e ndal dhimbjen — nis një proces rigjenerimi të thellë biologjik. Lyeni xhelin dy herë në ditë dhe qysh në orët e para do të ndieni lehtësim. Brenda një jave do të vini re se lëvizni më lehtë. Kurse pas kursit të plotë, nyjet tuaja do të jenë në gjendjen në të cilën ishin para 20–30 vjetësh.",
160: "Por më e çmuara është diçka tjetër: efekti është I QËNDRUESHËM. Sapo „zgjohen“, qelizat rigjeneruese vazhdojnë të punojnë me vite!",
161: "Falë „Nautubone“, mbi 19.000 njerëz në Shqipëri e kanë rifituar lëvizshmërinë e tyre. Ja vetëm një pjesë e vogël e atyre që i ndihmoi Gjyshi Selim:",
162: "Pensioniste, 66 vjeçe, Durrës. Katër rruaza të zhvendosura dhe radikulopati kronike. I biri ia sillte xhelin Nautubone nga Tirana. Dy muaj lyerje — kthim i plotë i shtyllës kurrizore në pozicion normal. Ortopedi i saj kërkoi emrin e produktit.",
163: "Kontabiliste, 41 vjeçe, Berat. Gjunjët i ishin deformuar nga brenda pas dy shtatzënive dhe shtimit në peshë. Ortopedi i tha „mësohuni“. Me xhelin Nautubone — 30 ditë lyerje, dy herë në ditë — boshti i gjunjëve u drejtua dukshëm në radiografi.",
164: "Pensionist, 73 vjeç, Gjirokastër. Artroza i kishte deformuar gishtat e këmbëve deri në atë pikë sa nuk vishte dot asnjë palë këpucë. E lyente xhelin Nautubone çdo ditë — brenda 21 ditësh gishtat u drejtuan, kurse këpucët e para 5 vjetësh i vijnë sërish.",
165: "Gjyshi Selim Doda:",
166: "— Këto fotografi nuk janë mrekulli — ato janë natyrë dhe durim. Secili prej këtyre njerëzve mori përsëri diçka për të cilën mjekët i kishin thënë se është e pamundur: nyje të shëndetshme dhe një jetë pa dhimbje. Nautubone ËSHTË KURORA E GJITHË JETËS SIME SI BIMËTAR — DHE TRASHËGIMIA IME PËR BREZAT E ARDHSHËM!",
167: "Pse Gjyshi Selim nuk pret më njerëz — dhe si u bë Nautubone e vetmja mënyrë për të arritur te receta e tij",
168: "„Shëndeti nuk më lejon më t'i pres të sëmurët personalisht. Por formula ime do të vazhdojë të shërojë — përmes duarve të djalit tim.“",
169: "Gjyshi Selim Doda:",
170: "— Vitin e kaluar mora vendimin më të vështirë në jetë: të mos pres më njerëz. Lista e pritjes kishte mbi 2.000 emra — dhe nuk mund t'i lija pa ndihmë. Prandaj e lashë djalin tim Arben ta çonte recetën atje ku do ta bëjnë për të gjithë. Tani jam i qetë — Nautubone është pikërisht ajo që u jepja njerëzve që vinin tek unë, vetëm në një formë të përshtatshme. Receta është në duar të sigurta.",
171: "Arben Doda:",
175: "Për t'u regjistruar, përdorni formularin zyrtar të porosisë më poshtë — ai vjen drejtpërdrejt nga ekipi i prodhimit i Arben Dodës.",
176: "Mos e humbisni mundësinë e fundit të këtij viti — Nautubone mund të shterojë para fundit të programit!",
177: "Arben Doda:",
178: "— Këtë vit arritëm të prodhojmë 5&nbsp;000 paketa të xhelit Nautubone posaçërisht për njerëzit nga Shqipëria. Por duke pasur parasysh kërkesën — që është e jashtëzakonshme — këto sasi do të shterojnë shpejt. Seria e ardhshme do të jetë gati vetëm në fund të",
180: ".",
181: "Programi i mbështetjes është aktiv deri më",
182: "— çdo banor i Shqipërisë mbi 40 vjeç mund të përfitojë",
183: "deri në 50% zbritje",
185: "Mos e shtyni. Babai gjithmonë u thoshte njerëzve: „Nyjet nuk ju presin — ato shkatërrohen çdo sekondë.“ Sa kohë që programi është aktiv, shfrytëzojeni. Nautubone ka efekt kumulativ — një kurs i plotë mjafton për 5–6 vjet nyje të shëndetshme.",
186: "Thjesht shkruani emrin dhe numrin e telefonit në formular. Një konsulent do t'ju telefonojë, do të hartojë një program individual për rastin tuaj dhe do të organizojë dërgesën në çdo adresë në Shqipëri — brenda 2–3 ditësh, me postë ose me korrier deri te dera juaj.",
187: "Ju uroj të gjithëve shëndet! Kujdesuni për nyjet tuaja sot, që të ecni nesër! Me respekt: Selim Doda dhe djali i tij Arben.",
188: "Përditësuar:",
190: "Për shkak të kërkesës jashtëzakonisht të madhe, stoqet e Nautubone mund të shterojnë para fundit të planifikuar të programit! Sot —",
191: "18/12/2025 — është dita e fundit për porosi me zbritje",
192: "ose deri në shterimin e stoqeve.",
193: "Kujdes! Mos e mbyllni dhe mos e rifreskoni faqen — xheli Nautubone i rezervuar për ju do t'i ofrohet të radhës nga lista e pritjes!",
194: "Vendi juaj i rezervuar në program:",
195: "Nr.",
197: "Formulari zyrtar i porosisë",
198: "Nr.",
202: "Që të përfitoni",
203: "50% zbritje",
204: ", shkruani emrin dhe numrin e telefonit në fushat më poshtë dhe shtypni butonin „POROSIT“.",
205: "Stoqet e mbetura:",
210: "Emri",
211: "Numri i telefonit",
212: "POROSIT",
213: "✔️ Dërgesë në çdo adresë në Shqipëri brenda 2–3 ditësh",
214: "me postë ose me korrier deri te dera juaj",
215: "KOMENTE:",
216: "Vjollca Berisha",
217: "Me muaj e prisja këtë shkrim! Një shoqja ime nga Tirana ka qenë personalisht te Gjyshi Selim para disa vitesh — thoshte se është një mrekulli njeriu. Gjynah që nuk pret më njerëz, por nëse Nautubone ka të njëjtën recetë — porosis menjëherë. Më vjen mirë që e kapa zbritjen!",
218: "Suela Prifti",
219: "Korrieri ma solli të mërkurën. Dhjetë ditë e lyej xhelin në mëngjes dhe në mbrëmje — dhe ndryshimi është I MADH! Ngrihem pa atë kërcitjen e tmerrshme! Burri shikon dhe nuk beson. Do ta bëj kursin e plotë 60-ditor, por tashmë jam e bindur se funksionon.",
220: "Lule Gjoka",
221: "Jam 72 vjeçe dhe tre vjet vuajta nga dhimbjet në kërbisht. Të ecurit ishte mundim. Ortopedi tha: „Protezë ose duro.“ Nuk doja as njërën, as tjetrën. Nautubone më ndihmoi brenda dy muajsh — tani eci një kilometër e gjysmë çdo ditë! Kurse radiografia tregon një përmirësim që mjeku im nuk di ta shpjegojë. Faleminderit, Gjyshi Selim, dhe djalit tënd!",
222: "Besnik Meta",
223: "Si ish-sportist, e di se çfarë do të thotë të jetosh me kërc të shkatërruar. Gjunjët i kisha si të një njeriu 90-vjeçar — kurse jam vetëm 54. Nautubone m'i ktheu lëvizjet që nuk i kisha bërë prej 10 vjetësh. Sërish mund të bëj gjunjëzime! Nuk njoh produkt tjetër që arrin diçka të tillë.",
224: "Shpresa Kola",
225: "Jam paksa e shqetësuar… A ia vlen? Jam 66 vjeçe, nyjet më kërcasin në çdo lëvizje dhe shpina nuk më lë të qetë. Por jam zhgënjyer aq shumë herë nga „ilaçe mrekullie“ të ndryshme, sa tashmë e kam të vështirë të besoj. A ndihmon vërtet?",
226: "Dritan Cani",
227: "Zonja Shpresa, i kuptoj plotësisht dyshimet — i kam pasur edhe unë. Por Nautubone është ndryshe nga gjithçka që kam provuar deri tani. E përdor prej 5 javësh për gjunjët dhe mesin — dhe mund t'ju them se ndryshimi është si dita me natën.",
228: "Më parë nuk përkulesha dot që të lidhja lidhëset e këpucëve. Tani e bëj pa u menduar. Porositni të paktën një paketë dhe gjykoni vetë — nuk keni çfarë të humbni!",
229: "Gabriela Nushi",
230: "Tri ditë pasi fillova ta lyej xhelin, dhimbja në gju m'u ul përgjysmë! Tani është dita e 12-të dhe tashmë ngjitem shkallëve pa u mbajtur pas parmakut. Do ta bëj kursin e plotë — besoj se pas dy muajsh do të jem si e re!",
231: "Jonida Zeneli",
232: "Në shpinë më kishte filluar të rritej një „gungë“ prej dy muajsh. U tmerrova! Provova pomada të ndryshme nga farmacia — asgjë. Por xheli Nautubone është krejt tjetër gjë — brenda 40 ditësh gunga u zhduk gati krejtësisht! Vazhdoj ta lyej, por tashmë jam jashtëzakonisht e kënaqur. Ja si duket ndryshimi:",
233: "Pranvera Lala",
234: "Kisha një nerv të shtypur në mes — nga dhimbja nuk flija dot as nuk qëndroja dot në këmbë. Mjeku më përshkroi qetësues të fortë, nga të cilët më vinte vazhdimisht keq. Fillova ta lyej xhelin Nautubone dy herë në ditë — pas një jave dhimbja u ul befas, kurse pas një muaji — u zhduk krejtësisht! Vazhdoj kursin, por jeta ime tashmë ka ndryshuar!",
235: "Bardhyl Gjini",
236: "Jam 79 vjeç dhe tre vjet mezi ecja. Djali më porositi Nautubone — pa më pyetur, sepse e dinte që do të refuzoja. Ma lyen xhelin çdo mëngjes dhe mbrëmje. E rezultati? Pas një muaji e gjysmë shëtis deri te parku çdo ditë! Ndihem sikur jam 60 vjeç! Faleminderit, Gjyshi Selim — në 102 vjeç je më i urtë se të gjithë mjekët e sotëm!",
237: "Thoma Stefani",
238: "Para Nautubone nuk i ngrija dot duart mbi kokë — supi më kërciste dhe më dhimbte tmerrësisht. Dy vjet vizitova mjekë — askush nuk ndihmoi. Dy muaj me Nautubone dhe duart më funksionojnë sërish normalisht. Ja radiografia ime — vetë mjeku nuk besoi:",
239: "Anila Ivanaj",
240: "Porosita për vjehrrën — është 81 vjeçe dhe gati nuk ngrihej dot nga shtrati. Mjekët refuzonin të bënin çfarëdo — „në këtë moshë asgjë më nuk ndihmon“, thoshin. Me Nautubone, brenda 2 muajsh ajo tashmë ecën nëpër oborr dhe madje gatuan! Nuk mund të besonim.",
241: "Emil Vata",
242: "Gruaja ime qëndroi në shtrat katër muaj — shtylla kurrizore thjesht dorëzoi. Mjekët propozuan një operacion prej 450.000 lekësh pa asnjë garanci. Vendosëm të provonim xhelin Nautubone — nuk kishim çfarë të humbnim. Ia lyeja dy herë në ditë. Pas 5 javësh u ngrit. Dje shkuam bashkë në pazar — për herë të parë pas gjysmë viti! Qava nga gëzimi.",
243: "Nora Bushati",
244: "Porosita javën e kaluar, e mora ditën e tretë. Menjëherë fillova ta lyej xhelin — dhe lehtësimi erdhi ditën e dytë! Sikur dikush m'i lyen nyjet nga brenda. Dy javë e lyej dy herë në ditë dhe tashmë mezi pres rezultatin e plotë!",
245: "Rrezarta Mema",
246: "Jam 74 vjeçe. Pesë vjet vuajta nga artroza dhe dhimbjet e shpinës. Provova fjalë për fjalë gjithçka — pomada, hape, injeksione, fizioterapi. ASGJË nuk ndihmoi në afat të gjatë. Xheli Nautubone është e vetmja gjë që më dha një REZULTAT TË VËRTETË — e lyej dy herë në ditë dhe brenda një muaji e gjysmë nyjet i ndiej rrënjësisht ndryshe. Mjeku nuk u beson radiografive!",
247: "Vera Peçi",
248: "E njoh personalisht Gjyshin Selim — para 12 vjetësh më ndihmoi me një hernie diskale. Brenda tri javësh isha sërish në këmbë! Emrin e tij e njeh gjithë rrethina e Tiranës. Më vjen mirë që djali i tij e vazhdon punën!",
249: "Gjyste Pali",
250: "Babai im është 84 vjeç dhe tre vjet nuk kishte dalë nga shtëpia. Nyjet, shpina, gjunjët — gjithçka e dhimbte. Thoshte se pret të ikë. Pas dy muajsh me Nautubone — dje doli në oborr dhe ujiti kopshtin! Për herë të parë pas tre vjetësh! Nuk mund ta përshkruaj çfarë ndjeva. Faleminderit nga zemra!!!",
251: "Mirela Dushku",
252: "A di ndokush nëse mund të përdoret në rast alergjish? Reagoj pothuajse ndaj gjithçkaje — edhe nga një aspirinë e zakonshme më ënjten gishtat. Kam frikë të provoj diçka të re…",
253: "Spiro Kaleshi",
254: "Mirela, unë jam alergjik ndaj katër llojeve barnash. E lyej xhelin Nautubone prej 50 ditësh — asnjë irritim, asnjë ënjtje, asnjë skuqje. Përbërja është krejtësisht nga ekstrakte natyrore — nuk përmban kimikate. Mund të porositni të qetë!",
255: "Dorina Saliu",
256: "Më parë nuk kisha fuqi të ngrihesha — çdo lëvizje ishte mundim, mendoja se jeta ime kishte marrë fund. Vajza ime porositi xhelin Nautubone dhe më detyroi ta provoja — ma lyente në mëngjes dhe në mbrëmje. Dy muaj më vonë? Vallëzova në dasmën e nipit tim!!! Kurrë në jetë nuk kam qenë kaq mirënjohëse!",
257: "Silvana Brahimi",
258: "Porosita për mamanë. Kishte dhimbje të vazhdueshme në qafë, që i shkaktonin marramendje dhe të përziera — jeta i ishte bërë e padurueshme. Në javën e dytë me Nautubone dhimbjet u ulën ndjeshëm, kurse marramendjet pushuan krejtësisht! Mamaja qesh sërish — prej kohësh nuk e kisha parë të tillë.",
259: "Sanije Mullai",
260: "Po pyes veten — nëse Gjyshi Selim është kaq i mirë, pse këto gjëra nuk shiten kudo? Pse vetëm online? Pse farmacitë nuk i ofrojnë?",
261: "Mikel Rrapi",
262: "Sepse farmacitë fitojnë nga njerëzit që blejnë qetësues çdo muaj! Po t'i shëronin të gjithë nyjet një herë e përgjithmonë — kush do t'ua blinte barnat e shtrenjta? Mendoni në mënyrë logjike!",
263: "Olta Kruja",
264: "I lexova të gjitha komentet — dhe u prek. Po porosis tani, për vete dhe për burrin. Mora tri paketa xhel, për kursin e plotë. Nëse ndihmon qoftë edhe gjysmën e asaj që shkruajnë njerëzit — do të jem e lumtur!",
265: "Lindita Muça",
266: "Ortopedi më tha se në moshën 63-vjeçare duhet të mësohem me dhimbjen — gjoja nuk ka ilaç. Porosita Nautubone pavarësisht gjithçkaje. Do të shohim kush ka të drejtë!",
268: "Ngarko avatar",
269: "Ngarko fotografi",
270: "DËRGO",
}

RAW = {
172: "— Nautubone nuk shitet në farmaci — procesi i prodhimit është i ndërlikuar, kurse\n      sasitë janë të kufizuara. Është i disponueshëm vetëm përmes programit online, dy herë në vit. Por në kuadër të\n      programit, zbritjet arrijnë deri në",
174: " — sepse qëllimi ynë nuk është fitimi,\n      por arritshmëria. Sidomos për pensionistët, për të cilët babai im këmbënguli të ketë zbritjen maksimale.",
184: ".\n      Pas kësaj date, do t'ju duhet të prisni të paktën 6 muaj për një mundësi të re.",
208: "5900\n            lekë",
209: "2950\n            lekë",
}

ATTRS = {
"Ваше име": "Emri juaj",
"Ваш број телефона": "Numri juaj i telefonit",
"Ваш коментар": "Komenti juaj",
}
