# -*- coding: utf-8 -*-
# Немецкая адаптация лендинга травника. Форм-фактор — КРЕМ.
# Живојин Поповић -> Wilhelm Reinhardt (Opa Wilhelm), 102, Kräuterkundiger, Dorf bei München
# Драган Поповић  -> Matthias Reinhardt
# Београд -> München | Минхен -> Basel | Србија -> Deutschland | RSD -> EUR

DE = {
0: "Wilhelm Reinhardt, 102-jähriger Kräuterkundiger aus der Nähe von München, enthüllt die Formel für die vollständige Wiederherstellung der Gelenke — die Methode ist für jeden Bürger Deutschlands zugänglich",
1: "MIT 102 JAHREN IST ER DER ÄLTESTE KRÄUTERKUNDIGE DEUTSCHLANDS UND DER EINZIGE SEINER GENERATION, DER OHNE GEHSTOCK GEHT. ZUM ERSTEN MAL ENTHÜLLT ER DIE FORMEL, DIE ER 40 JAHRE LANG NUR DENEN GAB, DIE ZU IHM KAMEN.",
2: "Veröffentlicht:",
3: "„Wie hat es Opa Wilhelm, der Kräuterkundige aus der Nähe von München, geschafft, seine Gelenke bis zum Alter von 102 Jahren in perfektem Zustand zu erhalten, während alle seine Altersgenossen längst nicht mehr gehen können?“",
4: "In einem Dorf unweit von München lebt ein Mann, der alles widerlegt, was wir über das Altern wissen. Mit 102 Jahren geht der Kräuterkundige Wilhelm Reinhardt jeden Morgen die Pfade oberhalb des Dorfes entlang, steigt ohne Hilfe Treppen und hat in seinem Leben nie einen Gehstock benutzt. Seine Altersgenossen sind längst nicht mehr am Leben oder an den Rollstuhl gefesselt — er dagegen steigt immer noch allein den Hügel hinauf, um Kräuter zu sammeln.",
5: "Bis zum vergangenen Jahr empfing Opa Wilhelm die Menschen in seinem Haus, in der alten Stube, in der er seit Jahrzehnten Kräuter trocknet. Über 70 Jahre Arbeit mit Kräutern, über 40.000 Menschen, Dutzende von Wirbelsäulen und Knien, die ins Leben zurückgeholt wurden, nachdem die Ärzte sie aufgegeben hatten. Es gab eine Warteliste von sechs Monaten — die Menschen kamen aus dem ganzen Land zu ihm.",
6: "Doch das eigentliche Rätsel sind nicht diejenigen, die zu ihm kamen. Das eigentliche Rätsel ist er selbst. Mit 102 Jahren — keine Arthritis, keine Arthrose, kein Bandscheibenvorfall. Die Röntgenaufnahmen seiner Gelenke sehen aus wie die eines 45-jährigen Mannes. Die Ärzte, die ihn untersuchen, trauen ihren eigenen Augen einfach nicht.",
7: "Jahrzehntelang hielt er sein Rezept geheim — er bereitete es selbst zu, in seiner Stube, und veröffentlichte es nie. Doch heute, da seine Gesundheit es ihm nicht mehr erlaubt, die Menschen persönlich zu empfangen, hat Opa Wilhelm eine Entscheidung getroffen, die alles verändert hat: seine Formel jedem Bürger Deutschlands zugänglich zu machen.",
8: "Opa Wilhelm Reinhardt: „Mein ganzes Leben lang habe ich beobachtet, wie Menschen vorzeitig altern — nicht weil ihr Körper schwach ist, sondern weil ihnen niemand gesagt hat, wie sie ihre eigenen Regenerationsmechanismen aktivieren. Mit 102 Jahren bin ich der lebende Beweis dafür, dass",
9: "Gelenke bis ins hohe Alter gesund bleiben können, wenn man weiß, wie man die Zellen „aufweckt“, die sie aufbauen.",
10: "MEIN ZIEL WAR IMMER NUR EIN EINZIGES — DEM KÖRPER ZU HELFEN, NEUES KNORPEL- UND KNOCHENGEWEBE ZU BILDEN, GENAU WIE IN JUNGEN JAHREN. JETZT HAT MEIN SOHN MATTHIAS ALL DAS IN EIN PRODUKT VERWANDELT",
11: "DAS IN JEDES ZUHAUSE IN DEUTSCHLAND GELANGEN KANN.",
13: "Matthias Reinhardt — der Sohn des Kräuterkundigen — wuchs zwischen den getrockneten Kräutern und den Waagen seines Vaters auf und lernte das Handwerk von Kindheit an. Er wurde kein Arzt. Jahrelang redete er auf seinen Vater ein, das Rezept dürfe nicht in einem einzigen Haus eingeschlossen bleiben, und fand dann selbst ein Labor und Menschen, die halfen, die jahrzehntelange Erfahrung von Opa Wilhelm in ein Produkt zu verwandeln, das für jeden zugänglich ist — damit es alle erreicht, die es brauchen.",
14: "Das Ergebnis dieser Zusammenarbeit übertraf alle Erwartungen. Doch bevor ich Ihnen von dem Produkt erzähle, sehen wir uns an, warum alles, was Sie über die Behandlung von Gelenken wissen, höchstwahrscheinlich falsch ist.",
15: "Die Lüge, an die ganz Deutschland glaubt:",
16: "„Schmerzmittel heilen die Gelenke“ — FALSCH, sie zerstören sie noch schneller!",
17: "Opa Wilhelm Reinhardt:",
18: "— Seit siebzig Jahren behandle ich Menschen, und ich sage Ihnen etwas, das Ihnen die Apotheken niemals zugeben werden: Kein einziges Schmerzmittel in der Geschichte der Medizin hat auch nur einen Millimeter Knorpel regeneriert. Kein einziges! Sie unterdrücken den Schmerz, doch währenddessen zerfällt der Knorpel weiter — Sie spüren es nur nicht mehr. Und wenn Sie es wieder spüren, wird es zu spät sein.",
19: "Doch das ist nicht das Schlimmste. Das Schlimmste ist, was diese chemischen Substanzen mit Ihren inneren Organen anrichten. In 70 Jahren Arbeit habe ich Hunderte von Menschen mit vollständig zerstörter Leber und Nieren gesehen — nicht durch Krankheit, sondern durch Medikamente! Der Körper ist nicht dafür gemacht, jahrzehntelang Chemikalien zu schlucken. Und doch ist es genau das, was die konventionelle Medizin „verschreibt“.",
20: "Die Wirbelsäule ist besonders anfällig. Die Bandscheiben haben keine eigene Blutversorgung — sie ernähren sich durch Diffusion, was bedeutet, dass ihre Schädigung still verläuft, ohne Schmerzen, manchmal über Jahre. Wenn der Schmerz endlich auftritt, ist die Schädigung bereits fortgeschritten. Der Nervendruck durch einen Bandscheibenvorfall verwandelt das Leben in einen Albtraum: Er beginnt mit einem leichten Taubheitsgefühl im Bein und endet mit dem vollständigen Verlust der Beweglichkeit.",
21: "Sehen Sie sich an, was dieses Röntgenbild zeigt. Eine Frau, gerade einmal 39 Jahre alt, Lehrerin — und ihre Wirbelsäule ist in einem Zustand, wie ich ihn vor 20 Jahren nur bei 70-Jährigen gesehen habe. Acht Stunden täglich auf dem Stuhl sitzen, Bewegungsmangel und völlige Unkenntnis des eigenen Körpers — das ist es, was die moderne Lebensweise mit sich bringt.",
22: "Eine Aufnahme aus dem Archiv, das Opa Wilhelm seit Jahrzehnten aufbewahrt: die Wirbelsäule einer 39-jährigen Lehrerin aus Nürnberg. Sie kam mit „leichter Müdigkeit im Lendenbereich“ — das Röntgenbild offenbarte drei geschädigte Bandscheiben, einen beginnenden Vorfall und Mikrorisse in der Knorpelhülle.",
23: "Wenn Sie nach dem 40. Lebensjahr Schmerzen, Steifheit oder Knirschen in den Gelenken spüren — Ihr Knorpel zerfällt bereits. Das kommt nicht „von der Müdigkeit“ und ist nicht „normal“.",
24: "Bei der Wirbelsäule verläuft der Prozess um ein Vielfaches schneller und heimtückischer — der Schmerz tritt erst auf, wenn die Schädigung bereits kritisch ist!",
25: "Opa Wilhelm Reinhardt:",
26: "— Ich möchte völlig offen sein. Ich kenne Menschen, die es monatelang aufgeschoben haben. Das Ergebnis? Ein eingeklemmter Nerv, der nie wieder normal funktionierte. Die Regeneration der Bandscheiben ist nutzlos, wenn der Nerv bereits abgestorben ist —",
27: "DIE BANDSCHEIBE KANN ZURÜCKKEHREN, ABER DER NERV — NICHT!",
28: "Und was bleibt dann? GEHSTOCK, ROLLSTUHL UND ABHÄNGIGKEIT VON FREMDER HILFE BIS ANS LEBENSENDE!",
29: "Und was bietet die moderne Chirurgie? Teure und riskante Operationen mit Metallimplantaten. Ich habe persönlich Hunderte von Menschen gesehen, denen es nach einer Wirbelsäulenoperation SCHLECHTER ging als davor.",
30: "INFEKTIONEN, MISSLUNGENE VERWACHSUNGEN, CHRONISCHE SCHMERZEN UND AM ENDE — EINE ERNEUTE OPERATION. UND MANCHMAL — IRREVERSIBLE SCHÄDEN!",
31: "Opa Wilhelm zeigt eine Aufnahme, die ihm ein Mann nach einer Operation mit Metallschrauben brachte: „Das ist ein typisches Ergebnis — das Implantat ist nicht richtig eingewachsen, das umliegende Gewebe ist entzündet, und der Schmerz ist stärker als vor der Operation. Ich habe Hunderte ähnlicher Fälle gesehen.“",
32: "Die Statistik ist gnadenlos: Bei 60 % der Operierten kehrt der Vorfall innerhalb von 2–4 Jahren zurück. Und der Preis? Monate der Unbeweglichkeit, Zehntausende Euro und völlige Ungewissheit. Viele geben zu: Könnten sie die Zeit zurückdrehen, würden sie sich nie auf den Operationstisch legen.",
33: "Diese Symptome bedeuten, dass Ihr Knorpel bereits stirbt! Und wenn Sie über 40–50 Jahre alt sind — ist der Prozess ohne Eingriff irreversibel!",
34: "— In 70 Jahren sind über 40.000 Menschen durch meine Hände gegangen, und ich kann Folgendes sagen: Jeder ignorierte Gelenkschmerz ist ein Schritt in Richtung Rollstuhl. Allein im Jahr",
35: " wurden in Deutschland über 125.000 neue Fälle schwerer Gelenkerkrankungen registriert — davon 23.000 bei Personen im Alter von 38 bis 48 Jahren. Das ist kein Problem des Alters. Das ist ein Problem der Untätigkeit.",
36: "Wenn Ihr Organismus Ihnen bereits eines dieser Signale gegeben hat — warten Sie keinen einzigen Tag!",
37: "Hier ist die Liste, die ich jedem Menschen schon an der Schwelle genannt habe:",
38: "Morgendliche Steifheit, die bei Bewegung nicht vergeht;",
39: "Knirschen, Knacken oder Quietschen bei Bewegung;",
40: "Verstärkung der Schmerzen bei Wetterwechsel;",
41: "Schwierigkeiten beim Beugen oder Strecken des Knies;",
42: "Schwellung, Rötung oder Wärme rund um das Gelenk;",
43: "Schmerzen beim Treppauf- oder Treppabgehen;",
44: "Chronische Müdigkeit und Schwere in den Beinen;",
45: "Schmerzen im Lendenbereich, die in den Oberschenkel oder Fuß „einschießen“;",
46: "Steifheit oder Kribbeln in den Fingern;",
47: "Veränderung des Gangs — Hinken, Unsicherheit;",
48: "Unfähigkeit, länger als 10–15 Minuten zu stehen;",
49: "Wenn Sie sich auch nur in zwei dieser Symptome wiedererkennen — Ihr Knorpel wird bereits zerstört. Und bei der Wirbelsäule verläuft der Prozess drei- bis viermal schneller, weil die Bandscheiben unter ständigem Druck stehen.",
50: "ERGEBNIS: VORFALL, EINGEKLEMMTER NERV, WIRBELDEFORMATION, VERLUST DER BEWEGLICHKEIT — UND ALL DAS KANN INNERHALB WENIGER WOCHEN GESCHEHEN!",
51: "Schieben Sie es nicht auf, denn Ihr Organismus gibt Ihnen keine unbegrenzten Chancen!",
52: "Sehen Sie sich diese Menschen unten an. Jeder von ihnen hatte dieselben Symptome, die Sie wahrscheinlich in diesem Moment spüren. Jeder sagte: „Das geht vorbei.“ Und jeder würde heute alles geben, um die Zeit zurückzudrehen und damals zu handeln, als er noch eine Chance hatte.",
53: "Ehemalige Patientin einer anderen Klinik, 58 Jahre, Leipzig. Drei Wirbel um über 8 mm verschoben, das Rückenmark unter Druck. Zweimal weigerte sie sich, zu Opa Wilhelm zu gehen — als sie endlich kam, war sie einen Schritt von der Lähmung entfernt.",
54: "Eine 61-jährige Frau aus Kassel — ihr Buckel wuchs in weniger als einem Jahr auf 4 cm an. Die Halswirbel sind so weit deformiert, dass sich der Kopf nicht mehr zur Seite drehen lässt. Die Schmerzmittel wirken seit 8 Monaten nicht mehr.",
55: "Hausfrau, 59 Jahre, Bremen. Ihre Kniegelenke sind so abgenutzt, dass der Knorpel auf unter 1 mm ausgedünnt ist. Jeder Schritt klingt wie das Quietschen einer alten Tür. Drei Orthopäden sagten ihr, die einzige Lösung sei eine doppelte Prothese, für über 12.000 Euro.",
56: "Ehemaliger Bergmann, 68 Jahre, Gelsenkirchen. Der Knorpel im rechten Knie ist vollständig zerstört, das Knochengewebe ist in die Nekrosephase eingetreten. Das Aufschieben um 4 Monate kostete ihn die Gliedmaße — Amputation oberhalb des Knies und lebenslange Abhängigkeit vom Rollstuhl.",
57: "Opa Wilhelm Reinhardt:",
58: "Ich bin 102 Jahre alt und kann Ihnen aus eigener Erfahrung sagen: Der Organismus ist in JEDEM Alter fähig, sich selbst zu regenerieren — vorausgesetzt, Sie wissen, WIE Sie ihn aktivieren. Genau dem habe ich mein Leben gewidmet.",
59: "UND WENN SIE BEREITS ÜBER 50–60 JAHRE ALT SIND, WARTEN SIE KEINE SEKUNDE!",
60: "Bei Ihnen ist die Schädigung mit ziemlicher Sicherheit in die kritische Phase eingetreten — Sie müssen dringend die Zerstörung stoppen und die Regeneration von neuem Knorpel, neuen Knochen und neuem Gewebe aktivieren!",
61: "Fälle, die von Ärzten als hoffnungslos erklärt wurden!",
62: "Hildegard Brunner geht mit 86 Jahren wieder ohne Hilfe, nachdem drei Krankenhäuser sie abgewiesen hatten. Hier ist ihre Geschichte…",
63: "Hildegard Brunner aus Augsburg litt an schwerer Kniearthrose und mehrfachen Bandscheibenvorfällen. Drei verschiedene Krankenhäuser wiesen sie ab — überall sagte man ihr dasselbe: „In diesem Alter lässt sich nichts mehr machen.“ Ihre Tochter hörte zufällig von einem Bekannten aus einem Dorf unweit von München von Opa Wilhelm und beschloss, ihn aufzusuchen.",
64: "„Ich lebte wie im Gefängnis — mein eigenes Haus wurde zu meiner Zelle. Ich konnte nicht bis zur Toilette gelangen, konnte nicht länger als eine Minute stehen, konnte mir keinen Tee kochen. Meine Kinder arbeiteten und konnten nicht jeden Tag kommen. Ich lag da und starrte an die Decke. Die Ärzte sagten, eine Operation habe in diesem Alter keinen Sinn, und gaben mir nur Schmerzmittel.",
65: "Als meine Tochter mich zu Opa Wilhelm brachte, sah er mich an und sagte etwas, das mir kein einziger Arzt gesagt hatte: „Frau Brunner, Ihr Körper hat NICHT aufgehört zu kämpfen. Ihm hat nur niemand geholfen.“ Er gab mir das, was er selbst zubereitet, und sagte, ich solle geduldig sein. In der dritten Woche stand ich zum ersten Mal seit anderthalb Jahren GANZ ALLEIN aus dem Bett auf!",
66: "Heute, fünf Monate später, gehe ich einkaufen, koche und kümmere mich sogar um den Blumengarten vor dem Haus. Mit 86 Jahren! Als die Nachbarn mich im Hof sahen, glaubten sie es nicht. Sie dachten, sie würden mich nie wiedersehen. Opa Wilhelm hat mir mein Leben zurückgegeben — und ich habe keine Worte, um ihm zu danken.“",
67: "Hildegard Brunner, 86 Jahre, Augsburg",
68: "Ein weiterer außergewöhnlicher Fall ist Thomas Vogler — ein 47-jähriger Bauarbeiter aus Ingolstadt, der nach 20 Jahren schwerer körperlicher Arbeit eine schwere Schädigung der Wirbelsäule erlitt und gezwungen war, sich im Rollstuhl fortzubewegen.",
69: "Thomas probierte die Methode von Opa Wilhelm aus, und die Ergebnisse schockierten sogar seinen Hausarzt.",
70: "SEINE WIRBELSÄULE BEGANN SICH ZU ERHOLEN, DER SCHMERZ VERSCHWAND VOLLSTÄNDIG, UND DAS UNGLAUBLICHSTE —",
71: "NACH NUR 4 WOCHEN VERLIESS ER DEN ROLLSTUHL!",
72: "Thomas hat uns erzählt:",
73: "„Zwanzig Jahre lang habe ich Gebäude gebaut, aber um meine eigene Wirbelsäule habe ich mich nicht gekümmert. Eines Morgens wachte ich auf und konnte den Lendenbereich nicht mehr bewegen. Meine Frau rief den Notarzt. Die Diagnose — drei Vorfälle und Druck auf die Nervenwurzel. Die Ärzte schlugen eine Operation für 8.000 Euro vor, aber ohne Garantie.",
74: "Monatelang saß ich zu Hause im Rollstuhl. Meine Kinder sahen mich traurig an, meine Frau weinte jeden Abend. Ich fühlte mich wie eine Last. Ich wünschte mir, ich würde verschwinden…",
75: "Da hörte mein Schwiegervater von Opa Wilhelm, von einem Mann, dem er geholfen hatte. Ich meldete mich, schickte die Röntgenbilder, und der Alte sagte: „Es ist nicht zu spät.“ Diese drei Worte gaben mir mehr Hoffnung als alles, was ich von Dutzenden von Ärzten gehört hatte.",
76: "Am vierten Tag konnte ich schon stehen. Die volle Kur dauerte 80 Tage. Heute arbeite ich wieder — nicht auf der Baustelle, sondern im Büro, aber ich GEHE. Ich renne mit meinen Kindern im Park. Ich lebe. Das Röntgenbild zeigt, dass meine Bandscheiben zu 90 % wiederhergestellt sind. Opa Wilhelm ist der Einzige, der mich nicht abgewiesen hat — und der Einzige, der mir geholfen hat.“",
77: "Die Geschichten der Tausenden von Menschen, denen Opa Wilhelm geholfen hat, sind ebenso beeindruckend: Menschen, denen die Ärzte sagten „gewöhnen Sie sich an den Schmerz“, gingen wieder, liefen wieder, lebten wieder. Wie ist das möglich?",
78: "Die Formel, die Opa Wilhelm über 40 Jahre lang mit eigenen Händen zubereitet hat!",
79: "Das Geheimnis der Methode „Endogene Gewebereaktivierung“ — wie der Organismus von selbst beginnt, neuen Knorpel, neue Knochen und neue Bänder zu bilden!",
80: "Opa Wilhelm Reinhardt:",
81: "— Erlauben Sie mir, Ihnen etwas zu erklären, was die konventionelle Medizin nicht anerkennen will. Der Organismus jedes Menschen — selbst der eines 90-Jährigen — verfügt über „schlafende“ regenerative Zellen. Dieselben Zellen, die in Ihrer Jugend mühelos Knorpel, Knochen und Bänder aufgebaut haben. Mit den Jahren sterben sie nicht — sie „schlafen“ einfach ein, weil der Organismus aufhört, ihnen die richtigen Signale zu senden.",
82: "Vor 40 Jahren entdeckte ich, dass eine bestimmte Kombination natürlicher Substanzen — in streng festgelegten Verhältnissen — wie ein „Zündschlüssel“ für diese schlafenden Zellen wirkt. Ich nannte die Methode",
83: "„Endogene Gewebereaktivierung“",
84: "— denn sie führt nichts Künstliches zu, sondern aktiviert die eigenen Ressourcen des Organismus. Genau deshalb gibt es bei mir KEINE Nebenwirkungen, KEINE Organschäden und KEINE Abhängigkeit.",
85: "Vier Jahrzehnte lang habe ich diese Methode bei jedem angewandt, der an meine Schwelle kam — und bei jedem habe ich dasselbe Ergebnis festgehalten: das Stoppen der Zerstörung, die Verringerung der Schmerzen und die allmähliche Rückkehr der Gelenkfunktion. Hunderte von Menschen, die als „letzte Chance“ zu mir kamen, verließen mein Haus auf eigenen Beinen.",
86: "Die Formel selbst ist nicht kompliziert — aber die Präzision ist alles. Jeder Bestandteil muss in exakter Menge vorliegen, bis auf das Hundertstel Milligramm. Werden die Verhältnisse nicht eingehalten, verschwindet die Wirkung einfach. Genau deshalb habe ich die Methode jahrzehntelang persönlich angewandt — denn ich konnte sie keiner Apotheke anvertrauen.",
87: "Zusammensetzung der Creme nach dem Rezept des Kräuterkundigen Reinhardt (Wirkstoffe pro Dosis):",
88: "Omega-3",
89: "Leinsamen: 4500 mg",
90: "Glucosaminsulfat",
91: "Krebstiere: 1100 mg",
92: "Magnesiumcitrat",
93: "Meeresalgen: 390 mg",
94: "Gingerol",
95: "Ingwer: Extrakt 4200 mg",
96: "AKBA",
97: "Weihrauchharz (Boswellia): Extrakt 1100 mg",
98: "Silizium",
99: "Ackerschachtelhalm: Extrakt 320 mg",
100: "Curcumin",
101: "Kurkuma: Extrakt 2300 mg",
102: "Diese Bestandteile sehen einfach aus, doch sie in der entsprechenden Qualität und aus der richtigen Quelle zu finden, ist außerordentlich schwierig. Die meisten sind in Apotheken nicht erhältlich und müssen aus verschiedenen Teilen der Welt beschafft werden. Und sie zu Hause zu mischen, ist praktisch unmöglich — denn die Dosierung muss auf 0,1 mg genau sein.",
103: "Genau deshalb habe ich die Mischung jahrzehntelang persönlich zubereitet, für jeden Menschen einzeln. Doch mein Sohn Matthias sah das ganze Bild.",
104: "Wie Matthias Reinhardt das 40 Jahre alte Rezept seines Vaters in eine für jeden zugängliche Creme verwandelte — Nautubone",
105: "Matthias Reinhardt:",
106: "— Ich bin in der Kräuterstube meines Vaters aufgewachsen. Jeden Tag sah ich, wie Menschen vor Schmerzen gekrümmt hereinkamen — und lächelnd wieder hinausgingen. Mit 14 Jahren kannte ich das Rezept bereits auswendig. Ich wurde kein Arzt — das Handwerk habe ich von ihm gelernt. Doch jahrelang redete ich auf ihn ein: Vater, dieses Rezept darf nicht in einem einzigen Haus eingeschlossen bleiben. Tausende von Menschen warten auf das, was du im Regal stehen hast.",
107: "Fünf Jahre lang klapperte ich Labore in München und Basel ab, bis ich Menschen fand, die die Rezeptur meines Vaters ernsthaft untersuchen wollten. Die Antwort, die ich erhielt, begeisterte mich: Die Kombination dieser Bestandteile in exakten Verhältnissen aktiviert die Produktion von Kollagen Typ II und Proteoglykanen — den beiden Hauptbausteinen des Knorpels. Mit anderen Worten: Der Organismus „erinnert sich“ buchstäblich daran, wie man neuen Knorpel aufbaut, er braucht nur das richtige Signal.",
108: "Gemeinsam mit dem Labor entwickelten wir ein Verfahren, das wir",
109: "„Nanodiffusionstechnologie mit erhöhter Bioverfügbarkeit“",
110: "nannten — eine Methode, bei der die Wirkstoffe in spezielle Nanopartikel eingeschlossen werden, die tief durch die Haut dringen und direkt zum geschädigten Gelenkgewebe gelangen. Das erhöht die Aufnahme um etwa 380 % im Vergleich zu gewöhnlichen Cremes und Salben. Das Produkt nannte ich",
111: "Nautubone",
112: "— eine Creme, die auf die Haut aufgetragen wird und genau dort wirkt, wo es nötig ist. Ich habe sie zu Ehren meines Vaters und seiner 40-jährigen Arbeit benannt.",
113: "Die Creme Nautubone enthält alle 7 Komponenten aus dem Originalrezept meines Vaters, plus 29 zusätzliche Extrakte und Vitamine, die wir nach den Laboruntersuchungen in Basel hinzugefügt haben. Das Ergebnis ist eine Creme, die GENAUSO GUT wirkt wie das, was mein Vater mit eigenen Händen zubereitet hat — die aber in jedes Zuhause in Deutschland geliefert werden kann. Tragen Sie sie zweimal täglich auf die Gelenke auf, und die Wirkstoffe dringen durch die Haut direkt zu den betroffenen Gelenken vor.",
114: "„Nautubone ist das Erbe meines Vaters — seine 40-jährige Erfahrung, eingeschlossen in eine einzige Formel. Jeder Bestandteil wurde mit derselben Präzision ausgewählt, mit der er jedem Menschen begegnete, der an seine Tür klopfte. Das ist kein Massenprodukt aus der Apotheke — das ist das Werk eines ganzen, der Heilung gewidmeten Lebens.“",
115: "Das Unglaublichste an Nautubone ist, dass es nicht nur den Schmerz lindert — sondern den Regenerationsmechanismus aktiviert, der mit den Jahren eingeschlafen ist. Die Creme wird auf die Haut aufgetragen, und die Nanopartikel transportieren die Wirkstoffe tief in das Gelenkgewebe — dorthin, wo gewöhnliche Tabletten und Injektionen niemals hingelangen. Die Synergie zwischen den Bestandteilen verstärkt die Wirkung um bis zu das 20-Fache im Vergleich zu ihrer getrennten Einnahme.",
116: "Vier Phasen der Genesung mit Nautubone — was in Ihrem Organismus Schritt für Schritt geschieht",
117: "Opa Wilhelm Reinhardt:",
118: "— Mein ganzes Leben als Kräuterkundiger habe ich beobachtet, wie Menschen dieselben vier Phasen durchlaufen. Mein Sohn hat sie dokumentiert und in Nautubone eingebaut, sodass jeder sie zu Hause durchlaufen kann.",
119: "Die vier Phasen der „Endogenen Gewebereaktivierung“:",
120: "Phase 1 — Stoppen von Schmerz und Entzündung:",
121: "Bereits ab dem ersten Auftragen der Creme transportieren die Nanopartikel die Wirkstoffe durch die Haut direkt in das geschädigte Gewebe und blockieren die Entzündungsmoleküle. Der Schmerz lässt innerhalb von 24–48 Stunden spürbar nach — ohne Belastung von Leber und Nieren, denn die Creme nutzt eine Technologie der gezielten Aufnahme durch die Haut und durchläuft nicht den herkömmlichen Leberstoffwechsel.",
122: "Phase 2 — Stoppen der Zerstörung:",
123: "Zwischen dem dritten und dem siebten Tag hört der Organismus auf, Knorpel- und Knochengewebe abzubauen. Die Produktion der Gelenkflüssigkeit — des natürlichen „Schmiermittels“ der Gelenke — steigt. Die Reibung nimmt ab, und die Bewegungen werden leichter.",
124: "Phase 3 — Aufwecken der regenerativen Zellen:",
125: "Das ist das Herzstück der Methode. Die „schlafenden“ Chondrozyten und Osteoblasten erhalten ein biochemisches Signal und beginnen, neuen Knorpel und neues Knochengewebe zu bilden. Genau diese Phase macht Nautubone einzigartig — kein anderes Produkt aktiviert diesen Mechanismus.",
126: "Phase 4 — Dauerhafte Schutzbarriere:",
127: "Nach 30–60 Tagen bildet das neu entstandene Gewebe eine feste Schutzschicht, die die Gelenke selbst bei Belastung widerstandsfähig macht. Opa Wilhelm nennt das „Gelenkimmunität“ — einmal erreicht, hält die Wirkung jahrelang an.",
128: "Jede dieser Phasen ist das Ergebnis von 40 Jahren Erfahrung eines Mannes und 5 Jahren Laboruntersuchungen. Nautubone bietet kein schnelles „Überdecken“ des Schmerzes — sondern setzt einen tiefen, biologischen Regenerationsprozess in Gang, der die Gelenke in den Zustand zurückversetzt, in dem sie vor Jahrzehnten waren.",
129: "Ergebnisse, die die medizinische Gemeinschaft überrascht haben — Beobachtung von 2.340 Menschen im Alter von 38 bis 89 Jahren",
130: "Matthias Reinhardt:",
131: "— Als wir die ersten Ergebnisse der Laboruntersuchungen veröffentlichten, war die Reaktion blitzschnell. Universitätskliniken aus München, Berlin und Wien baten darum, eigene Untersuchungen durchführen zu dürfen. Die Ergebnisse bei echten Menschen übertrafen sogar unsere Erwartungen — keine der bestehenden Behandlungsmethoden kommt diesen Werten nahe.",
132: "Menschen, die für den Einsatz einer Gelenkprothese vorgemerkt waren, sagten ihre Operationen ab. Menschen, die monatelang nicht aus dem Bett aufgestanden waren, gingen wieder. Orthopäden trauten ihren eigenen Röntgenbildern nicht.",
133: "Ergebnisse der Beobachtung von „Nautubone“ bei 2.340 Menschen im Alter von 38 bis 89 Jahren",
134: "Vollständige Beseitigung von Schmerz und Entzündung",
136: "Wiederherstellung des vollen Bewegungsumfangs",
138: "Tendinitis, Bursitis, Periarthritis",
140: "Stoppen und Rückbildung degenerativer Veränderungen",
142: "Synovitis, Ligamentitis",
144: "Osteoarthrose (alle Stadien)",
146: "Osteoporose",
148: "Rheumatoide Arthritis, Gicht",
150: "Arthrose, Spondylarthritis",
152: "Dokumentierte Regeneration von Knorpelgewebe",
154: "Genaue Genesungszeiten mit „Nautubone“:",
155: "Andere Wissenschaftlerteams in Europa versuchen, unsere Formel zu reproduzieren, doch die bisherigen Ergebnisse sind weit von unseren entfernt. Die gemeinsam mit unserem Labor entwickelte Nanodiffusionstechnologie mit erhöhter Bioverfügbarkeit lässt sich bislang nicht nachbilden — genau sie ermöglicht es der Creme, die Bestandteile durch die Haut direkt in das Gelenk zu bringen, statt einfach auf der Hautoberfläche zu bleiben.",
156: "Wie lange dauert die vollständige Genesung? Opa Wilhelm erklärt es auf der Grundlage von 70 Jahren Erfahrung",
157: "Opa Wilhelm Reinhardt:",
158: "— Die Mindestkur, die ich empfehle, dauert 30 Tage. Bei schwereren Schädigungen — 60, manchmal auch 90 Tage. Doch in meiner gesamten Laufbahn hatte ich KEINEN EINZIGEN FALL, in dem die Methode kein Ergebnis brachte. Keinen einzigen. Und ich habe Menschen von 85, 90, sogar 94 Jahren behandelt.",
159: "Nautubone stoppt nicht nur den Schmerz — es setzt einen Prozess der tiefen biologischen Regeneration in Gang. Tragen Sie die Creme zweimal täglich auf, und schon in den ersten Stunden spüren Sie Erleichterung. Innerhalb einer Woche werden Sie bemerken, dass Sie sich leichter bewegen. Und nach der vollen Kur werden Ihre Gelenke in dem Zustand sein, in dem sie vor 20–30 Jahren waren.",
160: "Doch das Wertvollste ist etwas anderes: Die Wirkung ist DAUERHAFT. Einmal „aufgeweckt“, arbeiten die regenerativen Zellen jahrelang weiter!",
161: "Dank „Nautubone“ haben über 19.000 Menschen in Deutschland ihre Beweglichkeit zurückgewonnen. Hier ist nur ein kleiner Teil derer, denen Opa Wilhelm geholfen hat:",
162: "Rentnerin, 66 Jahre, Rostock. Vier verschobene Wirbel und chronische Radikulopathie. Ihr Sohn brachte ihr die Creme Nautubone aus München. Zwei Monate Auftragen — vollständige Rückkehr der Wirbelsäule in die normale Position. Ihr Orthopäde fragte nach dem Namen des Produkts.",
163: "Buchhalterin, 41 Jahre, Fulda. Ihre Knie hatten sich nach zwei Schwangerschaften und Gewichtszunahme nach innen verformt. Der Orthopäde sagte ihr: „gewöhnen Sie sich daran“. Mit der Creme Nautubone — 30 Tage Auftragen, zweimal täglich — richtete sich die Knieachse im Röntgenbild sichtbar auf.",
164: "Rentner, 73 Jahre, Osnabrück. Die Arthrose hatte seine Zehen so weit deformiert, dass er kein einziges Paar Schuhe mehr anziehen konnte. Er trug die Creme Nautubone täglich auf — in 21 Tagen richteten sich die Zehen auf, und die Schuhe von vor 5 Jahren passen ihm wieder.",
165: "Opa Wilhelm Reinhardt:",
166: "— Diese Fotos sind keine Wunder — sie sind Natur und Geduld. Jeder dieser Menschen hat etwas zurückbekommen, von dem die Ärzte sagten, es sei unmöglich: gesunde Gelenke und ein Leben ohne Schmerzen. Nautubone IST DIE KRÖNUNG MEINES GANZEN LEBENS ALS KRÄUTERKUNDIGER — UND MEIN ERBE FÜR DIE KOMMENDEN GENERATIONEN!",
167: "Warum Opa Wilhelm keine Menschen mehr empfängt — und wie Nautubone der einzige Weg wurde, an sein Rezept zu gelangen",
168: "„Meine Gesundheit erlaubt es mir nicht mehr, die Kranken persönlich zu empfangen. Aber meine Formel wird weiter heilen — durch die Hände meines Sohnes.“",
169: "Opa Wilhelm Reinhardt:",
170: "— Im vergangenen Jahr habe ich die schwerste Entscheidung meines Lebens getroffen: keine Menschen mehr zu empfangen. Die Warteliste umfasste über 2.000 Namen — und ich konnte sie nicht ohne Hilfe lassen. Deshalb habe ich meinem Sohn Matthias erlaubt, das Rezept dorthin zu bringen, wo man es für alle herstellt. Jetzt bin ich ruhig — Nautubone ist genau das, was ich den Menschen gab, die zu mir kamen, nur in bequemer Form. Das Rezept ist in sicheren Händen.",
171: "Matthias Reinhardt:",
175: "Um sich anzumelden, nutzen Sie das offizielle Bestellformular unten — es kommt direkt vom Produktionsteam von Matthias Reinhardt.",
176: "Verpassen Sie nicht die letzte Gelegenheit in diesem Jahr — Nautubone kann vor dem Ende des Programms ausverkauft sein!",
177: "Matthias Reinhardt:",
178: "— In diesem Jahr ist es uns gelungen, 5&nbsp;000 Packungen der Creme Nautubone speziell für die Menschen in Deutschland herzustellen. Doch angesichts der Nachfrage — die enorm ist — werden diese Mengen schnell aufgebraucht sein. Die nächste Charge wird erst Ende",
180: " fertig sein.",
181: "Das Förderprogramm ist aktiv bis",
182: "— jeder Einwohner Deutschlands über 40 Jahre kann",
183: "bis zu 50 % Rabatt erhalten",
185: "Schieben Sie es nicht auf. Mein Vater hat den Menschen immer gesagt: „Die Gelenke warten nicht auf Sie — sie werden in jeder Sekunde zerstört.“ Solange das Programm läuft, nutzen Sie es. Nautubone hat eine kumulative Wirkung — eine volle Kur reicht für 5–6 Jahre gesunde Gelenke.",
186: "Geben Sie einfach Ihren Namen und Ihre Telefonnummer in das Formular ein. Ein Berater ruft Sie an, erstellt ein individuelles Programm für Ihren Fall und organisiert die Lieferung an jede Adresse in Deutschland — in 2–3 Tagen, per Post oder Kurier bis an Ihre Tür.",
187: "Ich wünsche allen Gesundheit! Kümmern Sie sich heute um Ihre Gelenke, damit Sie morgen gehen können! Mit freundlichen Grüßen: Wilhelm Reinhardt und sein Sohn Matthias.",
188: "Aktualisiert:",
190: "Wegen der außerordentlich großen Nachfrage können die Vorräte von Nautubone vor dem geplanten Ende des Programms aufgebraucht sein! Heute —",
191: "18.12.2025 — ist der letzte Tag für eine Bestellung mit Rabatt",
192: "oder solange der Vorrat reicht.",
193: "Achtung! Schließen und aktualisieren Sie die Seite nicht — die für Sie reservierte Creme Nautubone wird sonst dem Nächsten auf der Warteliste angeboten!",
194: "Ihr reservierter Platz im Programm:",
195: "Nr.",
197: "Offizielles Bestellformular",
198: "Nr.",
202: "Um",
203: "50 % Rabatt",
204: " zu erhalten, geben Sie Name und Telefonnummer in die Felder unten ein und drücken Sie die Schaltfläche „BESTELLEN“.",
205: "Verbleibender Vorrat:",
210: "Name",
211: "Telefonnummer",
212: "BESTELLEN",
213: "✔️ Lieferung an jede Adresse in Deutschland in 2–3 Tagen",
214: "per Post oder Kurier bis an Ihre Tür",
215: "KOMMENTARE:",
216: "Sabine Hoffmann",
217: "Monatelang habe ich auf diesen Text gewartet! Eine Freundin aus München war vor einigen Jahren persönlich bei Opa Wilhelm — sie sagte, er sei ein Wunder von einem Menschen. Schade, dass er niemanden mehr empfängt, aber wenn Nautubone dasselbe Rezept hat — bestelle ich sofort. Ich bin froh, dass ich den Rabatt erwischt habe!",
218: "Petra Lindner",
219: "Der Kurier hat sie mir am Mittwoch gebracht. Seit zehn Tagen trage ich die Creme morgens und abends auf — und der Unterschied ist RIESIG! Ich stehe auf, ohne dieses schreckliche Knirschen! Mein Mann schaut zu und glaubt es nicht. Ich mache die volle Kur von 60 Tagen, aber ich bin jetzt schon überzeugt, dass es wirkt.",
220: "Gertrud Baumann",
221: "Ich bin 72 Jahre alt und habe drei Jahre lang unter Hüftschmerzen gelitten. Das Gehen war eine Qual. Der Orthopäde sagte: „Prothese oder aushalten.“ Ich wollte weder das eine noch das andere. Nautubone hat mir in zwei Monaten geholfen — jetzt gehe ich jeden Tag anderthalb Kilometer spazieren! Und das Röntgenbild zeigt eine Verbesserung, die mein Arzt nicht erklären kann. Danke, Opa Wilhelm, und deinem Sohn!",
222: "Lars Wegener",
223: "Als ehemaliger Sportler weiß ich, was es heißt, mit zerstörtem Knorpel zu leben. Meine Knie waren wie die eines 90-Jährigen — dabei bin ich erst 54. Nautubone hat mir Bewegungen zurückgegeben, die ich 10 Jahre lang nicht gemacht habe. Ich kann wieder in die Hocke gehen! Ich kenne kein anderes Produkt, das so etwas erreicht.",
224: "Monika Reiter",
225: "Ich bin ein bisschen besorgt… Lohnt es sich? Ich bin 66, meine Gelenke knirschen bei jeder Bewegung, und mein Rücken lässt mir keine Ruhe. Aber ich wurde schon so oft von allerlei „Wundermitteln“ enttäuscht, dass es mir schwerfällt zu glauben. Hilft es wirklich?",
226: "Bernd Kaufmann",
227: "Frau Reiter, ich verstehe die Zweifel vollkommen — ich hatte sie auch. Aber Nautubone ist anders als alles, was ich bisher probiert habe. Ich benutze es seit 5 Wochen für die Knie und den Lendenbereich — und ich kann Ihnen sagen, der Unterschied ist wie Tag und Nacht.",
228: "Früher konnte ich mich nicht bücken, um meine Schnürsenkel zu binden. Jetzt mache ich das, ohne nachzudenken. Bestellen Sie wenigstens eine Packung und urteilen Sie selbst — Sie haben nichts zu verlieren!",
229: "Gabriele Pfeifer",
230: "Drei Tage, nachdem ich angefangen habe, die Creme aufzutragen, hat sich mein Knieschmerz halbiert! Jetzt ist der 12. Tag, und ich steige schon Treppen, ohne mich am Geländer festzuhalten. Ich mache die volle Kur — ich glaube, nach zwei Monaten bin ich wie neu!",
231: "Yvonne Krauss",
232: "Auf meinem Rücken begann schon vor zwei Monaten ein „Buckel“ zu wachsen. Ich war entsetzt! Ich habe alle möglichen Salben aus der Apotheke probiert — nichts. Aber die Creme Nautubone ist eine ganz andere Sache — in 40 Tagen ist der Buckel fast vollständig verschwunden! Ich trage sie weiter auf, aber ich bin schon unglaublich zufrieden. So sieht der Unterschied aus:",
233: "Ingrid Sommer",
234: "Ich hatte einen eingeklemmten Nerv im Lendenbereich — vor Schmerzen konnte ich weder schlafen noch stehen. Der Arzt verschrieb mir starke Schmerzmittel, von denen mir ständig übel war. Ich fing an, die Creme Nautubone zweimal täglich aufzutragen — nach einer Woche ließ der Schmerz schlagartig nach, und nach einem Monat — war er vollständig verschwunden! Ich mache die Kur weiter, aber mein Leben hat sich schon verändert!",
235: "Friedrich Ostermann",
236: "Ich bin 79 Jahre alt und konnte drei Jahre lang kaum gehen. Mein Sohn hat mir Nautubone bestellt — ohne mich zu fragen, weil er wusste, dass ich ablehnen würde. Er trägt mir die Creme jeden Morgen und Abend auf. Und das Ergebnis? Nach anderthalb Monaten spaziere ich jeden Tag bis zum Park! Ich fühle mich, als wäre ich 60! Danke, Opa Wilhelm — mit 102 Jahren bist du weiser als alle heutigen Ärzte!",
237: "Dieter Falk",
238: "Vor Nautubone konnte ich die Arme nicht über den Kopf heben — die Schulter knirschte und tat furchtbar weh. Zwei Jahre lang bin ich von Arzt zu Arzt gelaufen — niemand hat geholfen. Zwei Monate mit Nautubone, und meine Arme funktionieren wieder normal. Hier ist mein Röntgenbild — der Arzt selbst hat es nicht geglaubt:",
239: "Anke Riedel",
240: "Ich habe es für meine Schwiegermutter bestellt — sie ist 81 und konnte kaum aus dem Bett aufstehen. Die Ärzte weigerten sich, irgendetwas zu tun — „in diesem Alter hilft nichts mehr“, sagten sie. Mit Nautubone geht sie nach 2 Monaten schon im Hof umher und kocht sogar! Wir konnten es nicht glauben.",
241: "Emil Wagner",
242: "Meine Frau lag vier Monate im Bett — die Wirbelsäule hat einfach versagt. Die Ärzte schlugen eine Operation für 9.000 Euro vor, ohne jede Garantie. Wir beschlossen, die Creme Nautubone zu versuchen — wir hatten nichts zu verlieren. Ich habe sie ihr zweimal täglich aufgetragen. Nach 5 Wochen ist sie aufgestanden. Gestern sind wir zusammen auf den Markt gegangen — zum ersten Mal seit einem halben Jahr! Ich habe vor Glück geweint.",
243: "Nina Berger",
244: "Ich habe letzte Woche bestellt und am dritten Tag erhalten. Ich habe sofort angefangen, die Creme aufzutragen — und die Erleichterung kam am zweiten Tag! Als würde jemand meine Gelenke von innen ölen. Seit zwei Wochen trage ich sie zweimal täglich auf und kann das volle Ergebnis kaum erwarten!",
245: "Rosemarie Kluge",
246: "Ich bin 74 Jahre alt. Fünf Jahre lang habe ich unter Arthrose und Rückenschmerzen gelitten. Ich habe buchstäblich alles probiert — Salben, Tabletten, Spritzen, Physiotherapie. NICHTS hat auf Dauer geholfen. Die Creme Nautubone ist das Einzige, was mir ein ECHTES ERGEBNIS gebracht hat — ich trage sie zweimal täglich auf, und nach anderthalb Monaten fühlen sich meine Gelenke grundlegend anders an. Der Arzt glaubt den Röntgenbildern nicht!",
247: "Vera Pohlmann",
248: "Ich kenne Opa Wilhelm persönlich — vor 12 Jahren hat er mir bei einem Bandscheibenvorfall geholfen. In drei Wochen war ich wieder auf den Beinen! Seinen Namen kennt die ganze Gegend um München. Ich freue mich, dass sein Sohn das Werk fortsetzt!",
249: "Gisela Neumann",
250: "Mein Vater ist 84 Jahre alt und ist drei Jahre lang nicht aus dem Haus gekommen. Die Gelenke, der Rücken, die Knie — alles tat ihm weh. Er sagte, er warte darauf, zu gehen. Nach zwei Monaten mit Nautubone — ist er gestern in den Hof gegangen und hat den Garten gegossen! Zum ersten Mal seit drei Jahren! Ich kann nicht beschreiben, was ich gefühlt habe. Danke von Herzen!!!",
251: "Mirela Dorn",
252: "Weiß jemand, ob man es bei Allergien anwenden kann? Ich reagiere auf fast alles — selbst von gewöhnlichem Aspirin schwellen mir die Finger an. Ich habe Angst, etwas Neues auszuprobieren…",
253: "Kaspar Vogt",
254: "Mirela, ich bin gegen vier Arten von Medikamenten allergisch. Ich trage die Creme Nautubone seit 50 Tagen auf — keinerlei Reizung, keinerlei Schwellung, keinerlei Rötung. Die Zusammensetzung besteht vollständig aus natürlichen Extrakten — sie enthält keine Chemikalien. Sie können beruhigt bestellen!",
255: "Doris Sattler",
256: "Früher hatte ich keine Kraft aufzustehen — jede Bewegung war eine Qual, ich dachte, mein Leben sei vorbei. Meine Tochter hat die Creme Nautubone bestellt und mich gedrängt, sie auszuprobieren — sie hat sie mir morgens und abends aufgetragen. Zwei Monate später? Ich tanze auf der Hochzeit meines Enkels!!! Ich war noch nie in meinem Leben so dankbar!",
257: "Susanne Brandt",
258: "Ich habe es für meine Mutter bestellt. Sie hatte ständige Nackenschmerzen, die Schwindel und Übelkeit verursachten — ihr Leben war unerträglich. In der zweiten Woche mit Nautubone haben die Schmerzen drastisch nachgelassen, und der Schwindel hat vollständig aufgehört! Mama lächelt wieder — so habe ich sie lange nicht gesehen.",
259: "Sonja Menzel",
260: "Ich frage mich — wenn Opa Wilhelm so gut ist, warum werden diese Dinge dann nicht überall verkauft? Warum nur online? Warum bieten die Apotheken sie nicht an?",
261: "Michael Reich",
262: "Weil die Apotheken an denen verdienen, die jeden Monat Schmerzmittel kaufen! Wenn alle ihre Gelenke ein für alle Mal heilen würden — wer würde ihnen dann die teuren Medikamente abkaufen? Denken Sie logisch!",
263: "Olivia Kruse",
264: "Ich habe alle Kommentare gelesen — und bin richtig aufgemuntert. Ich bestelle jetzt, für mich und meinen Mann. Ich habe drei Packungen der Creme genommen, für die volle Kur. Wenn es auch nur zur Hälfte hilft, was die Leute schreiben — bin ich glücklich!",
265: "Lena Marquardt",
266: "Der Orthopäde hat mir gesagt, ich müsse mich mit 63 Jahren an den Schmerz gewöhnen — angeblich gebe es kein Mittel dagegen. Ich habe Nautubone trotzdem bestellt. Wir werden sehen, wer recht hat!",
268: "Avatar hochladen",
269: "Foto hochladen",
270: "SENDEN",
}

RAW = {
172: "— Nautubone wird nicht in Apotheken verkauft — der Herstellungsprozess ist komplex, und die\n      Mengen sind begrenzt. Es ist nur über ein Online-Programm erhältlich, zweimal im Jahr. Doch im Rahmen des\n      Programms erreichen die Rabatte",
174: " — denn unser Ziel ist nicht der Profit,\n      sondern die Verfügbarkeit. Besonders für Rentner, für die mein Vater auf einem maximalen Rabatt bestanden hat.",
184: ".\n      Nach diesem Datum müssen Sie mindestens 6 Monate auf eine neue Gelegenheit warten.",
208: "78\n            €",
209: "39\n            €",
}

ATTRS = {
"Ваше име": "Ihr Name",
"Ваш број телефона": "Ihre Telefonnummer",
"Ваш коментар": "Ihr Kommentar",
}
