# -*- coding: utf-8 -*-
# Ecuador / yerbatero, nodos 0..69 (forma: GEL)
E1 = {
0: "Manuel Guamán, yerbatero de 102 años de los pueblos cercanos a Quito, revela la fórmula para la recuperación completa de las articulaciones — un método al alcance de todo ecuatoriano",
1: "A LOS 102 AÑOS ES EL YERBATERO MÁS ANCIANO DEL ECUADOR Y EL ÚNICO DE SU GENERACIÓN QUE CAMINA SIN BASTÓN. POR PRIMERA VEZ REVELA LA FÓRMULA QUE DURANTE 40 AÑOS ENTREGÓ SOLO A QUIENES LLEGABAN HASTA ÉL.",
2: "Publicado:",
3: "„¿Cómo logró don Manuel Guamán, yerbatero de los pueblos cercanos a Quito, mantener sus articulaciones en perfecto estado hasta los 102 años, mientras que todos los de su edad hace mucho que ya no pueden caminar?“",
4: "En un pueblo no lejos de Quito vive un hombre que contradice todo lo que sabemos sobre el envejecimiento. A los 102 años, el yerbatero Manuel Guamán camina cada mañana por los senderos que están sobre el pueblo, sube las gradas sin ayuda de nadie y jamás en su vida ha usado un bastón. Los de su generación hace tiempo que ya no están entre los vivos o están atados a una silla de ruedas — y él todavía sube solo al cerro a recoger sus plantas.",
5: "Hasta el año pasado, don Manuel recibía a la gente en su propia casa, en el cuarto viejo donde seca las hierbas desde hace décadas. Más de 70 años de trabajo con las plantas, más de 40 000 personas, decenas de columnas y rodillas devueltas a la vida después de que los médicos ya las habían dado por perdidas. Había una lista de espera de seis meses — la gente venía de todo el país para verlo.",
6: "Pero el verdadero misterio no son quienes venían a verlo. El verdadero misterio es él mismo. A los 102 años — ni artritis, ni artrosis, ni una sola hernia discal. Las radiografías de sus articulaciones parecen las de un hombre de 45 años. Los médicos que lo examinan simplemente no dan crédito a sus ojos.",
7: "Durante décadas guardó su receta en secreto — la preparaba él mismo, en su cuarto, y nunca la hizo pública. Pero hoy, cuando la salud ya no le permite recibir a la gente en persona, don Manuel tomó una decisión que lo cambió todo: poner su fórmula al alcance de todo ecuatoriano.",
8: "Don Manuel Guamán: „Toda mi vida vi cómo la gente envejece antes de tiempo — no porque su cuerpo sea débil, sino porque nadie les dijo cómo encender sus propios mecanismos de regeneración. A los 102 años soy la prueba viviente de que",
9: "las articulaciones pueden mantenerse sanas hasta una vejez profunda, si uno sabe cómo „despertar“ las células que las construyen.",
10: "MI META SIEMPRE FUE UNA SOLA — AYUDAR AL CUERPO A PRODUCIR TEJIDO NUEVO DE CARTÍLAGO Y HUESO, EXACTAMENTE COMO EN LA JUVENTUD. AHORA MI HIJO ANDRÉS CONVIRTIÓ TODO ESTO EN UN PRODUCTO",
11: "QUE PUEDE LLEGAR A CADA CASA DEL ECUADOR.",
12: "Andrés Guamán — el hijo del yerbatero — creció entre las hierbas secas y las balanzas de su padre y aprendió el oficio desde niño. No se hizo médico. Durante años convenció a su padre de que la receta no se quedara encerrada en una sola casa, y después él mismo encontró un laboratorio y a las personas que ayudaron a convertir la experiencia de décadas de don Manuel en un producto al alcance de cualquiera — para que llegue a todos los que lo necesitan.",
13: "El resultado de esta colaboración superó todas las expectativas. Pero antes de contarle sobre el producto, veamos por qué todo lo que usted sabe sobre el tratamiento de las articulaciones es, con la mayor probabilidad, equivocado.",
14: "La mentira que se cree todo el Ecuador:",
15: "„Los analgésicos curan las articulaciones“ — ERROR, ¡las destruyen todavía más rápido!",
16: "Don Manuel Guamán:",
17: "— Llevo setenta años curando gente y le voy a decir algo que las farmacias jamás van a reconocer: ningún analgésico en la historia de la medicina ha regenerado ni un milímetro de cartílago. ¡Ninguno! Callan el dolor, pero mientras tanto el cartílago sigue destruyéndose — solo que usted ya no lo siente. Y cuando lo vuelva a sentir, será demasiado tarde.",
18: "Pero eso no es lo peor. Lo peor es lo que esas sustancias químicas les hacen a sus órganos internos. En 70 años de trabajo he visto a cientos de personas con el hígado y los riñones completamente destruidos — no por la enfermedad, ¡sino por los medicamentos! El cuerpo no fue hecho para tragar química durante décadas. Y sin embargo, eso es exactamente lo que „receta“ la medicina convencional.",
19: "La columna es especialmente vulnerable. Los discos intervertebrales no tienen irrigación sanguínea propia — se alimentan por difusión, lo que significa que su daño avanza en silencio, sin dolor, a veces durante años. Cuando el dolor por fin aparece, el daño ya está avanzado. La compresión del nervio por una hernia discal convierte la vida en una pesadilla: empieza con un leve adormecimiento en la pierna y termina con la pérdida total de movilidad.",
20: "Mire lo que muestra esta radiografía. Una mujer de apenas 39 años, profesora — y su columna está en un estado que hace 20 años yo veía recién en personas de 70. Ocho horas al día sentada en una silla, falta de movimiento y desconocimiento total del propio cuerpo — eso es lo que trae la vida moderna.",
21: "Imagen del archivo que don Manuel guarda desde hace décadas: la columna de una profesora de 39 años de Cuenca. Llegó con „un ligero cansancio en la cintura“ — la radiografía reveló tres discos dañados, una hernia incipiente y microfisuras en la cubierta del cartílago.",
22: "Si después de los 40 siente dolor, rigidez o crujidos en las articulaciones — su cartílago ya se está destruyendo. Esto no es „por el cansancio“ y no es „normal“.",
23: "En la columna el proceso es varias veces más rápido y más traicionero — ¡el dolor aparece recién cuando el daño ya es crítico!",
24: "— Quiero ser completamente franco. Conozco gente que fue dejando pasar los meses. ¿El resultado? Un nervio comprimido que nunca más volvió a funcionar con normalidad. Recuperar los discos cuando el nervio ya está muerto no sirve de nada —",
25: "¡EL DISCO PUEDE VOLVER, PERO EL NERVIO — NO!",
26: "¿Y qué queda entonces? ¡BASTÓN, SILLA DE RUEDAS Y DEPENDENCIA DE LA AYUDA AJENA HASTA EL FINAL DE LA VIDA!",
27: "¿Y qué ofrece la cirugía moderna? Operaciones caras y riesgosas con implantes metálicos. Personalmente he visto a cientos de personas que después de una operación de columna se sentían PEOR que antes.",
28: "INFECCIONES, FUSIONES QUE NO PEGAN, DOLOR CRÓNICO Y, AL FINAL — OTRA OPERACIÓN. Y A VECES — ¡DAÑOS IRREVERSIBLES!",
29: "Don Manuel muestra una radiografía que le trajo un hombre después de una operación con tornillos metálicos: „Este es el resultado típico — el implante no se fijó bien, los tejidos alrededor están inflamados y el dolor es más fuerte que antes de la operación. He visto cientos de casos parecidos.“",
30: "La estadística es implacable: en el 60% de los operados la hernia regresa en 2 a 4 años. ¿Y el precio? Meses de inmovilidad, miles de dólares y una incertidumbre total. Muchos lo reconocen: si pudieran devolver el tiempo, jamás se habrían acostado en la mesa de operaciones.",
31: "¡Estos síntomas significan que su cartílago ya se está muriendo! Y si usted pasa de los 40 o 50 años — ¡el proceso es irreversible sin intervención!",
32: "— En 70 años pasaron por mis manos más de 40 000 personas y puedo decirle lo siguiente: cada dolor de articulaciones que se ignora es un paso hacia la silla de ruedas. Solo en",
33: "en el Ecuador se registraron más de 345 000 nuevos casos de enfermedades articulares graves — de los cuales 63 000 en personas de entre 38 y 48 años. Este no es un problema de la vejez. Es un problema de no hacer nada.",
34: "Si su organismo ya le dio alguna de estas señales — ¡no espere ni un día!",
35: "Esta es la lista que le decía a cada persona apenas cruzaba el umbral:",
36: "Rigidez matutina que no se quita con el movimiento;",
37: "Crujidos, chasquidos o rechinar al moverse;",
38: "Aumento del dolor cuando cambia el clima;",
39: "Dificultad para doblar o estirar las rodillas;",
40: "Hinchazón, enrojecimiento o calor alrededor de la articulación;",
41: "Dolor al subir o bajar gradas;",
42: "Cansancio crónico y pesadez en las piernas;",
43: "Dolor en la cintura que „dispara“ hacia el muslo o el pie;",
44: "Adormecimiento u hormigueo en los dedos;",
45: "Cambio en la forma de caminar — cojera, inestabilidad;",
46: "Imposibilidad de estar de pie más de 10 a 15 minutos;",
47: "Si se reconoce aunque sea en dos de estos síntomas — su cartílago ya se está destruyendo. Y en la columna el proceso es tres o cuatro veces más rápido, porque los discos intervertebrales están bajo presión permanente.",
48: "EL RESULTADO: HERNIA, NERVIO COMPRIMIDO, DEFORMACIÓN DE LAS VÉRTEBRAS, PÉRDIDA DE MOVILIDAD — ¡Y TODO ESTO PUEDE OCURRIR EN POCAS SEMANAS!",
49: "No lo deje para después, ¡porque el organismo no da oportunidades infinitas!",
50: "Mire a estas personas que están más abajo. Cada una de ellas tuvo los mismos síntomas que usted probablemente siente en este momento. Cada una dijo „ya se pasará“. Y cada una daría hoy cualquier cosa por devolver el tiempo y actuar cuando todavía tenía la oportunidad.",
51: "Expaciente de otra clínica, 58 años, Guayaquil. Tres vértebras desplazadas más de 8 mm, la médula espinal bajo presión. Dos veces se negó a ir donde don Manuel — cuando por fin llegó, estaba a un paso de la parálisis.",
52: "Mujer de 61 años de Ambato — la joroba le creció hasta 4 cm en menos de un año. Las vértebras cervicales están deformadas al punto de que ya no puede girar la cabeza hacia un lado. Los analgésicos dejaron de hacerle efecto hace 8 meses.",
53: "Ama de casa, 59 años, Machala. Las articulaciones de las rodillas están tan gastadas que el cartílago se adelgazó a menos de 1 mm. Cada paso suena como el chirrido de una puerta vieja. Tres ortopedistas le dijeron que la única solución es una prótesis doble, por más de 8 000 dólares.",
54: "Exminero, 68 años, Portovelo. El cartílago de la rodilla derecha está completamente destruido, el tejido óseo entró en fase de necrosis. Cuatro meses de demora le costaron la pierna — amputación por encima de la rodilla y dependencia de por vida de la silla de ruedas.",
55: "Tengo 102 años y puedo decirle por experiencia propia: el organismo es capaz de regenerarse solo a CUALQUIER edad — siempre que usted sepa CÓMO encenderlo. A eso mismo le dediqué la vida.",
56: "Y SI USTED YA PASÓ LOS 50 O 60 AÑOS, ¡NO ESPERE NI UN SEGUNDO!",
57: "En su caso el daño casi con seguridad entró en fase crítica — ¡hay que detener urgentemente la destrucción y encender la regeneración de cartílago nuevo, huesos nuevos y tejidos nuevos!",
58: "¡Casos que los médicos declararon sin esperanza!",
59: "Rosario Cedeño, a los 86 años, volvió a caminar sin ayuda de nadie, después de que tres hospitales la rechazaran. Esta es su historia…",
60: "Rosario Cedeño, de Loja, sufría de artrosis severa de rodillas y de múltiples hernias discales. Tres hospitales distintos la rechazaron — en todos le decían lo mismo: „A su edad ya no se puede hacer nada.“ Su hija escuchó por casualidad sobre don Manuel de unos conocidos de un pueblo cercano a Quito y decidió buscarlo.",
61: "„Vivía como en una cárcel — mi propia casa se volvió una celda. No lograba llegar al baño, no podía estar de pie más de un minuto, ni siquiera podía prepararme un té. Mis hijos trabajaban y no podían venir todos los días. Me quedaba acostada mirando el techo. Los médicos dijeron que a mi edad no tenía sentido operar y solo me dieron analgésicos.",
62: "Cuando mi hija me llevó donde don Manuel, él me miró y me dijo algo que ningún médico me había dicho: „Doña Rosario, su cuerpo NO ha dejado de luchar. Lo que pasa es que nadie lo ha ayudado.“ Me dio lo que él mismo prepara y me dijo que tuviera paciencia. A la tercera semana, por primera vez en un año y medio, ¡ME LEVANTÉ SOLA de la cama!",
63: "Hoy, cinco meses después, voy a la tienda, cocino, incluso cuido el jardincito de flores frente a la casa. ¡A los 86 años! Cuando los vecinos me vieron en el patio, no lo podían creer. Pensaban que ya no me volverían a ver. Don Manuel me devolvió la vida — y no tengo palabras para agradecerle.“",
64: "Rosario Cedeño, 86 años, Loja",
65: "Otro caso excepcional es el de Wilson Zambrano — albañil de 47 años de Manta, quien después de 20 años de trabajo físico pesado sufrió un daño grave en la columna y se vio obligado a movilizarse en silla de ruedas.",
66: "Wilson probó el método de don Manuel, y los resultados dejaron impactado incluso a su médico de cabecera.",
67: "SU COLUMNA EMPEZÓ A RECUPERARSE, EL DOLOR DESAPARECIÓ POR COMPLETO Y, LO MÁS INCREÍBLE —",
68: "¡DEJÓ LA SILLA DE RUEDAS DESPUÉS DE SOLO 4 SEMANAS!",
69: "Wilson nos contó:",
}
