# -*- coding: utf-8 -*-
# Suomi / yrttiparantaja, solmut 0..69 (lääkemuoto: KAPSELI)
F1 = {
0: "Toivo Mäkelä, 102-vuotias yrttiparantaja Helsingin lähikylistä, paljastaa nivelten täydellisen palautumisen kaavan — menetelmän, joka on jokaisen suomalaisen ulottuvilla",
1: "102-VUOTIAANA HÄN ON SUOMEN VANHIN YRTTIPARANTAJA JA SUKUPOLVENSA AINOA, JOKA KÄVELEE ILMAN KEPPIÄ. NYT HÄN PALJASTAA ENSIMMÄISTÄ KERTAA KAAVAN, JONKA HÄN 40 VUODEN AJAN ANTOI VAIN NIILLE, JOTKA TULIVAT HÄNEN LUOKSEEN.",
2: "Julkaistu:",
3: "„Kuinka Toivo-vaari, yrttiparantaja Helsingin lähikylistä, onnistui pitämään nivelensä täydellisessä kunnossa 102 vuoden ikään asti, kun kaikki hänen ikätoverinsa eivät ole enää pitkään aikaan pystyneet kävelemään?“",
4: "Eräässä kylässä lähellä Helsinkiä asuu mies, joka kumoaa kaiken, mitä tiedämme vanhenemisesta. 102-vuotiaana yrttiparantaja Toivo Mäkelä kävelee joka aamu kylän yläpuolisia polkuja, nousee portaat ilman apua eikä ole koskaan elämässään käyttänyt keppiä. Hänen ikätovereistaan useimmat eivät ole enää elossa tai ovat sidottuja pyörätuoliin — hän taas nousee yhä itse mäelle keräämään yrttejä.",
5: "Viime vuoteen asti Toivo-vaari otti ihmisiä vastaan kotonaan, siinä vanhassa huoneessa, jossa hän on kuivannut yrttejä vuosikymmenten ajan. Yli 70 vuotta työtä yrttien parissa, yli 40 000 ihmistä, kymmeniä selkärankoja ja polvia palautettuna elämään sen jälkeen, kun lääkärit olivat jo luovuttaneet. Jonotuslista oli kuuden kuukauden mittainen — ihmisiä tuli häntä tapaamaan koko maasta.",
6: "Mutta todellinen arvoitus eivät ole ne, jotka tulivat hänen luokseen. Todellinen arvoitus on hän itse. 102-vuotiaana — ei niveltulehdusta, ei nivelrikkoa, ei ainuttakaan välilevytyrää. Hänen nivelistään otetut röntgenkuvat näyttävät 45-vuotiaan miehen kuvilta. Häntä tutkivat lääkärit eivät yksinkertaisesti usko silmiään.",
7: "Vuosikymmenten ajan hän piti reseptinsä salassa — valmisti sen itse, omassa huoneessaan, eikä koskaan julkaissut sitä. Mutta tänään, kun terveys ei enää salli ihmisten vastaanottamista henkilökohtaisesti, Toivo-vaari teki päätöksen, joka muutti kaiken: hän saattaa kaavansa jokaisen suomalaisen ulottuville.",
8: "Toivo Mäkelä: „Koko elämäni olen katsonut, kuinka ihmiset vanhenevat ennen aikojaan — ei siksi, että heidän kehonsa olisi heikko, vaan siksi, ettei kukaan ole kertonut heille, kuinka käynnistää omat uudistumisen mekanisminsa. 102-vuotiaana olen elävä todiste siitä, että",
9: "nivelet voivat pysyä terveinä syvään vanhuuteen asti, jos tietää, kuinka „herättää“ ne solut, jotka niitä rakentavat.",
10: "PÄÄMÄÄRÄNI ON AINA OLLUT VAIN YKSI — AUTTAA KEHOA TUOTTAMAAN UUTTA RUSTO- JA LUUKUDOSTA, AIVAN KUTEN NUORUUDESSA. NYT POIKANI MIKKO ON MUUTTANUT KAIKEN TÄMÄN TUOTTEEKSI,",
11: "JOKA VOI SAAPUA JOKAISEEN KOTIIN SUOMESSA.",
12: "Mikko Mäkelä — yrttiparantajan poika — kasvoi isänsä kuivattujen yrttien ja vaakojen keskellä ja oppi ammatin jo lapsena. Hänestä ei tullut lääkäriä. Vuosien ajan hän suostutteli isäänsä, ettei resepti jäisi lukkojen taakse yhteen taloon, ja löysi sitten itse laboratorion ja ihmiset, jotka auttoivat muuttamaan Toivo-vaarin vuosikymmenten kokemuksen kaikkien saatavilla olevaksi tuotteeksi — jotta se saavuttaisi kaikki, jotka sitä tarvitsevat.",
13: "Tämän yhteistyön tulos ylitti kaikki odotukset. Mutta ennen kuin kerron tuotteesta, katsotaan, miksi kaikki, mitä tiedät nivelten hoidosta, on mitä todennäköisimmin väärin.",
14: "Valhe, johon koko Suomi uskoo:",
15: "„Kipulääkkeet hoitavat niveliä“ — VIRHE, ne tuhoavat niitä vielä nopeammin!",
16: "Toivo Mäkelä:",
17: "— Olen hoitanut ihmisiä seitsemänkymmentä vuotta ja kerron teille jotain, mitä apteekit eivät koskaan myönnä: yksikään kipulääke lääketieteen historiassa ei ole palauttanut millimetriäkään rustoa. Ei yksikään! Ne vaimentavat kivun, mutta sillä välin rusto jatkaa hajoamistaan — te ette vain enää tunne sitä. Ja kun tunnette sen jälleen, on jo liian myöhäistä.",
18: "Mutta se ei ole pahinta. Pahinta on se, mitä nämä kemialliset aineet tekevät sisäelimillenne. 70 työvuoden aikana olen nähnyt satoja ihmisiä, joiden maksa ja munuaiset olivat täysin pilalla — ei sairaudesta, vaan lääkkeistä! Kehoa ei ole luotu nielemään kemikaaleja vuosikymmeniä. Ja silti juuri sitä tavanomainen lääketiede „määrää“.",
19: "Selkäranka on erityisen haavoittuva. Nikamavälilevyillä ei ole omaa verenkiertoa — ne saavat ravintonsa diffuusiolla, mikä tarkoittaa, että niiden vaurioituminen etenee hiljaa, kivutta, joskus vuosien ajan. Kun kipu vihdoin ilmaantuu, vaurio on jo pitkällä. Välilevytyrän aiheuttama hermon puristus muuttaa elämän painajaiseksi: se alkaa lievästä puutumisesta jalassa ja päättyy täydelliseen liikuntakyvyn menetykseen.",
20: "Katsokaa, mitä tämä röntgenkuva näyttää. Nainen, vain 39-vuotias, opettaja — ja hänen selkärankansa on sellaisessa kunnossa, jollaisen näin 20 vuotta sitten vasta 70-vuotiailla. Kahdeksan tuntia päivässä tuolilla istumista, liikkumattomuutta ja täydellistä oman kehon tuntemattomuutta — sitä nykyinen elämäntapa tuo mukanaan.",
21: "Kuva arkistosta, jota Toivo-vaari on säilyttänyt vuosikymmeniä: 39-vuotiaan tamperelaisen opettajan selkäranka. Hän tuli „lievän alaselän väsymyksen“ takia — röntgen paljasti kolme vaurioitunutta välilevyä, alkavan tyrän ja mikrohalkeamia rustokalvossa.",
22: "Jos tunnet 40 ikävuoden jälkeen kipua, jäykkyyttä tai rutinaa nivelissäsi — rustosi on jo hajoamassa. Tämä ei johdu „väsymyksestä“ eikä tämä ole „normaalia“.",
23: "Selkärangassa prosessi on monta kertaa nopeampi ja petollisempi — kipu ilmaantuu vasta silloin, kun vaurio on jo kriittinen!",
24: "— Haluan olla täysin suora. Tunnen ihmisiä, jotka lykkäsivät asiaa kuukausikaupalla. Lopputulos? Puristuksissa ollut hermo, joka ei koskaan enää toiminut normaalisti. Välilevyjen palauttaminen silloin, kun hermo on jo kuollut, on hyödytöntä —",
25: "VÄLILEVY VOI PALATA, MUTTA HERMO — EI!",
26: "Ja mitä silloin jää jäljelle? KEPPI, PYÖRÄTUOLI JA RIIPPUVUUS TOISTEN AVUSTA ELÄMÄN LOPPUUN ASTI!",
27: "Ja mitä nykyaikainen kirurgia tarjoaa? Kalliita ja riskialttiita leikkauksia metalli-implanteilla. Olen itse nähnyt satoja ihmisiä, jotka selkäleikkauksen jälkeen voivat HUONOMMIN kuin ennen sitä.",
28: "TULEHDUKSIA, EPÄONNISTUNEITA LUUTUMISIA, KROONISTA KIPUA JA LOPULTA — UUSI LEIKKAUS. JA JOSKUS — PERUUTTAMATTOMIA VAURIOITA!",
29: "Toivo-vaari näyttää kuvaa, jonka hänelle toi mies metalliruuveilla tehdyn leikkauksen jälkeen: „Tämä on tyypillinen lopputulos — implantti ei kiinnittynyt kunnolla, ympäröivät kudokset ovat tulehtuneet ja kipu on voimakkaampi kuin ennen leikkausta. Olen nähnyt satoja samanlaisia tapauksia.“",
30: "Tilastot ovat armottomat: 60 %:lla leikatuista tyrä palaa 2–4 vuodessa. Ja hinta? Kuukausia liikkumattomuutta, tuhansia euroja ja täydellinen epävarmuus. Monet myöntävät: jos he voisivat kääntää ajan takaisin, he eivät koskaan menisi leikkauspöydälle.",
31: "Nämä oireet tarkoittavat, että rustosi on jo kuolemassa! Ja jos olet yli 40–50-vuotias — prosessi on peruuttamaton ilman puuttumista!",
32: "— 70 vuoden aikana käsieni kautta on kulkenut yli 40 000 ihmistä ja voin sanoa seuraavaa: jokainen sivuutettu nivelkipu on askel kohti pyörätuolia. Pelkästään",
33: "Suomessa on kirjattu yli 108 000 uutta vakavaa nivelsairaustapausta — joista 20 000 on 38–48-vuotiailla. Tämä ei ole vanhuuden ongelma. Tämä on toimimattomuuden ongelma.",
34: "Jos elimistösi on jo antanut jonkin näistä merkeistä — älä odota päivääkään!",
35: "Tässä on lista, jonka kerroin jokaiselle ihmiselle jo kynnyksellä:",
36: "Aamujäykkyys, joka ei helpota liikkumalla;",
37: "Rutina, naksuminen tai narina liikkeessä;",
38: "Kivun voimistuminen sään vaihtuessa;",
39: "Vaikeus koukistaa tai suoristaa polvia;",
40: "Turvotus, punoitus tai kuumotus nivelen ympärillä;",
41: "Kipu portaita noustessa tai laskeutuessa;",
42: "Krooninen väsymys ja raskaus jaloissa;",
43: "Alaselän kipu, joka „ampuu“ reiteen tai jalkapohjaan;",
44: "Puutuminen tai pistely sormissa;",
45: "Kävelyn muuttuminen — ontuminen, epävakaus;",
46: "Kyvyttömyys seistä jaloillaan yli 10–15 minuuttia;",
47: "Jos tunnistat itsesi jo kahdesta näistä oireista — rustosi on jo tuhoutumassa. Ja selkärangassa prosessi on kolme–neljä kertaa nopeampi, koska nikamavälilevyt ovat jatkuvan paineen alla.",
48: "LOPPUTULOS: TYRÄ, PURISTUKSISSA OLEVA HERMO, NIKAMIEN VÄÄNTYMINEN, LIIKUNTAKYVYN MENETYS — JA KAIKKI TÄMÄ VOI TAPAHTUA MUUTAMASSA VIIKOSSA!",
49: "Älä lykkää, sillä elimistö ei anna loputtomia mahdollisuuksia!",
50: "Katsokaa näitä ihmisiä alla. Jokaisella heistä oli samat oireet, joita sinäkin luultavasti tunnet tällä hetkellä. Jokainen sanoi „kyllä se menee ohi“. Ja jokainen antaisi tänään mitä tahansa saadakseen ajan takaisin ja toimiakseen silloin, kun mahdollisuus vielä oli.",
51: "Toisen klinikan entinen potilas, 58 vuotta, Turku. Kolme nikamaa siirtynyt yli 8 mm, selkäydin paineen alla. Hän kieltäytyi kahdesti menemästä Toivo-vaarin luo — kun hän vihdoin tuli, hän oli askeleen päässä halvaantumisesta.",
52: "61-vuotias nainen Oulusta — kyttyrä kasvoi hänelle 4 senttimetriin alle vuodessa. Kaulanikamat ovat vääntyneet niin pahasti, ettei päätä voi enää kääntää sivulle. Kipulääkkeet lakkasivat tehoamasta 8 kuukautta sitten.",
53: "Kotiäiti, 59 vuotta, Jyväskylä. Polvinivelet ovat kuluneet niin pahoin, että rusto on ohentunut alle 1 millimetriin. Jokainen askel kuulostaa vanhan oven narinalta. Kolme ortopedia sanoi hänelle, että ainoa ratkaisu on kaksoisproteesi, yli 9 000 euroa.",
54: "Entinen kaivosmies, 68 vuotta, Outokumpu. Oikean polven rusto on täysin tuhoutunut, luukudos on siirtynyt kuolion vaiheeseen. Neljän kuukauden lykkäys maksoi hänelle raajan — amputaatio polven yläpuolelta ja elinikäinen riippuvuus pyörätuolista.",
55: "Olen 102-vuotias ja voin sanoa omasta kokemuksestani: elimistö kykenee uudistamaan itsensä MISSÄ TAHANSA iässä — sillä ehdolla, että tiedät, MITEN se käynnistetään. Juuri tähän olen omistanut elämäni.",
56: "JA JOS OLET JO YLI 50–60-VUOTIAS, ÄLÄ ODOTA SEKUNTIAKAAN!",
57: "Sinulla vaurio on lähes varmasti siirtynyt kriittiseen vaiheeseen — tuhoutuminen on pysäytettävä kiireesti ja käynnistettävä uuden ruston, uusien luiden ja uusien kudosten uudistuminen!",
58: "Tapaukset, jotka lääkärit julistivat toivottomiksi!",
59: "Aino Virtanen, 86-vuotias, kävelee jälleen ilman toisten apua sen jälkeen, kun kolme sairaalaa oli hylännyt hänet. Tässä on hänen tarinansa…",
60: "Kuopiolainen Aino Virtanen kärsi vaikeasta polvien nivelrikosta ja useista välilevytyristä. Kolme eri sairaalaa hylkäsi hänet — kaikkialla hänelle sanottiin samaa: „Tässä iässä ei enää voi tehdä mitään.“ Hänen tyttärensä kuuli sattumalta Toivo-vaarista tuttavilta eräästä Helsingin lähikylästä ja päätti etsiä hänet käsiinsä.",
61: "„Elin kuin vankilassa — omasta talostani tuli selli. En päässyt vessaan asti, en pystynyt seisomaan minuuttia kauempaa, en osannut edes keittää itselleni teetä. Lapseni olivat töissä eivätkä voineet tulla joka päivä. Makasin ja tuijotin kattoa. Lääkärit sanoivat, ettei leikkauksessa ole tässä iässä järkeä, ja antoivat vain kipulääkkeitä.",
62: "Kun tyttäreni vei minut Toivo-vaarin luo, hän katsoi minua ja sanoi jotain, mitä yksikään lääkäri ei ollut sanonut: „Aino-rouva, kehonne EI ole lakannut taistelemasta. Kukaan ei vain ole auttanut sitä.“ Hän antoi minulle sitä, mitä itse valmistaa, ja käski olla kärsivällinen. Kolmannella viikolla NOUSIN ITSE sängystä ensimmäistä kertaa puoleentoista vuoteen!",
63: "Tänään, viisi kuukautta myöhemmin, käyn kaupassa, laitan ruokaa ja hoidan jopa talon edessä olevaa kukkapenkkiä. 86-vuotiaana! Kun naapurit näkivät minut pihalla, he eivät uskoneet silmiään. He luulivat, etteivät näe minua enää koskaan. Toivo-vaari antoi minulle elämäni takaisin — enkä löydä sanoja kiittääkseni häntä.“",
64: "Aino Virtanen, 86 vuotta, Kuopio",
65: "Toinen poikkeuksellinen tapaus on Jarmo Laitinen — 47-vuotias rakennusmies Lahdesta, joka 20 raskaan ruumiillisen työn vuoden jälkeen sai vakavan selkärankavaurion ja joutui liikkumaan pyörätuolilla.",
66: "Jarmo kokeili Toivo-vaarin menetelmää, ja tulokset järkyttivät jopa hänen omalääkäriään.",
67: "HÄNEN SELKÄRANKANSA ALKOI PALAUTUA, KIPU KATOSI KOKONAAN, JA KAIKKEIN USKOMATTOMINTA —",
68: "HÄN JÄTTI PYÖRÄTUOLIN VAIN 4 VIIKON JÄLKEEN!",
69: "Jarmo kertoi meille:",
}
