# -*- coding: utf-8 -*-
# Suomi / yrttiparantaja, solmut 70..164 (lääkemuoto: KAPSELI)
F2 = {
70: "„Kaksikymmentä vuotta rakensin taloja, mutta omasta selästäni en pitänyt huolta. Eräänä aamuna heräsin enkä pystynyt liikuttamaan alaselkääni. Vaimoni soitti ambulanssin. Diagnoosi — kolme tyrää ja hermojuuren puristus. Lääkärit ehdottivat 6 500 euron leikkausta, mutta ilman takeita.",
71: "Kuukausikaupalla istuin kotona pyörätuolissa. Lapset katsoivat minua surullisina, vaimo itki joka ilta. Tunsin olevani taakka. Toivoin katoavani…",
72: "Silloin appeni kuuli Toivo-vaarista mieheltä, jota tämä oli auttanut. Soitin, lähetin röntgenkuvat, ja vanhus sanoi: „Ei ole myöhäistä.“ Ne kolme sanaa antoivat minulle enemmän toivoa kuin kaikki, mitä olin kuullut kymmeniltä lääkäreiltä.",
73: "Neljäntenä päivänä pystyin jo seisomaan. Täysi kuuri kesti 80 päivää. Nykyään käyn taas töissä — en työmaalla vaan toimistossa, mutta KÄVELEN. Juoksen lasten kanssa puistossa. Elän. Röntgen näyttää, että välilevyni ovat palautuneet 90-prosenttisesti. Toivo-vaari on ainoa, joka ei kääntänyt minulle selkäänsä — ja ainoa, joka auttoi.“",
74: "Niiden tuhansien ihmisten tarinat, joita Toivo-vaari on auttanut, ovat aivan yhtä hämmästyttäviä: ihmiset, joille lääkärit sanoivat „totu kipuun“, kävelivät jälleen, juoksivat jälleen, elivät jälleen. Kuinka se on mahdollista?",
75: "Kaava, jota Toivo-vaari valmisti omin käsin yli 40 vuoden ajan!",
76: "„Endogeenisen kudosaktivaation“ menetelmän salaisuus — kuinka elimistö alkaa itse tuottaa uutta rustoa, uutta luuta ja uusia nivelsiteitä!",
77: "— Sallikaa minun selittää jotain, mitä tavanomainen lääketiede kieltäytyy myöntämästä. Jokaisen ihmisen elimistössä — jopa 90-vuotiaan — on „nukahtaneita“ uudistavia soluja. Samoja soluja, jotka nuoruudessa rakensivat teille vaivatta rustoa, luuta ja nivelsiteitä. Vuosien myötä ne eivät kuole — ne vain „nukahtavat“, koska elimistö lakkaa lähettämästä niille oikeita signaaleja.",
78: "Neljäkymmentä vuotta sitten huomasin, että tietty luonnonaineiden yhdistelmä — tarkasti määritellyissä suhteissa — toimii näille nukkuville soluille kuin virta-avain. Nimesin menetelmän",
79: "„Endogeeninen kudosaktivaatio“",
80: "— koska se ei tuo mitään keinotekoista, vaan aktivoi elimistön omat voimavarat. Juuri siksi minulla EI ole haittavaikutuksia, EI elinvaurioita eikä riippuvuutta.",
81: "Neljän vuosikymmenen ajan sovelsin tätä menetelmää jokaiseen, joka astui kynnykseni yli — ja jokaisen kohdalla kirjasin saman tuloksen: tuhoutuminen pysähtyy, kipu vähenee ja nivelten toiminta palautuu vähitellen. Sadat ihmiset, jotka tulivat luokseni „viimeisenä oljenkortena“, lähtivät kotoani omilla jaloillaan.",
82: "Itse kaava ei ole monimutkainen — mutta tarkkuus on kaikki kaikessa. Jokaista ainesosaa on oltava juuri oikea määrä, milligramman sadasosaa myöten. Jos suhteita ei noudateta, vaikutus yksinkertaisesti katoaa. Juuri siksi sovelsin menetelmää vuosikymmeniä itse — koska en voinut uskoa sitä apteekkien käsiin.",
83: "Kapselin koostumus yrttiparantaja Mäkelän reseptin mukaan (vaikuttavat aineet annosta kohti):",
84: "Omega-3",
85: "pellavansiemen: 4500 mg",
86: "Glukosamiinisulfaatti",
87: "äyriäiset: 1100 mg",
88: "Magnesiumsitraatti",
89: "merilevä: 390 mg",
90: "Gingeroli",
91: "inkivääri: uute 4200 mg",
92: "AKBA",
93: "suitsukepihka (Boswellia): uute 1100 mg",
94: "Pii",
95: "peltokorte: uute 320 mg",
96: "Kurkumiini",
97: "kurkuma: uute 2300 mg",
98: "Nämä ainesosat vaikuttavat yksinkertaisilta, mutta niiden löytäminen oikeanlaatuisina ja oikeasta lähteestä on erittäin vaikeaa. Useimpia niistä ei ole apteekeissa, ja ne on tuotava eri puolilta maailmaa. Kotona sekoittaminen taas on käytännössä mahdotonta — koska annostelun on oltava tarkkaa 0,1 milligramman tarkkuudella.",
99: "Juuri siksi valmistin seosta vuosikymmeniä itse, jokaiselle ihmiselle erikseen. Mutta poikani Mikko näki koko kuvan.",
100: "Kuinka Mikko Mäkelä muutti isänsä 40 vuotta vanhan reseptin kaikkien saatavilla oleviksi kapseleiksi — Nautubone",
101: "Mikko Mäkelä:",
102: "— Kasvoin isäni yrttihuoneessa. Joka päivä näin, kuinka ihmiset tulivat sisään kivusta kaksinkerroin — ja lähtivät hymyillen. 14-vuotiaana osasin reseptin jo ulkoa. Minusta ei tullut lääkäriä — ammatin opin häneltä. Mutta vuosien ajan suostuttelin häntä: isä, tämä resepti ei saa jäädä lukkojen taakse yhteen taloon. Tuhannet ihmiset odottavat sitä, mitä sinä pidät hyllylläsi.",
103: "Viisi vuotta kiertelin laboratorioita Helsingissä ja Münchenissä, kunnes löysin ihmiset, jotka halusivat tutkia isäni reseptiä vakavasti. Saamani vastaus innosti minua: näiden ainesosien yhdistelmä juuri näissä suhteissa käynnistää tyypin II kollageenin ja proteoglykaanien tuotannon — ruston kahden tärkeimmän rakennusaineen. Toisin sanoen: elimistö kirjaimellisesti „muistaa“, kuinka rakentaa uutta rustoa, se tarvitsee vain oikean signaalin.",
104: "Yhdessä laboratorion kanssa kehitimme menetelmän, jonka nimesimme",
105: "„Nanodiffuusioteknologia parannetulla hyötyosuudella“",
106: "— menetelmä, jossa vaikuttavat aineet suljetaan erityisiin nanohiukkasiin, jotka vapautuvat suoraan ohutsuolessa maksa-aineenvaihdunnan ohittaen ja kulkeutuvat verenkierron mukana täsmälleen vaurioituneeseen nivelkudokseen. Tämä lisää imeytymistä noin 380 % tavallisiin tabletteihin verrattuna. Nimesin tuotteen",
107: "Nautubone",
108: "— suun kautta otettava kapseli, joka vaikuttaa juuri siellä, missä sitä tarvitaan. Nimesin sen isäni ja hänen 40 työvuotensa kunniaksi.",
109: "Nautubone-kapseli sisältää kaikki seitsemän isäni alkuperäisen reseptin ainesosaa sekä 29 lisäuutetta ja vitamiinia, jotka lisäsimme Münchenin laboratoriotutkimusten jälkeen. Tuloksena on tuote, joka toimii AIVAN YHTÄ HYVIN kuin se, mitä isäni valmisti omin käsin — mutta joka voidaan toimittaa jokaiseen kotiin Suomessa. Otat yhden kapselin kahdesti päivässä, ja vaikuttavat aineet kulkeutuvat verenkierron mukana suoraan vaurioituneisiin niveliin.",
110: "„Nautubone on isäni perintö — hänen 40 vuoden kokemuksensa suljettuna yhteen kaavaan. Jokainen ainesosa on valittu samalla tarkkuudella, jolla hän kumartui jokaisen ovelleen tulleen ihmisen puoleen. Tämä ei ole massatuote apteekin hyllyltä — tämä on kokonaisen, parantamiselle omistetun elämän työ.“",
111: "Uskomattominta Nautubonessa on se, ettei se vain lievitä kipua — vaan aktivoi uudistumisen mekanismin, joka on vuosien myötä nukahtanut. Kapseli otetaan suun kautta, ja nanohiukkaset vievät vaikuttavat aineet syvälle nivelkudokseen — sinne, minne tavalliset voiteet ja geelit eivät koskaan yllä. Ainesosien välinen synergia vahvistaa vaikutusta jopa 20-kertaiseksi verrattuna niiden ottamiseen erikseen.",
112: "Nautubonen neljä palautumisen vaihetta — mitä elimistössäsi tapahtuu askel askeleelta",
113: "— Koko elämäni yrttiparantajana olen katsonut, kuinka ihmiset käyvät läpi samat neljä vaihetta. Poikani dokumentoi ne ja rakensi ne Nautuboneen, jotta jokainen voisi käydä ne läpi kotona.",
114: "„Endogeenisen kudosaktivaation“ neljä vaihetta:",
115: "Vaihe 1 — Kivun ja tulehduksen pysäyttäminen:",
116: "Jo ensimmäisestä kapselista lähtien nanohiukkaset vapauttavat vaikuttavat aineet suolessa ja kuljettavat ne verenkierron mukana suoraan vaurioituneisiin kudoksiin, jolloin tulehdusmolekyylit salpautuvat. Kipu vähenee selvästi 24–48 tunnissa — kuormittamatta maksaa ja munuaisia, koska mikrokapselilla on suolistoliukoinen kuori ja se ohittaa perinteisen maksa-aineenvaihdunnan.",
117: "Vaihe 2 — Tuhoutumisen pysäyttäminen:",
118: "Kolmannen ja seitsemännen päivän välillä elimistö lakkaa hajottamasta rusto- ja luukudosta. Nivelnesteen — nivelten luonnollisen „voiteluaineen“ — tuotanto lisääntyy. Kitka vähenee ja liikkeet helpottuvat.",
119: "Vaihe 3 — Uudistavien solujen herättäminen:",
120: "Tämä on menetelmän ydin. „Nukahtaneet“ rustosolut ja luuta muodostavat solut saavat biokemiallisen signaalin ja alkavat tuottaa uutta rustoa ja uutta luukudosta. Juuri tämä vaihe tekee Nautubonesta ainutlaatuisen — mikään muu tuote ei käynnistä tätä mekanismia.",
121: "Vaihe 4 — Kestävä suojaava este:",
122: "30–60 päivän kuluttua vasta muodostuneet kudokset rakentavat vahvan suojakerroksen, joka tekee nivelistä kestäviä jopa rasituksessa. Toivo-vaari kutsuu tätä „nivelten immuniteetiksi“ — kerran saavutettuna vaikutus säilyy vuosia.",
123: "Jokainen näistä vaiheista on yhden ihmisen 40 vuoden kokemuksen ja 5 vuoden laboratoriotutkimusten tulos. Nautubone ei tarjoa kivun nopeaa „peittämistä“ — se käynnistää syvän, biologisen uudistumisprosessin, joka palauttaa nivelet siihen kuntoon, jossa ne olivat vuosikymmeniä sitten.",
124: "Tuloksia, jotka yllättivät lääkäriyhteisön — 2 340 ihmisen seuranta 38–89 vuoden iässä",
125: "— Kun julkaisimme ensimmäiset laboratoriotutkimusten tulokset, reaktio oli salamannopea. Yliopistoklinikat Helsingistä, Berliinistä ja Wienistä pyysivät saada tehdä omat tutkimuksensa. Tulokset oikeilla ihmisillä ylittivät jopa meidän odotuksemme — yksikään olemassa olevista hoitomenetelmistä ei pääse lähellekään näitä lukuja.",
126: "Ihmiset, jotka oli kirjattu nivelproteesileikkaukseen, peruivat leikkauksensa. Ihmiset, jotka eivät olleet kuukausiin nousseet sängystä, alkoivat jälleen kävellä. Ortopedit eivät uskoneet omia röntgenkuviaan.",
127: "„Nautubone“-seurannan tulokset 2 340 ihmisellä 38–89 vuoden iässä",
128: "Kivun ja tulehduksen täydellinen poistuminen",
129: "Täyden liikelaajuuden palautuminen",
130: "Jännetulehdus, limapussin tulehdus, periartriitti",
131: "Rappeutumismuutosten pysähtyminen ja korjaantuminen",
132: "Nivelkalvon ja nivelsiteiden tulehdus",
133: "Nivelrikko (kaikki vaiheet)",
134: "Osteoporoosi",
135: "Nivelreuma, kihti",
136: "Nivelrikko, spondylartriitti",
137: "Dokumentoitu rustokudoksen uudistuminen",
138: "Tarkat palautumisajat „Nautubonen“ kanssa:",
139: "Muut tiederyhmät Euroopassa yrittävät toistaa kaavamme, mutta tähänastiset tulokset ovat kaukana meidän tuloksistamme. Laboratoriomme kanssa kehitettyä nanodiffuusioteknologiaa parannetulla hyötyosuudella ei toistaiseksi pystytä jäljittelemään — juuri se antaa kapselin toimittaa ainesosat verenkierron kautta suoraan niveleen sen sijaan, että ne jäisivät yksinkertaisesti ihon pinnalle, kuten voiteet.",
140: "Kuinka kauan täysi palautuminen kestää? Toivo-vaari selittää 70 vuoden kokemuksen pohjalta",
141: "— Vähimmäiskuuri, jota suosittelen, on 30 päivää. Vakavammissa vaurioissa — 60, joskus jopa 90 päivää. Mutta koko urallani minulla EI OLE OLLUT YHTÄKÄÄN TAPAUSTA, jossa menetelmä ei olisi antanut tulosta. Ei yhtäkään. Ja olen hoitanut 85-, 90- ja jopa 94-vuotiaita ihmisiä.",
142: "Nautubone ei vain pysäytä kipua — se käynnistää syvän biologisen uudistumisen prosessin. Ota yksi kapseli kahdesti päivässä, niin tunnet helpotuksen jo ensimmäisten tuntien aikana. Viikon kuluessa huomaat liikkuvasi kevyemmin. Ja täyden kuurin jälkeen nivelesi ovat siinä kunnossa, jossa ne olivat 20–30 vuotta sitten.",
143: "Mutta arvokkainta on jokin muu: vaikutus on PYSYVÄ. Kerran „herätettyinä“ uudistavat solut jatkavat työtään vuosia!",
144: "„Nautubonen“ ansiosta yli 16 000 ihmistä Suomessa on saanut liikuntakykynsä takaisin. Tässä on vain pieni osa niistä, joita Toivo-vaari on auttanut:",
145: "Eläkeläinen, 66 vuotta, Joensuu. Neljä siirtynyttä nikamaa ja krooninen hermojuurikipu. Poika toi hänelle Nautubone-kapseleita Helsingistä. Kaksi kuukautta käyttöä — selkäranka palasi täysin normaaliin asentoon. Hänen ortopedinsä pyysi tuotteen nimeä.",
146: "Kirjanpitäjä, 41 vuotta, Vaasa. Polvet vääntyivät sisäänpäin kahden raskauden ja painonnousun jälkeen. Ortopedi sanoi hänelle „totu siihen“. Nautubone-kapseleilla — 30 päivää käyttöä, kahdesti päivässä — polvien akseli suoristui näkyvästi röntgenkuvassa.",
147: "Eläkeläinen, 73 vuotta, Pori. Nivelrikko oli vääntänyt hänen varpaansa niin pahoin, ettei hän saanut jalkaansa ainuttakaan kenkäparia. Hän otti Nautubone-kapseleita joka päivä — 21 päivässä varpaat suoristuivat, ja viisi vuotta vanhat kengät sopivat hänelle jälleen.",
148: "— Nämä kuvat eivät ole ihmeitä — ne ovat luontoa ja kärsivällisyyttä. Jokainen näistä ihmisistä sai takaisin jotain, mitä lääkärit olivat sanoneet mahdottomaksi: terveet nivelet ja elämän ilman kipua. Nautubone ON KOKO YRTTIPARANTAJAN ELÄMÄNI KRUUNU — JA PERINTÖNI TULEVILLE SUKUPOLVILLE!",
149: "Miksi Toivo-vaari ei enää ota ihmisiä vastaan — ja kuinka Nautubonesta tuli ainoa tie hänen reseptiinsä",
150: "„Terveyteni ei enää salli sairaiden vastaanottamista henkilökohtaisesti. Mutta kaavani jatkaa parantamista — poikani käsien kautta.“",
151: "— Viime vuonna tein elämäni vaikeimman päätöksen: en ota enää ihmisiä vastaan. Jonotuslistalla oli yli 2 000 nimeä — enkä voinut jättää heitä ilman apua. Siksi annoin poikani Mikon viedä reseptin sinne, missä se valmistetaan kaikille. Nyt olen rauhallinen — Nautubone on täsmälleen sitä, mitä annoin luokseni tulleille ihmisille, vain kätevässä muodossa. Resepti on hyvissä käsissä.",
152: "— Nautubonea ei myydä apteekeissa — valmistusprosessi on monimutkainen ja määrät ovat rajalliset. Se on saatavilla vain verkkokampanjan kautta, kahdesti vuodessa. Kampanjan puitteissa alennukset yltävät kuitenkin",
153: "— koska tavoitteemme ei ole voitto vaan saatavuus. Erityisesti eläkeläisille, joille isäni vaati ehdottomasti suurinta alennusta.",
154: "Ilmoittautuaksesi käytä alla olevaa virallista tilauslomaketta — se tulee suoraan Mikko Mäkelän tuotantotiimiltä.",
155: "Älä missaa tämän vuoden viimeistä mahdollisuutta — Nautubone voi loppua ennen kampanjan päättymistä!",
156: "— Tänä vuonna onnistuimme valmistamaan 5&nbsp;000 pakkausta Nautubone-kapseleita erityisesti Suomen asukkaille. Mutta kysyntä huomioon ottaen — ja se on valtava — nämä määrät loppuvat nopeasti. Seuraava erä on valmis vasta vuoden lopussa:",
157: "Tukikampanja on voimassa",
158: "asti — jokainen yli 40-vuotias Suomen asukas voi saada",
159: "jopa 50 % alennuksen",
160: ". Tämän päivämäärän jälkeen joudut odottamaan vähintään 6 kuukautta uutta mahdollisuutta.",
161: "Älä lykkää. Isäni sanoi ihmisille aina: „Nivelet eivät odota sinua — ne tuhoutuvat joka sekunti.“ Niin kauan kuin kampanja on voimassa, käytä se hyväksesi. Nautubonella on kumulatiivinen vaikutus — yksi täysi kuuri riittää 5–6 vuodeksi terveitä niveliä.",
162: "Kirjoita vain nimesi ja puhelinnumerosi lomakkeeseen. Neuvoja soittaa sinulle, laatii yksilöllisen ohjelman sinun tapaukseesi ja järjestää toimituksen mihin tahansa osoitteeseen Suomessa — 2–3 päivässä, postitse tai kuriirilla ovellesi.",
163: "Toivotan kaikille terveyttä! Pidä huolta nivelistäsi tänään, jotta kävelet huomenna! Kunnioittaen: Toivo Mäkelä ja hänen poikansa Mikko.",
164: "Päivitetty:",
}
