# -*- coding: utf-8 -*-
# Suomi / yrttiparantaja, solmut 165..236 + attribuutit (lääkemuoto: KAPSELI)
F3 = {
165: "Erittäin suuren kysynnän vuoksi Nautubonen varastot voivat loppua ennen kampanjan suunniteltua päättymistä! Tänään —",
166: "18.12.2025 — on viimeinen päivä tilata alennuksella",
167: "tai niin kauan kuin tavaraa riittää.",
168: "Huomio! Älä sulje äläkä päivitä sivua — sinulle varatut Nautubone-kapselit tarjotaan seuraavalle jonotuslistalla olevalle!",
169: "Varattu paikkasi kampanjassa:",
170: "Virallinen tilauslomake",
171: "Saadaksesi",
172: "50 % alennuksen",
173: ", kirjoita nimesi ja puhelinnumerosi alla oleviin kenttiin ja paina „TILAA“-painiketta.",
174: "Jäljellä olevat määrät:",
175: "79 €",
176: "39 €",
177: "Nimi",
178: "Puhelinnumero",
179: "TILAA",
180: "✔️ Toimitus mihin tahansa osoitteeseen Suomessa 2–3 päivässä",
181: "postitse tai kuriirilla ovellesi",
182: "KOMMENTIT:",
183: "Sirpa Nieminen",
184: "Odotin tätä tekstiä kuukausikaupalla! Eräs ystäväni Helsingistä kävi henkilökohtaisesti Toivo-vaarin luona muutama vuosi sitten — hän sanoi, että mies on suorastaan ihme. Harmi, ettei hän enää ota vastaan ihmisiä, mutta jos Nautubonessa on sama resepti — tilaan heti. Onneksi ehdin alennukseen!",
185: "Tuula Rantanen",
186: "Kuriiri toi sen keskiviikkona. Kymmenen päivää olen ottanut kapselia aamuin illoin — ja ero on VALTAVA! Nousen ylös ilman sitä kamalaa rutinaa! Mieheni katsoo eikä usko. Teen täyden 60 päivän kuurin, mutta olen jo vakuuttunut, että se toimii.",
187: "Ritva Koskinen",
188: "Olen 72-vuotias ja kolme vuotta kärsin lonkkakivusta. Käveleminen oli piinaa. Ortopedi sanoi: „Proteesi tai kestä.“ En halunnut kumpaakaan. Nautubone auttoi minua kahdessa kuukaudessa — nyt kävelen puolitoista kilometriä joka päivä! Ja röntgenkuva näyttää parannuksen, jota lääkärini ei osaa selittää. Kiitos, Toivo-vaari, ja kiitos pojallesi!",
189: "Veikko Salminen",
190: "Entisenä urheilijana tiedän, mitä tarkoittaa elää tuhoutuneen ruston kanssa. Polveni olivat kuin 90-vuotiaalla — vaikka olen vasta 54. Nautubone palautti minulle liikkeitä, joita en ollut tehnyt kymmeneen vuoteen. Pystyn taas kyykistymään! En tunne toista tuotetta, joka saisi aikaan tällaista.",
191: "Marjatta Salminen",
192: "Olen hieman huolissani… Kannattaako tämä? Olen 66-vuotias, nivelet rutisevat jokaisesta liikkeestä eikä selkä anna rauhaa. Mutta olen pettynyt niin monta kertaa kaikenlaisiin „ihmelääkkeisiin“, että minun on enää vaikea uskoa. Auttaako se todella?",
193: "Pekka Hämäläinen",
194: "Marjatta, ymmärrän epäilyksesi täysin — minullakin oli niitä. Mutta Nautubone on erilainen kuin kaikki, mitä olen tähän mennessä kokeillut. Olen käyttänyt sitä viisi viikkoa polviin ja alaselkään — ja voin sanoa, että ero on kuin yöllä ja päivällä.",
195: "Aiemmin en pystynyt kumartumaan sitomaan kengännauhojani. Nyt teen sen ajattelematta. Tilaa edes yksi pakkaus ja arvioi itse — sinulla ei ole mitään menetettävää!",
196: "Kaarina Lehtonen",
197: "Kolme päivää sen jälkeen, kun aloin ottaa kapselia, polveni kipu väheni puoleen! Nyt on 12. päivä ja nousen jo portaita pitämättä kiinni kaiteesta. Teen täyden kuurin — uskon, että kahden kuukauden päästä olen kuin uusi!",
198: "Johanna Virtanen",
199: "Selkääni alkoi kasvaa „kyttyrä“ noin kaksi kuukautta sitten. Kauhistuin! Kokeilin kaikenlaisia apteekin voiteita — ei mitään. Mutta Nautubone-kapselit ovat aivan eri asia — 40 päivässä kyttyrä katosi lähes kokonaan! Jatkan niiden ottamista, mutta olen jo uskomattoman tyytyväinen. Näin ero näyttää:",
200: "Paula Aaltonen",
201: "Minulla oli puristuksissa oleva hermo alaselässä — kivun takia en pystynyt nukkumaan enkä seisomaan. Lääkäri määräsi vahvoja kipulääkkeitä, joista minua voi jatkuvasti pahoin. Aloin ottaa Nautubone-kapseleita kahdesti päivässä — viikon jälkeen kipu väheni jyrkästi, ja kuukauden kuluttua — katosi kokonaan! Jatkan kuuria, mutta elämäni on jo muuttunut!",
202: "Reijo Laine",
203: "Olen 79-vuotias ja kolme vuotta tuskin kävelin. Poikani tilasi Nautubonen — kysymättä minulta, koska tiesi, että kieltäytyisin. Hän antaa minulle kapselin joka aamu ja joka ilta. Ja tulos? Puolentoista kuukauden jälkeen kävelen puistoon joka päivä! Tunnen itseni 60-vuotiaaksi! Kiitos, Toivo-vaari — 102-vuotiaana olet viisaampi kuin kaikki nykylääkärit!",
204: "Timo Heikkilä",
205: "Ennen Nautubonea en pystynyt nostamaan käsiäni pään yläpuolelle — olkapää rutisi ja särki hirveästi. Kaksi vuotta kiertelin lääkäreitä — kukaan ei auttanut. Kaksi kuukautta Nautubonea ja käteni toimivat taas normaalisti. Tässä on röntgenkuvani — lääkäri itsekään ei uskonut:",
206: "Anneli Korhonen",
207: "Tilasin anopilleni — hän on 81-vuotias eikä pystynyt juuri nousemaan sängystä. Lääkärit kieltäytyivät tekemästä yhtään mitään — „tässä iässä mikään ei enää auta“, he sanoivat. Nautubonen kanssa hän kävelee kahdessa kuukaudessa jo pihalla ja jopa laittaa ruokaa! Emme voineet uskoa sitä.",
208: "Esa Mattila",
209: "Vaimoni makasi vuoteessa neljä kuukautta — selkäranka yksinkertaisesti petti. Lääkärit ehdottivat 8 000 euron leikkausta ilman minkäänlaisia takeita. Päätimme kokeilla Nautubone-kapseleita — meillä ei ollut mitään menetettävää. Annoin niitä hänelle kahdesti päivässä. Viiden viikon jälkeen hän nousi ylös. Eilen kävimme yhdessä torilla — ensimmäistä kertaa puoleen vuoteen! Itkin onnesta.",
210: "Niina Väisänen",
211: "Tilasin viime viikolla, sain kolmantena päivänä. Aloin heti ottaa kapseleita — ja helpotus tuli toisena päivänä! Aivan kuin joku voitelisi niveleni sisältä. Kaksi viikkoa olen ottanut niitä kahdesti päivässä enkä malta odottaa täyttä tulosta!",
212: "Raija Mäkinen",
213: "Olen 74-vuotias. Viisi vuotta kärsin nivelrikosta ja selkäkivuista. Kokeilin kirjaimellisesti kaiken — voiteita, tabletteja, pistoksia, fysioterapiaa. MIKÄÄN ei auttanut pitkällä aikavälillä. Nautubone-kapselit ovat ainoa asia, joka antoi minulle TODELLISEN TULOKSEN — otan niitä kahdesti päivässä ja puolessatoista kuukaudessa nivelistäni tuntuvat aivan toisilta. Lääkäri ei usko röntgenkuvia!",
214: "Helena Pesonen",
215: "Tunnen Toivo-vaarin henkilökohtaisesti — 12 vuotta sitten hän auttoi minua välilevytyrässä. Kolmessa viikossa olin taas jaloillani! Hänen nimensä tuntee koko Helsingin ympäristö. Olen iloinen, että hänen poikansa jatkaa työtä!",
216: "Eila Turunen",
217: "Isäni on 84-vuotias eikä kolmeen vuoteen käynyt ulkona. Nivelet, selkä, polvet — kaikkea särki. Hän sanoi odottavansa lähtöä. Kahden Nautubone-kuukauden jälkeen — eilen hän meni pihalle ja kasteli puutarhan! Ensimmäistä kertaa kolmeen vuoteen! En osaa kuvailla, mitä tunsin. Kiitos sydämestäni!!!",
218: "Mirja Toivonen",
219: "Tietääkö kukaan, voiko tätä käyttää allergioiden kanssa? Reagoin melkein kaikkeen — jopa tavallisesta aspiriinista sormeni turpoavat. Pelkään kokeilla mitään uutta…",
220: "Kari Lindholm",
221: "Mirja, minä olen allerginen neljälle lääkeaineelle. Olen ottanut Nautubone-kapseleita 50 päivää — ei mitään ärsytystä, ei turvotusta, ei punoitusta. Koostumus on kokonaan luonnonuutteita — se ei sisällä kemikaaleja. Voit tilata huoletta!",
222: "Tarja Savolainen",
223: "Ennen minulla ei ollut voimia nousta ylös — jokainen liike oli tuskaa, luulin että elämäni oli ohi. Tyttäreni tilasi Nautubone-kapselit ja sai minut kokeilemaan niitä — hän antoi ne minulle aamuin illoin. Kaksi kuukautta myöhemmin? Tanssin lapsenlapseni häissä!!! En ole koskaan elämässäni ollut näin kiitollinen!",
224: "Leena Hakala",
225: "Tilasin äidilleni. Hänellä oli jatkuvia niskakipuja, jotka aiheuttivat huimausta ja pahoinvointia — hänen elämästään oli tullut sietämätöntä. Toisella Nautubone-viikolla kivut vähenivät jyrkästi ja huimaus loppui kokonaan! Äiti nauraa taas — en ollut pitkään aikaan nähnyt häntä sellaisena.",
226: "Sanna Karjalainen",
227: "Ihmettelen — jos Toivo-vaari on noin hyvä, miksi näitä ei myydä kaikkialla? Miksi vain verkossa? Miksi apteekit eivät tarjoa niitä?",
228: "Mikael Räsänen",
229: "Siksi, että apteekit tienaavat ihmisillä, jotka ostavat kipulääkkeitä joka kuukausi! Jos kaikki parantaisivat nivelensä kerralla ja lopullisesti — kuka ostaisi heidän kalliita lääkkeitään? Ajattele loogisesti!",
230: "Oili Kinnunen",
231: "Luin kaikki kommentit — ja liikutuin. Tilaan nyt, itselleni ja miehelleni. Otin kolme pakkausta kapseleita, täyttä kuuria varten. Jos se auttaa edes puolet siitä, mitä ihmiset kirjoittavat — olen onnellinen!",
232: "Liisa Manninen",
233: "Ortopedini sanoi, että 63-vuotiaana minun on totuttava kipuun — muka parannuskeinoa ei ole. Tilasin Nautubonen kaikkien uhalla. Katsotaan, kuka on oikeassa!",
234: "Lataa profiilikuva",
235: "Lataa valokuva",
236: "LÄHETÄ",
}
ATTRS_F = {
 "Вашето име": "Nimesi",
 "Вашият телефонен номер": "Puhelinnumerosi",
 "Вашият коментар": "Kommenttisi",
}
