# -*- coding: utf-8 -*-
# France / herboriste, nœuds 0..69 (forme : GÉLULES)
F1 = {
0: "Fernand Delaunay, herboriste de 102 ans des environs de Paris, révèle la formule de la récupération complète des articulations — une méthode accessible à chaque Français",
1: "À 102 ANS, IL EST LE PLUS ANCIEN HERBORISTE DE FRANCE ET LE SEUL DE SA GÉNÉRATION À MARCHER SANS CANNE. POUR LA PREMIÈRE FOIS, IL RÉVÈLE LA FORMULE QU'IL N'A DONNÉE PENDANT 40 ANS QU'À CEUX QUI VENAIENT JUSQU'À LUI.",
2: "Publié le :",
3: "« Comment le père Fernand Delaunay, herboriste des environs de Paris, a-t-il réussi à garder ses articulations en parfait état jusqu'à 102 ans, alors que tous ceux de son âge ne marchent plus depuis longtemps ? »",
4: "Dans un village non loin de Paris vit un homme qui contredit tout ce que nous savons sur le vieillissement. À 102 ans, l'herboriste Fernand Delaunay parcourt chaque matin les sentiers au-dessus du village, monte les escaliers sans aide et n'a jamais utilisé de canne de sa vie. Ceux de sa génération ne sont plus là depuis longtemps ou sont cloués dans un fauteuil roulant — et lui monte encore seul sur la colline pour ramasser ses plantes.",
5: "Jusqu'à l'année dernière, le père Fernand recevait les gens chez lui, dans la vieille pièce où il fait sécher ses plantes depuis des décennies. Plus de 70 ans de travail avec les plantes, plus de 40 000 personnes, des dizaines de colonnes vertébrales et de genoux ramenés à la vie après que les médecins les avaient déjà condamnés. Il y avait six mois d'attente — les gens venaient de tout le pays pour le voir.",
6: "Mais le vrai mystère, ce ne sont pas ceux qui venaient le voir. Le vrai mystère, c'est lui-même. À 102 ans — ni arthrite, ni arthrose, ni la moindre hernie discale. Les radios de ses articulations ressemblent à celles d'un homme de 45 ans. Les médecins qui l'examinent n'en croient tout simplement pas leurs yeux.",
7: "Pendant des décennies, il a gardé sa recette secrète — il la préparait lui-même, dans sa pièce, et ne l'a jamais rendue publique. Mais aujourd'hui, alors que sa santé ne lui permet plus de recevoir les gens en personne, le père Fernand a pris une décision qui a tout changé : rendre sa formule accessible à chaque Français.",
8: "Fernand Delaunay : « Toute ma vie, j'ai regardé les gens vieillir avant l'heure — non pas parce que leur corps est faible, mais parce que personne ne leur a dit comment enclencher leurs propres mécanismes de régénération. À 102 ans, je suis la preuve vivante que",
9: "les articulations peuvent rester saines jusqu'à un âge très avancé, si l'on sait comment « réveiller » les cellules qui les construisent.",
10: "MON BUT A TOUJOURS ÉTÉ LE MÊME — AIDER LE CORPS À PRODUIRE DU CARTILAGE ET DE L'OS NEUFS, EXACTEMENT COMME DANS LA JEUNESSE. AUJOURD'HUI, MON FILS JULIEN A TRANSFORMÉ TOUT CELA EN UN PRODUIT",
11: "QUI PEUT ARRIVER DANS CHAQUE FOYER EN FRANCE.",
12: "Julien Delaunay — le fils de l'herboriste — a grandi parmi les plantes séchées et les balances de son père et a appris le métier dès l'enfance. Il n'est pas devenu médecin. Pendant des années, il a convaincu son père que la recette ne devait pas rester enfermée dans une seule maison, puis il a trouvé lui-même un laboratoire et des gens qui ont aidé à transformer l'expérience de plusieurs décennies du père Fernand en un produit accessible à tous — pour qu'il parvienne à tous ceux qui en ont besoin.",
13: "Le résultat de cette collaboration a dépassé toutes les attentes. Mais avant de vous parler du produit, voyons pourquoi tout ce que vous savez sur le traitement des articulations est très probablement faux.",
14: "Le mensonge auquel croit toute la France :",
15: "« Les antidouleurs soignent les articulations » — ERREUR, ils les détruisent encore plus vite !",
16: "Fernand Delaunay :",
17: "— Cela fait soixante-dix ans que je soigne des gens et je vais vous dire une chose que les pharmacies ne reconnaîtront jamais : aucun antidouleur dans l'histoire de la médecine n'a régénéré ne serait-ce qu'un millimètre de cartilage. Aucun ! Ils étouffent la douleur, mais pendant ce temps le cartilage continue de se détruire — sauf que vous ne le sentez plus. Et quand vous le sentirez de nouveau, il sera trop tard.",
18: "Mais ce n'est pas le pire. Le pire, c'est ce que ces substances chimiques font à vos organes internes. En 70 ans de travail, j'ai vu des centaines de personnes avec le foie et les reins complètement détruits — pas par la maladie, mais par les médicaments ! Le corps n'a pas été fait pour avaler de la chimie pendant des décennies. Et pourtant, c'est exactement ce que « prescrit » la médecine classique.",
19: "La colonne vertébrale est particulièrement vulnérable. Les disques intervertébraux n'ont pas d'irrigation sanguine propre — ils se nourrissent par diffusion, ce qui signifie que leur détérioration se fait en silence, sans douleur, parfois pendant des années. Quand la douleur apparaît enfin, la détérioration est déjà avancée. La compression du nerf par une hernie discale transforme la vie en cauchemar : cela commence par un léger engourdissement dans la jambe et se termine par la perte totale de la mobilité.",
20: "Regardez ce que montre cette radio. Une femme de 39 ans à peine, institutrice — et sa colonne est dans un état que je ne voyais il y a 20 ans que chez des gens de 70 ans. Huit heures par jour assise sur une chaise, absence de mouvement et méconnaissance totale de son propre corps — voilà ce qu'apporte le mode de vie moderne.",
21: "Image tirée des archives que le père Fernand conserve depuis des décennies : la colonne d'une institutrice de 39 ans de Rouen. Elle est venue avec « une légère fatigue dans le bas du dos » — la radio a révélé trois disques abîmés, une hernie débutante et des microfissures dans l'enveloppe cartilagineuse.",
22: "Si après 40 ans vous ressentez des douleurs, des raideurs ou des craquements dans les articulations — votre cartilage est déjà en train de se détruire. Ce n'est pas « la fatigue » et ce n'est pas « normal ».",
23: "Dans la colonne vertébrale, le processus est plusieurs fois plus rapide et plus sournois — la douleur n'apparaît que lorsque les dégâts sont déjà critiques !",
24: "— Je veux être tout à fait franc. Je connais des gens qui ont repoussé pendant des mois. Le résultat ? Un nerf comprimé qui n'a plus jamais fonctionné normalement. Restaurer les disques quand le nerf est déjà mort ne sert à rien —",
25: "LE DISQUE PEUT REVENIR, MAIS LE NERF — NON !",
26: "Et que reste-t-il alors ? LA CANNE, LE FAUTEUIL ROULANT ET LA DÉPENDANCE À L'AIDE DES AUTRES JUSQU'À LA FIN DE LA VIE !",
27: "Et que propose la chirurgie moderne ? Des opérations coûteuses et risquées avec des implants métalliques. J'ai vu personnellement des centaines de personnes qui, après une opération de la colonne, se sentaient PLUS MAL qu'avant.",
28: "INFECTIONS, FUSIONS RATÉES, DOULEUR CHRONIQUE ET, AU BOUT DU COMPTE — UNE NOUVELLE OPÉRATION. ET PARFOIS — DES LÉSIONS IRRÉVERSIBLES !",
29: "Le père Fernand montre une radio qu'un homme lui a apportée après une opération avec des vis métalliques : « Voilà le résultat typique — l'implant n'a pas bien tenu, les tissus autour sont enflammés et la douleur est plus forte qu'avant l'opération. J'ai vu des centaines de cas semblables. »",
30: "Les statistiques sont impitoyables : chez 60 % des opérés, la hernie revient en 2 à 4 ans. Et le prix ? Des mois d'immobilité, des milliers d'euros et une incertitude totale. Beaucoup l'avouent : s'ils pouvaient revenir en arrière, ils ne monteraient jamais sur la table d'opération.",
31: "Ces symptômes signifient que votre cartilage est déjà en train de mourir ! Et si vous avez plus de 40–50 ans — le processus est irréversible sans intervention !",
32: "— En 70 ans, plus de 40 000 personnes sont passées entre mes mains et je peux dire ceci : chaque douleur articulaire ignorée est un pas vers le fauteuil roulant. Rien qu'en",
33: "on a enregistré en France plus de 1 250 000 nouveaux cas de maladies articulaires graves — dont 230 000 chez des personnes de 38 à 48 ans. Ce n'est pas un problème de vieillesse. C'est un problème d'inaction.",
34: "Si votre organisme vous a déjà envoyé l'un de ces signaux — n'attendez pas un seul jour !",
35: "Voici la liste que je récitais à chacun dès le pas de la porte :",
36: "Raideur matinale qui ne passe pas avec le mouvement ;",
37: "Craquements, claquements ou grincements en bougeant ;",
38: "Douleur qui s'intensifie quand le temps change ;",
39: "Difficulté à plier ou à tendre les genoux ;",
40: "Gonflement, rougeur ou chaleur autour de l'articulation ;",
41: "Douleur en montant ou en descendant les escaliers ;",
42: "Fatigue chronique et lourdeur dans les jambes ;",
43: "Douleur dans le bas du dos qui « tire » vers la cuisse ou le pied ;",
44: "Engourdissement ou fourmillements dans les doigts ;",
45: "Changement de la démarche — boiterie, instabilité ;",
46: "Impossibilité de rester debout plus de 10–15 minutes ;",
47: "Si vous vous reconnaissez ne serait-ce que dans deux de ces symptômes — votre cartilage est déjà en train d'être détruit. Et dans la colonne vertébrale, le processus est trois à quatre fois plus rapide, parce que les disques intervertébraux sont sous pression permanente.",
48: "LE RÉSULTAT : HERNIE, NERF COMPRIMÉ, DÉFORMATION DES VERTÈBRES, PERTE DE MOBILITÉ — ET TOUT CELA PEUT ARRIVER EN QUELQUES SEMAINES !",
49: "Ne remettez pas à plus tard, car l'organisme ne donne pas des chances à l'infini !",
50: "Regardez ces personnes ci-dessous. Chacune d'elles a eu les mêmes symptômes que vous ressentez probablement en ce moment. Chacune s'est dit « ça va passer ». Et chacune donnerait aujourd'hui n'importe quoi pour revenir en arrière et agir tant qu'il en était encore temps.",
51: "Ancienne patiente d'une autre clinique, 58 ans, Marseille. Trois vertèbres déplacées de plus de 8 mm, la moelle épinière sous pression. Elle a refusé deux fois d'aller voir le père Fernand — quand elle est enfin venue, elle était à un pas de la paralysie.",
52: "Femme de 61 ans de Lille — sa bosse a atteint 4 cm en moins d'un an. Les vertèbres cervicales sont déformées au point que la tête ne peut plus tourner sur le côté. Les antidouleurs ont cessé de faire effet il y a 8 mois.",
53: "Femme au foyer, 59 ans, Toulouse. Ses articulations du genou sont si usées que le cartilage s'est aminci à moins de 1 mm. Chaque pas résonne comme le grincement d'une vieille porte. Trois chirurgiens orthopédistes lui ont dit que la seule solution était une double prothèse, pour plus de 9 000 €.",
54: "Ancien mineur, 68 ans, Lens. Le cartilage du genou droit est complètement détruit, le tissu osseux est entré en phase de nécrose. Quatre mois de report lui ont coûté le membre — amputation au-dessus du genou et dépendance à vie au fauteuil roulant.",
55: "J'ai 102 ans et je peux vous dire d'expérience : l'organisme est capable de se régénérer lui-même à N'IMPORTE QUEL âge — à condition de savoir COMMENT l'enclencher. C'est précisément à cela que j'ai consacré ma vie.",
56: "ET SI VOUS AVEZ DÉJÀ PLUS DE 50–60 ANS, N'ATTENDEZ PAS UNE SECONDE !",
57: "Chez vous, les dégâts sont presque certainement entrés en phase critique — il faut d'urgence arrêter la destruction et enclencher la régénération d'un cartilage neuf, d'os neufs et de tissus neufs !",
58: "Des cas que les médecins avaient déclarés désespérés !",
59: "Yvonne Marchand, à 86 ans, remarche sans l'aide de personne, après avoir été refusée par trois hôpitaux. Voici son histoire…",
60: "Yvonne Marchand, de Limoges, souffrait d'une arthrose sévère des genoux et de multiples hernies discales. Trois hôpitaux différents l'ont refusée — partout on lui disait la même chose : « À votre âge, on ne peut plus rien faire. » Sa fille a entendu parler par hasard du père Fernand par des connaissances d'un village des environs de Paris et a décidé d'aller le chercher.",
61: "« Je vivais comme en prison — ma propre maison était devenue une cellule. Je n'arrivais pas jusqu'aux toilettes, je ne pouvais pas rester debout plus d'une minute, je ne pouvais même pas me faire un thé. Mes enfants travaillaient et ne pouvaient pas venir tous les jours. Je restais allongée à regarder le plafond. Les médecins ont dit qu'à mon âge une opération n'avait pas de sens et ne m'ont donné que des antidouleurs.",
62: "Quand ma fille m'a emmenée chez le père Fernand, il m'a regardée et m'a dit quelque chose qu'aucun médecin ne m'avait dit : « Madame Yvonne, votre corps n'a PAS cessé de se battre. C'est simplement que personne ne l'a aidé. » Il m'a donné ce qu'il prépare lui-même et m'a dit d'être patiente. La troisième semaine, pour la première fois en un an et demi, JE ME SUIS LEVÉE SEULE de mon lit !",
63: "Aujourd'hui, cinq mois plus tard, je vais au magasin, je cuisine, je m'occupe même du parterre de fleurs devant la maison. À 86 ans ! Quand les voisins m'ont vue dans la cour, ils n'y ont pas cru. Ils pensaient ne plus jamais me revoir. Le père Fernand m'a rendu la vie — et je n'ai pas de mots pour le remercier. »",
64: "Yvonne Marchand, 86 ans, Limoges",
65: "Un autre cas exceptionnel est celui de Thierry Rousseau — maçon de 47 ans de Nancy, qui, après 20 ans de travail physique lourd, a subi de graves lésions de la colonne vertébrale et a été contraint de se déplacer en fauteuil roulant.",
66: "Thierry a essayé la méthode du père Fernand, et les résultats ont choqué jusqu'à son propre médecin traitant.",
67: "SA COLONNE A COMMENCÉ À SE RECONSTRUIRE, LA DOULEUR A COMPLÈTEMENT DISPARU, ET LE PLUS INCROYABLE —",
68: "IL A QUITTÉ LE FAUTEUIL ROULANT APRÈS SEULEMENT 4 SEMAINES !",
69: "Thierry nous a raconté :",
}
