# -*- coding: utf-8 -*-
# France / herboriste, nœuds 70..164 (forme : GÉLULES)
F2 = {
70: "« Pendant vingt ans j'ai construit des bâtiments, mais je n'ai pas pris soin de ma propre colonne. Un matin je me suis réveillé et je ne pouvais plus bouger le bas du dos. Ma femme a appelé les secours. Le diagnostic — trois hernies et une compression de la racine nerveuse. Les médecins ont proposé une opération à 6 500 €, mais sans garanties.",
71: "Pendant des mois je suis resté à la maison en fauteuil roulant. Mes enfants me regardaient avec tristesse, ma femme pleurait tous les soirs. Je me sentais un fardeau. J'avais envie de disparaître…",
72: "C'est alors que mon beau-père a entendu parler du père Fernand par un homme qu'il avait aidé. J'ai appelé, j'ai envoyé les radios, et le vieil homme a dit : « Il n'est pas trop tard. » Ces quatre mots m'ont donné plus d'espoir que tout ce que j'avais entendu de dizaines de médecins.",
73: "Le quatrième jour, je pouvais déjà tenir debout. La cure complète a duré 80 jours. Aujourd'hui je travaille de nouveau — pas sur le chantier, mais au bureau, mais JE MARCHE. Je cours avec mes enfants dans le parc. Je vis. La radio montre que mes disques se sont reconstitués à 90 %. Le père Fernand est le seul qui ne m'a pas refusé — et le seul qui m'a aidé. »",
74: "Les histoires des milliers de personnes que le père Fernand a aidées sont tout aussi stupéfiantes : des gens à qui les médecins disaient « habituez-vous à la douleur » ont remarché, se sont remis à courir, à vivre. Comment est-ce possible ?",
75: "La formule que le père Fernand a préparée de ses propres mains pendant plus de 40 ans !",
76: "Le secret de la méthode « Réactivation tissulaire endogène » — comment l'organisme se met lui-même à produire du cartilage neuf, des os neufs et des ligaments neufs !",
77: "— Permettez-moi de vous expliquer une chose que la médecine classique refuse de reconnaître. L'organisme de chaque personne — même d'un homme de 90 ans — possède des cellules régénératrices « endormies ». Les mêmes cellules qui, dans la jeunesse, vous construisaient sans effort du cartilage, des os et des ligaments. Avec les années, elles ne meurent pas — elles « s'endorment » simplement, parce que l'organisme cesse de leur envoyer les bons signaux.",
78: "Il y a 40 ans, j'ai découvert qu'une certaine combinaison de substances naturelles — dans des proportions strictement définies — agit sur ces cellules endormies comme une clé de contact. J'ai appelé cette méthode",
79: "« Réactivation tissulaire endogène »",
80: "— parce qu'elle n'introduit rien d'artificiel, mais active les ressources propres de l'organisme. C'est justement pour cela qu'avec moi il n'y a AUCUN effet indésirable, AUCUNE atteinte des organes et AUCUNE dépendance.",
81: "Pendant quatre décennies, j'ai appliqué cette méthode à chacun de ceux qui franchissaient mon seuil — et chez chacun j'ai noté le même résultat : arrêt de la destruction, diminution de la douleur et retour progressif de la fonction des articulations. Des centaines de personnes qui venaient chez moi « en dernier recours » repartaient de ma maison sur leurs propres jambes.",
82: "La formule elle-même n'est pas compliquée — mais la précision est tout. Chaque ingrédient doit être présent en quantité exacte, au centième de milligramme près. Si les proportions ne sont pas respectées, l'effet disparaît tout simplement. C'est précisément pour cela que, pendant des décennies, j'ai appliqué la méthode personnellement — parce que je ne pouvais pas la confier aux pharmacies.",
83: "Composition des gélules selon la recette de l'herboriste Delaunay (substances actives par dose) :",
84: "Oméga-3",
85: "graines de lin : 4500 mg",
86: "Sulfate de glucosamine",
87: "crustacés : 1100 mg",
88: "Citrate de magnésium",
89: "algues marines : 390 mg",
90: "Gingérol",
91: "gingembre : extrait 4200 mg",
92: "AKBA",
93: "résine d'encens (Boswellia) : extrait 1100 mg",
94: "Silicium",
95: "prêle des champs : extrait 320 mg",
96: "Curcumine",
97: "curcuma : extrait 2300 mg",
98: "Ces ingrédients paraissent simples, mais les trouver dans la bonne qualité et à la bonne source est extrêmement difficile. La plupart ne se trouvent pas en pharmacie et doivent être acheminés depuis différents coins du monde. Et les mélanger à la maison est pratiquement impossible — car le dosage doit être exact à 0,1 mg près.",
99: "C'est justement pour cela que, pendant des décennies, j'ai préparé le mélange personnellement, pour chaque personne séparément. Mais mon fils Julien a vu l'ensemble du tableau.",
100: "Comment Julien Delaunay a transformé la recette vieille de 40 ans de son père en gélules accessibles à tous — Nautubone",
101: "Julien Delaunay :",
102: "— J'ai grandi dans la pièce aux plantes de mon père. Chaque jour je voyais les gens entrer pliés en deux par la douleur — et ressortir en souriant. À 14 ans je connaissais déjà la recette par cœur. Je ne suis pas devenu médecin — j'ai appris le métier auprès de lui. Mais pendant des années je l'ai convaincu : papa, cette recette n'a pas le droit de rester enfermée dans une seule maison. Des milliers de gens attendent ce que tu gardes sur ton étagère.",
103: "Pendant cinq ans, j'ai fait le tour des laboratoires à Paris et à Munich, jusqu'à trouver des gens prêts à étudier sérieusement la formule de mon père. La réponse que j'ai reçue m'a enthousiasmé : la combinaison de ces ingrédients dans ces proportions exactes déclenche la production de collagène de type II et de protéoglycanes — les deux principaux matériaux de construction du cartilage. Autrement dit : l'organisme se « souvient » littéralement de la façon de fabriquer du cartilage neuf, il lui faut simplement le bon signal.",
104: "Avec le laboratoire, nous avons mis au point un procédé que nous avons appelé",
105: "« Technologie de nanodiffusion à biodisponibilité avancée »",
106: "— une méthode dans laquelle les substances actives sont enfermées dans des nanoparticules spéciales, libérées directement dans l'intestin grêle en contournant le métabolisme hépatique, et parviennent par la circulation sanguine exactement jusqu'au tissu articulaire abîmé. Cela augmente l'absorption d'environ 380 % par rapport aux comprimés ordinaires. J'ai appelé le produit",
107: "Nautubone",
108: "— une gélule qui se prend par voie orale et agit exactement là où c'est nécessaire. Je l'ai nommée ainsi en l'honneur de mon père et de ses 40 années de travail.",
109: "La gélule Nautubone contient les sept composants de la recette originale de mon père, plus 29 extraits et vitamines supplémentaires que nous avons ajoutés après les tests de laboratoire de Munich. Le résultat est un produit qui fonctionne EXACTEMENT AUSSI BIEN que ce que mon père préparait de ses propres mains — mais qui peut être livré dans chaque foyer en France. Vous prenez une gélule deux fois par jour, et les substances actives parviennent par la circulation sanguine directement aux articulations touchées.",
110: "« Nautubone est l'héritage de mon père — ses 40 années d'expérience enfermées dans une seule formule. Chaque ingrédient est choisi avec la précision qu'il mettait à se pencher sur chaque personne venue à sa porte. Ce n'est pas un produit de masse d'une étagère de pharmacie — c'est l'œuvre de toute une vie consacrée à guérir. »",
111: "Le plus incroyable avec Nautubone, c'est qu'il ne soulage pas seulement la douleur — il active le mécanisme de régénération qui s'est endormi avec les années. La gélule se prend par voie orale, et les nanoparticules transportent les substances actives au plus profond du tissu articulaire — là où les crèmes et les gels ordinaires n'arrivent jamais. La synergie entre les ingrédients amplifie l'effet jusqu'à 20 fois par rapport à leur prise séparée.",
112: "Les quatre phases de la récupération avec Nautubone — ce qui se passe dans votre organisme, étape par étape",
113: "— Tout au long de ma vie d'herboriste, j'ai regardé les gens traverser les mêmes quatre phases. Mon fils les a documentées et les a intégrées dans Nautubone, pour que chacun puisse les traverser chez soi.",
114: "Les quatre phases de la « Réactivation tissulaire endogène » :",
115: "Phase 1 — Arrêter la douleur et l'inflammation :",
116: "Dès la première gélule, les nanoparticules libèrent les substances actives dans l'intestin et les transportent par la circulation sanguine directement jusqu'aux tissus abîmés, en bloquant les molécules inflammatoires. La douleur diminue nettement en 24–48 heures — sans charger le foie ni les reins, car la microcapsule possède un enrobage gastro-résistant et contourne le métabolisme hépatique traditionnel.",
117: "Phase 2 — Arrêter la destruction :",
118: "Entre le troisième et le septième jour, l'organisme cesse de dégrader le tissu cartilagineux et osseux. La production de liquide synovial — le « lubrifiant » naturel des articulations — augmente. Le frottement diminue et les mouvements deviennent plus faciles.",
119: "Phase 3 — Réveiller les cellules régénératrices :",
120: "C'est le cœur de la méthode. Les chondrocytes et les ostéoblastes « endormis » reçoivent un signal biochimique et se mettent à produire du cartilage neuf et du tissu osseux neuf. C'est justement cette phase qui rend Nautubone unique — aucun autre produit n'enclenche ce mécanisme.",
121: "Phase 4 — Une barrière protectrice durable :",
122: "Au bout de 30–60 jours, les tissus nouvellement formés construisent une couche protectrice solide, qui rend les articulations résistantes même à l'effort. Le père Fernand appelle cela « l'immunité des articulations » — une fois obtenue, l'effet tient pendant des années.",
123: "Chacune de ces phases est le résultat de 40 années d'expérience d'un seul homme et de 5 années de tests en laboratoire. Nautubone ne propose pas de « masquer » rapidement la douleur — il enclenche un processus biologique profond de régénération, qui ramène les articulations dans l'état où elles étaient il y a des décennies.",
124: "Des résultats qui ont surpris la communauté médicale — suivi de 2 340 personnes de 38 à 89 ans",
125: "— Quand nous avons publié les premiers résultats des tests de laboratoire, la réaction a été fulgurante. Des cliniques universitaires de Paris, de Berlin et de Vienne ont demandé à mener leurs propres recherches. Les résultats sur des personnes réelles ont dépassé même nos attentes — aucune des méthodes de traitement existantes n'approche ces chiffres.",
126: "Des personnes inscrites pour la pose d'une prothèse articulaire ont annulé leur opération. Des personnes qui ne se levaient plus de leur lit depuis des mois se sont remises à marcher. Les orthopédistes ne croyaient pas leurs propres radios.",
127: "Résultats du suivi de « Nautubone » chez 2 340 personnes de 38 à 89 ans",
128: "Disparition complète de la douleur et de l'inflammation",
129: "Retour de l'amplitude complète des mouvements",
130: "Tendinite, bursite, périarthrite",
131: "Arrêt et régression des modifications dégénératives",
132: "Synovite, ligamentite",
133: "Arthrose (tous les stades)",
134: "Ostéoporose",
135: "Polyarthrite rhumatoïde, goutte",
136: "Arthrose, spondylarthrite",
137: "Régénération documentée du tissu cartilagineux",
138: "Délais exacts de récupération avec « Nautubone » :",
139: "D'autres équipes scientifiques en Europe tentent de reproduire notre formule, mais les résultats obtenus jusqu'ici sont loin des nôtres. La technologie de nanodiffusion à biodisponibilité avancée, mise au point avec notre laboratoire, ne peut toujours pas être copiée — c'est justement elle qui permet à la gélule de livrer les ingrédients directement dans l'articulation par la circulation sanguine, au lieu qu'ils restent simplement à la surface de la peau, comme les pommades.",
140: "Combien de temps prend la récupération complète ? Le père Fernand explique, fort de 70 ans d'expérience",
141: "— La cure minimale que je recommande est de 30 jours. En cas d'atteintes plus graves — 60, et parfois 90 jours. Mais dans toute ma pratique, je n'ai eu AUCUN CAS où la méthode n'a pas donné de résultat. Aucun. Et j'ai soigné des personnes de 85, de 90, et même de 94 ans.",
142: "Nautubone ne fait pas qu'arrêter la douleur — il enclenche un processus de régénération biologique profonde. Prenez une gélule deux fois par jour et, dès les premières heures, vous sentirez un soulagement. En l'espace d'une semaine, vous remarquerez que vous bougez plus facilement. Et après la cure complète, vos articulations seront dans l'état où elles étaient il y a 20–30 ans.",
143: "Mais le plus précieux est ailleurs : l'effet est DURABLE. Une fois « réveillées », les cellules régénératrices continuent de travailler pendant des années !",
144: "Grâce à « Nautubone », plus de 190 000 personnes en France ont retrouvé leur mobilité. Voici seulement une petite partie de ceux que le père Fernand a aidés :",
145: "Retraitée, 66 ans, Angers. Quatre vertèbres déplacées et radiculopathie chronique. Son fils lui apportait les gélules Nautubone depuis Paris. Deux mois de cure — retour complet de la colonne en position normale. Son orthopédiste a demandé le nom du produit.",
146: "Comptable, 41 ans, Dijon. Ses genoux s'étaient déformés vers l'intérieur après deux grossesses et une prise de poids. L'orthopédiste lui a dit « habituez-vous ». Avec les gélules Nautubone — 30 jours de cure, deux fois par jour — l'axe des genoux s'est visiblement redressé sur la radio.",
147: "Retraité, 73 ans, Perpignan. L'arthrose lui avait déformé les orteils au point qu'il ne pouvait plus enfiler la moindre paire de chaussures. Il a pris les gélules Nautubone tous les jours — en 21 jours les orteils se sont redressés, et les chaussures d'il y a 5 ans lui vont de nouveau.",
148: "— Ces photos ne sont pas des miracles — ce sont la nature et la patience. Chacune de ces personnes a récupéré quelque chose que les médecins lui avaient dit impossible : des articulations saines et une vie sans douleur. Nautubone EST LE COURONNEMENT DE TOUTE MA VIE D'HERBORISTE — ET MON HÉRITAGE POUR LES GÉNÉRATIONS À VENIR !",
149: "Pourquoi le père Fernand ne reçoit plus personne — et comment Nautubone est devenu le seul moyen d'accéder à sa recette",
150: "« Ma santé ne me permet plus de recevoir les malades en personne. Mais ma formule continuera de soigner — par les mains de mon fils. »",
151: "— L'année dernière, j'ai pris la décision la plus difficile de ma vie : ne plus recevoir de gens. La liste d'attente comptait plus de 2 000 noms — et je ne pouvais pas les laisser sans aide. C'est pourquoi j'ai permis à mon fils Julien d'emporter la recette là où on la fabriquera pour tous. Maintenant je suis tranquille — Nautubone, c'est exactement ce que je donnais aux gens qui venaient chez moi, seulement sous une forme pratique. La recette est entre de bonnes mains.",
152: "— Nautubone ne se vend pas en pharmacie — le procédé de fabrication est complexe et les quantités sont limitées. Il n'est disponible que par le programme en ligne, deux fois par an. Mais dans le cadre du programme, les remises atteignent",
153: "— parce que notre but n'est pas le profit, mais l'accessibilité. Surtout pour les retraités, pour qui mon père a insisté qu'il y ait la remise maximale.",
154: "Pour vous inscrire, utilisez le formulaire de commande officiel ci-dessous — il vient directement de l'équipe de production de Julien Delaunay.",
155: "Ne manquez pas la dernière occasion de cette année — Nautubone peut être épuisé avant la fin du programme !",
156: "— Cette année, nous avons réussi à produire 5&nbsp;000 boîtes de gélules Nautubone spécialement pour les habitants de la France. Mais vu la demande — qui est énorme — ces quantités partiront vite. La série suivante ne sera prête qu'à la fin de",
157: "Le programme de soutien est actif jusqu'au",
158: "— chaque habitant de France de plus de 40 ans peut bénéficier",
159: "jusqu'à 50 % de remise",
160: ". Après cette date, il faudra attendre au moins 6 mois pour une nouvelle occasion.",
161: "Ne remettez pas à plus tard. Mon père disait toujours aux gens : « Vos articulations ne vous attendent pas — elles se détruisent à chaque seconde. » Tant que le programme est actif, profitez-en. Nautubone a un effet cumulatif — une seule cure complète suffit pour 5–6 ans d'articulations saines.",
162: "Il vous suffit d'indiquer votre nom et votre numéro de téléphone dans le formulaire. Un conseiller vous appellera, établira un programme individuel pour votre cas et organisera la livraison à n'importe quelle adresse en France — en 2–3 jours, par la poste ou par coursier jusqu'à votre porte.",
163: "Je souhaite la santé à tous ! Prenez soin de vos articulations aujourd'hui, pour marcher demain ! Avec respect : Fernand Delaunay et son fils Julien.",
164: "Mis à jour :",
}
