# -*- coding: utf-8 -*-
# France / herboriste, nœuds 165..236 + attributs (forme : GÉLULES)
F3 = {
165: "En raison d'une demande extrêmement forte, les stocks de Nautubone peuvent être épuisés avant la fin prévue du programme ! Aujourd'hui —",
166: "18/12/2025 — c'est le dernier jour pour commander avec la remise",
167: "ou jusqu'à épuisement des stocks.",
168: "Attention ! Ne fermez pas et n'actualisez pas la page — les gélules Nautubone réservées pour vous seront proposées à la personne suivante sur la liste d'attente !",
169: "Votre place réservée dans le programme :",
170: "Formulaire de commande officiel",
171: "Pour obtenir",
172: "50 % de remise",
173: ", indiquez votre nom et votre numéro de téléphone dans les champs ci-dessous et appuyez sur le bouton « COMMANDER ».",
174: "Stocks restants :",
175: "79 €",
176: "39 €",
177: "Nom",
178: "Numéro de téléphone",
179: "COMMANDER",
180: "✔️ Livraison à n'importe quelle adresse en France en 2–3 jours",
181: "par la poste ou par coursier jusqu'à votre porte",
182: "COMMENTAIRES :",
183: "Martine Lefèvre",
184: "J'ai attendu cet article pendant des mois ! Une amie de Paris est allée voir le père Fernand en personne il y a quelques années — elle disait que ce n'est pas un homme, c'est un miracle. Dommage qu'il ne reçoive plus personne, mais si Nautubone a la même recette — je commande tout de suite. Heureusement que j'ai attrapé la remise !",
185: "Danielle Perrot",
186: "Le coursier me l'a apporté mercredi. Cela fait dix jours que je prends une gélule matin et soir — et la différence est ÉNORME ! Je me lève sans ce craquement affreux ! Mon mari regarde et n'y croit pas. Je vais faire la cure complète de 60 jours, mais je suis déjà convaincue que ça marche.",
187: "Josiane Caron",
188: "J'ai 72 ans et pendant trois ans j'ai souffert de douleurs à la hanche. Marcher était un supplice. L'orthopédiste a dit : « Prothèse ou patience. » Je ne voulais ni l'un ni l'autre. Nautubone m'a aidée en deux mois — maintenant je marche un kilomètre et demi tous les jours ! Et la radio montre une amélioration que mon médecin n'arrive pas à expliquer. Merci, père Fernand, et merci à votre fils !",
189: "Bernard Chevalier",
190: "En tant qu'ancien sportif, je sais ce que veut dire vivre avec un cartilage détruit. J'avais les genoux d'un homme de 90 ans — alors que je n'en ai que 54. Nautubone m'a rendu des mouvements que je ne faisais plus depuis 10 ans. Je peux de nouveau m'accroupir ! Je ne connais aucun autre produit capable de faire cela.",
191: "Colette Chevalier",
192: "Je suis un peu inquiète… Est-ce que ça vaut le coup ? J'ai 66 ans, mes articulations craquent au moindre mouvement et mon dos ne me laisse aucun répit. Mais j'ai été déçue tellement de fois par toutes sortes de remèdes « miracles » qu'il m'est devenu difficile d'y croire. Est-ce que ça aide vraiment ?",
193: "Gérard Moulin",
194: "Madame Colette, je comprends parfaitement vos doutes — je les avais aussi. Mais Nautubone est différent de tout ce que j'ai essayé jusqu'ici. Je le prends depuis 5 semaines pour les genoux et le bas du dos — et je peux vous dire que la différence est le jour et la nuit.",
195: "Avant, je ne pouvais pas me pencher pour lacer mes chaussures. Maintenant je le fais sans y penser. Commandez au moins une boîte et jugez par vous-même — vous n'avez rien à perdre !",
196: "Sylvie Garnier",
197: "Trois jours après avoir commencé à prendre les gélules, la douleur dans mon genou a diminué de moitié ! Nous en sommes au 12e jour et je monte déjà les escaliers sans me tenir à la rampe. Je vais faire la cure complète — je crois que dans deux mois je serai comme neuve !",
198: "Nathalie Vasseur",
199: "Une « bosse » a commencé à pousser dans mon dos il y a environ deux mois. J'étais terrifiée ! J'ai essayé toutes sortes de pommades de pharmacie — rien. Mais les gélules Nautubone, c'est tout autre chose — en 40 jours la bosse a presque entièrement disparu ! Je continue à les prendre, mais je suis déjà incroyablement satisfaite. Voilà à quoi ressemble la différence :",
200: "Paulette Girard",
201: "J'avais un nerf comprimé dans le bas du dos — à cause de la douleur je ne pouvais ni dormir ni rester debout. Le médecin m'a prescrit des antidouleurs puissants qui me rendaient constamment malade. J'ai commencé à prendre les gélules Nautubone deux fois par jour — au bout d'une semaine la douleur a nettement diminué, et au bout d'un mois — elle a complètement disparu ! Je continue la cure, mais ma vie a déjà changé !",
202: "Roland Bertrand",
203: "J'ai 79 ans et pendant trois ans je marchais à peine. Mon fils a commandé Nautubone — sans me demander, parce qu'il savait que je refuserais. Il me donne la gélule chaque matin et chaque soir. Et le résultat ? Au bout d'un mois et demi, je vais jusqu'au parc tous les jours ! Je me sens comme à 60 ans ! Merci, père Fernand — à 102 ans vous êtes plus sage que tous les médecins d'aujourd'hui !",
204: "Michel Faure",
205: "Avant Nautubone, je ne pouvais pas lever les bras au-dessus de la tête — mon épaule craquait et me faisait horriblement mal. Pendant deux ans j'ai fait le tour des médecins — personne ne m'a aidé. Deux mois avec Nautubone et mes bras fonctionnent de nouveau normalement. Voici ma radio — le médecin lui-même n'y a pas cru :",
206: "Annie Leroux",
207: "J'ai commandé pour ma belle-mère — elle a 81 ans et n'arrivait presque plus à se lever du lit. Les médecins refusaient de faire quoi que ce soit — « à cet âge plus rien n'aide », disaient-ils. Avec Nautubone, en 2 mois elle marche déjà dans la cour et fait même la cuisine ! Nous n'en revenions pas.",
208: "Alain Marchal",
209: "Ma femme est restée couchée quatre mois — sa colonne a tout simplement lâché. Les médecins ont proposé une opération à 8 000 € sans la moindre garantie. Nous avons décidé d'essayer les gélules Nautubone — nous n'avions rien à perdre. Je les lui donnais deux fois par jour. Au bout de 5 semaines, elle s'est levée. Hier nous sommes allés ensemble au marché — pour la première fois depuis six mois ! J'ai pleuré de bonheur.",
210: "Nadine Boyer",
211: "J'ai commandé la semaine dernière, je l'ai reçu le troisième jour. J'ai tout de suite commencé à prendre les gélules — et le soulagement est venu le deuxième jour ! Comme si quelqu'un me graissait les articulations de l'intérieur. Cela fait deux semaines que je les prends deux fois par jour et j'ai hâte de voir le résultat complet !",
212: "Simone Renard",
213: "J'ai 74 ans. Pendant cinq ans j'ai souffert d'arthrose et de douleurs dorsales. J'ai essayé littéralement tout — pommades, comprimés, injections, kinésithérapie. RIEN n'a aidé sur la durée. Les gélules Nautubone sont la seule chose qui m'ait donné un VRAI RÉSULTAT — je les prends deux fois par jour et en un mois et demi mes articulations sont devenues totalement différentes. Le médecin ne croit pas les radios !",
214: "Véronique Legrand",
215: "Je connais le père Fernand personnellement — il y a 12 ans il m'a aidée avec une hernie discale. En trois semaines j'étais de nouveau sur pied ! Son nom, toute la région autour de Paris le connaît. Je suis heureuse que son fils poursuive son œuvre !",
216: "Ginette Delorme",
217: "Mon père a 84 ans et pendant trois ans il ne sortait plus de la maison. Les articulations, le dos, les genoux — tout lui faisait mal. Il disait qu'il attendait de partir. Après deux mois avec Nautubone — hier il est sorti dans la cour et a arrosé le jardin ! Pour la première fois depuis trois ans ! Je ne peux pas décrire ce que j'ai ressenti. Merci du fond du cœur !!!",
218: "Mireille Dubois",
219: "Est-ce que quelqu'un sait si on peut l'utiliser en cas d'allergies ? Je réagis à presque tout — même une simple aspirine me fait gonfler les doigts. J'ai peur d'essayer quelque chose de nouveau…",
220: "Patrick Colin",
221: "Mireille, moi je suis allergique à quatre types de médicaments. Je prends les gélules Nautubone depuis 50 jours — aucune irritation, aucun gonflement, aucune rougeur. La composition est entièrement faite d'extraits naturels — elle ne contient pas de produits chimiques. Vous pouvez commander en toute tranquillité !",
222: "Denise Aubert",
223: "Avant, je n'avais pas la force de me lever — chaque mouvement était une souffrance, je pensais que ma vie était finie. Ma fille a commandé les gélules Nautubone et m'a poussée à essayer — elle me les donnait matin et soir. Deux mois plus tard ? J'ai dansé au mariage de mon petit-fils !!! Jamais de ma vie je n'ai été aussi reconnaissante !",
224: "Élisabeth Blanchard",
225: "J'ai commandé pour ma mère. Elle avait des douleurs permanentes dans la nuque qui lui provoquaient des vertiges et des nausées — sa vie était devenue insupportable. Dès la deuxième semaine avec Nautubone, les douleurs ont fortement diminué et les vertiges ont complètement cessé ! Maman rit de nouveau — cela faisait longtemps que je ne l'avais pas vue ainsi.",
226: "Suzanne Morel",
227: "Je me demande — si le père Fernand est si bon, pourquoi ces produits ne se vendent-ils pas partout ? Pourquoi seulement en ligne ? Pourquoi les pharmacies ne les proposent-elles pas ?",
228: "Michel Rey",
229: "Parce que les pharmacies gagnent de l'argent sur les gens qui achètent des antidouleurs tous les mois ! Si tout le monde soignait ses articulations une bonne fois pour toutes — qui achèterait leurs médicaments hors de prix ? Réfléchissez logiquement !",
230: "Odette Perrin",
231: "J'ai lu tous les commentaires — et j'ai été touchée. Je commande maintenant, pour moi et pour mon mari. J'ai pris trois boîtes de gélules, pour la cure complète. Si ça aide ne serait-ce que la moitié de ce que les gens écrivent — je serai heureuse !",
232: "Lucienne Masson",
233: "Mon orthopédiste m'a dit qu'à 63 ans je devais m'habituer à la douleur — soi-disant il n'y a pas de remède. J'ai commandé Nautubone pour leur donner tort à tous. On verra bien qui a raison !",
234: "Télécharger un avatar",
235: "Télécharger une photo",
236: "ENVOYER",
}
ATTRS_F = {
 "Вашето име": "Votre nom",
 "Вашият телефонен номер": "Votre numéro de téléphone",
 "Вашият коментар": "Votre commentaire",
}
