# -*- coding: utf-8 -*-
# Хорватская адаптация ветеринарного лендинга. Форм-фактор — ГЕЛЬ.
# Добри Гьошев -> Mato Jurić (djed Mato), 97, veterinar, selo kraj Zagreba
# Пламен Гьошев -> Tomislav Jurić (фармацевт)
# Ганчо Хубенов -> Stjepan Barić, 66, potkivač, Samobor
# Валери Дренски -> Damir Novosel, 49, vozač kamiona, Bjelovar
# София -> Zagreb | лев -> euro (Хорватия в еврозоне, цена 78/39 EUR без изменений)

HR = {
0: "Mato Jurić, veterinar od 97 godina iz okolice Zagreba: šezdeset godina liječio je zglobove konja, krava, bikova i volova — a onda je po prvi put isprobao pripravak na sebi",
1: "SA 97 GODINA ON JE NAJSTARIJI VETERINAR U HRVATSKOJ I JEDINI IZ SVOJE GENERACIJE KOJI JOŠ UVIJEK ČUČNE UZ KONJA I SAM USTANE. ŠEZDESET GODINA DAVAO JE TAJ PRIPRAVAK ŽIVOTINJAMA — A ONDA GA JE, S OSAMDESET I JEDNOM, PO PRVI PUT ISPROBAO NA SEBI",
2: "Objavljeno:",
3: "„Kako je veterinar Mato Jurić šezdeset godina vraćao na posao konje, krave i volove — a onda, kada su njegova vlastita koljena otkazala, po prvi put isprobao isti pripravak na sebi“",
4: "U jednom selu nedaleko od Zagreba živi čovjek koji je šezdeset godina liječio zglobove onih koji se ne znaju žaliti. Konji, krave, bikovi, volovi. Sa 97 godina veterinar Mato Jurić svako jutro sam obiđe dvorište, sam podigne vreću zobi i — što je najvažnije — sam čučne i sam ustane. Iz njegove generacije veterinara nitko više ne izlazi na teren. Mnogi ne silaze ni s trijema.",
5: "Šezdeset godina radio je po stajama i dvorištima u okolici Zagreba: konji s nagnječenim zglobovima, krave koje nisu mogle ustati nakon teljenja, volovi i bikovi kojima je koljeno oteklo od tereta. Kroz njegove ruke prošlo je više od 30 000 grla. Ljudima dugo nije davao taj pripravak — nije ni imao pravo.",
6: "Ali prava zagonetka nisu životinje koje je vratio na posao. Prava zagonetka je on sam. Sa 97 godina — ni artroza, ni ukočen vrat, ni štap. A četrdeset godina radio je na koljenima, na betonu, u staji, zimi, s rukama do lakata u hladnoj vodi.",
7: "I nije uvijek bilo tako. S osamdeset i jednom koljena su mu otkazala. Tada je, po prvi put u životu, uzeo ono što je šezdeset godina davao životinjama — i isprobao na sebi. Danas, šesnaest godina kasnije, po prvi put je pristao da taj pripravak izađe u javnost.",
8: "Mato Jurić: „Cijeli život radio sam s onima koji ne znaju reći da ih boli — i upravo zato morao sam naučiti da se",
9: "zglob može obnoviti u svakoj dobi, ako znaš kako „probuditi“ stanice koje ga grade.",
10: "MOJ CILJ UVIJEK JE BIO SAMO JEDAN — POMOĆI TIJELU DA PROIZVODI NOVO HRSKAVIČNO I KOŠTANO TKIVO, TOČNO KAO U MLADOSTI. KADA SAM VIDIO DA TO DJELUJE I KOD MENE, POZVAO SAM SINA. SADA JE TOMISLAV SVE TO PRETVORIO U PROIZVOD,",
11: "KOJI MOŽE STIĆI U SVAKI DOM U HRVATSKOJ.",
13: "Tomislav Jurić — sin veterinara — odrastao je među vagama, bočicama i očevim obilascima i još je kao dijete znao što ide u kojoj mjeri. Nije postao veterinar — završio je farmaciju. Kada je vidio što se dogodilo s očevim koljenima, shvatio je da pripravak ne smije ostati u jednoj staji. Pronašao je laboratorij i ljude koji su preračunali doze sa životinje od 600 kilograma na čovjeka — i pretvorili šezdesetogodišnje iskustvo u proizvod dostupan svakome.",
14: "Rezultat te suradnje nadmašio je sva očekivanja. Ali prije nego što vam ispričam o proizvodu, pogledajmo zašto je sve što znate o liječenju zglobova najvjerojatnije pogrešno.",
15: "Laž u koju vjeruje cijela Hrvatska:",
16: "„Analgetici znače liječenje“ — POGREŠNO, to je samo dopuštenje da nastavite uništavati zglob!",
17: "Mato Jurić:",
18: "— Šezdeset godina radim sa zglobovima i reći ću vam nešto što nijedna ljekarna neće priznati: nijedan analgetik u povijesti nije obnovio ni milimetar hrskavice. Nijedan. On priguši bol, a hrskavica se u međuvremenu i dalje raspada — samo što vi to više ne osjećate. A kada ponovno osjetite, bit će kasno.",
19: "I sada ono najvažnije, ono čemu sam posvetio život. Čovjek zna trpjeti. Konj ne zna. Krava ne zna. Vol koji stane jest vol koji je već otpisan. Zato nama u veterini nikada nije bilo dopušteno prigušivati bol. Morali smo vraćati tkivo, jer ništa drugo nije imalo smisla. To je cijela razlika između onoga što piše na vašoj polici i onoga što sam ja šezdeset godina davao u staji.",
20: "Kralježnica je posebno ranjiva. Međukralježnični diskovi nemaju vlastitu prokrvljenost — hrane se difuzijom, što znači da njihovo oštećenje teče tiho, bez boli, ponekad godinama. Kada se bol napokon pojavi, oštećenje je već uznapredovalo. Pritisak na živac zbog diskus hernije pretvara život u noćnu moru: počinje laganim trncima u nozi, a završava potpunim gubitkom pokretljivosti.",
21: "Pogledajte što pokazuje ova rendgenska snimka. Žena, tek 39 godina, učiteljica — donijela mi ju je u dvorište jer joj nitko nije znao objasniti što se točno vidi. Kralježnica joj je u stanju u kakvom sam do prije dvadeset godina viđao zglob radnog konja koji je išao na otpis. Sjedenje na stolici po 8 sati dnevno, nedostatak kretanja i potpuno nepoznavanje vlastitog tijela — eto što donosi suvremeni način života.",
22: "Snimka iz mape koju djed Mato čuva desetljećima: kralježnica 39-godišnje učiteljice iz Osijeka. Došla je s „laganim umorom u križima“.",
23: "Ako nakon 40. godine osjećate bol, ukočenost ili pucketanje u zglobovima — vaša hrskavica se već raspada. To nije „od umora“ i nije „normalno“.",
24: "Kod kralježnice je proces nekoliko puta brži i podmukliji — bol se pojavljuje tek kada je oštećenje već kritično!",
25: "Mato Jurić:",
26: "— Želim biti potpuno iskren. Poznajem ljude koji su odgađali mjesecima. Rezultat? Pritisnut živac koji nikada više nije proradio normalno. Obnavljati disk kada je živac već mrtav nema nikakvog smisla —",
27: "DISK SE MOŽE VRATITI, ALI ŽIVAC — NE!",
28: "A što onda ostaje? ŠTAP, INVALIDSKA KOLICA I OVISNOST O TUĐOJ POMOĆI DO KRAJA ŽIVOTA!",
29: "A što nudi suvremena kirurgija? Skupe i rizične operacije s metalnim implantatima. Vidio sam dovoljno ljudi koji su se nakon operacije kralježnice osjećali GORE nego prije.",
30: "INFEKCIJE, NEUSPJELA SRASTANJA, KRONIČNA BOL I NA KRAJU — PONOVNA OPERACIJA. A PONEKAD — NEPOVRATNA OŠTEĆENJA!",
31: "Djed Mato pokazuje snimku koju mu je donio čovjek nakon operacije s metalnim vijcima: „To je tipičan rezultat — implantat se nije pravilno primio.“",
32: "Statistika je nemilosrdna: kod 60 % operiranih hernija se vraća za 2–4 godine. A cijena? Mjeseci nepokretnosti, tisuće eura i potpuna neizvjesnost. Mnogi priznaju: kada bi mogli vratiti vrijeme, nikada ne bi legli na operacijski stol.",
33: "Ti simptomi znače da vaša hrskavica već umire! A ako imate preko 40–50 godina — proces je nepovratan bez intervencije!",
34: "— Za šezdeset godina kroz moje ruke prošlo je više od 30 000 grla — konji, krave, bikovi i volovi — i mogu reći sljedeće: svaka zanemarena bol u zglobu korak je prema štapu. Samo tijekom",
35: " u Hrvatskoj je registrirano više od 125 000 novih slučajeva teških bolesti zglobova — od čega 23 000 kod osoba u dobi od 38 do 48 godina. To nije problem starosti. To je problem nedjelovanja.",
36: "Ako vam je organizam već dao neki od tih signala — ne čekajte nijedan dan!",
37: "Evo popisa zbog kojeg sam kod životinje odmah mijenjao terapiju — i zbog kojeg bih kod čovjeka učinio isto:",
38: "Jutarnja ukočenost koja ne prolazi s pokretom;",
39: "Pucketanje, škljocanje ili škripanje pri pokretu;",
40: "Pojačavanje boli pri promjeni vremena;",
41: "Poteškoće pri savijanju ili ispravljanju koljena;",
42: "Oticanje, crvenilo ili toplina oko zgloba;",
43: "Bol pri penjanju ili silaženju niz stube;",
44: "Kronični umor i težina u nogama;",
45: "Bol u križima koja „puca“ prema bedru ili stopalu;",
46: "Trnci ili mravinjanje u prstima;",
47: "Promjena hoda — šepanje, nestabilnost;",
48: "Nemogućnost stajanja duže od 10–15 minuta;",
49: "Ako se prepoznajete čak i u dva od tih simptoma — vaša hrskavica se već uništava. A kod kralježnice je proces tri do četiri puta brži, jer su međukralježnični diskovi pod stalnim pritiskom.",
50: "REZULTAT: HERNIJA, PRITISNUT ŽIVAC, DEFORMACIJA KRALJEŠAKA, GUBITAK POKRETLJIVOSTI — I SVE TO MOŽE SE DOGODITI ZA NEKOLIKO TJEDANA!",
51: "Ne odgađajte, jer vam organizam ne daje beskonačne prilike!",
52: "Pogledajte ove ljude ispod. Svatko od njih imao je iste simptome koje vjerojatno i vi osjećate u ovom trenutku. Svatko je rekao „proći će“. I svatko bi danas dao sve da vrati vrijeme i djeluje onda kada je još imao priliku.",
53: "Bivša pacijentica jedne klinike, 58 godina, Split. Tri pomaknuta kralješka za više od 8 mm, leđna moždina pod pritiskom. Dvaput je odgodila odlazak djedu Mati — kada je napokon došla, bila je korak od paralize.",
54: "Žena od 61 godine iz Rijeke — grba joj je narasla na 4 cm za manje od godine dana. Vratni kralješci su deformirani toliko da se glava više ne može okrenuti u stranu. Analgetici su prestali djelovati prije 8 mjeseci.",
55: "Domaćica, 59 godina, Karlovac. Koljenski zglobovi su joj toliko istrošeni da je hrskavica stanjena na manje od 1 mm. Svaki korak zvuči kao škripa starih vrata. Tri ortopeda rekla su joj da je jedino rješenje dvostruka proteza, za više od 10 000 eura.",
56: "Bivši rudar, 68 godina, Labin. Hrskavica u desnom koljenu potpuno je uništena, koštano tkivo ušlo je u fazu nekroze. Četveromjesečno odgađanje stajalo ga je uda — amputacija iznad koljena i doživotna ovisnost o invalidskim kolicima.",
57: "Mato Jurić:",
58: "Imam 97 godina i mogu vam reći iz osobnog iskustva — a pod osobnim mislim doslovno na vlastito koljeno: organizam se sposoban sam obnoviti u SVAKOJ dobi, pod uvjetom da znate KAKO ga pokrenuti.",
59: "A AKO STE VEĆ PREKO 50–60 GODINA, NE ČEKAJTE NI SEKUNDE!",
60: "Kod vas je oštećenje gotovo sigurno ušlo u kritičnu fazu — hitno morate zaustaviti uništavanje i pokrenuti izgradnju nove hrskavice, novih kostiju i novih tkiva!",
61: "Prvo je isprobao na sebi. Tek nakon toga — na onima koje su liječnici proglasili beznadnima!",
62: "S osamdeset i jednom koljena su mu otkazala. Ono što je šezdeset godina davao volovima, po prvi put je stavio na sebe — a nakon njega dobio je to potkivač Stjepan Barić. Evo kako je bilo…",
63: "„Šezdeset godina čučao sam pod životinjama i na kraju su moja koljena otkazala prva. Nisam mogao ustati sa zemlje bez ograde. Tri mjeseca sam trpio, a onda sam jedne večeri otišao u komoru, uzeo ono što sam istog jutra pripremio za jednog konja i — preračunao to na svoju težinu. Nisam rekao nikome. Ni ženi, ni sinu. Da nije djelovalo, nitko ne bi ni saznao.“",
64: "„Četrnaestog dana čučnuo sam uz psa i ustao bez oslonca. Sjeo sam na prag i dugo šutio. Šezdeset godina držao sam to za životinje, a nikada mi nije palo na pamet zapitati se zašto čovjeku ne dajemo isto. Odgovor je, naravno, jednostavan: zato što ja nisam liječnik i nisam imao pravo.“",
65: "„Prvi kojem sam ipak dao bio je Stjepan, potkivač iz Samobora. Trideset i sedam godina radio je čučeći pod konjem i cijelu godinu gledao sam ga kako šepa kroz moje dvorište. Ništa mu nisam obećao. Rekao sam mu samo: ‚Stjepane, ovo trideset godina vraća konje na posao, a već pola godine vraća i mene. Tebi nemam pravo davati, ali tebi nitko drugi ni neće ponuditi.‘“",
66: "Stjepan Barić: „Trećeg tjedna po prvi put nakon dvije godine čučnuo sam i ustao bez oslonca. Danas, godinu dana kasnije, radim po četiri konja dnevno, kao prije. Imam šezdeset i šest godina. Moj ortoped pogledao je novu snimku i pitao me što sam radio — rekao sam mu istinu. Nije mi povjerovao.“",
67: "Stjepan Barić, 66 godina, potkivač, Samobor — prvi čovjek nakon samog djeda Mate",
68: "Drugi iznimni slučaj je Damir Novosel — vozač kamiona od 49 godina iz Bjelovara, koji je nakon dvadeset godina za volanom zadobio teško oštećenje kralježnice i bio prisiljen kretati se u invalidskim kolicima.",
69: "Damir je isprobao metodu Mate Jurića, a rezultati su šokirali čak i njegova obiteljskog liječnika.",
70: "NJEGOVA KRALJEŽNICA POČELA SE OPORAVLJATI, BOL JE POTPUNO NESTALA, A NAJNEVJEROJATNIJE —",
71: "NAPUSTIO JE INVALIDSKA KOLICA NAKON SAMO 4 TJEDNA!",
72: "Damir nam je ispričao:",
73: "„Dvadeset godina vozio sam na duge relacije, ali o vlastitoj kralježnici nisam vodio računa. Jednog jutra probudio sam se i nisam mogao pomaknuti križa. Žena je pozvala Hitnu. Dijagnoza — tri hernije i pritisak na živčani korijen. Liječnici su predložili operaciju za 6 000 eura, ali bez jamstva.“",
74: "Mjesecima sam sjedio kod kuće u invalidskim kolicima. Djeca su me gledala s tugom, žena je plakala svake večeri. Osjećao sam se kao teret. Poželio sam nestati…",
75: "„Tada je moj šogor, koji radi u konjičkom centru, čuo za djeda Matu od jednog konjušara. Javio sam se, poslao rendgenske snimke i starac je rekao: ‚Nije kasno. Isto to vidio sam kod životinja koje su poslije trčale — a onda sam to vidio i na vlastitim koljenima.‘ Te riječi dale su mi više nade nego sve što sam čuo od desetaka liječnika.“",
76: "„Četvrtog dana već sam mogao stajati. Puni tečaj trajao je 80 dana. Danas ponovno radim — ne na dugim relacijama, nego u dispečerskom uredu, ali HODAM. Trčim s djecom u parku. Živim. Rendgen pokazuje da su mi diskovi obnovljeni 90 %. Djed Mato je jedini koji me nije odbio — i jedini koji mi je pomogao.“",
77: "Priča se brzo pročula: prvo potkivači i konjušari, zatim njihove žene, pa cijelo selo. Ljudi kojima su liječnici govorili „naviknite se na bol“ ponovno su prohodali. Kako je to moguće?",
78: "Pripravak koji je djed Mato šezdeset godina radio za životinje — i koji je s osamdeset i jednom po prvi put stavio na vlastito koljeno",
79: "Tajna metode „Endogena tkivna reaktivacija“ — kako organizam sam počinje proizvoditi novu hrskavicu, nove kosti i nove ligamente!",
80: "Mato Jurić:",
81: "— Dopustite da vam objasnim nešto što konvencionalna medicina odbija priznati. Organizam svakog živog bića — pa i čovjeka od 90 godina — posjeduje „uspavane“ stanice koje grade tkivo. Iste one koje su vam u mladosti lako pravile hrskavicu, kosti i ligamente. S godinama one ne umiru — jednostavno „zaspu“, jer im organizam prestaje slati ispravan signal.",
82: "Prije šezdeset godina, radeći sa životinjama koje su bile pred otpisom, otkrio sam da određena kombinacija prirodnih tvari — u strogo određenim omjerima — djeluje kao „ključ za paljenje“ za te uspavane stanice. Metodu sam nazvao",
83: "„Endogena tkivna reaktivacija“",
84: "— jer ne unosi ništa umjetno, nego pokreće vlastite rezerve organizma. Upravo zato NEMA nuspojava, NEMA oštećenja organa i NEMA ovisnosti. U veterini to inače ne bi ni prošlo: životinja ne može desetljećima piti tablete a da se to ne vidi na jetri. I zato, kada je došlo do mene samoga, znao sam da mogu mirno pokušati.",
85: "Šezdeset godina primjenjivao sam tu metodu kod životinja. Šesnaest godina primjenjujem je i na sebi. A posljednjih desetak — i kod ljudi iz mog sela, koji su me sami molili nakon što su vidjeli kako hodam. Uvijek isti redoslijed: zaustavljanje uništavanja, smanjenje boli i postupno vraćanje funkcije zgloba.",
86: "Sama formula nije složena — ali preciznost je sve. Svaki sastojak mora biti u točnoj količini, do stotinke miligrama. Ako se omjeri ne poštuju, učinak jednostavno nestaje. Upravo zato desetljećima sam mjerio osobno, za svaku životinju posebno — a kada je došlo do mog koljena, preračunavao sam mjeru tri večeri, jer nisam imao koga pitati.",
87: "Sastav po receptu veterinara Jurića — isti onaj koji je stavio na svoje koljeno (aktivne tvari po dozi):",
88: "Omega-3",
89: "laneno sjeme: 4500 mg",
90: "Glukozamin sulfat",
91: "rakovi: 1100 mg",
92: "Magnezijev citrat",
93: "morske alge: 390 mg",
94: "Gingerol",
95: "đumbir: ekstrakt 4200 mg",
96: "AKBA",
97: "tamjanova smola (Boswellia): ekstrakt 1100 mg",
98: "Silicij",
99: "poljska preslica: ekstrakt 320 mg",
100: "Kurkumin",
101: "kurkuma: ekstrakt 2300 mg",
102: "Ti sastojci izgledaju jednostavno, ali pronaći ih u odgovarajućoj kvaliteti i iz pravog izvora iznimno je teško. Glukozamin takve čistoće desetljećima se nabavljao veterinarskim kanalom, a ne preko ljekarni. A miješanje kod kuće praktički je nemoguće — jer doziranje mora biti točno do 0,1 mg, a razlika između životinje od 600 kilograma i čovjeka od 80 nije stvar procjene.",
103: "Upravo zato desetljećima sam mjerio sam, za svaku životinju posebno — i za sebe. Ali moj sin Tomislav vidio je cijelu sliku.",
104: "Kako je Tomislav Jurić preračunao šezdesetogodišnji očev recept sa životinje na čovjeka — Nautubone",
105: "Tomislav Jurić:",
106: "— Odrastao sam uz očevu vagu. Mjeru sam znao napamet sa četrnaest godina. Nisam postao veterinar — upisao sam farmaciju. A onda sam, prije šesnaest godina, vidio nešto zbog čega sam ga prestao nagovarati i počeo inzistirati: moj otac, s osamdeset i jednom, ponovno čučne i ustane. Tata, rekao sam mu, ovo ne smije ostati u našoj staji.",
107: "Pet godina obilazio sam laboratorije u Zagrebu i Münchenu dok nisam pronašao ljude koji su pristali ozbiljno ispitati očevu recepturu i preračunati je sa životinje od 600 kilograma na čovjeka. Odgovor koji sam dobio oduševio me: kombinacija tih sastojaka u točnim omjerima aktivira proizvodnju kolagena tipa II i proteoglikana — dvaju glavnih gradivnih elemenata hrskavice. Drugim riječima: organizam doslovno „pamti“ kako graditi novu hrskavicu, samo mu treba ispravan signal.",
108: "Zajedno s laboratorijem razvili smo postupak koji smo nazvali",
109: "„Tehnologija nanodifuzije s naprednom bioraspoloživošću“",
110: "— metoda kojom se aktivne tvari zatvaraju u posebne nanočestice koje prodiru duboko kroz kožu i stižu izravno do oštećenog zglobnog tkiva. To povećava apsorpciju za oko 380 % u usporedbi s običnim gelovima i mastima. Proizvod sam nazvao",
111: "Nautubone",
112: "— gel koji se nanosi na kožu i djeluje točno ondje gdje je potrebno. Nazvao sam ga u čast svog oca, njegovih šezdeset godina u staji i jednog koljena koje je dokazalo da to djeluje i kod čovjeka.",
113: "Gel Nautubone sadrži svih sedam sastojaka iz izvornog očevog pripravka, u dozama preračunatim za čovjeka, plus 29 dodatnih ekstrakata i vitamina koje smo dodali nakon laboratorijskih ispitivanja u Münchenu. Rezultat je gel koji djeluje TOČNO JEDNAKO DOBRO kao ono što je moj otac mjerio vlastitim rukama — ali može biti dostavljen u svaki dom u Hrvatskoj. Nanosite ga na zglobove dva puta dnevno, a aktivne tvari prodiru kroz kožu izravno do zahvaćenih zglobova.",
114: "„Nautubone je nasljeđe mog oca — njegovih šezdeset godina rada, zatvorenih u jednu formulu. Svaki sastojak odabran je s preciznošću s kojom je on mjerio svakoj životinji i svakom čovjeku koji je došao do njegove ograde. Ovo nije masovni proizvod iz ljekarne — ovo je djelo cijelog jednog života.“",
115: "Najnevjerojatnije kod Nautubonea jest to što ne samo da ublažava bol — nego aktivira mehanizam regeneracije koji je s godinama zaspao. Gel se nanosi na kožu, a nanočestice prenose aktivne tvari duboko u zglobno tkivo — ondje kamo obične tablete i injekcije nikada ne stižu. Sinergija između sastojaka pojačava učinak do 20 puta u usporedbi s njihovim odvojenim uzimanjem.",
116: "Četiri faze oporavka s Nautuboneom — što se događa u vašem organizmu korak po korak",
117: "Mato Jurić:",
118: "— Prvo sam te četiri faze gledao kod životinja. Zatim sam ih, s osamdeset i jednom, sam prošao. Moj sin ih je dokumentirao i ugradio u Nautubone, tako da ih svatko može proći kod kuće.",
119: "Četiri faze „Endogene tkivne reaktivacije“:",
120: "Faza 1 — Zaustavljanje boli i upale:",
121: "Već od prvog nanošenja gela nanočestice prenose aktivne tvari kroz kožu izravno u oštećena tkiva, blokirajući upalne molekule. Bol se vidljivo smanjuje za 24–48 sati — bez opterećivanja jetre i bubrega, jer gel koristi tehnologiju usmjerene apsorpcije kroz kožu i ne prolazi kroz tradicionalni jetreni metabolizam.",
122: "Faza 2 — Zaustavljanje uništavanja:",
123: "Između trećeg i sedmog dana organizam prestaje razgrađivati hrskavično i koštano tkivo. Povećava se proizvodnja sinovijalne tekućine — prirodnog „maziva“ zglobova. Trenje se smanjuje i pokreti postaju lakši.",
124: "Faza 3 — Buđenje regenerativnih stanica:",
125: "Ovo je srce metode. „Uspavani“ hondrociti i osteoblasti dobivaju biokemijski signal i počinju proizvoditi novu hrskavicu i koštano tkivo. Upravo ta faza čini Nautubone jedinstvenim — nijedan drugi proizvod ne aktivira taj mehanizam.",
126: "Faza 4 — Trajna zaštitna barijera:",
127: "Nakon 30–60 dana novonastala tkiva izgrađuju čvrst zaštitni sloj, koji zglobove čini otpornima čak i na opterećenje. Djed Mato to naziva „radnom spremnošću zgloba“ — jednom postignuta, zadržava se godinama.",
128: "Svaka od tih faza rezultat je šezdeset godina iskustva jednog čovjeka i 5 godina laboratorijskih ispitivanja. Nautubone ne nudi brzo „maskiranje“ boli — nego pokreće dubok, biološki proces regeneracije, koji vraća zglobove u stanje u kojem su bili prije desetljeća.",
129: "Rezultati koji su iznenadili medicinsku zajednicu — praćenje 2340 ljudi u dobi od 38 do 89 godina",
130: "Tomislav Jurić:",
131: "— Kada smo objavili prve rezultate laboratorijskih ispitivanja, reakcija je bila munjevita. Sveučilišne klinike iz Zagreba, Berlina i Beča zatražile su da provedu vlastita istraživanja. Rezultati kod stvarnih ljudi nadmašili su čak i naša očekivanja — nijedna od postojećih metoda liječenja ne približava se tim pokazateljima.",
132: "Ljudi koji su bili naručeni za ugradnju zglobne proteze otkazali su operacije. Ljudi koji mjesecima nisu ustajali iz kreveta ponovno su prohodali. Ortopedi nisu vjerovali vlastitim rendgenskim snimkama.",
133: "Rezultati praćenja „Nautubonea“ kod 2340 ljudi u dobi od 38 do 89 godina",
134: "Potpuno uklanjanje boli i upale",
136: "Vraćanje punog opsega pokreta",
138: "Tendinitis, burzitis, periartritis",
140: "Zaustavljanje i povlačenje degenerativnih promjena",
142: "Sinovitis, ligamentitis",
144: "Osteoartritis (svi stadiji)",
146: "Osteoporoza",
148: "Reumatoidni artritis, giht",
150: "Artroza, spondiloartritis",
152: "Dokumentirana regeneracija hrskavičnog tkiva",
154: "Točni rokovi oporavka s „Nautuboneom“:",
155: "Drugi znanstveni timovi u Europi pokušavaju reproducirati našu formulu, ali dosadašnji rezultati daleko su od naših. Tehnologija nanodifuzije s naprednom bioraspoloživošću, razvijena zajedno s našim laboratorijem, još se uvijek ne može ponoviti — upravo ona omogućuje gelu da dostavi sastojke izravno u zglob kroz kožu, umjesto da jednostavno ostanu na površini kože.",
156: "Koliko traje potpuni oporavak? Djed Mato objašnjava na temelju šezdeset godina iskustva",
157: "Mato Jurić:",
158: "— Minimalni tečaj koji preporučujem je 30 dana. Kod težih oštećenja — 60, a ponekad i 90 dana. Ja sam vlastito koljeno vraćao tri mjeseca. A radio sam i sa životinjama koje su bile pred otpisom, i s ljudima od 85, 90, pa čak i 95 godina.",
159: "Nautubone ne samo da zaustavlja bol — pokreće proces duboke biološke regeneracije. Nanosite gel dva puta dnevno i već ćete u prvim satima osjetiti olakšanje. Unutar tjedan dana primijetit ćete da se lakše krećete. A nakon punog tečaja vaši će zglobovi biti u stanju u kakvom su bili prije 20–30 godina.",
160: "Ali najvrjednije je nešto drugo: učinak je TRAJAN. Jednom „probuđene“, regenerativne stanice nastavljaju raditi godinama!",
161: "Zahvaljujući „Nautuboneu“ više od 19 000 ljudi u Hrvatskoj vratilo je svoju pokretljivost. A prvi na tom popisu je sam djed Mato. Evo samo malog dijela ostalih:",
162: "Umirovljenica, 66 godina, Varaždin. Četiri pomaknuta kralješka i kronična radikulopatija. Sin joj je donosio gel Nautubone iz Zagreba. Dva mjeseca nanošenja — potpuno vraćanje kralježnice u normalan položaj. Njezin ortoped zatražio je ime proizvoda.",
163: "Knjigovotkinja, 41 godina, Zadar. Koljena su joj se deformirala prema unutra nakon dvije trudnoće i debljanja. Ortoped joj je rekao „naviknite se“. S gelom Nautubone — 30 dana nanošenja, dva puta dnevno — os koljena vidljivo se ispravila na rendgenu.",
164: "Umirovljenik, 73 godine, Vinkovci. Artroza mu je deformirala prste na nogama toliko da nije mogao obuti nijedan par cipela. Nanosio je gel Nautubone svaki dan — za 21 dan prsti su se ispravili, a cipele od prije 5 godina ponovno mu odgovaraju.",
165: "Mato Jurić:",
166: "— Te fotografije nisu čuda — one su priroda i strpljenje. Svatko od tih ljudi vratio je nešto za što su mu rekli da je nemoguće. Ja sam to dobio prvi, s osamdeset i jednom. Nautubone JE KRUNA MOG ŠEZDESETOGODIŠNJEG RADA — I JEDINI NAČIN DA TO STIGNE DO SVIH.",
167: "Zašto djed Mato više ne prima ljude u svom dvorištu — i kako je Nautubone postao jedini način da se dođe do njegova pripravka",
168: "„Šezdeset godina držao sam to za životinje. Onda sam isprobao na sebi i vidio da nema razlike. Od tog dana nisam imao pravo šutjeti — ali nisam imao ni snage primati sve. Zato sam pozvao sina.“",
169: "Mato Jurić:",
170: "— Sa 97 godina više ne mogu po cijeli dan otvarati vrata. Na popisu je bilo više od 2000 imena, a ja sam veterinar i to mi nikada nije bilo dopušteno. Zato sam pustio sina Tomislava da odnese mjeru ondje gdje će je napraviti kako treba i za sve. Sada sam miran — Nautubone je točno ono što sam stavio na vlastito koljeno, samo u obliku koji ima pravo postojati.",
171: "Tomislav Jurić:",
175: "Da biste se prijavili, upotrijebite službeni obrazac za narudžbu ispod — on dolazi izravno od proizvodnog tima Tomislava Jurića.",
176: "Ne propustite posljednju priliku ove godine — Nautubone može nestati prije kraja programa!",
177: "Tomislav Jurić:",
178: "— Ove godine uspjeli smo proizvesti 5&nbsp;000 pakiranja gela Nautubone posebno za ljude iz Hrvatske. Ali s obzirom na potražnju — koja je ogromna — te će količine brzo nestati. Sljedeća serija bit će gotova tek krajem",
180: ".",
181: "Program podrške aktivan je do",
182: "— svaki stanovnik Hrvatske stariji od 40 godina može dobiti",
183: "do 50 % popusta",
185: "Ne odgađajte. Ja sam čekao do osamdeset i prve godine i to su tri izgubljene godine. Zglob te ne čeka — troši se svaki dan, i kod životinje i kod čovjeka. Dok je program aktivan, iskoristite ga. Nautubone ima kumulativni učinak — jedan puni tečaj dovoljan je za 5–6 godina zdravih zglobova.",
186: "Jednostavno unesite ime i broj telefona u obrazac. Konzultant će vas nazvati, izradit će individualni program za vaš slučaj i organizirati dostavu na svaku adresu u Hrvatskoj — za 2–3 dana, poštom ili kurirom na vaša vrata.",
187: "Želim svima zdravlje! Brinite o svojim zglobovima danas, da biste hodali sutra! S poštovanjem: Mato Jurić, veterinar, 97 godina, i njegov sin Tomislav.",
188: "Ažurirano:",
190: "Zbog iznimno velike potražnje zalihe Nautubonea mogu nestati prije planiranog kraja programa! Danas —",
191: "18.12.2025. — posljednji je dan za narudžbu s popustom",
192: "ili do isteka zaliha.",
193: "Pozor! Ne zatvarajte i ne osvježavajte stranicu — gel Nautubone rezerviran za vas bit će ponuđen sljedećem s liste čekanja!",
194: "Vaše rezervirano mjesto u programu:",
195: "Br.",
197: "Službeni obrazac za narudžbu",
198: "Br.",
202: "Da biste dobili",
203: "50 % popusta",
204: ", unesite ime i broj telefona u polja ispod i pritisnite gumb „NARUČI“.",
205: "Preostale zalihe:",
210: "Ime",
211: "Broj telefona",
212: "NARUČI",
213: "✔️ Dostava na svaku adresu u Hrvatskoj za 2–3 dana",
214: "poštom ili kurirom na vaša vrata",
215: "KOMENTARI:",
216: "Vesna Horvat",
217: "Mjesecima sam čekala ovaj tekst! Moj bratić drži krave kraj Velike Gorice i godinama priča o jednom veterinaru koji je navodno nešto isprobao na sebi, a poslije počeo davati i ljudima iz sela. Šteta što više ne prima, ali ako Nautubone ima isti sastav — naručujem odmah. Drago mi je što sam uhvatila popust!",
218: "Snježana Kolarić",
219: "Kurir mi ga je donio u srijedu. Deset dana nanosim gel ujutro i navečer — i razlika je OGROMNA! Ustajem bez onog groznog pucketanja! Muž gleda i ne vjeruje. Odradit ću puni tečaj od 60 dana, ali već sam uvjerena da djeluje.",
220: "Marija Vukelić",
221: "Imam 72 godine i tri godine sam patila od bolova u kuku. Hodanje je bilo mučenje. Ortoped je rekao: „Proteza ili trpite.“ Nisam htjela ni jedno ni drugo. Nautubone mi je pomogao za dva mjeseca — sada hodam kilometar i pol svaki dan! A rendgen pokazuje poboljšanje koje mi liječnik ne može objasniti. Hvala!",
222: "Ivica Šimunić",
223: "Kao bivši sportaš znam što znači živjeti s uništenom hrskavicom. Koljena su mi bila kao kod čovjeka od 90 godina — a imam samo 54. Nautubone mi je vratio pokrete koje nisam radio 10 godina. Ponovno mogu raditi čučnjeve! Ne znam drugi proizvod koji postiže takvo nešto.",
224: "Ljiljana Bosnar",
225: "Malo sam zabrinuta… Isplati li se? Imam 66 godina, zglobovi mi pucketaju pri svakom pokretu i leđa mi ne daju mira. Ali toliko puta sam se razočarala u razne „čudotvorne“ lijekove da mi je već teško vjerovati. Pomaže li stvarno?",
226: "Krešimir Lončar",
227: "Gospođo Ljiljana, potpuno razumijem sumnje — i ja sam ih imao. Ali mene je uvjerilo to što je čovjek prvo isprobao Nautubone na sebi, a tek onda dao drugima. Onome tko radi sa životinjama ne isplati se prigušivati bol — kod njega životinja mora prohodati. Koristim gel već 5 tjedana za koljena i križa — razlika je kao dan i noć.",
228: "Prije se nisam mogao sagnuti da zavežem vezice. Sada to radim bez razmišljanja. Naručite barem jedno pakiranje i prosudite sami — nemate što izgubiti!",
229: "Gabrijela Posavec",
230: "Tri dana nakon što sam počela nanositi gel, bol u koljenu smanjila mi se za pola! Sada je 12. dan i već se penjem stubama bez držanja za ogradu. Odradit ću puni tečaj — vjerujem da ću nakon dva mjeseca biti kao nova!",
231: "Ivana Krajačić",
232: "Na leđima mi je počela rasti „grba“ prije dva mjeseca. Užasnula sam se! Probala sam razne masti iz ljekarne — ništa. Ali gel Nautubone sasvim je druga stvar — za 40 dana grba je gotovo potpuno nestala! Nastavljam ga nanositi, ali već sam nevjerojatno zadovoljna. Evo kako izgleda razlika:",
233: "Nada Bilić",
234: "Imala sam pritisnut živac u križima — od boli nisam mogla ni spavati ni stajati. Liječnik mi je propisao jake analgetike od kojih mi je stalno bilo mučno. Počela sam nanositi gel Nautubone dva puta dnevno — nakon tjedan dana bol se naglo smanjila, a nakon mjesec dana — potpuno nestala! Nastavljam tečaj, ali život mi se već promijenio!",
235: "Franjo Klarić",
236: "Imam 79 godina i tri godine sam jedva hodao. Sin mi je naručio Nautubone — bez pitanja, jer je znao da bih odbio. Nanosi mi gel svako jutro i večer. A rezultat? Nakon mjesec i pol šetam do parka svaki dan! Osjećam se kao da imam 60! Hvala, djede Mato — sa 97 godina znaš o zglobovima više od svih suvremenih liječnika!",
237: "Zdravko Turk",
238: "Prije Nautubonea nisam mogao podići ruke iznad glave — rame je pucketalo i užasno boljelo. Dvije godine obilazio sam liječnike — nitko nije pomogao. Dva mjeseca s Nautuboneom i ruke mi ponovno rade normalno. Evo mog rendgena — sam liječnik nije povjerovao:",
239: "Anka Jurišić",
240: "Naručila sam za svekrvu — ima 81 godinu i gotovo nije mogla ustati iz kreveta. Liječnici su odbijali učiniti bilo što — „u tim godinama ništa više ne pomaže“, govorili su. S Nautuboneom za 2 mjeseca ona već hoda po dvorištu i čak kuha! Nismo mogli vjerovati.",
241: "Emil Vranić",
242: "Žena mi je ležala u krevetu četiri mjeseca — kralježnica je jednostavno popustila. Liječnici su predložili operaciju za 7 500 eura bez ikakvog jamstva. Odlučili smo probati gel Nautubone — nismo imali što izgubiti. Nanosio sam joj ga dva puta dnevno. Nakon 5 tjedana ustala je. Jučer smo zajedno otišli na tržnicu — prvi put nakon pola godine! Plakao sam od sreće.",
243: "Nina Božić",
244: "Naručila sam prošli tjedan, dobila sam trećeg dana. Odmah sam počela nanositi gel — i olakšanje je došlo drugog dana! Kao da mi netko podmazuje zglobove iznutra. Dva tjedna ga nanosim dva puta dnevno i već jedva čekam puni rezultat!",
245: "Ruža Miletić",
246: "Imam 74 godine. Pet godina patila sam od artroze i bolova u leđima. Probala sam doslovno sve — masti, tablete, injekcije, fizioterapiju. NIŠTA nije pomoglo dugoročno. Gel Nautubone jedino je što mi je dalo STVARAN REZULTAT — nanosim ga dva puta dnevno i za mjesec i pol zglobovi mi se osjećaju korjenito drukčije.",
247: "Blaženka Grgić",
248: "Moj pokojni muž držao je krave i djed Mato dolazio nam je dvadeset godina. Sjećam se kada su mu koljena otkazala — a nakon godinu dana ponovno je čučao uz životinje kao da ništa nije bilo. Tek smo poslije saznali što je učinio. Drago mi je što njegov sin nastavlja djelo!",
249: "Dubravka Petrić",
250: "Moj otac ima 84 godine i tri godine nije izlazio iz kuće. Zglobovi, leđa, koljena — sve ga je boljelo. Govorio je da čeka da ode. Nakon dva mjeseca s Nautuboneom — jučer je izašao u dvorište i zalio vrt! Prvi put nakon tri godine! Ne mogu opisati što sam osjetila. Hvala od srca!!!",
251: "Mirela Domitrović",
252: "Zna li netko može li se koristiti kod alergija? Reagiram gotovo na sve — čak mi i od običnog aspirina otiču prsti. Bojim se probati nešto novo…",
253: "Stipe Kaleb",
254: "Mirela, ja sam alergičan na četiri vrste lijekova. Nanosim gel Nautubone već 50 dana — nikakvo nadraživanje, nikakvo oticanje, nikakvo crvenilo. Sastav je u cijelosti od prirodnih ekstrakata — ne sadrži kemiju. Mirno možete naručiti!",
255: "Dora Sabljak",
256: "Prije nisam imala snage ustati — svaki pokret bio je muka, mislila sam da mi je život gotov. Kći mi je naručila gel Nautubone i natjerala me da ga probam — nanosila mi ga je ujutro i navečer. Dva mjeseca poslije? Plesala sam na unukovoj svadbi!!! Nikada u životu nisam bila toliko zahvalna!",
257: "Svjetlana Brkić",
258: "Naručila sam za mamu. Imala je stalne bolove u vratu koji su joj izazivali vrtoglavicu i mučninu — život joj je postao nepodnošljiv. U drugom tjednu s Nautuboneom bolovi su se naglo smanjili, a vrtoglavice potpuno prestale! Mama se ponovno smije — odavno je nisam vidjela takvu.",
259: "Sanja Mikulić",
260: "Pitam se — kad djeluje tako dobro, zašto se ne prodaje posvuda? Zašto samo online? Zašto ga ljekarne ne nude?",
261: "Mihael Radić",
262: "Zato što ovo nikada nije rađeno za ljekarnu! Čovjek je veterinar — šezdeset godina radio je za staje, a ne za police, i prvo je isprobao na vlastitom koljenu. A ljekarna zarađuje od onoga tko svaki mjesec dolazi po istu tubu. Razmislite logično!",
263: "Katarina Krznarić",
264: "Pročitala sam sve komentare — i ganula sam se. Naručujem sada, za sebe i za muža. Uzela sam tri pakiranja gela, za puni tečaj. Ako pomogne i upola onoga što ljudi pišu — bit ću sretna!",
265: "Lena Marinović",
266: "Ortoped mi je rekao da se sa 63 godine moram naviknuti na bol — tobože nema lijeka. Naručila sam Nautubone unatoč svemu. Vidjet ćemo tko je u pravu!",
268: "Prenesi avatar",
269: "Prenesi fotografiju",
270: "POŠALJI",
}

RAW = {
172: "— Nautubone se ne prodaje u ljekarnama — proizvodni proces je složen, a\n      količine su ograničene. Dostupan je samo putem online programa, dva puta godišnje. Ali u okviru\n      programa popusti dosežu",
174: " — jer naš cilj nije zarada,\n      nego dostupnost. Osobito za umirovljenike, za koje je moj otac inzistirao da imaju najveći popust.",
184: ".\n      Nakon tog datuma morat ćete čekati barem 6 mjeseci za novu priliku.",
}

ATTRS = {
"Вашето име": "Vaše ime",
"Вашият телефонен номер": "Vaš broj telefona",
"Вашият коментар": "Vaš komentar",
}
