# -*- coding: utf-8 -*-
# Венгерская адаптация ветеринарного лендинга. Форм-фактор — КАПСУЛЫ.
# Добри Гьошев -> Fazekas Imre (Imre bácsi), 97, állatorvos, falu Budapest mellett
# Пламен Гьошев -> Fazekas Gergely (фармацевт)
# Ганчо Хубенов -> Sipos Bertalan, 66, patkolókovács, Vác
# Валери Дренски -> Halász Zsolt, 49, kamionsofőr, Székesfehérvár
# София -> Budapest | лев -> forint | цена как на венгерском лендинге травника

HU = {
0: "Fazekas Imre, 97 éves állatorvos Budapest környékéről: hatvan éven át kezelte lovak, tehenek, bikák és ökrök ízületeit — majd először próbálta ki a készítményt önmagán",
1: "97 ÉVESEN Ő A LEGIDŐSEBB ÁLLATORVOS MAGYARORSZÁGON ÉS AZ EGYETLEN A NEMZEDÉKÉBŐL, AKI MÉG MINDIG LEGUGGOL A LÓHOZ ÉS EGYEDÜL ÁLL FEL. HATVAN ÉVEN ÁT AZ ÁLLATOKNAK ADTA EZT A KÉSZÍTMÉNYT — MAJD NYOLCVANEGY ÉVESEN ELŐSZÖR KIPRÓBÁLTA ÖNMAGÁN",
2: "Közzétéve:",
3: "„Hogyan hozta vissza Fazekas Imre állatorvos hatvan éven át a munkába a lovakat, teheneket és ökröket — majd amikor a saját térdei mondták fel a szolgálatot, először próbálta ki ugyanazt a készítményt önmagán“",
4: "Egy Budapesthez közeli faluban él egy ember, aki hatvan éven át azoknak az ízületeit kezelte, akik nem tudnak panaszkodni. Lovak, tehenek, bikák, ökrök. 97 évesen Fazekas Imre állatorvos minden reggel maga járja körbe az udvart, maga emeli fel a zabos zsákot és — ami a legfontosabb — maga guggol le és maga áll fel. A nemzedékéből egyetlen állatorvos sem jár már ki a terepre. Sokan a tornácról sem jönnek le.",
5: "Hatvan éven át dolgozott istállókban és udvarokban Budapest környékén: lovak zúzódott ízületekkel, tehenek, amelyek ellés után nem tudtak felállni, ökrök és bikák, akiknek a térde megdagadt a tehertől. Több mint 30 000 jószág ment át a kezén. Az embereknek sokáig nem adta ezt a készítményt — nem is volt rá joga.",
6: "De az igazi rejtély nem az állatok, amelyeket visszaadott a munkának. Az igazi rejtély ő maga. 97 évesen — se artrózis, se merev nyak, se bot. Pedig negyven éven át térden dolgozott, betonon, az istállóban, télen, könyékig hideg vízben.",
7: "És nem volt ez mindig így. Nyolcvanegy évesen a térdei felmondták a szolgálatot. Akkor, életében először, elvette azt, amit hatvan éven át az állatoknak adott — és kipróbálta önmagán. Ma, tizenhat évvel később, először egyezett bele, hogy ez a készítmény nyilvánosságra kerüljön.",
8: "Fazekas Imre: „Egész életemben azokkal dolgoztam, akik nem tudják elmondani, hogy fáj nekik — és éppen ezért kellett megtanulnom, hogy",
9: "az ízület bármely életkorban helyreállítható, ha tudod, hogyan „ébreszd fel“ azokat a sejteket, amelyek felépítik.",
10: "A CÉLOM MINDIG EGYETLEN VOLT — HOGY SEGÍTSEK A TESTNEK ÚJ PORC- ÉS CSONTSZÖVETET TERMELNI, PONTOSAN ÚGY, MINT FIATALKORBAN. AMIKOR LÁTTAM, HOGY NÁLAM IS MŰKÖDIK, HÍVTAM A FIAMAT. MOST GERGELY MINDEZT TERMÉKKÉ ALAKÍTOTTA,",
11: "AMELY ELJUTHAT MAGYARORSZÁG MINDEN OTTHONÁBA.",
13: "Fazekas Gergely — az állatorvos fia — az apja mérlegei, üvegcséi és kiszállásai között nőtt fel, és már gyerekként tudta, miből mennyi kell. Nem lett állatorvos — gyógyszerészetet végzett. Amikor látta, mi történt az apja térdével, megértette, hogy a készítmény nem maradhat egyetlen istállóban. Talált egy laboratóriumot és embereket, akik átszámolták az adagokat egy 600 kilós állatról az emberre — és a hatvan év tapasztalatát mindenki számára elérhető termékké alakították.",
14: "Ennek az együttműködésnek az eredménye minden várakozást felülmúlt. De mielőtt mesélnék a termékről, nézzük meg, miért téves nagy valószínűséggel minden, amit az ízületek kezeléséről tud.",
15: "A hazugság, amelyben egész Magyarország hisz:",
16: "„A fájdalomcsillapító azt jelenti, hogy kezelnek“ — TÉVEDÉS, ez csak engedély arra, hogy tovább pusztítsa az ízületet!",
17: "Fazekas Imre:",
18: "— Hatvan éve dolgozom ízületekkel, és elmondok valamit, amit egyetlen patika sem ismer be: a történelemben egyetlen fájdalomcsillapító sem állított helyre egyetlen milliméter porcot sem. Egyetlenegy sem. Elnyomja a fájdalmat, a porc pedig közben tovább bomlik — csak Ön már nem érzi. És amikor újra érezni fogja, késő lesz.",
19: "És most a legfontosabb, aminek az életemet szenteltem. Az ember tud tűrni. A ló nem tud. A tehén nem tud. Az ökör, amelyik megáll, olyan ökör, amelyiket már leírtak. Ezért nekünk az állatorvoslásban soha nem volt szabad elnyomni a fájdalmat. Vissza kellett adnunk a szövetet, mert semmi másnak nem volt értelme. Ez a teljes különbség aközött, ami az Ön polcán áll, és aközött, amit én hatvan éven át az istállóban adtam.",
20: "A gerincoszlop különösen sérülékeny. A porckorongoknak nincs saját vérellátásuk — diffúzióval táplálkoznak, ami azt jelenti, hogy a károsodásuk csendben zajlik, fájdalom nélkül, néha éveken át. Amikor a fájdalom végre megjelenik, a károsodás már előrehaladott. A porckorongsérv okozta idegnyomás rémálommá változtatja az életet: enyhe zsibbadással kezdődik a lábban, és a mozgásképesség teljes elvesztésével végződik.",
21: "Nézze meg, mit mutat ez a röntgenfelvétel. Egy nő, mindössze 39 éves, tanárnő — az udvaromba hozta el, mert senki nem tudta neki megmagyarázni, mi látszik rajta pontosan. A gerince olyan állapotban van, amilyenben húsz évvel ezelőtt egy selejtezésre szánt igásló ízületét láttam. Napi 8 óra ülés a széken, mozgáshiány és teljes tudatlanság a saját testéről — íme, mit hoz a modern életmód.",
22: "Felvétel abból a mappából, amelyet Imre bácsi évtizedek óta őriz: egy 39 éves győri tanárnő gerince. „Enyhe fáradtsággal a derekában“ érkezett.",
23: "Ha 40 éves kor után fájdalmat, merevséget vagy ropogást érez az ízületeiben — a porca már bomlik. Ez nem „a fáradtságtól“ van, és nem „normális“.",
24: "A gerincoszlopnál a folyamat többszörösen gyorsabb és alattomosabb — a fájdalom csak akkor jelentkezik, amikor a károsodás már kritikus!",
25: "Fazekas Imre:",
26: "— Teljesen őszinte akarok lenni. Ismerek embereket, akik hónapokig halogatták. Az eredmény? Beszorult ideg, amely soha többé nem működött normálisan. Porckorongot helyreállítani, amikor az ideg már elhalt, semmi értelme —",
27: "A PORCKORONG VISSZATÉRHET, DE AZ IDEG — NEM!",
28: "És akkor mi marad? BOT, KEREKESSZÉK ÉS MÁSOK SEGÍTSÉGÉTŐL VALÓ FÜGGŐSÉG AZ ÉLET VÉGÉIG!",
29: "És mit kínál a modern sebészet? Drága és kockázatos műtéteket fémimplantátumokkal. Eleget láttam olyan embert, aki gerincműtét után ROSSZABBUL érezte magát, mint előtte.",
30: "FERTŐZÉSEK, SIKERTELEN ÖSSZENÖVÉSEK, KRÓNIKUS FÁJDALOM ÉS A VÉGÉN — ÚJABB MŰTÉT. NÉHA PEDIG — VISSZAFORDÍTHATATLAN KÁROSODÁS!",
31: "Imre bácsi mutat egy felvételt, amelyet egy férfi hozott neki fémcsavaros műtét után: „Ez a tipikus eredmény — az implantátum nem épült be rendesen.“",
32: "A statisztika könyörtelen: a megműtöttek 60%-ánál a sérv 2–4 éven belül visszatér. És az ára? Hónapok mozdulatlanság, több millió forint és teljes bizonytalanság. Sokan bevallják: ha visszaforgathatnák az időt, soha nem feküdnének műtőasztalra.",
33: "Ezek a tünetek azt jelentik, hogy a porca már haldoklik! Ha pedig elmúlt 40–50 éves — a folyamat beavatkozás nélkül visszafordíthatatlan!",
34: "— Hatvan év alatt több mint 30 000 jószág ment át a kezemen — lovak, tehenek, bikák és ökrök — és a következőt mondhatom: minden figyelmen kívül hagyott ízületi fájdalom egy lépés a bot felé. Csak",
35: "-ben Magyarországon több mint 125 000 új súlyos ízületi megbetegedést regisztráltak — ebből 23 000-et 38 és 48 év közötti embereknél. Ez nem az öregség problémája. Ez a tétlenség problémája.",
36: "Ha a szervezete már adott Önnek egyet ezek közül a jelek közül — ne várjon egyetlen napot sem!",
37: "Íme a lista, ami miatt az állatnál azonnal kezelést váltottam — és ami miatt az embernél ugyanezt tenném:",
38: "Reggeli merevség, amely mozgásra sem múlik el;",
39: "Ropogás, kattogás vagy csikorgás mozgás közben;",
40: "A fájdalom erősödése időjárás-változáskor;",
41: "Nehézség a térd hajlításánál vagy kinyújtásánál;",
42: "Duzzanat, bőrpír vagy melegség az ízület körül;",
43: "Fájdalom lépcsőn fel- vagy lemenetkor;",
44: "Krónikus fáradtság és nehézség a lábakban;",
45: "Fájdalom a derékban, amely „belenyilall“ a combba vagy a lábfejbe;",
46: "Zsibbadás vagy bizsergés az ujjakban;",
47: "A járás megváltozása — sántítás, bizonytalanság;",
48: "Képtelenség 10–15 percnél tovább állni;",
49: "Ha akár két tünetben is magára ismer — a porca már pusztul. A gerincoszlopnál pedig a folyamat három-négyszer gyorsabb, mert a porckorongok állandó nyomás alatt vannak.",
50: "AZ EREDMÉNY: SÉRV, BESZORULT IDEG, CSIGOLYADEFORMÁCIÓ, A MOZGÁSKÉPESSÉG ELVESZTÉSE — ÉS MINDEZ MEGTÖRTÉNHET NÉHÁNY HÉT ALATT!",
51: "Ne halogassa, mert a szervezet nem ad Önnek végtelen esélyt!",
52: "Nézze meg ezeket az embereket alább. Mindegyiküknek ugyanazok a tünetei voltak, amelyeket Ön is érez valószínűleg ebben a pillanatban. Mindegyikük azt mondta: „elmúlik“. És mindegyikük mindent megadna ma azért, hogy visszaforgassa az időt, és akkor cselekedjen, amikor még volt esélye.",
53: "Egy klinika egykori páciense, 58 éves, Sopron. Három csigolya több mint 8 mm-rel elcsúszott, a gerincvelő nyomás alatt. Kétszer halasztotta el, hogy elmenjen Imre bácsihoz — amikor végre eljött, egy lépésre volt a bénulástól.",
54: "Egy 61 éves nő Békéscsabáról — a púpja kevesebb mint egy év alatt 4 cm-esre nőtt. A nyakcsigolyái annyira deformálódtak, hogy a fejét már nem tudja oldalra fordítani. A fájdalomcsillapítók 8 hónapja nem hatnak.",
55: "Háztartásbeli, 59 éves, Kaposvár. A térdízületei annyira elkoptak, hogy a porc 1 mm alá vékonyodott. Minden lépés úgy hangzik, mint egy régi ajtó nyikorgása. Három ortopéd orvos mondta neki, hogy az egyetlen megoldás a dupla protézis, több mint 2 400 000 forintért.",
56: "Egykori bányász, 68 éves, Ózd. A jobb térdében a porc teljesen tönkrement, a csontszövet nekrózisos fázisba lépett. A négyhónapos halogatás a végtagjába került — térd feletti amputáció és élethosszig tartó kerekesszék-függőség.",
57: "Fazekas Imre:",
58: "97 éves vagyok, és személyes tapasztalatból mondhatom — és személyes alatt szó szerint a saját térdemet értem: a szervezet BÁRMELY korban képes önmagát helyreállítani, feltéve, hogy tudja, HOGYAN indítsa be.",
59: "HA PEDIG MÁR ELMÚLT 50–60 ÉVES, NE VÁRJON EGY MÁSODPERCET SEM!",
60: "Önnél a károsodás szinte biztosan kritikus fázisba lépett — sürgősen meg kell állítania a pusztulást, és beindítania az új porc, az új csont és az új szövetek felépítését!",
61: "Először önmagán próbálta ki. Csak azután — azokon, akiket az orvosok reménytelennek nyilvánítottak!",
62: "Nyolcvanegy évesen a térdei felmondták a szolgálatot. Azt, amit hatvan éven át az ökröknek adott, először önmagának adta be — utána pedig Sipos Bertalan patkolókovács kapta meg. Íme, hogyan történt…",
63: "„Hatvan éven át guggoltam az állatok alatt, és a végén az én térdeim mondták fel elsőként a szolgálatot. Nem tudtam felállni a földről kerítés nélkül. Három hónapig tűrtem, aztán egy este bementem a kamrába, elvettem azt, amit aznap reggel egy lónak készítettem, és — átszámoltam a saját testsúlyomra. Nem szóltam senkinek. Sem a feleségemnek, sem a fiamnak. Ha nem használt volna, senki nem is tudott volna róla.“",
64: "„A tizennegyedik napon leguggoltam a kutyához, és támasz nélkül álltam fel. Leültem a küszöbre, és sokáig hallgattam. Hatvan éven át ezt az állatoknak tartogattam, és soha nem jutott eszembe megkérdezni, miért nem adjuk ugyanezt az embernek. A válasz persze egyszerű: mert én nem vagyok orvos, és nem volt hozzá jogom.“",
65: "„Az első, akinek mégis adtam, Bertalan volt, patkolókovács Vácról. Harminchét éven át dolgozott a ló alatt guggolva, és egy egész éven át néztem, hogyan sántikál át az udvaromon. Semmit nem ígértem neki. Csak annyit mondtam: ‚Bertalan, ez harminc éve visszaadja a lovakat a munkának, és fél éve engem is. Neked nincs jogom adni, de neked más úgysem fog ajánlani semmit.‘“",
66: "Sipos Bertalan: „A harmadik héten két év után először guggoltam le és álltam fel támasz nélkül. Ma, egy évvel később, napi négy lóval dolgozom, mint azelőtt. Hatvanhat éves vagyok. Az ortopédem megnézte az új felvételt, és megkérdezte, mit csináltam — megmondtam neki az igazat. Nem hitte el.“",
67: "Sipos Bertalan, 66 éves, patkolókovács, Vác — az első ember Imre bácsi után",
68: "Egy másik rendkívüli eset Halász Zsolté — a 49 éves székesfehérvári kamionsofőré, aki húsz év volán mögött töltött idő után súlyos gerincsérülést szenvedett, és kerekesszékbe kényszerült.",
69: "Zsolt kipróbálta Fazekas Imre módszerét, az eredmények pedig még a háziorvosát is sokkolták.",
70: "A GERINCE ELKEZDETT HELYREÁLLNI, A FÁJDALOM TELJESEN ELTŰNT, ÉS A LEGHIHETETLENEBB —",
71: "MINDÖSSZE 4 HÉT UTÁN ELHAGYTA A KEREKESSZÉKET!",
72: "Zsolt elmesélte nekünk:",
73: "„Húsz éven át jártam a hosszú távokat, de a saját gerincemmel nem törődtem. Egy reggel felébredtem, és nem tudtam megmozdítani a derekamat. A feleségem mentőt hívott. A diagnózis — három sérv és nyomás az ideggyökre. Az orvosok 1 400 000 forintos műtétet javasoltak, de garancia nélkül.“",
74: "Hónapokon át ültem otthon kerekesszékben. A gyerekeim szomorúan néztek rám, a feleségem minden este sírt. Tehernek éreztem magam. Azt kívántam, bárcsak eltűnnék…",
75: "„Akkor a sógorom, aki egy lovasparkban dolgozik, hallott Imre bácsiról egy lovásztól. Jelentkeztem, elküldtem a röntgenfelvételeket, az öreg pedig azt mondta: ‚Nem késő. Pontosan ezt láttam olyan állatoknál, amelyek utána futottak — aztán a saját térdemen is láttam.‘ Ezek a szavak több reményt adtak, mint minden, amit orvosok tucatjaitól hallottam.“",
76: "„A negyedik napon már tudtam állni. A teljes kúra 80 napig tartott. Ma újra dolgozom — nem a hosszú távokon, hanem a diszpécserirodában, de JÁROK. Futok a gyerekeimmel a parkban. Élek. A röntgen azt mutatja, hogy a porckorongjaim 90%-ban helyreálltak. Imre bácsi az egyetlen, aki nem utasított el — és az egyetlen, aki segített.“",
77: "A történet gyorsan elterjedt: először a patkolókovácsok és a lovászok, aztán a feleségeik, aztán az egész falu. Emberek, akiknek az orvosok azt mondták, „szokjon hozzá a fájdalomhoz“, újra járni kezdtek. Hogyan lehetséges ez?",
78: "A készítmény, amelyet Imre bácsi hatvan éven át az állatoknak csinált — és amelyet nyolcvanegy évesen először vett be maga",
79: "Az „Endogén szöveti reaktiváció“ módszerének titka — hogyan kezd a szervezet magától új porcot, új csontot és új szalagokat termelni!",
80: "Fazekas Imre:",
81: "— Engedje meg, hogy elmagyarázzak valamit, amit a hagyományos orvoslás nem hajlandó elismerni. Minden élőlény szervezete — egy 90 éves emberé is — rendelkezik „elaltatott“ sejtekkel, amelyek szövetet építenek. Ugyanazokkal, amelyek fiatalkorában könnyedén csináltak Önnek porcot, csontot és szalagot. Az évekkel ezek nem halnak meg — egyszerűen „elalszanak“, mert a szervezet abbahagyja a helyes jel küldését.",
82: "Hatvan évvel ezelőtt, selejtezés előtt álló állatokkal dolgozva fedeztem fel, hogy természetes anyagok bizonyos kombinációja — szigorúan meghatározott arányokban — „gyújtáskulcsként“ működik ezeknek az elaltatott sejteknek. A módszert így neveztem el:",
83: "„Endogén szöveti reaktiváció“",
84: "— mert nem visz be semmi mesterségeset, hanem a szervezet saját tartalékait indítja be. Pontosan ezért NINCS mellékhatás, NINCS szervkárosodás és NINCS függőség. Az állatorvoslásban ez másképp nem is menne át: az állat nem szedhet évtizedeken át fájdalomcsillapítót anélkül, hogy az meg ne látszana a máján. És ezért, amikor rám került a sor, tudtam, hogy nyugodtan megpróbálhatom.",
85: "Hatvan éven át alkalmaztam ezt a módszert az állatoknál. Tizenhat éve magamon is alkalmazom. Az utóbbi tíz évben pedig a falum lakóinál is, akik maguk kértek rá, miután látták, hogyan járok. Mindig ugyanaz a sorrend: a pusztulás megállítása, a fájdalom csökkenése és az ízület működésének fokozatos visszatérése.",
86: "Maga a formula nem bonyolult — de a pontosság minden. Minden összetevőnek pontos mennyiségben kell lennie, a milligramm századrészéig. Ha az arányokat nem tartják be, a hatás egyszerűen eltűnik. Pontosan ezért mértem évtizedeken át személyesen, minden állatnak külön — és amikor a saját térdemre került a sor, három estén át számoltam át az adagot, mert nem volt kitől megkérdeznem.",
87: "Összetétel Fazekas állatorvos receptje szerint — ugyanaz, amit a saját térdére vett be (hatóanyagok adagonként):",
88: "Omega-3",
89: "lenmag: 4500 mg",
90: "Glükozamin-szulfát",
91: "rákfélék: 1100 mg",
92: "Magnézium-citrát",
93: "tengeri alga: 390 mg",
94: "Gingerol",
95: "gyömbér: kivonat 4200 mg",
96: "AKBA",
97: "tömjénfagyanta (Boswellia): kivonat 1100 mg",
98: "Szilícium",
99: "mezei zsurló: kivonat 320 mg",
100: "Kurkumin",
101: "kurkuma: kivonat 2300 mg",
102: "Ezek az összetevők egyszerűnek tűnnek, de megfelelő minőségben és a megfelelő forrásból megtalálni őket rendkívül nehéz. Ilyen tisztaságú glükozamint évtizedeken át az állatorvosi csatornán lehetett beszerezni, nem a patikákban. Otthon összekeverni pedig gyakorlatilag lehetetlen — mert az adagolásnak 0,1 mg pontosságúnak kell lennie, és a 600 kilós állat meg a 80 kilós ember közötti különbség nem megérzés kérdése.",
103: "Pontosan ezért mértem évtizedeken át magam, minden állatnak külön — és magamnak is. De a fiam, Gergely, meglátta a teljes képet.",
104: "Hogyan számolta át Fazekas Gergely az apja hatvanéves receptjét az állatról az emberre — Nautubone",
105: "Fazekas Gergely:",
106: "— Az apám mérlege mellett nőttem fel. Tizennégy évesen fejből tudtam az adagokat. Nem lettem állatorvos — gyógyszerészetre jelentkeztem. Aztán tizenhat évvel ezelőtt láttam valamit, ami miatt abbahagytam a győzködést, és elkezdtem követelni: az apám, nyolcvanegy évesen, újra leguggol és feláll. Apám, mondtam neki, ez nem maradhat a mi istállónkban.",
107: "Öt éven át jártam a laboratóriumokat Budapesten és Münchenben, amíg nem találtam embereket, akik hajlandók voltak komolyan megvizsgálni apám receptúráját, és átszámolni egy 600 kilós állatról az emberre. A válasz, amelyet kaptam, lenyűgözött: ezeknek az összetevőknek a kombinációja pontos arányokban aktiválja a II-es típusú kollagén és a proteoglikánok termelését — a porc két fő építőelemét. Más szóval: a szervezet szó szerint „emlékszik“ arra, hogyan kell új porcot építeni, csak a helyes jelre van szüksége.",
108: "A laboratóriummal együtt kidolgoztunk egy eljárást, amelyet így neveztünk el:",
109: "„Nanodiffúziós technológia fokozott biohasznosulással“",
110: "— olyan módszer, amellyel a hatóanyagokat speciális nanorészecskékbe zárjuk, amelyek sértetlenül haladnak át a gyomron, a bélfalon keresztül szívódnak fel, és a véráramon át közvetlenül a sérült ízületi szövethez jutnak. Ez körülbelül 380%-kal növeli a felszívódást a hagyományos tablettákhoz és étrend-kiegészítőkhöz képest. A terméket így neveztem el:",
111: "Nautubone",
112: "— kapszula, amelyet naponta kétszer kell bevenni, és pontosan ott hat, ahol szükség van rá. Az apám tiszteletére neveztem el, az istállóban töltött hatvan évére és egy térdre, amely bebizonyította, hogy ez az embernél is működik.",
113: "A Nautubone kapszula tartalmazza apám eredeti készítményének mind a hét komponensét, emberre átszámolt adagokban, plusz 29 további kivonatot és vitamint, amelyeket a müncheni laboratóriumi vizsgálatok után adtunk hozzá. Az eredmény olyan kapszula, amely PONTOSAN OLYAN JÓL működik, mint amit az apám a saját kezével mért ki — de eljuttatható Magyarország minden otthonába. Naponta kétszer vegyen be egy kapszulát, a hatóanyagok pedig a véráramon át közvetlenül az érintett ízületekhez jutnak.",
114: "„A Nautubone az apám öröksége — hatvan év munkája, egyetlen formulába zárva. Minden összetevőt azzal a pontossággal választottunk ki, amellyel ő mért minden állatnak és minden embernek, aki a kerítéséhez jött. Ez nem tömegtermék a patikából — ez egy egész élet műve.“",
115: "A Nautubone-ban az a leghihetetlenebb, hogy nemcsak enyhíti a fájdalmat — hanem aktiválja azt a regenerációs mechanizmust, amely az évekkel elaludt. A kapszula hatóanyagai a bélfalon át szívódnak fel, a nanorészecskék pedig mélyen az ízületi szövetbe juttatják őket — oda, ahová a hagyományos étrend-kiegészítők és injekciók soha nem jutnak el. Az összetevők közötti szinergia akár 20-szorosára erősíti a hatást a külön-külön szedésükhöz képest.",
116: "A Nautubone-nal történő felépülés négy fázisa — mi történik a szervezetében lépésről lépésre",
117: "Fazekas Imre:",
118: "— Először az állatoknál néztem végig ezt a négy fázist. Aztán nyolcvanegy évesen magam is végigmentem rajtuk. A fiam dokumentálta őket, és beépítette a Nautubone-ba, hogy mindenki otthon végigmehessen rajtuk.",
119: "Az „Endogén szöveti reaktiváció“ négy fázisa:",
120: "1. fázis — A fájdalom és a gyulladás megállítása:",
121: "Már az első bevett kapszulától a nanorészecskék a véráramon át közvetlenül a sérült szövetekbe juttatják a hatóanyagokat, blokkolva a gyulladásos molekulákat. A fájdalom 24–48 óra alatt láthatóan csökken — a máj és a vese túlterhelése nélkül, mert a kapszula kizárólag természetes kivonatokat tartalmaz, nem szintetikus vegyületeket, a nanorészecskék pedig célzottan az ízületi szövetbe jutnak, ahelyett hogy az egész szervezetben szétszóródnának.",
122: "2. fázis — A pusztulás megállítása:",
123: "A harmadik és a hetedik nap között a szervezet abbahagyja a porc- és csontszövet lebontását. Növekszik az ízületi folyadék — az ízületek természetes „kenőanyagának“ — termelése. A súrlódás csökken, és a mozgás könnyebbé válik.",
124: "3. fázis — A regeneratív sejtek felébresztése:",
125: "Ez a módszer szíve. Az „elaltatott“ kondrociták és oszteoblasztok biokémiai jelet kapnak, és elkezdenek új porcot és csontszövetet termelni. Pontosan ez a fázis teszi egyedivé a Nautubone-t — semmilyen más termék nem aktiválja ezt a mechanizmust.",
126: "4. fázis — Tartós védőgát:",
127: "30–60 nap után az újonnan képződött szövetek szilárd védőréteget építenek, amely az ízületeket még terhelésre is ellenállóvá teszi. Imre bácsi ezt „az ízület munkakészségének“ nevezi — ha egyszer elérte, évekig megmarad.",
128: "Mindegyik fázis egy ember hatvanéves tapasztalatának és 5 év laboratóriumi vizsgálatnak az eredménye. A Nautubone nem gyors fájdalom-„elfedést“ kínál — hanem mély, biológiai regenerációs folyamatot indít el, amely az ízületeket olyan állapotba hozza vissza, amilyenben évtizedekkel ezelőtt voltak.",
129: "Eredmények, amelyek meglepték az orvosi közösséget — 2340, 38 és 89 év közötti ember követése",
130: "Fazekas Gergely:",
131: "— Amikor közzétettük a laboratóriumi vizsgálatok első eredményeit, a reakció villámgyors volt. Budapesti, berlini és bécsi egyetemi klinikák kérték, hogy saját kutatásokat végezhessenek. A valós embereknél kapott eredmények még a mi várakozásainkat is felülmúlták — egyetlen létező kezelési módszer sem közelíti meg ezeket a mutatókat.",
132: "Emberek, akiket ízületi protézis beültetésére írtak elő, lemondták a műtétet. Emberek, akik hónapokig nem keltek fel az ágyból, újra járni kezdtek. Az ortopéd orvosok nem hittek a saját röntgenfelvételeiknek.",
133: "A „Nautubone“ követésének eredményei 2340, 38 és 89 év közötti embernél",
134: "A fájdalom és a gyulladás teljes megszüntetése",
136: "A teljes mozgástartomány visszatérése",
138: "Ínhüvelygyulladás, nyáktömlő-gyulladás, periartritisz",
140: "A degeneratív elváltozások megállítása és visszafordulása",
142: "Ízületi tokgyulladás, szalaggyulladás",
144: "Osteoarthritis (minden stádium)",
146: "Csontritkulás",
148: "Reumatoid artritisz, köszvény",
150: "Artrózis, spondiloartritisz",
152: "Dokumentált porcszövet-regeneráció",
154: "Pontos felépülési idők a „Nautubone“-nal:",
155: "Más európai tudományos csoportok próbálják reprodukálni a formulánkat, de az eddigi eredmények messze elmaradnak a mieinktől. A laboratóriumunkkal közösen kifejlesztett, fokozott biohasznosulású nanodiffúziós technológiát egyelőre nem lehet megismételni — pontosan ez teszi lehetővé, hogy a kapszula hatóanyagai a bélfalon át felszívódva közvetlenül az ízületbe jussanak, ahelyett hogy a szervezet emésztés közben lebontaná őket.",
156: "Mennyi ideig tart a teljes felépülés? Imre bácsi hatvan év tapasztalata alapján magyarázza",
157: "Fazekas Imre:",
158: "— A minimális kúra, amelyet ajánlok, 30 nap. Súlyosabb károsodásnál — 60, néha 90 nap. Én a saját térdemet három hónapig hoztam vissza. Dolgoztam selejtezés előtt álló állatokkal is, és 85, 90, sőt 95 éves emberekkel is.",
159: "A Nautubone nemcsak megállítja a fájdalmat — mély biológiai regenerációs folyamatot indít el. Szedje a kapszulát naponta kétszer, és már az első órákban megkönnyebbülést érez. Egy héten belül észreveszi, hogy könnyebben mozog. A teljes kúra után pedig az ízületei olyan állapotban lesznek, amilyenben 20–30 évvel ezelőtt voltak.",
160: "De a legértékesebb valami más: a hatás TARTÓS. Az egyszer „felébresztett“ regeneratív sejtek évekig tovább dolgoznak!",
161: "A „Nautubone“-nak köszönhetően több mint 19 000 ember nyerte vissza a mozgásképességét Magyarországon. A lista élén pedig maga Imre bácsi áll. Íme csak egy kis része a többieknek:",
162: "Nyugdíjas, 66 éves, Veszprém. Négy elcsúszott csigolya és krónikus radikulopátia. A fia hozta neki a Nautubone kapszulát Budapestről. Két hónap szedés — a gerincoszlop teljes visszatérése normál helyzetbe. Az ortopédje elkérte a termék nevét.",
163: "Könyvelő, 41 éves, Zalaegerszeg. A térdei befelé deformálódtak két terhesség és a hízás után. Az ortopéd azt mondta neki: „szokja meg“. A Nautubone kapszulával — 30 nap szedés, naponta kétszer — a térdtengely láthatóan kiegyenesedett a röntgenen.",
164: "Nyugdíjas, 73 éves, Baja. Az artrózis annyira deformálta a lábujjait, hogy egyetlen pár cipőt sem tudott felhúzni. Minden nap szedte a Nautubone kapszulát — 21 nap alatt az ujjai kiegyenesedtek, és az 5 évvel ezelőtti cipői újra jók rá.",
165: "Fazekas Imre:",
166: "— Ezek a fényképek nem csodák — ezek a természet és a türelem. Mindegyik ember visszakapott valamit, amiről azt mondták neki, hogy lehetetlen. Én kaptam meg elsőként, nyolcvanegy évesen. A Nautubone A HATVANÉVES MUNKÁM KORONÁJA — ÉS AZ EGYETLEN MÓD, HOGY EZ MINDENKIHEZ ELJUSSON.",
167: "Miért nem fogad többé embereket Imre bácsi az udvarában — és hogyan lett a Nautubone az egyetlen mód, hogy hozzájussunk a készítményéhez",
168: "„Hatvan éven át ezt az állatoknak tartogattam. Aztán kipróbáltam magamon, és láttam, hogy nincs különbség. Attól a naptól nem volt jogom hallgatni — de erőm sem volt mindenkit fogadni. Ezért hívtam a fiamat.“",
169: "Fazekas Imre:",
170: "— 97 évesen már nem tudok egész nap kaput nyitni. A listán több mint 2000 név volt, én pedig állatorvos vagyok, és ez nekem soha nem volt megengedve. Ezért engedtem el a fiamat, Gergelyt, hogy elvigye az adagot oda, ahol rendesen és mindenkinek elkészítik. Most nyugodt vagyok — a Nautubone pontosan az, amit a saját térdemre vettem be, csak olyan formában, amelynek joga van létezni.",
171: "Fazekas Gergely:",
175: "A jelentkezéshez használja az alábbi hivatalos megrendelőlapot — ez közvetlenül Fazekas Gergely gyártócsapatától érkezik.",
176: "Ne szalassza el az év utolsó lehetőségét — a Nautubone elfogyhat a program vége előtt!",
177: "Fazekas Gergely:",
178: "— Idén 5&nbsp;000 csomag Nautubone kapszulát sikerült legyártanunk kifejezetten a magyarországi embereknek. De tekintettel a keresletre — amely óriási — ezek a mennyiségek gyorsan elfogynak. A következő sorozat csak",
180: " végén készül el.",
181: "A támogatási program eddig aktív:",
182: "— Magyarország minden 40 év feletti lakosa megkaphatja",
183: "akár 50% kedvezményt",
185: "Ne halogasson. Én nyolcvanegy éves koromig vártam, és ez három elvesztegetett év. Az ízület nem vár Önre — minden nap kopik, az állaté is, az emberé is. Amíg a program aktív, éljen vele. A Nautubone-nak kumulatív hatása van — egy teljes kúra elegendő 5–6 év egészséges ízülethez.",
186: "Egyszerűen írja be a nevét és a telefonszámát az űrlapba. A tanácsadó felhívja Önt, egyéni programot dolgoz ki az Ön esetére, és megszervezi a kiszállítást bármely magyarországi címre — 2–3 nap alatt, postán vagy futárral az ajtajáig.",
187: "Mindenkinek egészséget kívánok! Törődjön ma az ízületeivel, hogy holnap is járni tudjon! Tisztelettel: Fazekas Imre állatorvos, 97 éves, és a fia, Gergely.",
188: "Frissítve:",
190: "A rendkívül nagy kereslet miatt a Nautubone készlete a program tervezett vége előtt elfogyhat! Ma —",
191: "2025.12.18. — az utolsó nap a kedvezményes megrendelésre",
192: "vagy a készlet erejéig.",
193: "Figyelem! Ne zárja be és ne frissítse az oldalt — az Ön számára lefoglalt Nautubone kapszulát felajánljuk a várólistán következőnek!",
194: "Az Ön lefoglalt helye a programban:",
195: "Sz.",
197: "Hivatalos megrendelőlap",
198: "Sz.",
202: "Ahhoz, hogy megkapja a",
203: "50% kedvezményt",
204: ", írja be a nevét és a telefonszámát az alábbi mezőkbe, és nyomja meg a „MEGRENDELEM“ gombot.",
205: "Fennmaradó készlet:",
208: "23 900 Ft",
209: "11 950 Ft",
210: "Név",
211: "Telefonszám",
212: "MEGRENDELEM",
213: "✔️ Kiszállítás bármely magyarországi címre 2–3 nap alatt",
214: "postán vagy futárral az ajtajáig",
215: "HOZZÁSZÓLÁSOK:",
216: "Bakos Viola",
217: "Hónapok óta vártam erre a cikkre! Az unokatestvérem teheneket tart Gödöllő mellett, és évek óta mesél egy állatorvosról, aki állítólag kipróbált valamit önmagán, aztán elkezdte a falubelieknek is adni. Kár, hogy már nem fogad senkit, de ha a Nautubone-ban ugyanaz van — azonnal rendelek. Örülök, hogy elcsíptem a kedvezményt!",
218: "Erdélyi Katalin",
219: "A futár szerdán hozta ki. Tíz napja szedem a kapszulát reggel és este — és a különbség ÓRIÁSI! Úgy kelek fel, hogy nincs az a szörnyű ropogás! A férjem nézi, és nem hiszi el. Végigcsinálom a teljes 60 napos kúrát, de már meg vagyok győződve róla, hogy működik.",
220: "Kis Margit",
221: "72 éves vagyok, és három évig szenvedtem a csípőízületi fájdalmaktól. A járás kínszenvedés volt. Az ortopéd azt mondta: „Protézis, vagy tűrje.“ Egyiket sem akartam. A Nautubone két hónap alatt segített — most már minden nap sétálok másfél kilométert! A röntgen pedig olyan javulást mutat, amit az orvosom nem tud megmagyarázni. Köszönöm!",
222: "Fodor Zsolt",
223: "Egykori sportolóként tudom, mit jelent tönkrement porccal élni. A térdeim olyanok voltak, mint egy 90 éves emberé — pedig csak 54 vagyok. A Nautubone visszaadta azokat a mozdulatokat, amelyeket 10 éve nem csináltam. Újra tudok guggolni! Nem ismerek más terméket, amely ilyet elér.",
224: "Kozma Ilona",
225: "Kicsit aggódom… Megéri? 66 éves vagyok, az ízületeim minden mozdulatnál ropognak, és a hátam sem hagy nyugodni. De annyiszor csalódtam már mindenféle „csodaszerben“, hogy már nehezen hiszek. Tényleg segít?",
226: "Hegedűs Attila",
227: "Ilona asszony, teljesen megértem a kétségeket — nekem is voltak. De engem az győzött meg, hogy az ember először önmagán próbálta ki a Nautubone-t, és csak azután adta másoknak. Aki állatokkal dolgozik, annak nem éri meg elnyomni a fájdalmat — nála az állatnak járnia kell. 5 hete szedem a térdemre és a derekamra — a különbség ég és föld.",
228: "Korábban nem tudtam lehajolni, hogy bekössem a cipőfűzőmet. Most gondolkodás nélkül csinálom. Rendeljen legalább egy csomaggal, és ítélje meg maga — nincs vesztenivalója!",
229: "Balla Renáta",
230: "Három nappal azután, hogy elkezdtem szedni a kapszulát, a térdfájdalmam felére csökkent! Most a 12. nap van, és már úgy megyek fel a lépcsőn, hogy nem kapaszkodom a korlátba. Végigcsinálom a teljes kúrát — hiszem, hogy két hónap múlva újjászületek!",
231: "Sáfrány Judit",
232: "A hátamon két hónapja kezdett nőni egy „púp“. Megrémültem! Kipróbáltam mindenféle patikai kenőcsöt — semmi. De a Nautubone kapszula egészen más dolog — 40 nap alatt a púp szinte teljesen eltűnt! Folytatom a szedést, de már hihetetlenül elégedett vagyok. Íme, így néz ki a különbség:",
233: "Németh Piroska",
234: "Beszorult idegem volt a derekamban — a fájdalomtól sem aludni, sem állni nem tudtam. Az orvos erős fájdalomcsillapítót írt fel, amitől állandóan rosszul voltam. Elkezdtem naponta kétszer szedni a Nautubone kapszulát — egy hét után a fájdalom hirtelen csökkent, egy hónap után pedig — teljesen elmúlt! Folytatom a kúrát, de az életem már megváltozott!",
235: "Csordás Bálint",
236: "79 éves vagyok, és három éve alig jártam. A fiam megrendelte nekem a Nautubone-t — anélkül, hogy megkérdezett volna, mert tudta, hogy visszautasítanám. Minden reggel és este ideadja nekem. Az eredmény? Másfél hónap után minden nap elsétálok a parkig! Úgy érzem magam, mintha 60 lennék! Köszönöm, Imre bácsi — 97 évesen többet tud az ízületekről, mint az összes mai orvos!",
237: "Szűcs Tibor",
238: "A Nautubone előtt nem tudtam a fejem fölé emelni a karomat — a vállam ropogott és iszonyúan fájt. Két évig jártam orvosokhoz — senki nem segített. Két hónap a Nautubone-nal, és a karjaim újra normálisan működnek. Íme a röntgenem — maga az orvos sem hitte el:",
239: "Vincze Andrea",
240: "Az anyósomnak rendeltem — 81 éves, és szinte nem tudott felkelni az ágyból. Az orvosok nem voltak hajlandók semmit tenni — „ebben a korban már semmi sem segít“, mondogatták. A Nautubone-nal 2 hónap alatt már az udvaron járkál, sőt főz is! Nem akartunk hinni a szemünknek.",
241: "Lakatos Ernő",
242: "A feleségem négy hónapig feküdt az ágyban — a gerince egyszerűen felmondta a szolgálatot. Az orvosok 1 800 000 forintos műtétet javasoltak mindenféle garancia nélkül. Úgy döntöttünk, kipróbáljuk a Nautubone kapszulát — nem volt vesztenivalónk. Naponta kétszer adtam be neki. 5 hét után felkelt. Tegnap együtt mentünk el a piacra — fél év után először! Sírtam a boldogságtól.",
243: "Jakab Nikolett",
244: "Múlt héten rendeltem, harmadnap megkaptam. Azonnal elkezdtem szedni a kapszulát — és a megkönnyebbülés a második napon megjött! Mintha valaki belülről megolajozná az ízületeimet. Két hete szedem naponta kétszer, és már alig várom a teljes eredményt!",
245: "Székely Irén",
246: "74 éves vagyok. Öt évig szenvedtem az artrózistól és a hátfájástól. Szó szerint mindent kipróbáltam — kenőcsöket, tablettákat, injekciókat, gyógytornát. SEMMI nem segített hosszú távon. A Nautubone kapszula az egyetlen, ami VALÓDI EREDMÉNYT hozott — naponta kétszer szedem, és másfél hónap alatt az ízületeim gyökeresen máshogy érzik magukat.",
247: "Farkas Veronika",
248: "A néhai férjem teheneket tartott, és Imre bácsi húsz éven át járt hozzánk. Emlékszem, amikor a térdei felmondták a szolgálatot — egy évvel később pedig újra ott guggolt az állatok mellett, mintha mi sem történt volna. Csak később tudtuk meg, mit csinált. Örülök, hogy a fia folytatja a munkáját!",
249: "Bede Gyöngyi",
250: "Az apám 84 éves, és három éve nem mozdult ki a házból. Az ízületei, a háta, a térdei — minden fájt neki. Azt mondta, várja, hogy elmenjen. Két hónap Nautubone után — tegnap kiment az udvarra, és meglocsolta a kertet! Három év után először! Nem tudom leírni, mit éreztem. Köszönöm szívből!!!",
251: "Dévai Melinda",
252: "Tudja valaki, hogy allergia esetén használható-e? Szinte mindenre reagálok — még a közönséges aszpirintól is bedagadnak az ujjaim. Félek új dolgot kipróbálni…",
253: "Hajdu Kálmán",
254: "Melinda, én négyféle gyógyszerre vagyok allergiás. 50 napja szedem a Nautubone kapszulát — semmilyen irritáció, semmilyen duzzanat, semmilyen gyomorpanasz. Az összetétel teljesen természetes kivonatokból áll — nem tartalmaz vegyszereket. Nyugodtan rendelhet!",
255: "Sasvári Dorottya",
256: "Korábban nem volt erőm felkelni — minden mozdulat kín volt, azt hittem, vége az életemnek. A lányom megrendelte a Nautubone kapszulát, és rávett, hogy próbáljam ki — reggel és este ideadta nekem. Két hónappal később? Táncoltam az unokám esküvőjén!!! Soha életemben nem voltam ilyen hálás!",
257: "Török Emese",
258: "Anyukámnak rendeltem. Állandó nyaki fájdalmai voltak, amelyek szédülést és hányingert okoztak — az élete elviselhetetlenné vált. A második héten a Nautubone-nal a fájdalmak drasztikusan csökkentek, a szédülés pedig teljesen megszűnt! Anyu újra nevet — rég nem láttam ilyennek.",
259: "Bognár Zsanett",
260: "Azt kérdezem — ha ennyire jól működik, miért nem árulják mindenhol? Miért csak online? Miért nem kínálják a patikák?",
261: "Major Mihály",
262: "Mert ezt soha nem patikának csinálták! Az ember állatorvos — hatvan éven át az istállóknak dolgozott, nem a polcoknak, és először a saját térdén próbálta ki. A patika pedig azon keres, aki minden hónapban ugyanazért a dobozért jön. Gondolkodjon logikusan!",
263: "Halmi Orsolya",
264: "Elolvastam az összes hozzászólást — és meghatódtam. Most rendelek, magamnak és a férjemnek. Három csomag kapszulát vettem, a teljes kúrához. Ha annak a felét is segít, amit az emberek írnak — boldog leszek!",
265: "Szalai Emma",
266: "Az ortopéd azt mondta, hogy 63 évesen meg kell szoknom a fájdalmat — állítólag nincs rá gyógymód. Mindennek ellenére megrendeltem a Nautubone-t. Majd meglátjuk, kinek van igaza!",
268: "Avatár feltöltése",
269: "Fénykép feltöltése",
270: "KÜLDÉS",
}

RAW = {
172: "— A Nautubone-t nem árulják patikákban — a gyártási folyamat összetett, a\n      mennyiségek pedig korlátozottak. Csak az online program keretében érhető el, évente kétszer. De a\n      program keretében a kedvezmény eléri az",
174: "-ot — mert a célunk nem a profit,\n      hanem az elérhetőség. Különösen a nyugdíjasok számára, akiknek az apám ragaszkodott a maximális kedvezményhez.",
184: ".\n      Ezen dátum után legalább 6 hónapot kell várnia egy új lehetőségre.",
}

ATTRS = {
"Вашето име": "Az Ön neve",
"Вашият телефонен номер": "Az Ön telefonszáma",
"Вашият коментар": "Az Ön hozzászólása",
}
