# -*- coding: utf-8 -*-
# Венгерская адаптация лендинга травника.
# Живојин Поповић -> Balogh Gyula (Gyula bácsi), 102, füvesember, Budapest melletti falu
# Драган Поповић  -> Balogh Zoltán
# Србија -> Magyarország; RSD -> Ft (курс ~1 RSD = 3.3 HUF)

HU = {
0: "Balogh Gyula, a Budapest környéki 102 éves füvesember feltárja az ízületek teljes helyreállításának formuláját — a módszer minden magyarországi lakos számára elérhető",
1: "102 ÉVESEN Ő A LEGIDŐSEBB FÜVESEMBER MAGYARORSZÁGON, ÉS AZ EGYETLEN A NEMZEDÉKÉBŐL, AKI BOT NÉLKÜL JÁR. ELSŐ ALKALOMMAL TÁRJA FEL AZT A FORMULÁT, AMELYET 40 ÉVEN ÁT CSAK AZOKNAK ADOTT, AKIK ELMENTEK HOZZÁ.",
2: "Közzétéve:",
3: "„Hogyan sikerült Gyula bácsinak, a Budapest környéki füvesembernek tökéletes állapotban megőriznie az ízületeit 102 éves koráig, miközben a kortársai már rég járni sem tudnak?”",
4: "Egy Budapest melletti faluban él egy ember, aki cáfol mindent, amit az öregedésről tudunk. 102 évesen Balogh Gyula füvesember minden reggel végigsétál a falu feletti ösvényeken, segítség nélkül megy fel a lépcsőn, és életében soha nem használt botot. A kortársai már rég nincsenek az élők sorában, vagy kerekesszékhez vannak kötve — ő pedig továbbra is egyedül mászik fel a dombra gyógynövényért.",
5: "Tavalyig Gyula bácsi a saját házában fogadta az embereket, abban a régi szobában, ahol évtizedek óta szárítja a gyógynövényeket. Több mint 70 év munka a növényekkel, több mint 40 000 ember, több tucat gerinc és térd visszahozva az életbe, amelyeket az orvosok leírtak. Hat hónapos várólista volt — az emberek az egész országból jöttek hozzá.",
6: "De az igazi rejtély nem azok, akik hozzá jártak. Az igazi rejtély ő maga. 102 évesen — se ízületi gyulladás, se artrózis, se porckorongsérv. Az ízületeiről készült röntgenfelvételek úgy néznek ki, mint egy 45 éves férfié. Az orvosok, akik megvizsgálják, egyszerűen nem hisznek a saját szemüknek.",
7: "Évtizedeken át titokban tartotta a receptjét — maga készítette, a saját szobájában, és soha nem hozta nyilvánosságra. De ma, amikor az egészsége már nem engedi, hogy személyesen fogadja az embereket, Gyula bácsi olyan döntést hozott, amely mindent megváltoztatott: hogy a formuláját elérhetővé teszi minden magyarországi lakos számára.",
8: "Balogh Gyula bácsi: „Egész életemben azt figyeltem, hogyan öregszenek meg az emberek idő előtt — nem azért, mert gyenge a testük, hanem mert senki nem mondta el nekik, hogyan aktiválják a saját regenerációs mechanizmusaikat. 102 évesen élő bizonyíték vagyok arra, hogy",
9: "az ízületek egészségesek maradhatnak mély öregkorig, ha tudod, hogyan „ébreszd fel” azokat a sejteket, amelyek felépítik őket.",
10: "A CÉLOM MINDIG EGYETLEN VOLT — HOGY SEGÍTSEK A TESTNEK ÚJ PORC- ÉS CSONTSZÖVETET TERMELNI, PONTOSAN ÚGY, MINT FIATALKORBAN. MOST A FIAM, ZOLTÁN, MINDEZT TERMÉKKÉ ALAKÍTOTTA",
11: "AMELY ELJUTHAT MAGYARORSZÁG MINDEN OTTHONÁBA.",
13: "Balogh Zoltán — a füvesember fia — a szárított gyógynövények és az apja mérlegei között nőtt fel, és gyermekkorától tanulta a mesterséget. Nem lett orvos. Éveken át győzködte az apját, hogy a recept ne maradjon egyetlen házba zárva, majd maga talált laboratóriumot és embereket, akik segítettek Gyula bácsi évtizedes tapasztalatát mindenki számára elérhető termékké alakítani — hogy eljusson mindenkihez, akinek szüksége van rá.",
14: "Ennek az együttműködésnek az eredménye minden várakozást felülmúlt. De mielőtt mesélnék a termékről, nézzük meg, miért téves nagy valószínűséggel minden, amit az ízületek kezeléséről tud.",
15: "A hazugság, amelyben egész Magyarország hisz:",
16: "„A fájdalomcsillapítók gyógyítják az ízületeket” — TÉVEDÉS, még gyorsabban tönkreteszik őket!",
17: "Balogh Gyula bácsi:",
18: "— Hetven éve gyógyítok embereket, és elmondok valamit, amit a patikák soha nem ismernek be: az orvostudomány történetében egyetlen fájdalomcsillapító sem regenerált egyetlen milliméter porcot sem. Egyetlenegy sem! Elnyomják a fájdalmat, de közben a porc tovább bomlik — csak már nem érzi. És amikor újra érezni fogja, késő lesz.",
19: "De nem ez a legrosszabb. A legrosszabb az, amit ezek a vegyi anyagok a belső szerveivel művelnek. A 70 év munkám alatt több száz embert láttam teljesen tönkretett májjal és vesével — nem betegségtől, hanem a gyógyszerektől! A test nem arra készült, hogy évtizedeken át vegyszereket nyeljen. És mégis pontosan ezt „írja fel” a hagyományos orvoslás.",
20: "A gerincoszlop különösen sérülékeny. A porckorongoknak nincs saját érhálózatuk — diffúzióval táplálkoznak, ami azt jelenti, hogy a károsodásuk csendben zajlik, fájdalom nélkül, néha éveken át. Amikor a fájdalom végre megjelenik, a károsodás már előrehaladott. A porckorongsérv okozta idegnyomás rémálommá változtatja az életet: enyhe zsibbadással kezdődik a lábban, és a mozgásképesség teljes elvesztésével végződik.",
21: "Nézze meg, mit mutat ez a röntgen. Egy nő, mindössze 39 éves, tanárnő — a gerince pedig olyan állapotban van, amilyet 20 évvel ezelőtt csak 70 éves embereknél láttam. Napi 8 óra ülés a széken, mozgáshiány és teljes tudatlanság a saját testéről — íme, mit hoz a modern életmód.",
22: "Felvétel abból az archívumból, amelyet Gyula bácsi évtizedek óta őriz: egy 39 éves debreceni tanárnő gerince. „Enyhe fáradtsággal a derék tájékán” érkezett — a röntgen három sérült porckorongot, kezdődő sérvet és mikrorepedéseket tárt fel a porcburokban.",
23: "Ha 40 éves kor után fájdalmat, merevséget vagy ropogást érez az ízületeiben — a porca már bomlik. Ez nem „a fáradtságtól” van, és nem „normális”.",
24: "A gerincoszlopnál a folyamat többszörösen gyorsabb és alattomosabb — a fájdalom csak akkor jelentkezik, amikor a károsodás már kritikus!",
25: "Balogh Gyula bácsi:",
26: "— Teljesen őszinte akarok lenni. Ismerek embereket, akik hónapokig halogatták. Az eredmény? Beszorult ideg, amely soha többé nem működött normálisan. A porckorongok regenerálása, amikor az ideg már elhalt, hiábavaló —",
27: "A PORCKORONG VISSZATÉRHET, DE AZ IDEG — NEM!",
28: "És akkor mi marad? BOT, KEREKESSZÉK ÉS MÁSOK SEGÍTSÉGÉTŐL VALÓ FÜGGŐSÉG AZ ÉLET VÉGÉIG!",
29: "És mit kínál a modern sebészet? Drága és kockázatos műtéteket fémimplantátumokkal. Személyesen láttam több száz embert, akik a gerincműtét után ROSSZABBUL érezték magukat, mint előtte.",
30: "FERTŐZÉSEK, SIKERTELEN ÖSSZENÖVÉSEK, KRÓNIKUS FÁJDALOM ÉS A VÉGÉN — ÚJABB MŰTÉT. NÉHA PEDIG — VISSZAFORDÍTHATATLAN KÁROSODÁS!",
31: "Gyula bácsi mutatja a felvételt, amelyet egy férfi hozott neki a fémcsavaros műtét után: „Ez tipikus eredmény — az implantátum nem épült be megfelelően, a környező szövetek begyulladtak, a fájdalom pedig erősebb, mint a műtét előtt. Több száz hasonló esetet láttam.”",
32: "A statisztika könyörtelen: a megműtöttek 60%-ánál a sérv 2–4 éven belül visszatér. És az ára? Hónapok mozdulatlanság, több százezer forint és teljes bizonytalanság. Sokan bevallják: ha visszaforgathatnák az időt, soha nem feküdnének műtőasztalra.",
33: "Ezek a tünetek azt jelentik, hogy a porca már haldoklik! Ha pedig elmúlt 40–50 éves — a folyamat beavatkozás nélkül visszafordíthatatlan!",
34: "— A 70 év alatt több mint 40 000 ember ment át a kezemen, és a következőt mondhatom: minden figyelmen kívül hagyott ízületi fájdalom egy lépés a kerekesszék felé. Csak",
35: "-ben Magyarországon több mint 125 000 új súlyos ízületi megbetegedést regisztráltak — ebből 23 000-et 38 és 48 év közötti személyeknél. Ez nem az életkor problémája. Ez a tétlenség problémája.",
36: "Ha a szervezete már adott Önnek egyet ezek közül a jelek közül — ne várjon egyetlen napot sem!",
37: "Íme a lista, amelyet minden embernek elmondtam már a küszöbön:",
38: "Reggeli merevség, amely mozgásra sem múlik el;",
39: "Ropogás, pattogás vagy csikorgás mozgás közben;",
40: "A fájdalom erősödése időjárás-változáskor;",
41: "Nehézség a térd hajlításánál vagy kinyújtásánál;",
42: "Duzzanat, bőrpír vagy melegség az ízület körül;",
43: "Fájdalom lépcsőn fel- vagy lemenetkor;",
44: "Krónikus fáradtság és nehézség a lábakban;",
45: "Fájdalom a derék tájékán, amely „belenyilall” a combba vagy a lábfejbe;",
46: "Merevség vagy zsibbadás az ujjakban;",
47: "A járás megváltozása — sántítás, bizonytalanság;",
48: "Képtelenség 10–15 percnél tovább állni;",
49: "Ha akár két tünetben is magára ismer — a porca már pusztul. A gerincoszlopnál pedig a folyamat három-négyszer gyorsabb, mert a porckorongok állandó nyomás alatt vannak.",
50: "EREDMÉNY: SÉRV, BESZORULT IDEG, CSIGOLYADEFORMÁCIÓ, A MOZGÁSKÉPESSÉG ELVESZTÉSE — ÉS MINDEZ MEGTÖRTÉNHET NÉHÁNY HÉT ALATT!",
51: "Ne halogassa, mert a szervezete nem ad végtelen esélyt!",
52: "Nézze meg ezeket az embereket alább. Mindegyiküknek ugyanazok a tünetei voltak, amelyeket Ön is érez valószínűleg ebben a pillanatban. Mindegyikük azt mondta: „elmúlik”. És mindegyikük mindent megadna ma azért, hogy visszaforgassa az időt, és akkor cselekedjen, amikor még volt esélye.",
53: "Egy másik klinika egykori páciense, 58 éves, Szeged. Három csigolya több mint 8 mm-rel elcsúszott, a gerincvelő nyomás alatt. Kétszer utasította vissza, hogy elmenjen Gyula bácsihoz — amikor végre eljött, egy lépésre volt a bénulástól.",
54: "Egy 61 éves nő Miskolcról — a púpja kevesebb mint egy év alatt 4 cm-esre nőtt. A nyakcsigolyái annyira deformálódtak, hogy a fejét már nem tudja oldalra fordítani. A fájdalomcsillapítók 8 hónapja nem hatnak.",
55: "Háztartásbeli, 59 éves, Pécs. A térdízületei annyira elkoptak, hogy a porc 1 mm alá vékonyodott. Minden lépés úgy hangzik, mint egy régi ajtó nyikorgása. Három ortopéd orvos mondta neki, hogy az egyetlen megoldás a dupla protézis, több mint 130 000 forintért.",
56: "Egykori bányász, 68 éves, Tatabánya. A jobb térdében a porc teljesen tönkrement, a csontszövet nekrózisos fázisba lépett. A 4 hónapos halogatás a végtagjába került — térd feletti amputáció és élethosszig tartó kerekesszék-függőség.",
57: "Balogh Gyula bácsi:",
58: "102 éves vagyok, és személyes tapasztalatból mondhatom: a szervezet BÁRMELY korban képes önmagát regenerálni — feltéve, hogy tudja, HOGYAN aktiválja. Pontosan ennek szenteltem az életemet.",
59: "HA PEDIG MÁR ELMÚLT 50–60 ÉVES, NE VÁRJON EGY MÁSODPERCET SEM!",
60: "Önnél a károsodás szinte biztosan kritikus fázisba lépett — sürgősen meg kell állítania a pusztulást, és aktiválnia kell az új porc, az új csont és az új szövetek regenerációját!",
61: "Esetek, amelyeket az orvosok reménytelennek nyilvánítottak!",
62: "Kovács Erzsébet 86 évesen újra jár segítség nélkül, miután három kórház utasította el. Íme a története…",
63: "A kecskeméti Kovács Erzsébet súlyos térdartrózistól és többszörös porckorongsérvtől szenvedett. Három különböző kórház utasította el — mindenhol ugyanazt mondták neki: „Ebben a korban már semmit sem lehet tenni.” A lánya véletlenül hallott Gyula bácsiról egy ismerőstől, egy Budapest melletti faluból, és úgy döntött, felkeresi.",
64: "„Úgy éltem, mint a börtönben — a saját házam lett a cellám. Nem tudtam eljutni a mellékhelyiségig, nem tudtam egy percnél tovább állni, nem tudtam magamnak teát főzni. A gyerekeim dolgoztak, és nem tudtak minden nap jönni. Feküdtem, és néztem a plafont. Az orvosok azt mondták, ebben a korban nincs értelme a műtétnek, és csak fájdalomcsillapítót adtak.",
65: "Amikor a lányom elvitt Gyula bácsihoz, rám nézett, és mondott valamit, amit egyetlen orvos sem mondott nekem: „Erzsike néni, a teste NEM hagyta abba a küzdelmet. Csak senki nem segített neki.” Odaadta azt, amit maga készít, és azt mondta, legyek türelmes. A harmadik héten, másfél év után először, EGYEDÜL KELTEM FEL az ágyból!",
66: "Ma, öt hónappal később, boltba járok, főzök, sőt még a ház előtti virágoskertet is gondozom. 86 évesen! Amikor a szomszédok megláttak az udvaron, nem hittek a szemüknek. Azt hitték, többé nem látnak. Gyula bácsi visszaadta az életemet — és nincsenek szavaim, amelyekkel megköszönhetném.”",
67: "Kovács Erzsébet, 86 éves, Kecskemét",
68: "Egy másik rendkívüli eset Nagy Sándoré — a 47 éves szolnoki építőmunkásé, aki 20 év nehéz fizikai munka után súlyos gerincsérülést szenvedett, és kerekesszékbe kényszerült.",
69: "Sándor kipróbálta Gyula bácsi módszerét, az eredmények pedig még a háziorvosát is sokkolták.",
70: "A GERINCE ELKEZDETT HELYREÁLLNI, A FÁJDALOM TELJESEN MEGSZŰNT, ÉS A LEGHIHETETLENEBB —",
71: "MINDÖSSZE 4 HÉT UTÁN ELHAGYTA A KEREKESSZÉKET!",
72: "Sándor elmesélte nekünk:",
73: "„Húsz éven át épületeket építettem, de a saját gerincemmel nem törődtem. Egy reggel felébredtem, és nem tudtam megmozdítani a derekamat. A feleségem mentőt hívott. A diagnózis — három sérv és nyomás az ideggyökre. Az orvosok 80 000 forintos műtétet javasoltak, de garancia nélkül.",
74: "Hónapokig ültem otthon kerekesszékben. A gyerekeim szomorúan néztek rám, a feleségem minden este sírt. Tehernek éreztem magam. Azt kívántam, bárcsak eltűnnék…",
75: "Akkor az apósom hallott Gyula bácsiról egy embertől, akinek segített. Jelentkeztem, elküldtem a röntgenfelvételeket, az öreg pedig azt mondta: „Nem késő.” Ez a három szó több reményt adott, mint minden, amit orvosok tucatjaitól hallottam.",
76: "A negyedik napon már tudtam állni. A teljes kúra 80 napig tartott. Ma újra dolgozom — nem az építkezésen, hanem irodában, de JÁROK. Futok a gyerekeimmel a parkban. Élek. A röntgen azt mutatja, hogy a porckorongjaim 90%-ban helyreálltak. Gyula bácsi az egyetlen, aki nem utasított el — és az egyetlen, aki segített.”",
77: "Azoknak az ezreknek a történetei, akiknek Gyula bácsi segített, ugyanilyen lenyűgözőek: emberek, akiknek az orvosok azt mondták, „szokja meg a fájdalmat”, újra járni kezdtek, újra futottak, újra éltek. Hogyan lehetséges ez?",
78: "A formula, amelyet Gyula bácsi több mint 40 éven át a saját kezével készített!",
79: "Az „Endogén szöveti reaktiváció” módszerének titka — hogyan kezd a szervezet magától új porcot, új csontot és új szalagokat termelni!",
80: "Balogh Gyula bácsi:",
81: "— Engedje meg, hogy elmagyarázzak valamit, amit a hagyományos orvoslás nem hajlandó elismerni. Minden ember szervezete — még egy 90 évesé is — rendelkezik „alvó” regeneratív sejtekkel. Ugyanazokkal a sejtekkel, amelyek fiatalkorában könnyedén építették a porcot, a csontot és a szalagokat. Az évekkel ezek nem halnak meg — egyszerűen „elalszanak”, mert a szervezet abbahagyja a megfelelő jelek küldését.",
82: "Negyven évvel ezelőtt felfedeztem, hogy a természetes anyagok bizonyos kombinációja — szigorúan meghatározott arányokban — „gyújtáskulcsként” működik ezeknek az alvó sejteknek. A módszert így neveztem el:",
83: "„Endogén szöveti reaktiváció”",
84: "— mert nem visz be semmi mesterségeset, hanem a szervezet saját erőforrásait aktiválja. Pontosan ezért NINCS nálam mellékhatás, NINCS szervkárosodás és NINCS függőség.",
85: "Négy évtizeden át alkalmaztam ezt a módszert mindenkinél, aki a küszöbömre lépett — és mindenkinél ugyanazt az eredményt jegyeztem fel: a pusztulás megállását, a fájdalom csökkenését és az ízületi működés fokozatos visszatérését. Több százan, akik „utolsó esélyként” jöttek hozzám, a saját lábukon távoztak az otthonomból.",
86: "Maga a formula nem bonyolult — de a pontosság minden. Minden összetevőnek pontos mennyiségben kell jelen lennie, a milligramm századrészéig. Ha az arányokat nem tartják be, a hatás egyszerűen eltűnik. Pontosan ezért alkalmaztam évtizedeken át személyesen a módszert — mert nem bízhattam patikákra.",
87: "A Balogh-féle recept szerinti gél összetétele (hatóanyagok adagonként):",
88: "Omega-3",
89: "lenmag: 4500 mg",
90: "Glükozamin-szulfát",
91: "rákfélék: 1100 mg",
92: "Magnézium-citrát",
93: "tengeri alga: 390 mg",
94: "Gingerol",
95: "gyömbér: kivonat 4200 mg",
96: "AKBA",
97: "tömjénfagyanta (Boswellia): kivonat 1100 mg",
98: "Szilícium",
99: "mezei zsurló: kivonat 320 mg",
100: "Kurkumin",
101: "kurkuma: kivonat 2300 mg",
102: "Ezek az összetevők egyszerűnek tűnnek, de megfelelő minőségben és a megfelelő forrásból megtalálni őket rendkívül nehéz. A legtöbbjük nem kapható patikában, és a világ különböző részeiről kell beszerezni őket. Otthon összekeverni pedig gyakorlatilag lehetetlen — mert az adagolásnak 0,1 mg pontosságúnak kell lennie.",
103: "Pontosan ezért készítettem évtizedeken át személyesen a keveréket, minden embernek külön. De a fiam, Zoltán, meglátta a teljes képet.",
104: "Hogyan alakította Balogh Zoltán az apja 40 éves receptjét mindenki számára elérhető géllé — Nautubone",
105: "Balogh Zoltán:",
106: "— Az apám gyógynövényes szobájában nőttem fel. Minden nap néztem, ahogy az emberek fájdalomtól görnyedten bejönnek — és mosolyogva távoznak. 14 évesen már fejből tudtam a receptet. Én nem lettem orvos — a mesterséget tőle tanultam. De éveken át győzködtem: apám, ez a recept nem maradhat egyetlen házba zárva. Emberek ezrei várják azt, amit te a polcon tartasz.",
107: "Öt éven át jártam a budapesti és müncheni laboratóriumokat, amíg nem találtam embereket, akik komolyan meg akarták vizsgálni apám receptúráját. A válasz, amelyet kaptam, lenyűgözött: ezeknek az összetevőknek a kombinációja pontos arányokban aktiválja a II-es típusú kollagén és a proteoglikánok termelését — a porc két fő építőelemét. Más szóval: a szervezet szó szerint „emlékszik” arra, hogyan kell új porcot építeni, csak a megfelelő jelre van szüksége.",
108: "A laboratóriummal együtt kidolgoztunk egy eljárást, amelyet így neveztünk el:",
109: "„Nanodiffúziós technológia fokozott biohasznosulással”",
110: "— olyan módszer, amellyel a hatóanyagokat speciális nanorészecskékbe zárjuk, amelyek mélyen áthatolnak a bőrön, és közvetlenül a sérült ízületi szövethez jutnak. Ez körülbelül 380%-kal növeli a felszívódást a hagyományos gélekhez és kenőcsökhöz képest. A terméket így neveztem el:",
111: "Nautubone",
112: "— gél, amelyet a bőrre kell felvinni, és pontosan ott hat, ahol szükség van rá. Az apám és a 40 éves munkája tiszteletére neveztem el.",
113: "A Nautubone gél tartalmazza apám eredeti receptjének mind a 7 összetevőjét, valamint további 29 kivonatot és vitamint, amelyeket a müncheni laboratóriumi vizsgálatok után adtunk hozzá. Az eredmény olyan gél, amely UGYANOLYAN JÓL működik, mint amit az apám a saját kezével készített — de eljuttatható Magyarország minden otthonába. Naponta kétszer kenje az ízületeire, a hatóanyagok pedig a bőrön át közvetlenül az érintett ízületekhez jutnak.",
114: "„A Nautubone az apám öröksége — a 40 éves tapasztalata egyetlen formulába zárva. Minden összetevőt olyan pontossággal választottunk ki, amilyennel ő fordult minden emberhez, aki bekopogott hozzá. Ez nem tömegtermék a patikából — ez egy egész, gyógyításnak szentelt élet műve.”",
115: "A Nautubone-ban az a leghihetetlenebb, hogy nemcsak enyhíti a fájdalmat — hanem aktiválja azt a regenerációs mechanizmust, amely az évekkel elaludt. A gélt a bőrre kell felvinni, a nanorészecskék pedig mélyen az ízületi szövetbe juttatják a hatóanyagokat — oda, ahová a szokásos tabletták és injekciók soha nem jutnak el. Az összetevők közötti szinergia akár 20-szorosára erősíti a hatást a külön-külön szedésükhöz képest.",
116: "A Nautubone-nal történő felépülés négy fázisa — mi történik a szervezetében lépésről lépésre",
117: "Balogh Gyula bácsi:",
118: "— Füvesemberként az egész életem során azt figyeltem, hogyan mennek át az emberek ugyanazon a négy fázison. A fiam dokumentálta őket, és beépítette a Nautubone-ba, hogy mindenki otthon végigmehessen rajtuk.",
119: "Az „Endogén szöveti reaktiváció” négy fázisa:",
120: "1. fázis — A fájdalom és a gyulladás megállítása:",
121: "Már a gél első felvitelétől a nanorészecskék a bőrön át közvetlenül a sérült szövetekbe juttatják a hatóanyagokat, blokkolva a gyulladásos molekulákat. A fájdalom 24–48 óra alatt láthatóan csökken — a máj és a vese terhelése nélkül, mert a gél célzott, bőrön át történő felszívódási technológiát használ, és nem megy át a hagyományos májanyagcserén.",
122: "2. fázis — A pusztulás megállítása:",
123: "A harmadik és a hetedik nap között a szervezet abbahagyja a porc- és csontszövet lebontását. Növekszik az ízületi folyadék — az ízületek természetes „kenőanyagának” — termelése. A súrlódás csökken, a mozgás könnyebbé válik.",
124: "3. fázis — A regeneratív sejtek felébresztése:",
125: "Ez a módszer szíve. Az „alvó” kondrociták és oszteoblasztok biokémiai jelet kapnak, és elkezdenek új porcot és csontszövetet termelni. Pontosan ez a fázis teszi egyedivé a Nautubone-t — semmilyen más termék nem aktiválja ezt a mechanizmust.",
126: "4. fázis — Tartós védőgát:",
127: "30–60 nap után az újonnan képződött szövetek szilárd védőréteget hoznak létre, ami az ízületeket még terhelésre is ellenállóvá teszi. Gyula bácsi ezt „ízületi immunitásnak” nevezi — ha egyszer elérte, a hatás évekig fennmarad.",
128: "Mindegyik fázis egy ember 40 éves tapasztalatának és 5 év laboratóriumi vizsgálatnak az eredménye. A Nautubone nem gyors fájdalom-„elfedést” kínál — hanem mély, biológiai regenerációs folyamatot indít el, amely az ízületeket olyan állapotba hozza vissza, amilyenben évtizedekkel ezelőtt voltak.",
129: "Eredmények, amelyek meglepték az orvosi közösséget — 2340, 38 és 89 év közötti ember követése",
130: "Balogh Zoltán:",
131: "— Amikor közzétettük a laboratóriumi vizsgálatok első eredményeit, a reakció villámgyors volt. Budapesti, berlini és bécsi egyetemi klinikák kérték, hogy saját kutatásokat végezhessenek. A valós embereknél kapott eredmények még a mi várakozásainkat is felülmúlták — egyetlen létező kezelési módszer sem közelíti meg ezeket a mutatókat.",
132: "Emberek, akiket ízületi protézis beültetésére írtak elő, lemondták a műtétet. Emberek, akik hónapokig nem keltek fel az ágyból, újra járni kezdtek. Az ortopéd orvosok nem hittek a saját röntgenfelvételeiknek.",
133: "A „Nautubone” követésének eredményei 2340, 38 és 89 év közötti embernél",
134: "A fájdalom és a gyulladás teljes megszüntetése",
136: "A teljes mozgástartomány visszatérése",
138: "Ínhüvelygyulladás, nyáktömlő-gyulladás, periartritisz",
140: "A degeneratív elváltozások megállítása és visszafordulása",
142: "Ízületi tokgyulladás, szalaggyulladás",
144: "Osteoarthritis (minden stádium)",
146: "Csontritkulás",
148: "Reumatoid artritisz, köszvény",
150: "Artrózis, spondiloartritisz",
152: "Dokumentált porcszövet-regeneráció",
154: "Pontos felépülési idők a „Nautubone”-nal:",
155: "Más európai tudományos csoportok próbálják reprodukálni a formulánkat, de az eddigi eredmények messze elmaradnak a mieinktől. A laboratóriumunkkal közösen kifejlesztett, fokozott biohasznosulású nanodiffúziós technológiát egyelőre nem lehet lemásolni — pontosan ez teszi lehetővé, hogy a gél a bőrön át közvetlenül az ízületbe juttassa az összetevőket, ahelyett hogy egyszerűen a bőr felszínén maradna.",
156: "Mennyi ideig tart a teljes felépülés? Gyula bácsi 70 év tapasztalata alapján magyarázza",
157: "Balogh Gyula bácsi:",
158: "— A minimális kúra, amelyet ajánlok, 30 nap. Súlyosabb károsodásnál — 60, néha 90 nap. De az egész pályafutásom alatt EGYETLEN OLYAN ESETEM SEM VOLT, amelyben a módszer ne hozott volna eredményt. Egyetlenegy sem. Pedig kezeltem 85, 90, sőt 94 éves embereket is.",
159: "A Nautubone nemcsak megállítja a fájdalmat — mély biológiai regenerációs folyamatot indít el. Kenje a gélt naponta kétszer, és már az első órákban megkönnyebbülést érez. Egy héten belül észreveszi, hogy könnyebben mozog. A teljes kúra után pedig az ízületei olyan állapotban lesznek, amilyenben 20–30 évvel ezelőtt voltak.",
160: "De a legértékesebb valami más: a hatás TARTÓS. Az egyszer „felébresztett” regeneratív sejtek évekig tovább dolgoznak!",
161: "A „Nautubone”-nak köszönhetően több mint 19 000 ember nyerte vissza a mozgásképességét Magyarországon. Íme csak egy kis része azoknak, akiknek Gyula bácsi segített:",
162: "Nyugdíjas, 66 éves, Nyíregyháza. Négy elcsúszott csigolya és krónikus radikulopátia. A fia hozta neki a Nautubone gélt Budapestről. Két hónap kenés — a gerincoszlop teljes visszatérése normál helyzetbe. Az ortopéd orvosa elkérte a termék nevét.",
163: "Könyvelő, 41 éves, Eger. A térdei befelé deformálódtak két terhesség és a súlygyarapodás után. Az ortopéd azt mondta neki: „szokja meg”. A Nautubone géllel — 30 nap kenés, naponta kétszer — a térdtengely láthatóan kiegyenesedett a röntgenen.",
164: "Nyugdíjas, 73 éves, Szombathely. Az artrózis annyira deformálta a lábujjait, hogy egyetlen pár cipőt sem tudott felhúzni. Naponta kente a Nautubone gélt — 21 nap alatt az ujjai kiegyenesedtek, és az 5 évvel ezelőtti cipői újra jók rá.",
165: "Balogh Gyula bácsi:",
166: "— Ezek a fényképek nem csodák — ezek a természet és a türelem. Mindegyik ember visszakapott valamit, amiről az orvosok azt mondták, lehetetlen: egészséges ízületeket és fájdalom nélküli életet. A Nautubone A FÜVESEMBERKÉNT LEÉLT EGÉSZ ÉLETEM KORONÁJA — ÉS AZ ÖRÖKSÉGEM A JÖVŐ NEMZEDÉKEI SZÁMÁRA!",
167: "Miért nem fogad többé embereket Gyula bácsi — és hogyan lett a Nautubone az egyetlen mód, hogy hozzájussunk a receptjéhez",
168: "„Az egészségem már nem engedi, hogy személyesen fogadjam a betegeket. De a formulám tovább fog gyógyítani — a fiam kezén keresztül.”",
169: "Balogh Gyula bácsi:",
170: "— Tavaly hoztam meg életem legnehezebb döntését: hogy többé nem fogadok embereket. A várólistán több mint 2000 név szerepelt — és nem hagyhattam őket segítség nélkül. Ezért engedtem meg a fiamnak, Zoltánnak, hogy kivigye a receptet oda, ahol mindenkinek elkészítik. Most nyugodt vagyok — a Nautubone pontosan az, amit azoknak az embereknek adtam, akik hozzám jöttek, csak kényelmes formában. A recept biztos kezekben van.",
171: "Balogh Zoltán:",
172: "— A Nautubone-t nem árulják patikákban — a gyártási folyamat összetett, a",
174: "-ot — mert a célunk nem a profit,",
175: "A jelentkezéshez használja az alábbi hivatalos megrendelőlapot — ez közvetlenül Balogh Zoltán gyártócsapatától érkezik.",
176: "Ne szalassza el az év utolsó lehetőségét — a Nautubone elfogyhat a program vége előtt!",
177: "Balogh Zoltán:",
178: "— Idén 5&nbsp;000 csomag Nautubone gélt sikerült legyártanunk kifejezetten a magyarországi emberek számára. De tekintettel a keresletre — amely óriási — ezek a mennyiségek gyorsan elfogynak. A következő sorozat csak",
180: " végén készül el.",
181: "A támogatási program eddig aktív:",
182: "— Magyarország minden 40 év feletti lakosa megkaphatja",
183: "akár 50% kedvezményt",
185: "Ne halogasson. Az apám mindig azt mondta az embereknek: „Az ízületek nem várnak Önre — minden másodpercben pusztulnak.” Amíg a program aktív, éljen vele. A Nautubone-nak kumulatív hatása van — egy teljes kúra elegendő 5–6 év egészséges ízülethez.",
186: "Egyszerűen írja be a nevét és a telefonszámát az űrlapba. A tanácsadó felhívja Önt, egyéni programot dolgoz ki az Ön esetére, és megszervezi a kiszállítást bármely magyarországi címre — 2–3 nap alatt, postán vagy futárral az ajtajáig.",
187: "Mindenkinek egészséget kívánok! Törődjön ma az ízületeivel, hogy holnap is járni tudjon! Tisztelettel: Balogh Gyula és a fia, Zoltán.",
188: "Frissítve:",
190: "A rendkívül nagy kereslet miatt a Nautubone készlete a program tervezett vége előtt elfogyhat! Ma —",
191: "18/12/2025 — az utolsó nap a kedvezményes megrendelésre",
192: "vagy a készlet erejéig.",
193: "Figyelem! Ne zárja be és ne frissítse az oldalt — az Ön számára lefoglalt Nautubone gélt felajánljuk a várólistán következőnek!",
194: "Az Ön lefoglalt helye a programban:",
195: "Sz.",
197: "Hivatalos megrendelőlap",
198: "Sz.",
202: "Ahhoz, hogy megkapja a",
203: "50% kedvezményt",
204: ", írja be a nevét és a telefonszámát az alábbi mezőkbe, és nyomja meg a „MEGRENDELEM” gombot.",
205: "Fennmaradó készlet:",
210: "Név",
211: "Telefonszám",
212: "MEGRENDELEM",
213: "✔️ Kiszállítás bármely magyarországi címre 2–3 nap alatt",
214: "postán vagy futárral az ajtajáig",
215: "HOZZÁSZÓLÁSOK:",
216: "Szabó Violetta",
217: "Hónapok óta vártam erre a cikkre! Egy barátnőm Budapestről néhány éve személyesen járt Gyula bácsinál — azt mondta, csodálatos ember. Kár, hogy már nem fogad senkit, de ha a Nautubone-ban ugyanaz a recept van — azonnal rendelek. Örülök, hogy elcsíptem a kedvezményt!",
218: "Tóth Stefánia",
219: "A futár szerdán hozta ki. Tíz napja kenem a gélt reggel és este — és a különbség ÓRIÁSI! Úgy kelek fel, hogy nincs az a szörnyű ropogás! A férjem nézi, és nem hiszi el. Végigcsinálom a teljes 60 napos kúrát, de már meg vagyok győződve róla, hogy működik.",
220: "Varga Jolán",
221: "72 éves vagyok, és három éve szenvedtem a csípőfájdalomtól. A járás kínszenvedés volt. Az ortopéd azt mondta: „Protézis, vagy tűrje.” Egyiket sem akartam. A Nautubone két hónap alatt segített — most már minden nap sétálok másfél kilométert! A röntgen pedig olyan javulást mutat, amit az orvosom nem tud megmagyarázni. Köszönöm, Gyula bácsi, és a fiának is!",
222: "Molnár László",
223: "Egykori sportolóként tudom, mit jelent tönkrement porccal élni. A térdeim olyanok voltak, mint egy 90 éves emberé — pedig csak 54 vagyok. A Nautubone visszaadta azokat a mozdulatokat, amelyeket 10 éve nem csináltam. Újra tudok guggolni! Nem ismerek más terméket, amely ilyet elér.",
224: "Fehér Szilvia",
225: "Kicsit aggódom… Megéri? 66 éves vagyok, az ízületeim minden mozdulatnál ropognak, és a hátam sem hagy nyugodni. De annyiszor csalódtam már mindenféle „csodaszerben”, hogy már nehezen hiszek. Tényleg segít?",
226: "Deák Tamás",
227: "Szilvia asszony, teljesen megértem a kétségeket — nekem is voltak. De a Nautubone más, mint minden, amit eddig kipróbáltam. 5 hete használom a térdemre és a derekamra — és elmondhatom, hogy a különbség ég és föld.",
228: "Korábban nem tudtam lehajolni, hogy bekössem a cipőfűzőmet. Most gondolkodás nélkül csinálom. Rendeljen legalább egy csomaggal, és ítélje meg maga — nincs vesztenivalója!",
229: "Papp Gabriella",
230: "Három nappal azután, hogy elkezdtem kenni a gélt, a térdfájdalmam felére csökkent! Most a 12. nap van, és már úgy megyek fel a lépcsőn, hogy nem kapaszkodom a korlátba. Végigcsinálom a teljes kúrát — hiszem, hogy két hónap múlva újjászületek!",
231: "Juhász Ivett",
232: "A hátamon már két hónapja kezdett nőni egy „púp”. Megrémültem! Kipróbáltam mindenféle patikai kenőcsöt — semmi. De a Nautubone gél egészen más dolog — 40 nap alatt a púp szinte teljesen eltűnt! Folytatom a kenést, de már hihetetlenül elégedett vagyok. Íme, így néz ki a különbség:",
233: "Simon Pálma",
234: "Beszorult idegem volt a derekamban — a fájdalomtól sem aludni, sem állni nem tudtam. Az orvos erős fájdalomcsillapítót írt fel, amitől állandóan rosszul voltam. Elkezdtem naponta kétszer kenni a Nautubone gélt — egy hét után a fájdalom hirtelen csökkent, egy hónap után pedig — teljesen elmúlt! Folytatom a kúrát, de az életem már megváltozott!",
235: "Bogdán Ferenc",
236: "79 éves vagyok, és három éve alig jártam. A fiam megrendelte nekem a Nautubone-t — anélkül, hogy megkérdezett volna, mert tudta, hogy visszautasítanám. Minden reggel és este megkeni vele. Az eredmény? Másfél hónap után minden nap elsétálok a parkig! Úgy érzem magam, mintha 60 lennék! Köszönöm, Gyula bácsi — 102 évesen bölcsebb vagy minden mai orvosnál!",
237: "Takács Tivadar",
238: "A Nautubone előtt nem tudtam a fejem fölé emelni a karomat — a vállam ropogott és iszonyúan fájt. Két évig jártam orvosokhoz — senki nem segített. Két hónap a Nautubone-nal, és a karjaim újra normálisan működnek. Íme a röntgenem — maga az orvos sem hitte el:",
239: "Illés Anikó",
240: "Az anyósomnak rendeltem — 81 éves, és szinte nem tudott felkelni az ágyból. Az orvosok nem voltak hajlandók semmit sem tenni — „ebben a korban már semmi sem segít”, mondogatták. A Nautubone-nal 2 hónap alatt már az udvaron járkál, sőt főz is! Nem akartunk hinni a szemünknek.",
241: "Vass Emil",
242: "A feleségem négy hónapig feküdt az ágyban — a gerince egyszerűen felmondta a szolgálatot. Az orvosok 100 000 forintos műtétet javasoltak mindenféle garancia nélkül. Úgy döntöttünk, kipróbáljuk a Nautubone gélt — nem volt vesztenivalónk. Naponta kétszer kentem rá. 5 hét után felkelt. Tegnap együtt mentünk el a piacra — fél év után először! Sírtam a boldogságtól.",
243: "Boros Nóra",
244: "Múlt héten rendeltem, harmadnap megkaptam. Azonnal elkezdtem kenni a gélt — és a megkönnyebbülés a második napon megjött! Mintha valaki belülről megolajozná az ízületeimet. Két hete kenem naponta kétszer, és már alig várom a teljes eredményt!",
245: "Mészáros Rozália",
246: "74 éves vagyok. Öt évig szenvedtem az artrózistól és a hátfájástól. Szó szerint mindent kipróbáltam — kenőcsöket, tablettákat, injekciókat, gyógytornát. SEMMI nem segített hosszú távon. A Nautubone gél az egyetlen, ami VALÓDI EREDMÉNYT hozott — naponta kétszer kenem, és másfél hónap alatt az ízületeim gyökeresen máshogy érzik magukat. Az orvos nem hisz a röntgeneknek!",
247: "Pintér Vera",
248: "Személyesen ismerem Gyula bácsit — 12 évvel ezelőtt segített nekem a porckorongsérvemmel. Három hét alatt újra talpon voltam! A nevét az egész Budapest környéke ismeri. Örülök, hogy a fia folytatja a munkáját!",
249: "Gulyás Gizella",
250: "Az apám 84 éves, és három éve nem mozdult ki a házból. Az ízületei, a háta, a térdei — minden fájt neki. Azt mondta, várja, hogy elmenjen. Két hónap Nautubone után — tegnap kiment az udvarra, és meglocsolta a kertet! Három év után először! Nem tudom leírni, mit éreztem. Köszönöm szívből!!!",
251: "Dobos Mirella",
252: "Tudja valaki, hogy allergia esetén használható-e? Szinte mindenre reagálok — még a közönséges aszpirintól is bedagadnak az ujjaim. Félek új dolgot kipróbálni…",
253: "Kelemen Gáspár",
254: "Mirella, én négyféle gyógyszerre vagyok allergiás. 50 napja kenem a Nautubone gélt — semmilyen irritáció, semmilyen duzzanat, semmilyen bőrpír. Az összetétel teljesen természetes kivonatokból áll — nem tartalmaz vegyszereket. Nyugodtan rendelhet!",
255: "Somogyi Dóra",
256: "Korábban nem volt erőm felkelni — minden mozdulat kín volt, azt hittem, vége az életemnek. A lányom megrendelte a Nautubone gélt, és rávett, hogy próbáljam ki — reggel és este megkente vele. Két hónappal később? Táncolok az unokám esküvőjén!!! Soha életemben nem voltam ilyen hálás!",
257: "Barta Sarolta",
258: "Anyukámnak rendeltem. Állandó nyaki fájdalmai voltak, amelyek szédülést és hányingert okoztak — az élete elviselhetetlen volt. A második héten a Nautubone-nal a fájdalmak drasztikusan csökkentek, a szédülés pedig teljesen megszűnt! Anyu újra mosolyog — rég nem láttam ilyennek.",
259: "Nemes Zsuzsa",
260: "Azt kérdezem — ha Gyula bácsi ennyire jó, miért nem árulják ezeket a dolgokat mindenhol? Miért csak online? Miért nem kínálják a patikák?",
261: "Rácz Mihály",
262: "Azért, mert a patikák azokon keresnek, akik minden hónapban fájdalomcsillapítót vesznek! Ha mindenki egyszer s mindenkorra meggyógyítaná az ízületeit — ki venné meg tőlük a drága gyógyszereket? Gondolkodjon logikusan!",
263: "Kerekes Olívia",
264: "Elolvastam az összes hozzászólást — és felvidultam. Most rendelek, magamnak és a férjemnek. Három csomag gélt vettem, a teljes kúrához. Ha annak a felét is segít, amit az emberek írnak — boldog leszek!",
265: "Marosi Lenke",
266: "Az ortopéd azt mondta, hogy 63 évesen meg kell szoknom a fájdalmat — állítólag nincs rá gyógymód. Mindennek ellenére megrendeltem a Nautubone-t. Majd meglátjuk, kinek van igaza!",
268: "Avatár feltöltése",
269: "Fénykép feltöltése",
270: "KÜLDÉS",
}

# Узлы с внутренними переносами строк — задаём целиком, с сохранением вёрстки
MULTILINE = {
173: None,   # "50%" — не меняется
}

# Многострочные узлы, которые надо заменить с сохранением структуры переносов
RAW = {
172: "— A Nautubone-t nem árulják patikákban — a gyártási folyamat összetett, a\n      mennyiségek pedig korlátozottak. Csak online program keretében érhető el, évente kétszer. De a program\n      keretében a kedvezmény eléri az",
174: "-ot — mert a célunk nem a profit,\n      hanem az elérhetőség. Különösen a nyugdíjasok számára, akiknek az apám ragaszkodott a maximális kedvezményhez.",
184: ".\n      Ezen dátum után legalább 6 hónapot kell várnia egy új lehetőségre.",
208: "23 900\n            Ft",
209: "11 950\n            Ft",
}

# placeholder-атрибуты
ATTRS = {
"Ваше име": "Az Ön neve",
"Ваш број телефона": "Az Ön telefonszáma",
"Ваш коментар": "Az Ön hozzászólása",
}
