# -*- coding: utf-8 -*-
# Indonesia / ahli herbal, nodes 0..69 (bentuk: KAPSUL)
I1 = {
0: "Suparno Hadi, ahli herbal berusia 102 tahun dari desa-desa di sekitar Jakarta, mengungkap formula pemulihan sendi secara menyeluruh — metode yang terjangkau bagi setiap warga Indonesia",
1: "DI USIA 102 TAHUN, BELIAU ADALAH AHLI HERBAL TERTUA DI INDONESIA DAN SATU-SATUNYA DARI GENERASINYA YANG MASIH BERJALAN TANPA TONGKAT. UNTUK PERTAMA KALINYA BELIAU MENGUNGKAP FORMULA YANG SELAMA 40 TAHUN HANYA DIBERIKAN KEPADA MEREKA YANG DATANG SENDIRI KEPADANYA.",
2: "Diterbitkan:",
3: "„Bagaimana Mbah Suparno Hadi, ahli herbal dari desa-desa di sekitar Jakarta, bisa menjaga sendi-sendinya tetap sempurna sampai usia 102 tahun, sementara semua orang seumurannya sudah lama tidak bisa berjalan?“",
4: "Di sebuah desa tidak jauh dari Jakarta hidup seorang pria yang membantah semua yang kita ketahui tentang penuaan. Di usia 102 tahun, ahli herbal Suparno Hadi setiap pagi masih menyusuri jalan setapak di atas desa, menaiki tangga tanpa bantuan siapa pun, dan seumur hidupnya tidak pernah memakai tongkat. Orang-orang seusianya sudah lama tiada atau terikat di kursi roda — sementara beliau sampai hari ini masih naik sendiri ke bukit untuk memetik tanaman obat.",
5: "Sampai tahun lalu, Mbah Suparno masih menerima orang di rumahnya sendiri, di ruangan tua tempat beliau mengeringkan tanaman obat selama puluhan tahun. Lebih dari 70 tahun bekerja dengan tanaman obat, lebih dari 40.000 orang, puluhan tulang belakang dan lutut yang dikembalikan ke kehidupan setelah para dokter menyerah. Ada antrean enam bulan — orang-orang datang menemuinya dari seluruh negeri.",
6: "Tetapi misteri yang sesungguhnya bukanlah mereka yang datang kepadanya. Misteri yang sesungguhnya adalah beliau sendiri. Di usia 102 tahun — tidak ada radang sendi, tidak ada pengapuran, tidak ada satu pun saraf terjepit. Foto rontgen sendi-sendinya tampak seperti milik pria berusia 45 tahun. Para dokter yang memeriksanya benar-benar tidak percaya pada mata mereka sendiri.",
7: "Selama puluhan tahun beliau merahasiakan resepnya — meraciknya sendiri, di ruangannya, dan tidak pernah mempublikasikannya. Namun hari ini, ketika kesehatannya tidak lagi memungkinkan untuk menerima orang secara langsung, Mbah Suparno mengambil keputusan yang mengubah segalanya: menjadikan formulanya terjangkau bagi setiap warga Indonesia.",
8: "Suparno Hadi: „Seumur hidup saya menyaksikan orang-orang menua sebelum waktunya — bukan karena tubuh mereka lemah, melainkan karena tidak ada yang memberi tahu mereka cara menyalakan kembali mekanisme peremajaan mereka sendiri. Di usia 102 tahun saya adalah bukti hidup bahwa",
9: "sendi bisa tetap sehat sampai usia sangat lanjut, asalkan Anda tahu cara „membangunkan“ sel-sel yang membangunnya.",
10: "TUJUAN SAYA SELALU SATU — MEMBANTU TUBUH MEMPRODUKSI JARINGAN TULANG RAWAN DAN TULANG YANG BARU, PERSIS SEPERTI DI MASA MUDA. KINI PUTRA SAYA, BAMBANG, TELAH MENGUBAH SEMUA INI MENJADI SEBUAH PRODUK",
11: "YANG BISA SAMPAI KE SETIAP RUMAH DI INDONESIA.",
12: "Bambang Hadi — putra sang ahli herbal — tumbuh besar di antara tanaman obat yang dikeringkan dan timbangan milik ayahnya, dan mempelajari keahlian ini sejak kecil. Ia tidak menjadi dokter. Bertahun-tahun ia meyakinkan ayahnya agar resep itu tidak terkunci di satu rumah saja, lalu ia sendiri mencari laboratorium dan orang-orang yang membantu mengubah pengalaman puluhan tahun Mbah Suparno menjadi produk yang terjangkau bagi semua orang — agar sampai kepada semua yang membutuhkannya.",
13: "Hasil kerja sama ini melampaui semua harapan. Namun sebelum saya bercerita tentang produknya, mari kita lihat mengapa semua yang Anda ketahui tentang pengobatan sendi kemungkinan besar keliru.",
14: "Kebohongan yang dipercaya seluruh Indonesia:",
15: "„Obat pereda nyeri menyembuhkan sendi“ — SALAH, obat itu justru merusaknya lebih cepat!",
16: "Suparno Hadi:",
17: "— Tujuh puluh tahun saya mengobati orang dan saya akan mengatakan sesuatu yang tidak akan pernah diakui apotek: tidak ada satu pun obat pereda nyeri dalam sejarah kedokteran yang pernah mengembalikan tulang rawan walau satu milimeter. Tidak ada satu pun! Obat itu hanya membungkam rasa sakit, sementara tulang rawan terus hancur — hanya saja Anda tidak lagi merasakannya. Dan ketika Anda merasakannya lagi, semuanya sudah terlambat.",
18: "Tetapi itu belum yang terburuk. Yang terburuk adalah apa yang dilakukan bahan-bahan kimia itu terhadap organ dalam Anda. Dalam 70 tahun bekerja, saya melihat ratusan orang dengan hati dan ginjal yang rusak total — bukan karena penyakitnya, melainkan karena obatnya! Tubuh tidak diciptakan untuk menelan bahan kimia selama puluhan tahun. Namun justru itulah yang „diresepkan“ kedokteran konvensional.",
19: "Tulang belakang sangat rentan. Cakram di antara ruas tulang belakang tidak memiliki aliran darah sendiri — ia mendapat asupan melalui difusi, artinya kerusakannya berlangsung diam-diam, tanpa rasa sakit, kadang bertahun-tahun. Ketika rasa sakit akhirnya muncul, kerusakannya sudah parah. Saraf yang terjepit akibat cakram yang bergeser mengubah hidup menjadi mimpi buruk: dimulai dari kesemutan ringan di kaki dan berakhir dengan hilangnya kemampuan bergerak sepenuhnya.",
20: "Lihatlah apa yang ditunjukkan foto rontgen ini. Seorang perempuan, baru berusia 39 tahun, seorang guru — sementara tulang belakangnya berada dalam kondisi yang 20 tahun lalu hanya saya jumpai pada orang berusia 70 tahun. Delapan jam sehari duduk di kursi, kurang gerak, dan sama sekali tidak mengenal tubuh sendiri — itulah yang dibawa gaya hidup modern.",
21: "Foto dari arsip yang disimpan Mbah Suparno selama puluhan tahun: tulang belakang seorang guru berusia 39 tahun dari Bandung. Ia datang dengan keluhan „pinggang sedikit pegal“ — rontgen mengungkap tiga cakram yang rusak, saraf yang mulai terjepit, dan retakan mikro pada selaput tulang rawan.",
22: "Jika setelah usia 40 tahun Anda merasakan nyeri, kaku, atau bunyi berderak pada sendi — tulang rawan Anda sudah mulai hancur. Ini bukan „karena kelelahan“ dan ini bukan hal yang „wajar“.",
23: "Pada tulang belakang prosesnya beberapa kali lebih cepat dan lebih licik — rasa sakit baru muncul ketika kerusakannya sudah kritis!",
24: "— Saya ingin benar-benar terus terang. Saya kenal orang-orang yang menunda-nunda berbulan-bulan. Hasilnya? Saraf terjepit yang tidak pernah lagi berfungsi normal. Memperbaiki cakram ketika sarafnya sudah mati sama sekali tidak ada gunanya —",
25: "CAKRAM MASIH BISA KEMBALI, TETAPI SARAF — TIDAK LAGI!",
26: "Lalu apa yang tersisa? TONGKAT, KURSI RODA, DAN KETERGANTUNGAN PADA BANTUAN ORANG LAIN SAMPAI AKHIR HAYAT!",
27: "Dan apa yang ditawarkan bedah modern? Operasi mahal dan berisiko dengan implan logam. Saya sendiri melihat ratusan orang yang setelah operasi tulang belakang justru merasa LEBIH BURUK daripada sebelumnya.",
28: "INFEKSI, TULANG YANG TIDAK MENYATU, NYERI KRONIS, DAN PADA AKHIRNYA — OPERASI ULANG. DAN TERKADANG — KERUSAKAN YANG TIDAK BISA DIPULIHKAN!",
29: "Mbah Suparno menunjukkan foto rontgen yang dibawa seorang pria kepadanya setelah operasi dengan sekrup logam: „Inilah hasil yang biasa — implannya tidak menempel dengan benar, jaringan di sekitarnya meradang, dan rasa sakitnya lebih parah daripada sebelum operasi. Saya sudah melihat ratusan kasus serupa.“",
30: "Statistiknya tidak berbelas kasihan: pada 60% pasien yang dioperasi, sarafnya terjepit lagi dalam 2–4 tahun. Dan berapa harganya? Berbulan-bulan tidak bisa bergerak, puluhan juta rupiah, dan ketidakpastian total. Banyak yang mengakui: seandainya bisa memutar waktu, mereka tidak akan pernah naik ke meja operasi.",
31: "Gejala-gejala ini berarti tulang rawan Anda sudah sekarat! Dan jika usia Anda di atas 40–50 tahun — prosesnya tidak bisa dibalik tanpa tindakan!",
32: "— Dalam 70 tahun, lebih dari 40.000 orang melewati tangan saya dan saya bisa mengatakan ini: setiap nyeri sendi yang diabaikan adalah satu langkah menuju kursi roda. Hanya pada",
33: "di Indonesia tercatat lebih dari 5.400.000 kasus baru penyakit sendi berat — 990.000 di antaranya pada orang berusia 38 sampai 48 tahun. Ini bukan masalah usia tua. Ini masalah tidak melakukan apa-apa.",
34: "Jika tubuh Anda sudah memberi salah satu dari sinyal-sinyal ini — jangan menunggu satu hari pun!",
35: "Inilah daftar yang saya sampaikan kepada setiap orang bahkan sejak di ambang pintu:",
36: "Kaku di pagi hari yang tidak hilang meski sudah bergerak;",
37: "Bunyi berderak, klik, atau berdecit saat bergerak;",
38: "Nyeri yang bertambah saat cuaca berubah;",
39: "Sulit menekuk atau meluruskan lutut;",
40: "Bengkak, kemerahan, atau rasa panas di sekitar sendi;",
41: "Nyeri saat naik atau turun tangga;",
42: "Lelah menahun dan kaki terasa berat;",
43: "Nyeri pinggang yang „menjalar“ ke paha atau telapak kaki;",
44: "Kebas atau kesemutan pada jari-jari;",
45: "Perubahan cara berjalan — pincang, tidak stabil;",
46: "Tidak sanggup berdiri lebih dari 10–15 menit;",
47: "Jika Anda mengenali diri Anda bahkan hanya pada dua gejala ini — tulang rawan Anda sudah dalam proses kehancuran. Dan pada tulang belakang prosesnya tiga sampai empat kali lebih cepat, karena cakramnya berada di bawah tekanan terus-menerus.",
48: "HASILNYA: SARAF TERJEPIT, CAKRAM BERGESER, RUAS TULANG BELAKANG BERUBAH BENTUK, HILANGNYA KEMAMPUAN BERGERAK — DAN SEMUA ITU BISA TERJADI DALAM HITUNGAN MINGGU!",
49: "Jangan menunda, karena tubuh tidak memberi kesempatan tanpa batas!",
50: "Lihatlah orang-orang di bawah ini. Setiap dari mereka mengalami gejala yang sama seperti yang mungkin Anda rasakan saat ini. Setiap dari mereka berkata „nanti juga hilang“. Dan setiap dari mereka hari ini rela memberikan apa saja untuk memutar waktu dan bertindak selagi masih ada kesempatan.",
51: "Mantan pasien klinik lain, 58 tahun, Surabaya. Tiga ruas tulang belakang bergeser lebih dari 8 mm, sumsum tulang belakang tertekan. Dua kali ia menolak pergi menemui Mbah Suparno — ketika akhirnya datang, ia tinggal selangkah dari kelumpuhan.",
52: "Perempuan 61 tahun dari Medan — punggungnya membungkuk sampai 4 cm dalam waktu kurang dari setahun. Ruas tulang lehernya berubah bentuk sedemikian rupa sehingga kepalanya tidak bisa lagi menoleh ke samping. Obat pereda nyeri sudah tidak mempan sejak 8 bulan lalu.",
53: "Ibu rumah tangga, 59 tahun, Semarang. Sendi lututnya begitu aus sehingga tulang rawannya menipis hingga kurang dari 1 mm. Setiap langkah berbunyi seperti derit pintu tua. Tiga dokter ortopedi mengatakan bahwa satu-satunya jalan keluar adalah penggantian sendi ganda, lebih dari Rp 120 juta.",
54: "Mantan penambang, 68 tahun, Sawahlunto. Tulang rawan di lutut kanannya hancur total, jaringan tulangnya memasuki tahap kematian jaringan. Penundaan empat bulan membuatnya kehilangan kaki — diamputasi di atas lutut dan seumur hidup bergantung pada kursi roda.",
55: "Usia saya 102 tahun dan dari pengalaman sendiri saya bisa berkata: tubuh mampu meremajakan dirinya sendiri pada USIA BERAPA PUN — asalkan Anda tahu BAGAIMANA menyalakannya. Untuk itulah saya mengabdikan hidup saya.",
56: "DAN JIKA USIA ANDA SUDAH DI ATAS 50–60 TAHUN, JANGAN MENUNGGU SEDETIK PUN!",
57: "Pada Anda, kerusakannya hampir pasti sudah memasuki tahap kritis — kehancuran harus segera dihentikan dan pembentukan tulang rawan baru, tulang baru, serta jaringan baru harus segera dinyalakan!",
58: "Kasus-kasus yang sudah dinyatakan tanpa harapan oleh para dokter!",
59: "Sumiyati, di usia 86 tahun, kembali berjalan tanpa bantuan siapa pun setelah ditolak tiga rumah sakit. Inilah kisahnya…",
60: "Sumiyati dari Yogyakarta menderita pengapuran lutut yang parah dan beberapa cakram tulang belakang yang bergeser. Tiga rumah sakit berbeda menolaknya — di mana pun ia mendengar hal yang sama: „Di usia seperti ini sudah tidak ada yang bisa dilakukan.“ Putrinya secara kebetulan mendengar tentang Mbah Suparno dari kenalan di sebuah desa dekat Jakarta dan memutuskan untuk mencarinya.",
61: "„Saya hidup seperti di penjara — rumah saya sendiri menjadi sel. Saya tidak sanggup berjalan sampai ke kamar mandi, tidak bisa berdiri lebih dari satu menit, bahkan menyeduh teh untuk diri sendiri pun tidak mampu. Anak-anak saya bekerja dan tidak bisa datang setiap hari. Saya hanya berbaring menatap langit-langit. Dokter bilang operasi tidak ada gunanya di usia saya, dan hanya memberi saya obat pereda nyeri.",
62: "Ketika putri saya membawa saya kepada Mbah Suparno, beliau menatap saya dan mengatakan sesuatu yang tidak pernah dikatakan dokter mana pun: „Bu Sumiyati, tubuh Ibu BELUM berhenti berjuang. Hanya saja belum ada yang menolongnya.“ Beliau memberi saya racikannya sendiri dan menyuruh saya bersabar. Pada minggu ketiga, untuk pertama kalinya dalam satu setengah tahun, SAYA BANGKIT SENDIRI dari tempat tidur!",
63: "Hari ini, lima bulan kemudian, saya pergi ke pasar, memasak, bahkan merawat petak bunga di depan rumah. Di usia 86 tahun! Ketika para tetangga melihat saya di halaman, mereka tidak percaya. Mereka mengira tidak akan melihat saya lagi. Mbah Suparno mengembalikan hidup saya — dan saya tidak punya kata-kata untuk berterima kasih kepadanya.“",
64: "Sumiyati, 86 tahun, Yogyakarta",
65: "Kasus luar biasa lainnya adalah Agus Setiawan — tukang bangunan berusia 47 tahun dari Malang, yang setelah 20 tahun kerja fisik berat mengalami kerusakan parah pada tulang belakang dan terpaksa bergerak dengan kursi roda.",
66: "Agus mencoba metode Mbah Suparno, dan hasilnya mengejutkan bahkan dokter keluarganya sendiri.",
67: "TULANG BELAKANGNYA MULAI PULIH, RASA SAKITNYA HILANG SEPENUHNYA, DAN YANG PALING LUAR BIASA —",
68: "IA MENINGGALKAN KURSI RODA HANYA DALAM 4 MINGGU!",
69: "Agus bercerita kepada kami:",
}
