# -*- coding: utf-8 -*-
# Indonesia / ahli herbal, nodes 70..164 (bentuk: KAPSUL)
I2 = {
70: "„Dua puluh tahun saya membangun gedung, tetapi tidak menjaga tulang belakang saya sendiri. Suatu pagi saya terbangun dan tidak bisa menggerakkan pinggang. Istri saya memanggil ambulans. Diagnosisnya — tiga cakram bergeser dan akar saraf terjepit. Dokter menawarkan operasi seharga Rp 75 juta, tetapi tanpa jaminan.",
71: "Berbulan-bulan saya duduk di rumah di kursi roda. Anak-anak menatap saya dengan sedih, istri saya menangis setiap malam. Saya merasa menjadi beban. Rasanya ingin lenyap saja…",
72: "Lalu mertua saya mendengar tentang Mbah Suparno dari seorang pria yang pernah ditolongnya. Saya menelepon, mengirimkan foto rontgen, dan orang tua itu berkata: „Belum terlambat.“ Tiga kata itu memberi saya harapan lebih besar daripada semua yang pernah saya dengar dari puluhan dokter.",
73: "Pada hari keempat saya sudah bisa berdiri. Kursus penuhnya berlangsung 80 hari. Sekarang saya bekerja lagi — bukan di proyek, melainkan di kantor, tetapi SAYA BERJALAN. Saya berlarian dengan anak-anak di taman. Saya hidup. Rontgen menunjukkan cakram saya pulih 90%. Mbah Suparno adalah satu-satunya yang tidak menolak saya — dan satu-satunya yang menolong saya.“",
74: "Kisah ribuan orang yang ditolong Mbah Suparno sama menakjubkannya: orang-orang yang oleh dokter disuruh „biasakan saja dengan rasa sakitnya“ kembali berjalan, kembali berlari, kembali hidup. Bagaimana itu mungkin?",
75: "Formula yang diracik Mbah Suparno dengan tangannya sendiri selama lebih dari 40 tahun!",
76: "Rahasia metode „Reaktivasi Jaringan Endogen“ — bagaimana tubuh sendiri mulai memproduksi tulang rawan baru, tulang baru, dan ligamen baru!",
77: "— Izinkan saya menjelaskan sesuatu yang tidak mau diakui kedokteran konvensional. Tubuh setiap orang — bahkan orang berusia 90 tahun — memiliki sel-sel peremaja yang „tertidur“. Sel-sel yang sama yang di masa muda dengan mudah membangun tulang rawan, tulang, dan ligamen Anda. Seiring tahun mereka tidak mati — mereka hanya „tertidur“, karena tubuh berhenti mengirimkan sinyal yang tepat kepada mereka.",
78: "Empat puluh tahun lalu saya menemukan bahwa kombinasi tertentu dari bahan-bahan alami — dalam takaran yang sangat tepat — bekerja seperti „kunci kontak“ bagi sel-sel yang tertidur itu. Metode itu saya beri nama",
79: "„Reaktivasi Jaringan Endogen“",
80: "— karena metode ini tidak memasukkan sesuatu yang buatan, melainkan mengaktifkan sumber daya tubuh itu sendiri. Justru karena itulah pada saya TIDAK ADA efek samping, TIDAK ADA kerusakan organ, dan TIDAK ADA ketergantungan.",
81: "Empat dasawarsa saya menerapkan metode ini pada setiap orang yang melangkah ke rumah saya — dan pada setiap orang saya mencatat hasil yang sama: kehancuran berhenti, rasa sakit berkurang, dan fungsi sendi perlahan kembali. Ratusan orang yang datang kepada saya sebagai „harapan terakhir“ pulang dari rumah saya dengan kaki mereka sendiri.",
82: "Formulanya sendiri tidak rumit — tetapi ketepatan adalah segalanya. Setiap bahan harus dalam jumlah yang persis, sampai seperseratus miligram. Jika takarannya tidak dipatuhi, khasiatnya hilang begitu saja. Justru karena itulah selama puluhan tahun saya meraciknya sendiri — karena saya tidak bisa mempercayakannya kepada apotek.",
83: "Komposisi kapsul menurut resep ahli herbal Hadi (bahan aktif per dosis):",
84: "Omega-3",
85: "biji rami: 4500 mg",
86: "Glukosamin sulfat",
87: "krustasea: 1100 mg",
88: "Magnesium sitrat",
89: "rumput laut: 390 mg",
90: "Gingerol",
91: "jahe: ekstrak 4200 mg",
92: "AKBA",
93: "getah kemenyan (Boswellia): ekstrak 1100 mg",
94: "Silikon",
95: "rumput betung: ekstrak 320 mg",
96: "Kurkumin",
97: "kunyit: ekstrak 2300 mg",
98: "Bahan-bahan ini tampak sederhana, tetapi menemukannya dalam mutu yang tepat dan dari sumber yang tepat sangatlah sulit. Sebagian besar tidak ada di apotek dan harus didatangkan dari berbagai penjuru dunia. Sedangkan mencampurnya di rumah praktis mustahil — karena takarannya harus tepat sampai 0,1 mg.",
99: "Justru karena itulah selama puluhan tahun saya meracik campuran ini sendiri, untuk setiap orang secara terpisah. Tetapi putra saya, Bambang, melihat gambaran utuhnya.",
100: "Bagaimana Bambang Hadi mengubah resep berusia 40 tahun milik ayahnya menjadi kapsul yang terjangkau semua orang — Nautubone",
101: "Bambang Hadi:",
102: "— Saya tumbuh besar di ruang tanaman obat milik ayah saya. Setiap hari saya melihat orang-orang masuk dengan badan membungkuk menahan sakit — dan keluar sambil tersenyum. Di usia 14 tahun saya sudah hafal resepnya di luar kepala. Saya tidak menjadi dokter — keahlian ini saya pelajari dari beliau. Tetapi bertahun-tahun saya membujuknya: Pak, resep ini tidak boleh terkunci di satu rumah saja. Ribuan orang menunggu apa yang Bapak simpan di rak itu.",
103: "Lima tahun saya berkeliling laboratorium di Jakarta dan Munich sampai menemukan orang-orang yang sungguh-sungguh ingin meneliti formula ayah saya. Jawaban yang saya terima membuat saya bersemangat: kombinasi bahan-bahan ini dalam takaran yang persis mengaktifkan produksi kolagen tipe II dan proteoglikan — dua bahan bangunan utama tulang rawan. Dengan kata lain: tubuh benar-benar „mengingat“ cara membangun tulang rawan baru, ia hanya membutuhkan sinyal yang tepat.",
104: "Bersama laboratorium, kami mengembangkan sebuah proses yang kami beri nama",
105: "„Teknologi Nanodifusi dengan Bioavailabilitas Tingkat Lanjut“",
106: "— sebuah metode di mana bahan-bahan aktif dibungkus dalam nanopartikel khusus, yang dilepaskan langsung di usus halus, melewati metabolisme hati, dan mengalir melalui darah tepat menuju jaringan sendi yang rusak. Ini meningkatkan penyerapan sekitar 380% dibandingkan tablet biasa. Produk itu saya beri nama",
107: "Nautubone",
108: "— kapsul yang diminum dan bekerja tepat di tempat yang membutuhkannya. Saya menamainya demikian untuk menghormati ayah saya dan 40 tahun kerja beliau.",
109: "Kapsul Nautubone mengandung ketujuh komponen dari resep asli ayah saya, ditambah 29 ekstrak dan vitamin lain yang kami tambahkan setelah pengujian laboratorium di Munich. Hasilnya adalah produk yang bekerja SAMA BAIKNYA dengan racikan tangan ayah saya sendiri — tetapi bisa dikirim ke setiap rumah di Indonesia. Anda minum satu kapsul dua kali sehari, dan bahan-bahan aktifnya mengalir melalui darah langsung menuju sendi yang bermasalah.",
110: "„Nautubone adalah warisan ayah saya — 40 tahun pengalaman beliau yang terkunci dalam satu formula. Setiap bahan dipilih dengan ketelitian yang sama seperti ketika beliau membungkuk menolong setiap orang yang mengetuk pintunya. Ini bukan produk massal dari rak apotek — ini adalah karya sepanjang hidup yang diabdikan untuk menyembuhkan.“",
111: "Hal paling luar biasa dari Nautubone adalah ia tidak sekadar meredakan rasa sakit — ia menyalakan kembali mekanisme peremajaan yang tertidur seiring bertambahnya usia. Kapsul diminum, dan nanopartikel membawa bahan-bahan aktif jauh ke dalam jaringan sendi — ke tempat yang tidak pernah dijangkau krim dan gel biasa. Sinergi antarbahan memperkuat khasiatnya sampai 20 kali lipat dibandingkan bila diminum terpisah.",
112: "Empat tahap pemulihan dengan Nautubone — apa yang terjadi di tubuh Anda selangkah demi selangkah",
113: "— Sepanjang hidup saya sebagai ahli herbal, saya menyaksikan orang-orang melewati empat tahap yang sama. Putra saya mendokumentasikannya dan memasukkannya ke dalam Nautubone, agar setiap orang bisa melewatinya di rumah.",
114: "Empat tahap „Reaktivasi Jaringan Endogen“:",
115: "Tahap 1 — Menghentikan rasa sakit dan peradangan:",
116: "Sejak kapsul pertama, nanopartikel melepaskan bahan aktif di usus dan membawanya melalui darah langsung ke jaringan yang rusak, sambil menghambat molekul peradangan. Rasa sakit berkurang secara nyata dalam 24–48 jam — tanpa membebani hati dan ginjal, karena mikrokapsulnya memiliki lapisan enterik dan melewati metabolisme hati yang biasa.",
117: "Tahap 2 — Menghentikan kehancuran:",
118: "Antara hari ketiga dan ketujuh, tubuh berhenti merombak jaringan tulang rawan dan tulang. Produksi cairan sendi — „pelumas“ alami sendi — meningkat. Gesekan berkurang dan gerakan menjadi lebih ringan.",
119: "Tahap 3 — Membangunkan sel-sel peremaja:",
120: "Inilah inti metodenya. Kondrosit dan osteoblas yang „tertidur“ menerima sinyal biokimia dan mulai memproduksi tulang rawan baru serta jaringan tulang baru. Justru tahap inilah yang membuat Nautubone unik — tidak ada produk lain yang menyalakan mekanisme ini.",
121: "Tahap 4 — Perisai pelindung yang tahan lama:",
122: "Setelah 30–60 hari, jaringan yang baru terbentuk membangun lapisan pelindung yang kuat, yang membuat sendi tahan bahkan terhadap beban berat. Mbah Suparno menyebutnya „kekebalan sendi“ — sekali diperoleh, khasiatnya bertahan bertahun-tahun.",
123: "Setiap tahap ini adalah hasil dari 40 tahun pengalaman satu orang dan 5 tahun pengujian laboratorium. Nautubone tidak menawarkan „penutupan“ rasa sakit yang cepat — ia memulai proses peremajaan biologis yang mendalam, yang mengembalikan sendi ke kondisi puluhan tahun yang lalu.",
124: "Hasil yang mengejutkan kalangan medis — pemantauan 2.340 orang berusia 38 sampai 89 tahun",
125: "— Ketika kami mempublikasikan hasil pengujian laboratorium yang pertama, reaksinya secepat kilat. Rumah sakit universitas dari Jakarta, Berlin, dan Wina meminta izin melakukan penelitian mereka sendiri. Hasil pada orang sungguhan bahkan melampaui harapan kami — tidak satu pun metode pengobatan yang ada mendekati angka-angka ini.",
126: "Orang-orang yang sudah dijadwalkan pemasangan sendi buatan membatalkan operasinya. Orang-orang yang berbulan-bulan tidak bangkit dari tempat tidur kembali berjalan. Para dokter ortopedi tidak percaya pada foto rontgen mereka sendiri.",
127: "Hasil pemantauan „Nautubone“ pada 2.340 orang berusia 38 sampai 89 tahun",
128: "Rasa sakit dan peradangan hilang sepenuhnya",
129: "Rentang gerak kembali sepenuhnya",
130: "Tendinitis, bursitis, periartritis",
131: "Berhentinya dan mundurnya perubahan degeneratif",
132: "Sinovitis, ligamentitis",
133: "Osteoartritis (semua tahap)",
134: "Osteoporosis",
135: "Artritis reumatoid, asam urat",
136: "Pengapuran sendi, spondiloartritis",
137: "Peremajaan jaringan tulang rawan yang terdokumentasi",
138: "Rentang waktu pemulihan yang pasti dengan „Nautubone“:",
139: "Tim ilmuwan lain di Eropa mencoba meniru formula kami, tetapi hasil mereka sejauh ini masih jauh dari hasil kami. Teknologi Nanodifusi dengan Bioavailabilitas Tingkat Lanjut, yang dikembangkan bersama laboratorium kami, sampai sekarang belum bisa ditiru — justru teknologi inilah yang memungkinkan kapsul mengantarkan bahan-bahannya langsung ke dalam sendi melalui darah, alih-alih hanya tertinggal di permukaan kulit seperti salep.",
140: "Berapa lama pemulihan penuh berlangsung? Mbah Suparno menjelaskan berdasarkan 70 tahun pengalaman",
141: "— Kursus paling singkat yang saya anjurkan adalah 30 hari. Pada kerusakan yang lebih berat — 60, dan kadang 90 hari. Tetapi sepanjang praktik saya TIDAK PERNAH ADA SATU KASUS PUN di mana metode ini tidak memberi hasil. Tidak satu pun. Dan saya sudah mengobati orang berusia 85, 90, bahkan 94 tahun.",
142: "Nautubone tidak hanya menghentikan rasa sakit — ia memulai proses peremajaan biologis yang mendalam. Minumlah satu kapsul dua kali sehari dan pada jam-jam pertama Anda sudah akan merasakan kelegaan. Dalam satu minggu Anda akan melihat gerakan Anda menjadi lebih ringan. Dan setelah kursus penuh, sendi Anda akan berada dalam kondisi seperti 20–30 tahun yang lalu.",
143: "Tetapi yang paling berharga adalah hal lain: khasiatnya BERTAHAN LAMA. Sekali „dibangunkan“, sel-sel peremaja terus bekerja bertahun-tahun!",
144: "Berkat „Nautubone“, lebih dari 820.000 orang di Indonesia telah mendapatkan kembali kemampuan bergerak mereka. Ini hanya sebagian kecil dari mereka yang ditolong Mbah Suparno:",
145: "Pensiunan, 66 tahun, Palembang. Empat ruas tulang belakang bergeser dan nyeri saraf menahun. Putranya membawakan kapsul Nautubone dari Jakarta. Dua bulan mengonsumsi — tulang belakang kembali sepenuhnya ke posisi normal. Dokter ortopedinya menanyakan nama produknya.",
146: "Pembukuan, 41 tahun, Makassar. Lututnya berubah bentuk ke dalam setelah dua kali melahirkan dan kenaikan berat badan. Dokter ortopedi mengatakan kepadanya „biasakan saja“. Dengan kapsul Nautubone — 30 hari konsumsi, dua kali sehari — garis lututnya terlihat jelas menjadi lurus pada foto rontgen.",
147: "Pensiunan, 73 tahun, Solo. Pengapuran membuat jari-jari kakinya berubah bentuk sampai tidak ada satu pun sepatu yang muat. Ia minum kapsul Nautubone setiap hari — dalam 21 hari jari-jarinya kembali lurus, dan sepatu dari 5 tahun lalu kembali pas di kakinya.",
148: "— Foto-foto ini bukan mukjizat — ini adalah alam dan kesabaran. Setiap orang di sini mendapatkan kembali sesuatu yang oleh dokter dikatakan mustahil: sendi yang sehat dan hidup tanpa rasa sakit. Nautubone ADALAH MAHKOTA SELURUH HIDUP SAYA SEBAGAI AHLI HERBAL — DAN WARISAN SAYA UNTUK GENERASI MENDATANG!",
149: "Mengapa Mbah Suparno tidak lagi menerima orang — dan bagaimana Nautubone menjadi satu-satunya jalan menuju resepnya",
150: "„Kesehatan saya tidak lagi memungkinkan menerima orang sakit secara langsung. Tetapi formula saya akan terus menyembuhkan — melalui tangan putra saya.“",
151: "— Tahun lalu saya mengambil keputusan tersulit dalam hidup saya: tidak lagi menerima orang. Daftar tunggunya berisi lebih dari 2.000 nama — dan saya tidak bisa membiarkan mereka tanpa pertolongan. Karena itu saya mengizinkan putra saya, Bambang, membawa resep itu ke tempat yang akan membuatnya untuk semua orang. Sekarang hati saya tenang — Nautubone persis sama dengan yang saya berikan kepada orang-orang yang datang kepada saya, hanya dalam bentuk yang praktis. Resep itu berada di tangan yang tepat.",
152: "— Nautubone tidak dijual di apotek — proses produksinya rumit dan jumlahnya terbatas. Produk ini hanya tersedia melalui program daring, dua kali setahun. Namun dalam program ini, diskonnya mencapai",
153: "— karena tujuan kami bukan keuntungan, melainkan keterjangkauan. Terutama bagi para pensiunan, yang menurut ayah saya harus mendapatkan diskon terbesar.",
154: "Untuk mendaftar, gunakan formulir pemesanan resmi di bawah ini — formulir ini datang langsung dari tim produksi Bambang Hadi.",
155: "Jangan lewatkan kesempatan terakhir tahun ini — Nautubone bisa habis sebelum program berakhir!",
156: "— Tahun ini kami berhasil memproduksi 5&nbsp;000 kotak kapsul Nautubone khusus untuk masyarakat Indonesia. Tetapi mengingat permintaannya yang sangat besar, jumlah ini akan cepat habis. Seri berikutnya baru akan siap pada akhir",
157: "Program dukungan ini aktif sampai",
158: "— setiap penduduk Indonesia yang berusia di atas 40 tahun bisa mendapatkan",
159: "diskon sampai 50%",
160: ". Setelah tanggal itu, Anda harus menunggu setidaknya 6 bulan untuk kesempatan berikutnya.",
161: "Jangan menunda. Ayah saya selalu berkata kepada orang-orang: „Sendi Anda tidak menunggu Anda — mereka hancur setiap detik.“ Selama program masih aktif, manfaatkanlah. Nautubone memiliki khasiat yang menumpuk — satu kursus penuh saja cukup untuk 5–6 tahun sendi yang sehat.",
162: "Cukup tuliskan nama dan nomor telepon Anda di formulir. Konsultan akan menelepon Anda, menyusun program khusus untuk kasus Anda, dan mengatur pengiriman ke alamat mana pun di Indonesia — dalam 2–3 hari, lewat pos atau kurir sampai ke depan pintu Anda.",
163: "Saya mendoakan kesehatan untuk semuanya! Jagalah sendi Anda hari ini, agar besok Anda masih bisa berjalan! Hormat saya: Suparno Hadi dan putranya, Bambang.",
164: "Diperbarui:",
}
