# -*- coding: utf-8 -*-
# Indonesia / ahli herbal, nodes 165..236 + attrs (bentuk: KAPSUL)
I3 = {
165: "Karena permintaan yang sangat tinggi, persediaan Nautubone bisa habis sebelum program berakhir sesuai rencana! Hari ini —",
166: "18/12/2025 — adalah hari terakhir untuk memesan dengan diskon",
167: "atau sampai persediaan habis.",
168: "Perhatian! Jangan menutup dan jangan menyegarkan halaman ini — kapsul Nautubone yang sudah dipesankan untuk Anda akan ditawarkan kepada orang berikutnya dalam daftar tunggu!",
169: "Tempat Anda yang sudah dipesan dalam program:",
170: "Formulir pemesanan resmi",
171: "Untuk mendapatkan",
172: "diskon 50%",
173: ", tuliskan nama dan nomor telepon Anda pada kolom di bawah ini lalu tekan tombol „PESAN SEKARANG“.",
174: "Sisa persediaan:",
175: "Rp 590.000",
176: "Rp 295.000",
177: "Nama",
178: "Nomor telepon",
179: "PESAN SEKARANG",
180: "✔️ Pengiriman ke alamat mana pun di Indonesia dalam 2–3 hari",
181: "lewat pos atau kurir sampai ke depan pintu Anda",
182: "KOMENTAR:",
183: "Sri Wahyuni",
184: "Berbulan-bulan saya menunggu artikel ini! Seorang teman dari Jakarta pernah datang sendiri ke Mbah Suparno beberapa tahun lalu — katanya beliau itu bukan manusia biasa, tapi keajaiban. Sayang sekali beliau tidak menerima orang lagi, tetapi kalau Nautubone memakai resep yang sama — saya pesan sekarang juga. Syukurlah masih kebagian diskon!",
185: "Endang Lestari",
186: "Kurirnya datang hari Rabu. Sudah sepuluh hari saya minum kapsulnya pagi dan malam — dan bedanya LUAR BIASA! Saya bangun tanpa bunyi kretek-kretek yang menyeramkan itu lagi! Suami saya melihat dan tidak percaya. Saya akan menuntaskan kursus penuh 60 hari, tapi sekarang saja saya sudah yakin ini bekerja.",
187: "Siti Rahayu",
188: "Usia saya 72 tahun dan tiga tahun saya menderita nyeri panggul. Berjalan itu siksaan. Dokter ortopedi berkata: „Ganti sendi atau tahan saja.“ Saya tidak mau keduanya. Nautubone menolong saya dalam dua bulan — sekarang saya berjalan satu setengah kilometer setiap hari! Dan foto rontgennya menunjukkan perbaikan yang tidak bisa dijelaskan dokter saya. Terima kasih, Mbah Suparno, dan terima kasih juga untuk putra Bapak!",
189: "Bambang Susilo",
190: "Sebagai mantan atlet, saya tahu betul rasanya hidup dengan tulang rawan yang sudah hancur. Lutut saya seperti milik orang berusia 90 tahun — padahal umur saya baru 54. Nautubone mengembalikan gerakan-gerakan yang sudah 10 tahun tidak bisa saya lakukan. Saya bisa jongkok lagi! Saya tidak tahu ada produk lain yang mampu melakukan hal seperti ini.",
191: "Yuni Susilo",
192: "Saya agak khawatir… Apakah sepadan? Umur saya 66 tahun, sendi saya berbunyi setiap kali bergerak dan punggung saya tidak pernah tenang. Tetapi saya sudah begitu sering kecewa dengan berbagai obat „ajaib“ sampai sekarang sulit sekali percaya. Apakah benar-benar menolong?",
193: "Hendra Gunawan",
194: "Bu Yuni, saya sangat memahami keraguan Ibu — saya pun dulu begitu. Tetapi Nautubone berbeda dari semua yang pernah saya coba. Sudah 5 minggu saya meminumnya untuk lutut dan pinggang — dan saya bisa katakan bedanya seperti siang dan malam.",
195: "Dulu saya tidak bisa membungkuk untuk mengikat tali sepatu. Sekarang saya melakukannya tanpa berpikir. Pesanlah setidaknya satu kotak dan nilai sendiri — Anda tidak rugi apa pun!",
196: "Dewi Anggraini",
197: "Tiga hari setelah mulai minum kapsulnya, nyeri lutut saya berkurang setengahnya! Sekarang hari ke-12 dan saya sudah menaiki tangga tanpa berpegangan pada pagar. Saya akan menuntaskan kursus penuh — saya yakin dalam dua bulan saya akan seperti baru lagi!",
198: "Ratna Puspita",
199: "Di punggung saya mulai tumbuh „punuk“ sekitar dua bulan lalu. Saya sangat ketakutan! Saya mencoba bermacam salep dari apotek — tidak ada hasilnya. Tetapi kapsul Nautubone benar-benar lain — dalam 40 hari punuknya hampir hilang seluruhnya! Saya masih meminumnya, tetapi sekarang saja saya sudah luar biasa senang. Begini perbedaannya:",
200: "Nurhayati",
201: "Saraf saya terjepit di pinggang — karena sakitnya saya tidak bisa tidur maupun berdiri. Dokter meresepkan obat pereda nyeri yang keras, yang membuat saya terus-menerus mual. Saya mulai minum kapsul Nautubone dua kali sehari — setelah seminggu rasa sakitnya turun drastis, dan setelah sebulan — hilang sama sekali! Saya masih melanjutkan kursusnya, tetapi hidup saya sudah berubah!",
202: "Slamet Riyadi",
203: "Umur saya 79 tahun dan selama tiga tahun saya nyaris tidak bisa berjalan. Anak saya memesan Nautubone — tanpa bertanya kepada saya, karena dia tahu saya pasti menolak. Dia memberi saya kapsulnya setiap pagi dan setiap malam. Dan hasilnya? Setelah satu setengah bulan saya berjalan ke taman setiap hari! Rasanya seperti umur 60 lagi! Terima kasih, Mbah Suparno — di usia 102 tahun Anda lebih bijak daripada semua dokter zaman sekarang!",
204: "Teguh Prasetyo",
205: "Sebelum Nautubone saya tidak bisa mengangkat tangan di atas kepala — bahu saya berbunyi dan sakitnya luar biasa. Dua tahun saya berpindah-pindah dokter — tidak ada yang menolong. Dua bulan dengan Nautubone dan tangan saya kembali berfungsi normal. Ini foto rontgen saya — dokternya sendiri pun tidak percaya:",
206: "Ani Kusuma",
207: "Saya memesan untuk ibu mertua saya — usianya 81 tahun dan nyaris tidak bisa bangun dari tempat tidur. Para dokter menolak melakukan apa pun — „di usia segitu tidak ada lagi yang menolong“, kata mereka. Dengan Nautubone, dalam 2 bulan beliau sudah berjalan di halaman dan bahkan memasak! Kami tidak percaya melihatnya.",
208: "Joko Santoso",
209: "Istri saya terbaring empat bulan — tulang belakangnya benar-benar menyerah. Dokter menawarkan operasi seharga Rp 95 juta tanpa jaminan apa pun. Kami memutuskan mencoba kapsul Nautubone — kami tidak punya apa-apa lagi untuk hilang. Saya memberikannya dua kali sehari. Setelah 5 minggu istri saya bangkit. Kemarin kami pergi bersama ke pasar — untuk pertama kalinya dalam setengah tahun! Saya menangis bahagia.",
210: "Nia Rahmawati",
211: "Saya memesan minggu lalu, barangnya sampai pada hari ketiga. Saya langsung mulai minum kapsulnya — dan kelegaan datang pada hari kedua! Seperti ada yang meminyaki sendi saya dari dalam. Sudah dua minggu saya minum dua kali sehari dan saya tidak sabar menunggu hasil penuhnya!",
212: "Rukmini",
213: "Umur saya 74 tahun. Lima tahun saya menderita pengapuran sendi dan nyeri punggung. Saya benar-benar sudah mencoba semuanya — salep, tablet, suntikan, fisioterapi. TIDAK ADA yang menolong dalam jangka panjang. Kapsul Nautubone adalah satu-satunya yang memberi saya HASIL NYATA — saya minum dua kali sehari dan dalam satu setengah bulan sendi saya terasa benar-benar berbeda. Dokternya tidak percaya pada foto rontgennya!",
214: "Wulandari",
215: "Saya mengenal Mbah Suparno secara pribadi — 12 tahun lalu beliau menolong saya dengan saraf terjepit. Dalam tiga minggu saya sudah berdiri lagi! Namanya dikenal seluruh kawasan sekitar Jakarta. Saya senang putranya melanjutkan karya beliau!",
216: "Tuti Handayani",
217: "Ayah saya berusia 84 tahun dan tiga tahun tidak keluar rumah. Sendi, punggung, lutut — semuanya sakit. Beliau bilang tinggal menunggu waktu saja. Setelah dua bulan dengan Nautubone — kemarin beliau keluar ke halaman dan menyiram kebun! Untuk pertama kalinya dalam tiga tahun! Saya tidak bisa menggambarkan perasaan saya. Terima kasih dari lubuk hati!!!",
218: "Mirna Sari",
219: "Ada yang tahu apakah ini bisa dipakai kalau punya alergi? Saya bereaksi terhadap hampir semua hal — bahkan aspirin biasa saja membuat jari-jari saya bengkak. Saya takut mencoba sesuatu yang baru…",
220: "Agus Purnomo",
221: "Bu Mirna, saya alergi terhadap empat jenis obat. Sudah 50 hari saya minum kapsul Nautubone — tidak ada iritasi, tidak ada bengkak, tidak ada kemerahan. Komposisinya sepenuhnya ekstrak alami — tidak mengandung bahan kimia. Anda bisa memesan dengan tenang!",
222: "Darmi",
223: "Dulu saya tidak punya tenaga untuk bangun — setiap gerakan adalah siksaan, saya pikir hidup saya sudah berakhir. Anak perempuan saya memesan kapsul Nautubone dan memaksa saya mencobanya — dia memberikannya kepada saya pagi dan malam. Dua bulan kemudian? Saya menari di pernikahan cucu saya!!! Belum pernah seumur hidup saya merasa sebersyukur ini!",
224: "Elisabeth Tanuwijaya",
225: "Saya memesan untuk ibu saya. Lehernya terus-menerus sakit sampai membuatnya pusing dan mual — hidupnya menjadi tidak tertahankan. Pada minggu kedua dengan Nautubone rasa sakitnya turun drastis, dan pusingnya berhenti sama sekali! Ibu tertawa lagi — sudah lama saya tidak melihat beliau seperti itu.",
226: "Susanti",
227: "Saya jadi bertanya-tanya — kalau Mbah Suparno memang sehebat itu, mengapa barang seperti ini tidak dijual di mana-mana? Mengapa hanya daring? Mengapa apotek tidak menyediakannya?",
228: "Muhammad Fadli",
229: "Karena apotek untung dari orang-orang yang membeli obat pereda nyeri setiap bulan! Kalau semua orang menyembuhkan sendinya sekali untuk selamanya — siapa yang akan membeli obat-obat mahal mereka? Berpikirlah dengan logika!",
230: "Olivia Kurnia",
231: "Saya membaca semua komentarnya — dan saya terharu. Saya pesan sekarang, untuk saya dan untuk suami saya. Saya ambil tiga kotak kapsul, untuk kursus penuh. Kalau menolong walau setengah dari yang ditulis orang-orang — saya sudah bahagia!",
232: "Lusiana Dewi",
233: "Dokter ortopedi saya bilang di usia 63 tahun saya harus membiasakan diri dengan rasa sakit — katanya tidak ada obatnya. Saya pesan Nautubone justru untuk membuktikan sebaliknya. Kita lihat saja siapa yang benar!",
234: "Unggah avatar",
235: "Unggah foto",
236: "KIRIM",
}
ATTRS_I = {
 "Вашето име": "Nama Anda",
 "Вашият телефонен номер": "Nomor telepon Anda",
 "Вашият коментар": "Komentar Anda",
}
