# -*- coding: utf-8 -*-
# Philippines / herbolaryo, nodes 0..69 (anyo: KAPSULA)
P1 = {
0: "Si Ambrosio Dimalanta, 102-anyos na herbolaryo mula sa mga bayang malapit sa Maynila, ibinunyag ang pormula para sa ganap na paggaling ng mga kasukasuan — isang paraang abot-kaya ng bawat Pilipino",
1: "SA EDAD NA 102, SIYA ANG PINAKAMATANDANG HERBOLARYO SA PILIPINAS AT ANG TANGING TAO SA KANYANG HENERASYON NA NAKALALAKAD PA NANG WALANG TUNGKOD. SA UNANG PAGKAKATAON, IBINUBUNYAG NIYA ANG PORMULANG SA LOOB NG 40 TAON AY IBINIGAY LAMANG NIYA SA MGA DUMARATING SA KANYA.",
2: "Nailathala noong:",
3: "„Paano nagawa ni Lolo Ambrosio Dimalanta, herbolaryo mula sa mga bayang malapit sa Maynila, na panatilihing perpekto ang kanyang mga kasukasuan hanggang sa edad na 102, samantalang ang lahat ng kaedad niya ay matagal nang hindi makalakad?“",
4: "Sa isang bayan na di-kalayuan sa Maynila ay may nakatirang lalaki na sumasalungat sa lahat ng alam natin tungkol sa pagtanda. Sa edad na 102, ang herbolaryong si Ambrosio Dimalanta ay naglalakad tuwing umaga sa mga daan sa itaas ng bayan, umaakyat ng hagdan nang walang tulong, at kailanman ay hindi pa nakagamit ng tungkod. Ang mga kaedad niya ay matagal nang wala o nakagapos na sa wheelchair — samantalang siya ay umaakyat pa rin mag-isa sa burol para mamitas ng halamang gamot.",
5: "Hanggang noong isang taon, tumatanggap si Lolo Ambrosio ng mga tao sa sarili niyang bahay, sa lumang silid kung saan siya nagpapatuyo ng mga halaman sa loob ng mga dekada. Mahigit 70 taon ng pakikipagtulungan sa mga halaman, mahigit 40,000 katao, dose-dosenang gulugod at tuhod na naibalik sa buhay matapos silang isuko na ng mga doktor. May anim na buwang pila — mula sa buong bansa ang mga taong pumupunta sa kanya.",
6: "Ngunit ang tunay na misteryo ay hindi ang mga pumupunta sa kanya. Ang tunay na misteryo ay siya mismo. Sa edad na 102 — walang arthritis, walang osteoarthritis, walang kahit isang herniated disc. Ang mga X-ray ng kanyang mga kasukasuan ay parang sa isang 45-anyos na lalaki. Ang mga doktor na sumusuri sa kanya ay hindi makapaniwala sa kanilang nakikita.",
7: "Sa loob ng mga dekada, itinago niya ang kanyang resipe — siya mismo ang naghahanda nito, sa kanyang silid, at kailanman ay hindi niya inilathala. Ngunit ngayon, kung kailan hindi na siya pinapayagan ng kanyang kalusugan na tumanggap ng tao nang personal, gumawa si Lolo Ambrosio ng desisyon na nagbago ng lahat: gawing abot-kaya ang kanyang pormula para sa bawat Pilipino.",
8: "Ambrosio Dimalanta: „Buong buhay ko ay pinanood ko kung paano tumatanda ang mga tao nang wala pa sa panahon — hindi dahil mahina ang kanilang katawan, kundi dahil walang nagsabi sa kanila kung paano paganahin ang sarili nilang mekanismo ng pagpapanumbalik. Sa edad na 102, ako ang buhay na patunay na",
9: "maaaring manatiling malusog ang mga kasukasuan hanggang sa napakatandang edad, kung alam mo kung paano „gisingin“ ang mga selulang bumubuo sa kanila.",
10: "IISA LAMANG ANG LAGI KONG LAYUNIN — TULUNGAN ANG KATAWAN NA GUMAWA NG BAGONG KARTILAGO AT BUTO, TULAD NG NOONG BATA PA. NGAYON, ANG ANAK KONG SI RAMON AY GINAWANG PRODUKTO ANG LAHAT NG ITO,",
11: "NA MAKAKARATING SA BAWAT TAHANAN SA PILIPINAS.",
12: "Si Ramon Dimalanta — ang anak ng herbolaryo — ay lumaki sa gitna ng mga pinatuyong halaman at ng timbangan ng kanyang ama, at natutunan ang hanapbuhay na ito mula pagkabata. Hindi siya naging doktor. Sa loob ng maraming taon ay hinikayat niya ang kanyang ama na huwag manatili ang resipe sa iisang bahay lamang, at pagkatapos ay siya mismo ang naghanap ng laboratoryo at ng mga taong tumulong upang ang dekada-dekadang karanasan ni Lolo Ambrosio ay maging produktong abot-kaya ng lahat — upang marating nito ang lahat ng nangangailangan.",
13: "Ang resulta ng pagtutulungang ito ay lumampas sa lahat ng inaasahan. Ngunit bago ko ikuwento ang produkto, tingnan muna natin kung bakit halos tiyak na mali ang lahat ng alam ninyo tungkol sa paggamot ng mga kasukasuan.",
14: "Ang kasinungalingang pinaniniwalaan ng buong Pilipinas:",
15: "„Ang mga pain reliever ay nagpapagaling ng kasukasuan“ — MALI, mas mabilis pa nila itong sinisira!",
16: "Ambrosio Dimalanta:",
17: "— Pitumpung taon na akong gumagamot ng tao at sasabihin ko sa inyo ang isang bagay na kailanman ay hindi aaminin ng mga botika: wala ni isang pain reliever sa kasaysayan ng medisina ang nakapagbalik ng kahit isang milimetro ng kartilago. Wala ni isa! Pinapatahimik nila ang sakit, ngunit habang ganoon ay patuloy na nasisira ang kartilago — nararamdaman ninyo lang. At kapag muli ninyong naramdaman, huli na ang lahat.",
18: "Pero hindi iyon ang pinakamasama. Ang pinakamasama ay kung ano ang ginagawa ng mga kemikal na ito sa inyong mga panloob na organo. Sa 70 taon ng aking trabaho, nakakita ako ng daan-daang taong wasak na wasak ang atay at bato — hindi dahil sa sakit, kundi dahil sa gamot! Hindi ginawa ang katawan para lumunok ng kemikal sa loob ng mga dekada. Gayunpaman, iyan mismo ang „inirereseta“ ng karaniwang medisina.",
19: "Lalong mahina ang gulugod. Ang mga disc sa pagitan ng mga buto ay walang sariling daluyan ng dugo — kumakain sila sa pamamagitan ng diffusion, na ang ibig sabihin ay tahimik na nangyayari ang pagkasira nila, walang sakit, minsan sa loob ng maraming taon. Kapag sa wakas ay lumitaw na ang sakit, malala na ang pinsala. Ang pagkakadiin ng ugat dahil sa herniated disc ay ginagawang bangungot ang buhay: nagsisimula sa bahagyang pamamanhid ng binti, at nagtatapos sa ganap na pagkawala ng kakayahang gumalaw.",
20: "Tingnan ninyo ang ipinapakita ng X-ray na ito. Isang babae, 39 anyos pa lamang, guro — at ang kanyang gulugod ay nasa kalagayang 20 taon na ang nakalipas ay nakikita ko lamang sa mga taong 70-anyos. Walong oras kada araw na nakaupo sa silya, kawalan ng galaw at ganap na kawalan ng kaalaman sa sariling katawan — iyan ang dala ng makabagong pamumuhay.",
21: "Larawan mula sa arkibong iniingatan ni Lolo Ambrosio sa loob ng mga dekada: ang gulugod ng isang 39-anyos na guro mula sa Cebu. Dumating siya dahil sa „bahagyang pananakit ng bewang“ — ipinakita ng X-ray ang tatlong sirang disc, nagsisimulang herniation at mga mikroskopikong bitak sa balot na kartilago.",
22: "Kung pagkatapos ng edad na 40 ay nakakaramdam kayo ng sakit, paninigas o pagkalutong ng mga kasukasuan — nasisira na ang inyong kartilago. Hindi ito „pagod lang“ at hindi ito „normal“.",
23: "Sa gulugod, ilang beses na mas mabilis at mas mapanlinlang ang prosesong ito — lumilitaw lamang ang sakit kapag kritikal na ang pinsala!",
24: "— Gusto kong maging tapat na tapat. May mga kilala akong tao na ipinagpaliban ito nang buwan-buwan. Ang resulta? Isang naipit na ugat na kailanman ay hindi na muling gumana nang normal. Walang saysay ang pagpapanumbalik ng mga disc kapag patay na ang ugat —",
25: "MAAARING BUMALIK ANG DISC, PERO ANG UGAT — HINDI NA!",
26: "At ano ang natitira? TUNGKOD, WHEELCHAIR AT PAGDEPENDE SA IBA HANGGANG SA HULING ARAW NG BUHAY!",
27: "At ano ang inaalok ng modernong kirurhiya? Mahal at mapanganib na operasyon na may metal na implant. Personal akong nakakita ng daan-daang taong pagkatapos ng operasyon sa gulugod ay MAS MASAMA pa ang pakiramdam kaysa noong bago pa ito.",
28: "IMPEKSIYON, HINDI MAAYOS NA PAGKAKABUO NG BUTO, PANGMATAGALANG SAKIT AT SA HULI — ISA NA NAMANG OPERASYON. AT KUNG MINSAN — PINSALANG HINDI NA MAIBABALIK!",
29: "Ipinapakita ni Lolo Ambrosio ang isang X-ray na dinala sa kanya ng isang lalaki matapos ang operasyong may metal na turnilyo: „Ito ang karaniwang resulta — hindi maayos na kumapit ang implant, namamaga ang mga tisyu sa paligid, at mas malala ang sakit kaysa bago ang operasyon. Daan-daang ganitong kaso na ang nakita ko.“",
30: "Walang awa ang estadistika: sa 60% ng mga naoperahan, bumabalik ang herniation sa loob ng 2–4 na taon. At ang halaga? Buwan-buwang hindi makagalaw, daan-daang libong piso, at ganap na kawalang-katiyakan. Marami ang umaamin: kung maibabalik lang nila ang oras, hindi na sila hihiga sa mesa ng operasyon.",
31: "Ang mga sintomas na ito ay nangangahulugang namamatay na ang inyong kartilago! At kung lampas 40–50 anyos na kayo — hindi na maibabalik ang proseso kung walang gagawin!",
32: "— Sa loob ng 70 taon, mahigit 40,000 katao ang dumaan sa aking mga kamay at masasabi ko ito: bawat sakit ng kasukasuan na binabalewala ay isang hakbang patungo sa wheelchair. Noong",
33: "lamang ay naitala sa Pilipinas ang mahigit 2,200,000 bagong kaso ng malubhang sakit sa kasukasuan — at 400,000 dito ay sa mga taong 38 hanggang 48 anyos. Hindi ito problema ng katandaan. Problema ito ng kawalang-kilos.",
34: "Kung nagbigay na ang inyong katawan ng alinman sa mga senyas na ito — huwag nang maghintay kahit isang araw!",
35: "Narito ang listahang sinasabi ko sa bawat tao pagpasok pa lamang niya sa pintuan:",
36: "Paninigas sa umaga na hindi nawawala kahit gumalaw;",
37: "Lutong, kalog o langitngit kapag gumagalaw;",
38: "Lumalalang sakit kapag nagbabago ang panahon;",
39: "Hirap na iyuko o ituwid ang mga tuhod;",
40: "Pamamaga, pamumula o pag-init sa paligid ng kasukasuan;",
41: "Sakit kapag umaakyat o bumababa ng hagdan;",
42: "Pangmatagalang pagkapagod at bigat ng mga binti;",
43: "Sakit sa bewang na „kumikirot“ pababa sa hita o talampakan;",
44: "Pamamanhid o pangingimay ng mga daliri;",
45: "Pagbabago ng paglakad — pagkapilay, hindi matatag na tindig;",
46: "Hindi makatayo nang lampas 10–15 minuto;",
47: "Kung nakikilala ninyo ang sarili ninyo kahit sa dalawa lamang sa mga sintomas na ito — sinisira na ang inyong kartilago. At sa gulugod, tatlo hanggang apat na beses na mas mabilis ang proseso, dahil laging may diin sa mga disc.",
48: "ANG RESULTA: HERNIATION, NAIPIT NA UGAT, PAGKABALUKTOT NG MGA BUTO, PAGKAWALA NG KAKAYAHANG GUMALAW — AT ANG LAHAT NG ITO AY MAAARING MANGYARI SA LOOB NG ILANG LINGGO!",
49: "Huwag ipagpaliban, dahil hindi walang-hanggan ang pagkakataong ibinibigay ng katawan!",
50: "Tingnan ninyo ang mga taong nasa ibaba. Bawat isa sa kanila ay nagkaroon ng parehong sintomas na malamang ay nararamdaman ninyo ngayon. Bawat isa ay nagsabing „mawawala rin ito“. At bawat isa ngayon ay ibibigay ang kahit ano para maibalik ang oras at kumilos noong may pagkakataon pa.",
51: "Dating pasyente ng ibang klinika, 58 anyos, Davao. Tatlong buto ang lumihis nang mahigit 8 mm, may diin ang spinal cord. Dalawang beses siyang tumangging pumunta kay Lolo Ambrosio — nang sa wakas ay dumating siya, isang hakbang na lang siya sa pagkaparalisa.",
52: "Babae, 61 anyos, mula sa Iloilo — lumaki ang kanyang umbok sa likod nang 4 cm sa wala pang isang taon. Baluktot na ang mga buto sa leeg kaya hindi na maibaling ang ulo sa gilid. Walong buwan nang hindi na tumatalab ang mga pain reliever.",
53: "Maybahay, 59 anyos, Cagayan de Oro. Ubos na ubos na ang kasukasuan ng kanyang mga tuhod kaya numipis na ang kartilago sa wala pang 1 mm. Bawat hakbang ay parang langitngit ng lumang pinto. Sinabi ng tatlong orthopedic surgeon na ang tanging solusyon ay dobleng prosthesis, mahigit ₱400,000.",
54: "Dating minero, 68 anyos, Itogon, Benguet. Tuluyan nang nasira ang kartilago sa kanang tuhod, pumasok na sa yugto ng necrosis ang tisyu ng buto. Ang apat na buwang pagpapaliban ay nagkahalaga sa kanya ng kanyang binti — pinutol ito sa itaas ng tuhod at panghabambuhay na siyang nakadepende sa wheelchair.",
55: "Ako ay 102 anyos na at masasabi ko mula sa sarili kong karanasan: kayang-kaya ng katawan na magpanumbalik ng sarili sa KAHIT ANONG edad — basta't alam ninyo KUNG PAANO ito paganahin. Doon ko mismo inialay ang aking buhay.",
56: "AT KUNG LAMPAS 50–60 ANYOS NA KAYO, HUWAG NANG MAGHINTAY KAHIT ISANG SEGUNDO!",
57: "Sa inyo, halos tiyak na pumasok na sa kritikal na yugto ang pinsala — kailangang-kailangan nang ihinto ang pagkasira at simulan ang paglikha ng bagong kartilago, bagong buto at bagong tisyu!",
58: "Mga kasong ipinahayag na ng mga doktor na wala nang pag-asa!",
59: "Si Consolacion Rivera, sa edad na 86, ay muling nakalalakad nang walang tulong ng iba, matapos siyang tanggihan ng tatlong ospital. Narito ang kanyang kuwento…",
60: "Si Consolacion Rivera mula sa Naga ay dumaranas ng malubhang osteoarthritis sa tuhod at maraming herniated disc. Tinanggihan siya ng tatlong magkakaibang ospital — saanman ay iisa ang sinasabi sa kanya: „Sa edad ninyo, wala nang magagawa.“ Ang kanyang anak na babae ay nakarinig nang di-sinasadya tungkol kay Lolo Ambrosio mula sa mga kakilala sa isang bayang malapit sa Maynila at nagpasyang hanapin siya.",
61: "„Namuhay ako na parang nasa bilangguan — ang sarili kong bahay ay naging selda ko. Hindi ako makarating sa banyo, hindi ako makatayo nang lampas isang minuto, hindi man lang ako makapagtimpla ng kape para sa sarili ko. Nagtatrabaho ang mga anak ko at hindi sila makadalaw araw-araw. Nakahiga lang ako at nakatingin sa kisame. Sinabi ng mga doktor na wala nang saysay ang operasyon sa edad ko, at pain reliever lang ang ibinigay nila.",
62: "Nang dalhin ako ng anak ko kay Lolo Ambrosio, tiningnan niya ako at may sinabi siyang kailanman ay hindi sinabi sa akin ng kahit sinong doktor: „Aling Consolacion, HINDI pa tumitigil sa paglaban ang katawan ninyo. Walang tumulong dito, iyon lang.“ Ibinigay niya sa akin ang inihahanda niya mismo at sinabihan akong magtiis. Sa ikatlong linggo, sa unang pagkakataon sa loob ng isang taon at kalahati, TUMAYO AKO MAG-ISA mula sa kama!",
63: "Ngayon, limang buwan ang nakalipas, nakakapunta ako sa tindahan, nagluluto ako, inaalagaan ko pa nga ang halamanan sa harap ng bahay. Sa edad na 86! Nang makita ako ng mga kapitbahay sa bakuran, hindi sila makapaniwala. Akala nila hindi na nila ako makikitang muli. Ibinalik sa akin ni Lolo Ambrosio ang buhay ko — at wala akong salitang sapat para magpasalamat sa kanya.“",
64: "Consolacion Rivera, 86 anyos, Naga",
65: "Isa pang kakaibang kaso ay si Rogelio Baltazar — 47-anyos na mason mula sa Batangas, na matapos ang 20 taon ng mabigat na trabaho ay nagkaroon ng malubhang pinsala sa gulugod at napilitang gumamit ng wheelchair.",
66: "Sinubukan ni Rogelio ang paraan ni Lolo Ambrosio, at ang mga resulta ay ikinagulat maging ng sarili niyang doktor.",
67: "NAGSIMULANG GUMALING ANG KANYANG GULUGOD, TULUYANG NAWALA ANG SAKIT, AT ANG PINAKAKAHANGA-HANGA —",
68: "IWINAKSI NIYA ANG WHEELCHAIR PAGKATAPOS LAMANG NG 4 NA LINGGO!",
69: "Ikinuwento sa amin ni Rogelio:",
}
