# -*- coding: utf-8 -*-
# Philippines / herbolaryo, nodes 70..164 (anyo: KAPSULA)
P2 = {
70: "„Dalawampung taon akong nagtayo ng mga gusali, pero hindi ko inalagaan ang sarili kong gulugod. Isang umaga, nagising ako at hindi ko na maigalaw ang bewang ko. Tumawag ang asawa ko ng ambulansya. Ang diagnosis — tatlong herniation at naipit na ugat. Nag-alok ang mga doktor ng operasyong nagkakahalaga ng ₱250,000, pero walang garantiya.",
71: "Buwan-buwan akong nakaupo sa bahay sa wheelchair. Malungkot akong tinitingnan ng mga anak ko, umiiyak ang asawa ko tuwing gabi. Pakiramdam ko ay pabigat ako. Gusto ko na lang maglaho…",
72: "Noon nabalitaan ng biyenan ko si Lolo Ambrosio mula sa isang lalaking natulungan niya. Tumawag ako, ipinadala ko ang mga X-ray, at sinabi ng matanda: „Hindi pa huli.“ Ang tatlong salitang iyon ay nagbigay sa akin ng mas malaking pag-asa kaysa sa lahat ng narinig ko mula sa dose-dosenang doktor.",
73: "Sa ikaapat na araw ay nakatayo na ako. Ang buong kurso ay tumagal ng 80 araw. Ngayon ay nagtatrabaho na ako uli — hindi sa construction site kundi sa opisina, pero NAKALALAKAD AKO. Humahabol ako sa mga anak ko sa parke. Nabubuhay ako. Ipinapakita ng X-ray na 90% nang gumaling ang mga disc ko. Si Lolo Ambrosio lang ang hindi tumanggi sa akin — at siya lang ang tumulong.“",
74: "Kasing-kagulat-gulat ang mga kuwento ng libo-libong taong natulungan ni Lolo Ambrosio: mga taong sinabihan ng mga doktor na „masanay ka na lang sa sakit“ ay muling nakalakad, muling nakatakbo, muling nabuhay. Paanong nangyari iyon?",
75: "Ang pormulang inihanda ni Lolo Ambrosio gamit ang sarili niyang mga kamay sa loob ng mahigit 40 taon!",
76: "Ang lihim ng paraang „Endogenous Tissue Reactivation“ — paano nagsisimulang gumawa ang katawan mismo ng bagong kartilago, bagong buto at bagong litid!",
77: "— Hayaan ninyong ipaliwanag ko ang isang bagay na ayaw aminin ng karaniwang medisina. Ang katawan ng bawat tao — kahit ng isang 90-anyos — ay may mga „natutulog“ na selulang pampanumbalik. Ang mismong mga selulang noong kabataan ninyo ay walang hirap na bumubuo ng kartilago, buto at litid. Sa paglipas ng panahon ay hindi sila namamatay — „nakakatulog“ lamang sila, dahil tumitigil ang katawan sa pagpapadala sa kanila ng tamang senyas.",
78: "Apatnapung taon na ang nakalipas, natuklasan ko na ang isang tiyak na kombinasyon ng mga likas na sangkap — sa mahigpit na itinakdang sukat — ay gumagana bilang „susi ng pagpapaandar“ para sa mga natutulog na selulang iyon. Tinawag ko ang paraang ito na",
79: "„Endogenous Tissue Reactivation“",
80: "— dahil wala itong ipinapasok na artipisyal, kundi ginigising nito ang sariling yaman ng katawan. Iyan mismo ang dahilan kung bakit sa akin ay WALANG masamang epekto, WALANG pinsala sa mga organo at WALANG pagkalulong.",
81: "Apat na dekada kong ginamit ang paraang ito sa bawat taong tumatawid sa aking pintuan — at sa bawat isa ay iisa ang naitala kong resulta: humihinto ang pagkasira, bumababa ang sakit, at unti-unting bumabalik ang paggana ng mga kasukasuan. Daan-daang taong dumarating sa akin bilang „huling pag-asa“ ang lumalabas sa bahay ko na naglalakad sa sarili nilang mga paa.",
82: "Ang pormula mismo ay hindi kumplikado — pero ang katumpakan ang lahat. Ang bawat sangkap ay dapat nasa eksaktong dami, hanggang sa ikasandaang bahagi ng milligram. Kapag hindi nasunod ang sukat, basta na lang nawawala ang bisa. Iyan mismo ang dahilan kung bakit sa loob ng mga dekada ay ako mismo ang gumagawa nito — dahil hindi ko ito maipagkakatiwala sa mga botika.",
83: "Komposisyon ng kapsula ayon sa resipe ng herbolaryong Dimalanta (mga aktibong sangkap kada dosis):",
84: "Omega-3",
85: "buto ng flax: 4500 mg",
86: "Glucosamine sulfate",
87: "crustacean: 1100 mg",
88: "Magnesium citrate",
89: "damong-dagat: 390 mg",
90: "Gingerol",
91: "luya: extract 4200 mg",
92: "AKBA",
93: "dagta ng insenso (Boswellia): extract 1100 mg",
94: "Silicon",
95: "horsetail: extract 320 mg",
96: "Curcumin",
97: "luyang dilaw: extract 2300 mg",
98: "Mukhang simple ang mga sangkap na ito, pero napakahirap hanapin ang mga ito sa tamang kalidad at mula sa tamang pinagmulan. Karamihan ay wala sa botika at kailangang dalhin mula sa iba't ibang panig ng mundo. Ang paghahalo naman sa bahay ay halos imposible — dahil ang pagsukat ay dapat eksakto hanggang 0.1 mg.",
99: "Iyan mismo ang dahilan kung bakit sa loob ng mga dekada ay ako mismo ang naghahanda ng halo, para sa bawat tao nang isa-isa. Ngunit nakita ng anak kong si Ramon ang buong larawan.",
100: "Paano ginawa ni Ramon Dimalanta ang 40-taong resipe ng kanyang ama na maging kapsulang abot-kaya ng lahat — Nautubone",
101: "Ramon Dimalanta:",
102: "— Lumaki ako sa silid ng mga halaman ng tatay ko. Araw-araw kong nakikita ang mga taong pumapasok na nakabaluktot sa sakit — at lumalabas na nakangiti. Sa edad na 14 ay kabisado ko na ang resipe. Hindi ako naging doktor — sa kanya ko natutunan ang hanapbuhay na ito. Pero sa loob ng maraming taon ay kinukumbinsi ko siya: Tay, hindi puwedeng manatili ang resipeng ito sa iisang bahay lang. Libo-libong tao ang naghihintay sa itinatago mo sa istante.",
103: "Limang taon akong umikot sa mga laboratoryo sa Maynila at Munich hanggang sa makahanap ako ng mga taong seryosong nais pag-aralan ang pormula ng tatay ko. Ang sagot na natanggap ko ay ikinatuwa ko: ang kombinasyon ng mga sangkap na ito sa eksaktong sukat ay nagpapagana sa paglikha ng type II collagen at proteoglycans — ang dalawang pangunahing materyales sa pagbuo ng kartilago. Sa madaling salita: literal na „naaalala“ ng katawan kung paano bumuo ng bagong kartilago, kailangan lang nito ng tamang senyas.",
104: "Kasama ang laboratoryo, bumuo kami ng prosesong tinawag naming",
105: "„Nanodiffusion Technology na may Advanced Bioavailability“",
106: "— isang paraan kung saan ang mga aktibong sangkap ay nakabalot sa espesyal na nanoparticles, na inilalabas nang diretso sa maliit na bituka, nilalampasan ang metabolismo sa atay, at dumadaloy sa dugo patungo mismo sa nasirang tisyu ng kasukasuan. Pinapataas nito ang pagsipsip nang mga 380% kumpara sa karaniwang tableta. Tinawag ko ang produkto na",
107: "Nautubone",
108: "— isang kapsulang iniinom at gumagana mismo doon kung saan ito kailangan. Ipinangalan ko ito bilang parangal sa aking ama at sa 40 taon ng kanyang trabaho.",
109: "Ang kapsulang Nautubone ay naglalaman ng lahat ng pitong sangkap ng orihinal na resipe ng tatay ko, kasama ang 29 pang extract at bitamina na idinagdag namin matapos ang pagsusuri sa laboratoryo sa Munich. Ang resulta ay isang produktong GUMAGANA NANG KASINGHUSAY ng inihahanda mismo ng tatay ko — pero maihahatid sa bawat tahanan sa Pilipinas. Uminom kayo ng isang kapsula dalawang beses sa isang araw, at ang mga aktibong sangkap ay dadaloy sa dugo diretso patungo sa mga apektadong kasukasuan.",
110: "„Ang Nautubone ay pamana ng tatay ko — ang 40 taon ng kanyang karanasan na nakabalot sa iisang pormula. Bawat sangkap ay pinili nang may parehong katumpakan na ginamit niya sa bawat taong kumatok sa kanyang pinto. Hindi ito produktong pangmasa mula sa istante ng botika — ito ay gawa ng isang buong buhay na inialay sa pagpapagaling.“",
111: "Ang pinakakahanga-hanga sa Nautubone ay hindi lamang nito pinapawi ang sakit — ginigising nito ang mekanismo ng pagpapanumbalik na natulog sa paglipas ng panahon. Iniinom ang kapsula, at dinadala ng nanoparticles ang mga aktibong sangkap nang malalim sa tisyu ng kasukasuan — doon kung saan hindi kailanman nakakarating ang mga ordinaryong cream at gel. Ang pagtutulungan ng mga sangkap ay nagpapalakas ng epekto nang hanggang 20 beses kumpara sa hiwa-hiwalay na pag-inom.",
112: "Ang apat na yugto ng paggaling gamit ang Nautubone — kung ano ang nangyayari sa katawan ninyo hakbang-hakbang",
113: "— Sa buong buhay ko bilang herbolaryo, pinanood ko ang mga tao na dumaan sa parehong apat na yugto. Idinokumento ito ng anak ko at isinama sa Nautubone, para madaanan ito ng kahit sino sa sarili nilang tahanan.",
114: "Ang apat na yugto ng „Endogenous Tissue Reactivation“:",
115: "Yugto 1 — Pagpigil sa sakit at pamamaga:",
116: "Mula pa lamang sa unang kapsula, inilalabas ng nanoparticles ang mga aktibong sangkap sa bituka at dinadala ito sa dugo diretso sa mga nasirang tisyu, na hinaharangan ang mga molekula ng pamamaga. Kapansin-pansing bumababa ang sakit sa loob ng 24–48 oras — nang hindi binibigatan ang atay at bato, dahil ang mikrokapsula ay may enteric coating at nilalampasan nito ang karaniwang metabolismo sa atay.",
117: "Yugto 2 — Pagpigil sa pagkasira:",
118: "Sa pagitan ng ikatlo at ikapitong araw, tumitigil ang katawan sa pagsira ng tisyu ng kartilago at buto. Tumataas ang paggawa ng synovial fluid — ang likas na „pampadulas“ ng mga kasukasuan. Bumababa ang pagkuskos at gumagaan ang paggalaw.",
119: "Yugto 3 — Paggising sa mga selulang pampanumbalik:",
120: "Ito ang puso ng paraang ito. Ang „natutulog“ na chondrocytes at osteoblasts ay tumatanggap ng senyas na biochemical at nagsisimulang gumawa ng bagong kartilago at bagong tisyu ng buto. Ang yugtong ito mismo ang gumagawa sa Nautubone na natatangi — walang ibang produktong nagpapaandar ng mekanismong ito.",
121: "Yugto 4 — Matibay na pananggalang:",
122: "Pagkatapos ng 30–60 araw, ang mga bagong nabuong tisyu ay bumubuo ng matibay na proteksiyon, na nagpapatibay sa mga kasukasuan kahit sa mabigat na gamit. Tinatawag ito ni Lolo Ambrosio na „immunity ng kasukasuan“ — kapag nakamit na ito, tumatagal ang epekto nang maraming taon.",
123: "Ang bawat isa sa mga yugtong ito ay bunga ng 40 taong karanasan ng iisang tao at 5 taong pagsusuri sa laboratoryo. Hindi nag-aalok ang Nautubone ng mabilisang „pagtatakip“ sa sakit — sinisimulan nito ang malalim at biyolohikal na proseso ng pagpapanumbalik, na nagbabalik sa mga kasukasuan sa kalagayang mayroon sila mga dekada na ang nakalipas.",
124: "Mga resultang ikinagulat ng komunidad medikal — pagsubaybay sa 2,340 katao na may edad 38 hanggang 89",
125: "— Nang ilathala namin ang unang resulta ng mga pagsusuri sa laboratoryo, mabilis ang naging reaksiyon. Humiling ang mga unibersidad-ospital mula sa Maynila, Berlin at Vienna na makapagsagawa ng sarili nilang pananaliksik. Ang mga resulta sa tunay na tao ay lumampas pa sa aming inaasahan — wala ni isa sa mga umiiral na paraan ng paggamot ang nakakalapit sa mga bilang na ito.",
126: "Mga taong nakatakda nang lagyan ng artipisyal na kasukasuan ay kinansela ang kanilang operasyon. Mga taong buwan nang hindi makabangon sa kama ay muling nakalakad. Hindi makapaniwala ang mga orthopedic surgeon sa sarili nilang X-ray.",
127: "Mga resulta ng pagsubaybay sa „Nautubone“ sa 2,340 katao na may edad 38 hanggang 89",
128: "Ganap na pagkawala ng sakit at pamamaga",
129: "Pagbalik ng buong saklaw ng paggalaw",
130: "Tendinitis, bursitis, periarthritis",
131: "Paghinto at pag-urong ng mga pagbabagong degeneratibo",
132: "Synovitis, ligamentitis",
133: "Osteoarthritis (lahat ng yugto)",
134: "Osteoporosis",
135: "Rheumatoid arthritis, gout",
136: "Osteoarthritis, spondyloarthritis",
137: "Dokumentadong pagpapanumbalik ng tisyu ng kartilago",
138: "Tumpak na tagal ng paggaling gamit ang „Nautubone“:",
139: "Sinusubukan ng ibang siyentipikong grupo sa Europa na kopyahin ang aming pormula, pero malayo pa rin sa amin ang mga resulta nila hanggang ngayon. Ang Nanodiffusion Technology na may Advanced Bioavailability, na binuo kasama ang aming laboratoryo, ay hindi pa rin nagagaya — dahil ito mismo ang nagbibigay-daan sa kapsula na ihatid ang mga sangkap diretso sa loob ng kasukasuan sa pamamagitan ng dugo, sa halip na manatili lamang sa ibabaw ng balat, tulad ng mga pamahid.",
140: "Gaano katagal bago ganap na gumaling? Ipinapaliwanag ni Lolo Ambrosio batay sa 70 taong karanasan",
141: "— Ang pinakamaikling kursong inirerekomenda ko ay 30 araw. Sa mas malubhang pinsala — 60, at kung minsan ay 90 araw. Pero sa buong karera ko ay WALA NI ISANG KASO na hindi nagbunga ang paraang ito. Wala ni isa. At nakagamot na ako ng mga taong 85, 90, at maging 94 anyos.",
142: "Hindi lamang pinipigil ng Nautubone ang sakit — sinisimulan nito ang malalim na biyolohikal na pagpapanumbalik. Uminom ng isang kapsula dalawang beses sa isang araw at sa mga unang oras pa lamang ay makakaramdam na kayo ng ginhawa. Sa loob ng isang linggo ay mapapansin ninyong mas magaan na kayong gumalaw. At pagkatapos ng buong kurso, ang inyong mga kasukasuan ay babalik sa kalagayan nila noong 20–30 taon na ang nakalipas.",
143: "Pero may isa pang mas mahalaga: PANGMATAGALAN ang epekto. Kapag „nagising“ na ang mga selulang pampanumbalik, patuloy silang gagana sa loob ng maraming taon!",
144: "Salamat sa „Nautubone“, mahigit 330,000 katao sa Pilipinas ang nakabawi ng kanilang kakayahang gumalaw. Narito ang maliit na bahagi lamang ng mga natulungan ni Lolo Ambrosio:",
145: "Retirado, 66 anyos, Tarlac. Apat na butong lumihis at pangmatagalang radiculopathy. Ang anak niyang lalaki ang nagdadala sa kanya ng kapsulang Nautubone mula sa Maynila. Dalawang buwang pag-inom — ganap na bumalik sa normal na posisyon ang gulugod. Hiningi ng kanyang orthopedic surgeon ang pangalan ng produkto.",
146: "Bookkeeper, 41 anyos, Dumaguete. Baluktot papasok ang kanyang mga tuhod matapos ang dalawang panganganak at pagtaba. Sinabi ng orthopedic surgeon na „masanay ka na lang“. Sa kapsulang Nautubone — 30 araw na pag-inom, dalawang beses araw-araw — kapansin-pansing tumuwid ang linya ng mga tuhod sa X-ray.",
147: "Retirado, 73 anyos, Zamboanga. Baluktot na ng osteoarthritis ang mga daliri ng kanyang paa kaya wala nang sapatos na kasya sa kanya. Umiinom siya ng kapsulang Nautubone araw-araw — sa loob ng 21 araw ay tumuwid ang mga daliri, at kasya na sa kanya muli ang sapatos niya noong 5 taon na ang nakalipas.",
148: "— Ang mga larawang ito ay hindi himala — kalikasan at pagtitiis ang mga ito. Bawat isa sa mga taong ito ay nakabawi ng isang bagay na sinabi ng mga doktor na imposible: malulusog na kasukasuan at buhay na walang sakit. Ang Nautubone AY KORONA NG BUONG BUHAY KO BILANG HERBOLARYO — AT PAMANA KO SA MGA SUSUNOD NA HENERASYON!",
149: "Bakit hindi na tumatanggap ng tao si Lolo Ambrosio — at paano naging tanging daan ang Nautubone patungo sa kanyang resipe",
150: "„Hindi na ako pinapayagan ng kalusugan ko na tumanggap ng may sakit nang personal. Pero magpapatuloy ang pormula ko sa pagpapagaling — sa pamamagitan ng mga kamay ng anak ko.“",
151: "— Noong nakaraang taon ay ginawa ko ang pinakamahirap na desisyon sa buhay ko: hindi na tumanggap ng mga tao. Mahigit 2,000 pangalan ang nasa listahan ng naghihintay — at hindi ko sila maaaring iwang walang tulong. Kaya pinayagan ko ang anak kong si Ramon na dalhin ang resipe doon kung saan gagawin ito para sa lahat. Ngayon ay panatag na ako — ang Nautubone ay eksaktong iyon mismo ang ibinibigay ko sa mga taong dumarating sa akin, nasa maginhawang anyo lamang. Nasa mabuting kamay ang resipe.",
152: "— Hindi ibinebenta ang Nautubone sa mga botika — kumplikado ang proseso ng paggawa at limitado ang dami. Makukuha lamang ito sa pamamagitan ng online na programa, dalawang beses sa isang taon. Pero sa loob ng programa, umaabot ang diskuwento sa",
153: "— dahil hindi tubo ang layunin namin, kundi ang maabot ito ng lahat. Lalo na ng mga senior citizen, na iginiit ng tatay ko na dapat makakuha ng pinakamalaking diskuwento.",
154: "Para makapagparehistro, gamitin ang opisyal na order form sa ibaba — direkta itong nagmumula sa production team ni Ramon Dimalanta.",
155: "Huwag palampasin ang huling pagkakataon ngayong taon — maaaring maubos ang Nautubone bago matapos ang programa!",
156: "— Ngayong taon ay nakagawa kami ng 5&nbsp;000 kahon ng kapsulang Nautubone lalo na para sa mga taga-Pilipinas. Pero dahil sa napakalaking demand, mabilis na mauubos ang dami na ito. Ang susunod na batch ay magiging handa lamang sa pagtatapos ng",
157: "Aktibo ang programa ng suporta hanggang",
158: "— bawat residente ng Pilipinas na lampas 40 anyos ay maaaring makakuha ng",
159: "hanggang 50% diskuwento",
160: ". Pagkatapos ng petsang ito, kakailanganin ninyong maghintay ng hindi bababa sa 6 na buwan para sa bagong pagkakataon.",
161: "Huwag ipagpaliban. Lagi kong sinasabi ng tatay ko sa mga tao: „Hindi kayo hinihintay ng mga kasukasuan ninyo — nasisira sila bawat segundo.“ Habang aktibo ang programa, samantalahin ninyo ito. May kumukulektang epekto ang Nautubone — isang buong kurso lamang ay sapat na para sa 5–6 taon ng malulusog na kasukasuan.",
162: "Isulat lamang ang inyong pangalan at numero ng telepono sa form. Tatawagan kayo ng konsultant, gagawa siya ng indibidwal na programa para sa inyong kaso at aayusin ang paghahatid sa kahit anong address sa Pilipinas — sa loob ng 2–3 araw, sa pamamagitan ng koreo o courier hanggang sa inyong pintuan.",
163: "Kalusugan ang hinihiling ko para sa inyong lahat! Alagaan ninyo ang inyong mga kasukasuan ngayon, para makalakad pa kayo bukas! Nang buong paggalang: Ambrosio Dimalanta at ang kanyang anak na si Ramon.",
164: "Na-update noong:",
}
