# -*- coding: utf-8 -*-
# Philippines / herbolaryo, nodes 165..236 + attrs (anyo: KAPSULA)
P3 = {
165: "Dahil sa napakalaking demand, maaaring maubos ang stock ng Nautubone bago pa matapos ang nakatakdang programa! Ngayong araw —",
166: "18/12/2025 — ang huling araw para makapag-order nang may diskuwento",
167: "o hanggang maubos ang stock.",
168: "Babala! Huwag isara o i-refresh ang page — ang kapsulang Nautubone na nakareserba para sa inyo ay ibibigay sa susunod na tao sa listahan ng naghihintay!",
169: "Ang inyong nakareserbang puwesto sa programa:",
170: "Opisyal na order form",
171: "Para makuha ang",
172: "50% diskuwento",
173: ", isulat ang inyong pangalan at numero ng telepono sa mga kahon sa ibaba at pindutin ang butones na „MAG-ORDER“.",
174: "Natitirang stock:",
175: "₱1,890",
176: "₱945",
177: "Pangalan",
178: "Numero ng telepono",
179: "MAG-ORDER",
180: "✔️ Paghahatid sa kahit anong address sa Pilipinas sa loob ng 2–3 araw",
181: "sa pamamagitan ng koreo o courier hanggang sa inyong pintuan",
182: "MGA KOMENTO:",
183: "Marilou Santos",
184: "Ilang buwan kong hinintay ang artikulong ito! May kaibigan ako sa Maynila na personal na nagpunta kay Lolo Ambrosio ilang taon na ang nakalipas — sabi niya hindi raw ito ordinaryong tao, himala ito. Sayang at hindi na siya tumatanggap ng pasyente, pero kung pareho ang resipe ng Nautubone — mag-o-order na ako ngayon din. Buti na lang naabutan ko ang diskuwento!",
185: "Estrella Bautista",
186: "Dinala ito ng courier noong Miyerkules. Sampung araw na akong umiinom ng kapsula tuwing umaga at gabi — at MALAKI ang pinagbago! Bumabangon na ako nang wala na iyong nakakatakot na lutong! Nakatingin lang ang asawa ko at hindi makapaniwala. Tatapusin ko ang buong 60-araw na kurso, pero kumbinsido na ako ngayon pa lang na epektibo ito.",
187: "Nenita Cruz",
188: "72 anyos na ako at tatlong taon akong nagdusa sa sakit ng balakang. Parusa ang paglakad. Sabi ng orthopedic surgeon: „Prosthesis o tiisin mo.“ Ayaw ko sa dalawa. Natulungan ako ng Nautubone sa loob ng dalawang buwan — ngayon ay isa't kalahating kilometro ang nilalakad ko araw-araw! At ipinapakita ng X-ray ang pagbuting hindi maipaliwanag ng doktor ko. Salamat po, Lolo Ambrosio, at salamat din sa anak ninyo!",
189: "Rodolfo Aquino",
190: "Bilang dating atleta, alam ko kung ano ang mabuhay na wasak na ang kartilago. Parang sa 90-anyos na ang tuhod ko — samantalang 54 pa lang ako. Ibinalik sa akin ng Nautubone ang mga galaw na hindi ko na nagagawa sa loob ng 10 taon. Nakakaupo na ako uli nang nakabaluktot! Wala akong ibang alam na produktong kayang gawin ito.",
191: "Lourdes Aquino",
192: "Medyo kinakabahan ako… Sulit ba ito? 66 anyos na ako, lumalutong ang mga kasukasuan ko sa bawat galaw at hindi ako tinatantanan ng sakit ng likod. Pero napakadalas na akong nabigo sa iba't ibang „milagrosong“ gamot kaya mahirap na akong maniwala. Talaga bang nakakatulong ito?",
193: "Efren Villanueva",
194: "Aling Lourdes, lubos kong naiintindihan ang pag-aalinlangan ninyo — nagkaroon din ako niyan. Pero iba ang Nautubone sa lahat ng nasubukan ko na. Limang linggo ko nang iniinom para sa tuhod at bewang — at masasabi kong parang araw at gabi ang pinagkaiba.",
195: "Dati ay hindi ako makayuko para itali ang sintas ng sapatos ko. Ngayon ay nagagawa ko na ito nang hindi nag-iisip. Mag-order kayo kahit isang kahon at kayo mismo ang humusga — wala kayong mawawala!",
196: "Corazon Reyes",
197: "Tatlong araw matapos akong magsimulang uminom ng kapsula, kalahati na lang ang sakit ng tuhod ko! Ika-12 araw na ngayon at umaakyat na ako ng hagdan nang hindi humahawak sa railing. Tatapusin ko ang buong kurso — sa tingin ko pagkatapos ng dalawang buwan ay parang bago na ako!",
198: "Jocelyn Mendoza",
199: "May „umbok“ na nagsimulang lumaki sa likod ko mga dalawang buwan na ang nakalipas. Kinabahan ako nang husto! Sinubukan ko ang iba't ibang pamahid sa botika — wala. Pero ibang-iba ang kapsulang Nautubone — sa loob ng 40 araw ay halos tuluyan nang nawala ang umbok! Patuloy pa rin akong umiinom, pero sobrang saya ko na ngayon. Ganito ang pinagkaiba:",
200: "Perlita Garcia",
201: "May naipit akong ugat sa bewang — dahil sa sakit ay hindi ako makatulog ni makatayo. Binigyan ako ng doktor ng malakas na pain reliever na palagi akong pinapahilo. Nagsimula akong uminom ng kapsulang Nautubone dalawang beses sa isang araw — pagkalipas ng isang linggo ay biglang bumaba ang sakit, at pagkatapos ng isang buwan — tuluyan na itong nawala! Ipinagpapatuloy ko pa ang kurso, pero nagbago na ang buhay ko!",
202: "Danilo Ocampo",
203: "79 anyos na ako at sa loob ng tatlong taon ay halos hindi na ako makalakad. Nag-order ang anak ko ng Nautubone — hindi man lang ako tinanong, dahil alam niyang tatanggi ako. Binibigay niya sa akin ang kapsula tuwing umaga at tuwing gabi. At ang resulta? Pagkalipas ng isa't kalahating buwan ay naglalakad ako papuntang parke araw-araw! Pakiramdam ko ay 60 anyos lang ako! Salamat po, Lolo Ambrosio — sa edad na 102 ay mas marunong pa kayo sa lahat ng doktor ngayon!",
204: "Teodoro Ramos",
205: "Bago ang Nautubone ay hindi ko maitaas ang mga braso ko sa ibabaw ng ulo — lumulutong ang balikat ko at sobrang sakit. Dalawang taon akong nagpalipat-lipat ng doktor — walang nakatulong. Dalawang buwan sa Nautubone at normal nang gumagana ang mga braso ko. Narito ang X-ray ko — hindi makapaniwala maging ang doktor mismo:",
206: "Adelaida Torres",
207: "Nag-order ako para sa biyenan ko — 81 anyos na siya at halos hindi na makabangon sa kama. Tumatanggi ang mga doktor na gumawa ng kahit ano — „sa edad na iyan ay wala nang nakakatulong“, sabi nila. Sa Nautubone, sa loob ng 2 buwan ay naglalakad na siya sa bakuran at nagluluto pa nga! Hindi kami makapaniwala.",
208: "Eduardo Fernandez",
209: "Apat na buwang nakahiga ang asawa ko — basta na lang sumuko ang gulugod niya. Nag-alok ang mga doktor ng operasyong nagkakahalaga ng ₱320,000 nang walang anumang garantiya. Nagpasya kaming subukan ang kapsulang Nautubone — wala na kaming mawawala. Binibigay ko sa kanya dalawang beses sa isang araw. Pagkatapos ng 5 linggo ay nakabangon siya. Kahapon ay sabay kaming pumunta sa palengke — sa unang pagkakataon sa loob ng kalahating taon! Umiyak ako sa tuwa.",
210: "Nida Bernardo",
211: "Nag-order ako noong isang linggo, natanggap ko sa ikatlong araw. Agad akong nagsimulang uminom ng kapsula — at dumating ang ginhawa sa ikalawang araw! Para bang may nagpapadulas sa mga kasukasuan ko mula sa loob. Dalawang linggo na akong umiinom nang dalawang beses araw-araw at hindi na ako makapaghintay sa buong resulta!",
212: "Rosario Del Rosario",
213: "74 anyos na ako. Limang taon akong nagdusa sa osteoarthritis at sakit ng likod. Literal na sinubukan ko ang lahat — pamahid, tableta, iniksiyon, physical therapy. WALA ni isang nakatulong nang pangmatagalan. Ang kapsulang Nautubone lang ang nagbigay sa akin ng TUNAY NA RESULTA — umiinom ako dalawang beses sa isang araw at sa loob ng isa't kalahating buwan ay ibang-iba na ang pakiramdam ng mga kasukasuan ko. Hindi makapaniwala ang doktor sa mga X-ray!",
214: "Virginia Domingo",
215: "Personal kong kilala si Lolo Ambrosio — 12 taon na ang nakalipas ay tinulungan niya ako sa herniated disc. Sa loob ng tatlong linggo ay nakatayo na ako uli! Kilala ang pangalan niya sa buong paligid ng Maynila. Masaya ako at ipinagpapatuloy ng anak niya ang kanyang gawain!",
216: "Gloria Pascual",
217: "84 anyos na ang tatay ko at tatlong taon siyang hindi lumalabas ng bahay. Ang mga kasukasuan, ang likod, ang tuhod — masakit ang lahat sa kanya. Sabi niya ay naghihintay na lang siyang mawala. Pagkatapos ng dalawang buwan sa Nautubone — kahapon ay lumabas siya sa bakuran at nagdilig ng halaman! Sa unang pagkakataon sa loob ng tatlong taon! Hindi ko mailarawan ang naramdaman ko. Maraming-maraming salamat po!!!",
218: "Milagros Enriquez",
219: "May nakakaalam ba kung puwede ba itong gamitin kapag maraming allergy? Halos sa lahat ako nagre-react — kahit sa ordinaryong aspirin ay namamaga ang mga daliri ko. Natatakot akong sumubok ng bago…",
220: "Arturo Salvador",
221: "Aling Milagros, ako ay allergic sa apat na uri ng gamot. Limampung araw na akong umiinom ng kapsulang Nautubone — walang pangangati, walang pamamaga, walang pamumula. Puro likas na extract ang komposisyon — walang kemikal. Puwede kayong mag-order nang panatag ang loob!",
222: "Dolores Navarro",
223: "Dati ay wala akong lakas na bumangon — parusa ang bawat galaw, akala ko tapos na ang buhay ko. Nag-order ang anak kong babae ng kapsulang Nautubone at pinilit akong subukan — siya ang nagbibigay nito sa akin tuwing umaga at gabi. Dalawang buwan ang lumipas? Sumayaw ako sa kasal ng apo ko!!! Kailanman sa buhay ko ay hindi pa ako naging ganito kalaki ang pasasalamat!",
224: "Elizabeth Lim",
225: "Nag-order ako para sa nanay ko. Palagi siyang sinasaktan ng batok na nagdudulot sa kanya ng pagkahilo at pagduduwal — naging hindi na matiis ang buhay niya. Sa ikalawang linggo sa Nautubone ay malaki ang ibinaba ng sakit, at tuluyang tumigil ang pagkahilo! Tumatawa na uli si Nanay — matagal ko na siyang hindi nakitang ganoon.",
226: "Susana Manalo",
227: "Nagtataka ako — kung napakagaling ni Lolo Ambrosio, bakit hindi ito ibinebenta kahit saan? Bakit online lang? Bakit hindi ito inaalok ng mga botika?",
228: "Miguel Padilla",
229: "Dahil kumikita ang mga botika sa mga taong bumibili ng pain reliever buwan-buwan! Kung magpapagaling ang lahat ng kasukasuan nila nang minsanan at tuluyan — sino pa ang bibili ng mamahaling gamot nila? Mag-isip kayo nang lohikal!",
230: "Olivia Sarmiento",
231: "Binasa ko lahat ng komento — at naantig ako. Mag-o-order na ako ngayon, para sa akin at para sa asawa ko. Kumuha ako ng tatlong kahon ng kapsula, para sa buong kurso. Kung makakatulong lang ito kahit kalahati ng isinusulat ng mga tao — masaya na ako!",
232: "Lucia Mercado",
233: "Sinabi sa akin ng orthopedic surgeon ko na sa edad na 63 ay dapat masanay na lang ako sa sakit — na wala raw lunas. Nag-order ako ng Nautubone kahit ano pa ang sabihin nila. Tingnan natin kung sino ang tama!",
234: "Mag-upload ng avatar",
235: "Mag-upload ng larawan",
236: "IPADALA",
}
ATTRS_P = {
 "Вашето име": "Ang pangalan ninyo",
 "Вашият телефонен номер": "Ang numero ng telepono ninyo",
 "Вашият коментар": "Ang komento ninyo",
}
