# -*- coding: utf-8 -*-
# El Salvador / yerbatero (forma: GEL)
S3 = {
165: "¡Debido a la demanda extremadamente alta, las existencias de Nautubone pueden agotarse antes del final previsto del programa! Hoy —",
166: "18/12/2025 — es el último día para pedir con descuento",
167: "o hasta agotar existencias.",
168: "¡Atención! No cierre ni actualice la página — ¡el gel Nautubone reservado para usted será ofrecido a la siguiente persona de la lista de espera!",
169: "Su lugar reservado en el programa:",
170: "Formulario oficial de pedido",
171: "Para obtener el",
172: "50% de descuento",
173: ", escriba su nombre y su número de teléfono en los campos de abajo y presione el botón „PEDIR“.",
174: "Existencias restantes:",
175: "$79",
176: "$39",
177: "Nombre",
178: "Número de teléfono",
179: "PEDIR",
180: "✔️ Entrega a cualquier dirección de El Salvador en 2 a 3 días",
181: "por correo o con mensajero hasta su puerta",
182: "COMENTARIOS:",
183: "Blanca Menjívar",
184: "¡Meses enteros esperé este artículo! Una amiga de San Salvador estuvo personalmente donde don Marcelino hace unos años — decía que es un milagro de hombre. Lástima que ya no reciba gente, pero si Nautubone tiene la misma receta — pido ahora mismo. ¡Qué bueno que alcancé el descuento!",
185: "Reina Guzmán",
186: "El mensajero me lo trajo el miércoles. Llevo diez días aplicándome el gel mañana y noche — ¡y la diferencia es ENORME! ¡Me levanto sin ese crujido horrible! Mi marido mira y no lo cree. Voy a hacer el tratamiento completo de 60 días, pero ya estoy convencida de que funciona.",
187: "Marta Escobar",
188: "Tengo 72 años y tres años sufrí de dolor en la cadera. Caminar era un martirio. El ortopedista dijo: „Prótesis o aguante.“ No quería ni lo uno ni lo otro. Nautubone me ayudó en dos meses — ¡ahora camino un kilómetro y medio todos los días! Y la radiografía muestra una mejora que mi médico no sabe explicar. ¡Gracias, don Marcelino, y gracias a su hijo!",
189: "Salvador Chicas",
190: "Como exdeportista sé lo que significa vivir con el cartílago destruido. Tenía las rodillas de un hombre de 90 años — y apenas tengo 54. Nautubone me devolvió movimientos que no hacía desde hace 10 años. ¡Puedo volver a ponerme en cuclillas! No conozco otro producto capaz de lograr algo así.",
191: "Dinora Chicas",
192: "Estoy un poco preocupada… ¿Vale la pena? Tengo 66 años, las articulaciones me crujen con cada movimiento y la espalda no me da tregua. Pero me he decepcionado tantas veces con toda clase de remedios „milagrosos“ que ya me cuesta creer. ¿De verdad ayuda?",
193: "Óscar Quintanilla",
194: "Doña Dinora, entiendo perfectamente sus dudas — yo también las tenía. Pero Nautubone es distinto a todo lo que probé hasta ahora. Lo uso desde hace 5 semanas para las rodillas y la cintura — y le puedo decir que la diferencia es como del día a la noche.",
195: "Antes no podía agacharme a amarrarme los cordones. Ahora lo hago sin pensarlo. Pida aunque sea un envase y juzgue usted misma — ¡no tiene nada que perder!",
196: "Karla Melara",
197: "¡Tres días después de empezar a aplicarme el gel, el dolor de la rodilla se me redujo a la mitad! Hoy es el día 12 y ya subo las gradas sin agarrarme del pasamanos. Voy a completar todo el tratamiento — ¡creo que en dos meses voy a estar como nueva!",
198: "Yesenia Sorto",
199: "En la espalda me empezó a crecer una „joroba“ hace unos dos meses. ¡Me horroricé! Probé toda clase de pomadas de farmacia — nada. Pero el gel Nautubone es otra cosa completamente distinta — ¡en 40 días la joroba desapareció casi por completo! Sigo aplicándomelo, pero ya estoy increíblemente contenta. Así se ve la diferencia:",
200: "Morena Rivas",
201: "Tenía un nervio comprimido en la cintura — del dolor no podía ni dormir ni estar de pie. El médico me recetó analgésicos fuertes que me tenían mal todo el tiempo. Empecé a aplicarme el gel Nautubone dos veces al día — ¡después de una semana el dolor bajó de golpe, y al mes desapareció por completo! Sigo con el tratamiento, ¡pero mi vida ya cambió!",
202: "Ovidio Hernández",
203: "Tengo 79 años y tres años apenas caminaba. Mi hijo pidió Nautubone — sin preguntarme, porque sabía que yo me iba a negar. Me aplica el gel todas las mañanas y todas las noches. ¿Y el resultado? ¡Después de un mes y medio camino hasta el parque todos los días! ¡Me siento de 60! Gracias, don Marcelino — ¡a los 102 años es usted más sabio que todos los médicos de hoy!",
204: "Tránsito Ayala",
205: "Antes de Nautubone no podía levantar los brazos por encima de la cabeza — el hombro me crujía y me dolía horrible. Dos años anduve de médico en médico — nadie me ayudó. Dos meses con Nautubone y mis brazos vuelven a funcionar normalmente. Esta es mi radiografía — ni el propio médico lo creyó:",
206: "Ana Gladis Cruz",
207: "Pedí para mi suegra — tiene 81 años y casi no podía levantarse de la cama. Los médicos se negaban a hacer cualquier cosa — „a esta edad ya nada ayuda“, decían. ¡Con Nautubone, en 2 meses ya camina por el patio e incluso cocina! No lo podíamos creer.",
208: "Edwin Menéndez",
209: "Mi esposa estuvo cuatro meses en cama — la columna simplemente cedió. Los médicos propusieron una operación de 6 000 dólares sin ninguna garantía. Decidimos probar el gel Nautubone — no teníamos nada que perder. Se lo aplicaba dos veces al día. Después de 5 semanas se levantó. ¡Ayer fuimos juntos al mercado — por primera vez en medio año! Lloré de felicidad.",
210: "Nubia Peña",
211: "Pedí la semana pasada, me llegó al tercer día. Empecé a aplicarme el gel enseguida — ¡y el alivio llegó al segundo día! Es como si alguien me engrasara las articulaciones por dentro. Llevo dos semanas aplicándomelo dos veces al día y ya no aguanto las ganas de ver el resultado completo.",
212: "Rosa Amelia Flores",
213: "Tengo 74 años. Cinco años sufrí de artrosis y de dolores de espalda. Probé literalmente todo — pomadas, pastillas, inyecciones, fisioterapia. NADA ayudó a largo plazo. El gel Nautubone es lo único que me dio un RESULTADO REAL — me lo aplico dos veces al día y en un mes y medio mis articulaciones se sienten completamente distintas. ¡El médico no cree las radiografías!",
214: "Vilma Aguilar",
215: "Conozco a don Marcelino personalmente — hace 12 años me ayudó con una hernia discal. ¡En tres semanas estaba de nuevo de pie! Su nombre lo conoce toda la zona alrededor de San Salvador. ¡Me alegra que su hijo continúe la obra!",
216: "Gloria Recinos",
217: "Mi papá tiene 84 años y tres años no salía de la casa. Las articulaciones, la espalda, las rodillas — todo le dolía. Decía que estaba esperando irse. Después de dos meses con Nautubone — ¡ayer salió al patio y regó el jardín! ¡Por primera vez en tres años! No puedo describir lo que sentí. ¡Gracias de corazón!!!",
218: "Mirna Bonilla",
219: "¿Alguien sabe si se puede usar en caso de alergias? Reacciono a casi todo — hasta con una aspirina común se me hinchan los dedos. Tengo miedo de probar algo nuevo…",
220: "Nelson Argueta",
221: "Mirna, yo soy alérgico a cuatro tipos de medicamentos. Llevo 50 días aplicándome el gel Nautubone — ninguna irritación, ninguna hinchazón, ningún enrojecimiento. La composición es enteramente de extractos naturales — no contiene química. ¡Puede pedirlo tranquila!",
222: "Dora Interiano",
223: "Antes no tenía fuerzas ni para levantarme — cada movimiento era un sufrimiento, pensaba que mi vida se había acabado. Mi hija pidió el gel Nautubone y me hizo probarlo — me lo aplicaba mañana y noche. ¿Dos meses después? ¡¡¡Bailé en la boda de mi nieto!!! ¡Nunca en mi vida he estado tan agradecida!",
224: "Elizabeth Cardoza",
225: "Pedí para mi mamá. Tenía dolores permanentes en el cuello que le causaban mareos y náuseas — su vida se había vuelto insoportable. ¡En la segunda semana con Nautubone los dolores bajaron muchísimo y los mareos pararon por completo! Mi mamá vuelve a reírse — hacía mucho que no la veía así.",
226: "Susana Mejía",
227: "Me pregunto — si don Marcelino es tan bueno, ¿por qué estas cosas no se venden en todas partes? ¿Por qué solo en línea? ¿Por qué las farmacias no las ofrecen?",
228: "Miguel Ángel Orellana",
229: "¡Porque las farmacias ganan con la gente que compra analgésicos todos los meses! Si todos se curaran las articulaciones de una vez por todas — ¿quién les compraría sus medicamentos caros? ¡Piense con lógica!",
230: "Olga Zelaya",
231: "Leí todos los comentarios — y me emocioné. Pido ahora mismo, para mí y para mi esposo. Llevé tres envases del gel, para el tratamiento completo. Si ayuda aunque sea la mitad de lo que escribe la gente — ¡voy a ser feliz!",
232: "Lucía Bermúdez",
233: "El ortopedista me dijo que a los 63 años tengo que acostumbrarme al dolor — que supuestamente no hay cura. Pedí Nautubone a pesar de todos. ¡Vamos a ver quién tiene la razón!",
234: "Subir avatar",
235: "Subir foto",
236: "ENVIAR",
}
ATTRS_S = {
 "Вашето име": "Su nombre",
 "Вашият телефонен номер": "Su número de teléfono",
 "Вашият коментар": "Su comentario",
}
