# -*- coding: utf-8 -*-
# Турецкая адаптация лендинга травника. Форм-фактор — ГЕЛЬ (в источнике были капсулы).
# Vasile Dobre -> Hüseyin Yılmaz (Hüseyin Dede), 102, aktar, İstanbul'a yakın köy
# Andrei Dobre -> Emre Yılmaz | București -> İstanbul | lei -> TL

TR = {
0: "İstanbul yakınlarındaki köylerden 102 yaşındaki aktar Hüseyin Yılmaz, eklemlerin tamamen yenilenmesi için gereken formülü açıklıyor — Türkiye'deki her vatandaşın ulaşabileceği bir yöntem",
1: "102 YAŞINDA TÜRKİYE'NİN EN YAŞLI AKTARI VE KENDİ KUŞAĞINDAN BASTONSUZ YÜRÜYEN TEK KİŞİ. 40 YIL BOYUNCA YALNIZCA KENDİSİNE GELENLERE VERDİĞİ FORMÜLÜ İLK KEZ AÇIKLIYOR.",
2: "Yayınlandı:",
3: "“İstanbul yakınlarındaki köylerden aktar Hüseyin Dede, yaşıtlarının çoktan yürüyemez hale geldiği bir çağda, eklemlerini 102 yaşına kadar nasıl kusursuz durumda tutmayı başardı?”",
4: "İstanbul'a yakın bir köyde, yaşlanma hakkında bildiğimiz her şeyi çürüten bir adam yaşıyor. 102 yaşındaki aktar Hüseyin Yılmaz her sabah köyün üstündeki patikalarda yürüyor, merdivenleri yardımsız çıkıyor ve hayatı boyunca hiç baston kullanmadı. Yaşıtları çoktan hayatta değil ya da tekerlekli sandalyeye bağlı — o ise hâlâ tek başına bitki toplamak için tepeye tırmanıyor.",
5: "Geçen yıla kadar Hüseyin Dede insanları kendi evinde, onlarca yıldır bitki kuruttuğu o eski odada kabul ediyordu. Bitkilerle 70 yılı aşkın çalışma, 40.000'den fazla insan, doktorların gözden çıkardığı onlarca omurga ve diz yeniden hayata döndürüldü. Altı aylık bir bekleme listesi vardı — insanlar onu görmek için ülkenin dört bir yanından geliyordu.",
6: "Ama asıl sır ona gelenler değil. Asıl sır kendisi. 102 yaşında — ne artrit, ne artroz, ne de disk fıtığı. Eklemlerinin röntgenleri 45 yaşında bir erkeğinki gibi görünüyor. Onu muayene eden doktorlar gözlerine inanamıyor.",
7: "Tarifini onlarca yıl gizli tuttu — kendi odasında kendisi hazırladı ve hiçbir zaman açıklamadı. Ama bugün, sağlığı artık insanları bizzat kabul etmesine izin vermediğinde, Hüseyin Dede her şeyi değiştiren bir karar verdi: formülünü Türkiye'deki her vatandaşın ulaşabileceği hale getirmek.",
8: "Hüseyin Dede Yılmaz: “Hayatım boyunca insanların vaktinden önce yaşlanmasını izledim — bedenleri zayıf olduğu için değil, kendi yenilenme mekanizmalarını nasıl harekete geçireceklerini kimse onlara söylemediği için. 102 yaşında ben şunun canlı kanıtıyım:",
9: "eklemler, onları inşa eden hücreleri nasıl “uyandıracağınızı” bilirseniz, ileri yaşlara kadar sağlıklı kalabilir.",
10: "HEDEFİM HER ZAMAN TEK BİR ŞEYDİ — BEDENE, TIPKI GENÇLİKTEKİ GİBİ YENİ KIKIRDAK VE KEMİK DOKUSU ÜRETMESİ İÇİN YARDIM ETMEK. ŞİMDİ OĞLUM EMRE BÜTÜN BUNLARI BİR ÜRÜNE DÖNÜŞTÜRDÜ",
11: "VE BU ÜRÜN TÜRKİYE'DEKİ HER EVE ULAŞABİLİR.",
13: "Emre Yılmaz — aktarın oğlu — babasının kurutulmuş bitkileri ve terazileri arasında büyüdü ve mesleği daha çocukken öğrendi. Doktor olmadı. Yıllarca babasını, tarifin tek bir evde kapalı kalmaması gerektiğine ikna etmeye çalıştı; sonra kendisi bir laboratuvar ve Hüseyin Dede'nin onlarca yıllık deneyimini herkesin ulaşabileceği bir ürüne dönüştürmeye yardım eden insanlar buldu — ihtiyacı olan herkese ulaşsın diye.",
14: "Bu iş birliğinin sonucu bütün beklentileri aştı. Ama size üründen bahsetmeden önce, eklem tedavisi hakkında bildiğiniz her şeyin neden büyük olasılıkla yanlış olduğuna bakalım.",
15: "Bütün Türkiye'nin inandığı yalan:",
16: "“Ağrı kesiciler eklemleri iyileştirir” — YANLIŞ, onları daha da hızlı yok ediyorlar!",
17: "Hüseyin Dede Yılmaz:",
18: "— Yetmiş yıldır insanları tedavi ediyorum ve size eczanelerin asla kabul etmeyeceği bir şey söyleyeceğim: tıp tarihinde hiçbir ağrı kesici bir milimetre bile kıkırdak yenilemedi. Hiçbiri! Ağrıyı bastırırlar, ama bu sırada kıkırdak parçalanmaya devam eder — sadece siz artık hissetmezsiniz. Ve yeniden hissettiğinizde, çok geç olacak.",
19: "Ama en kötüsü bu değil. En kötüsü, bu kimyasal maddelerin iç organlarınıza yaptığı şey. 70 yıllık çalışmamda karaciğeri ve böbrekleri tamamen harap olmuş yüzlerce insan gördüm — hastalıktan değil, ilaçlardan! Beden, onlarca yıl kimyasal yutmak için yaratılmadı. Ama geleneksel tıbbın “reçete ettiği” tam olarak bu.",
20: "Omurga özellikle savunmasızdır. Omurlar arası diskler kendi kan dolaşımına sahip değildir — difüzyonla beslenirler, bu da hasarlarının sessizce, ağrısız, bazen yıllarca sürdüğü anlamına gelir. Ağrı nihayet ortaya çıktığında, hasar çoktan ilerlemiştir. Disk fıtığının sinire yaptığı baskı hayatı kâbusa çevirir: bacakta hafif bir uyuşmayla başlar ve hareket kabiliyetinin tamamen kaybıyla biter.",
21: "Bu röntgenin ne gösterdiğine bakın. Yalnızca 39 yaşında bir kadın, öğretmen — omurgası ise 20 yıl önce ancak 70 yaşındaki insanlarda gördüğüm durumda. Günde 8 saat sandalyede oturmak, hareketsizlik ve kendi bedenini hiç tanımamak — modern yaşam biçiminin getirdiği şey işte bu.",
22: "Hüseyin Dede'nin onlarca yıldır sakladığı arşivden bir görüntü: Konyalı 39 yaşındaki bir öğretmenin omurgası. “Belde hafif bir yorgunlukla” geldi — röntgen üç hasarlı disk, başlangıç aşamasında bir fıtık ve kıkırdak zarında mikro çatlaklar ortaya çıkardı.",
23: "40 yaşından sonra eklemlerinizde ağrı, tutukluk veya çıtırtı hissediyorsanız — kıkırdağınız çoktan parçalanıyor demektir. Bu “yorgunluktan” değildir ve “normal” değildir.",
24: "Omurgada süreç birkaç kat daha hızlı ve daha sinsidir — ağrı ancak hasar kritik hale geldiğinde ortaya çıkar!",
25: "Hüseyin Dede Yılmaz:",
26: "— Tamamen açık olmak istiyorum. Aylarca erteleyen insanlar tanıyorum. Sonuç? Bir daha asla normal çalışmayan sıkışmış bir sinir. Sinir çoktan ölmüşken diskleri yenilemek işe yaramaz —",
27: "DİSK GERİ GELEBİLİR, AMA SİNİR — GELMEZ!",
28: "Peki geriye ne kalır? BASTON, TEKERLEKLİ SANDALYE VE ÖMÜR BOYU BAŞKASININ YARDIMINA BAĞIMLILIK!",
29: "Peki modern cerrahi ne sunuyor? Metal implantlarla yapılan pahalı ve riskli ameliyatlar. Omurga ameliyatından sonra kendini öncesinden DAHA KÖTÜ hisseden yüzlerce insanı bizzat gördüm.",
30: "ENFEKSİYONLAR, BAŞARISIZ KAYNAMALAR, KRONİK AĞRI VE SONUNDA — YENİ BİR AMELİYAT. BAZEN DE — GERİ DÖNÜŞÜ OLMAYAN HASARLAR!",
31: "Hüseyin Dede, metal vidalarla ameliyat olmuş bir adamın kendisine getirdiği bir görüntüyü gösteriyor: “Bu tipik sonuçtur — implant doğru kabul edilmemiş, çevredeki dokular iltihaplanmış ve ağrı ameliyattan öncekinden daha şiddetli. Buna benzer yüzlerce vaka gördüm.”",
32: "İstatistik acımasız: ameliyat olanların %60'ında fıtık 2–4 yıl içinde geri dönüyor. Peki bedeli? Aylarca hareketsizlik, yüz binlerce lira ve tam bir belirsizlik. Birçoğu itiraf ediyor: zamanı geri alabilselerdi, bir daha asla ameliyat masasına yatmazlardı.",
33: "Bu belirtiler kıkırdağınızın çoktan ölmekte olduğu anlamına gelir! Ve eğer 40–50 yaşın üzerindeyseniz — süreç müdahale olmadan geri döndürülemez!",
34: "— 70 yılda elimden 40.000'den fazla insan geçti ve şunu söyleyebilirim: göz ardı edilen her eklem ağrısı tekerlekli sandalyeye doğru atılmış bir adımdır. Yalnızca",
35: " yılında Türkiye'de 340.000'den fazla yeni ciddi eklem hastalığı vakası kaydedildi — bunların 62.000'i 38 ile 48 yaş arasındaki kişilerde. Bu bir yaşlılık sorunu değil. Bu bir hareketsizlik sorunu.",
36: "Bedeniniz size bu sinyallerden birini çoktan verdiyse — bir gün bile beklemeyin!",
37: "İşte daha kapıda her insana söylediğim liste:",
38: "Hareketle geçmeyen sabah tutukluğu;",
39: "Hareket sırasında çıtırtı, kütürtü veya gıcırtı;",
40: "Hava değişiminde ağrının şiddetlenmesi;",
41: "Dizleri bükerken veya uzatırken zorlanma;",
42: "Eklem çevresinde şişlik, kızarıklık veya sıcaklık;",
43: "Merdiven çıkarken veya inerken ağrı;",
44: "Kronik yorgunluk ve bacaklarda ağırlık;",
45: "Belde uyluğa veya tabana “vuran” ağrı;",
46: "Parmaklarda tutukluk veya karıncalanma;",
47: "Yürüyüşün değişmesi — topallama, dengesizlik;",
48: "10–15 dakikadan fazla ayakta duramamak;",
49: "Bu belirtilerden yalnızca ikisinde bile kendinizi tanıyorsanız — kıkırdağınız çoktan yok oluyor demektir. Omurgada ise süreç üç dört kat daha hızlıdır, çünkü omurlar arası diskler sürekli baskı altındadır.",
50: "SONUÇ: FITIK, SIKIŞMIŞ SİNİR, OMUR DEFORMASYONU, HAREKET KABİLİYETİNİN KAYBI — VE BÜTÜN BUNLAR BİRKAÇ HAFTA İÇİNDE OLABİLİR!",
51: "Ertelemeyin, çünkü bedeniniz size sonsuz şans vermez!",
52: "Aşağıdaki insanlara bakın. Her birinde, muhtemelen şu anda sizin de hissettiğiniz belirtiler vardı. Her biri “geçer” dedi. Ve her biri bugün, zamanı geri alıp hâlâ şansı varken harekete geçmek için her şeyini verirdi.",
53: "Başka bir kliniğin eski hastası, 58 yaşında, Trabzon. Üç omur 8 mm'den fazla kaymış, omurilik baskı altında. Hüseyin Dede'ye gitmeyi iki kez reddetti — nihayet geldiğinde, felce bir adım kalmıştı.",
54: "İzmir'den 61 yaşında bir kadın — kamburu bir yıldan kısa sürede 4 cm'ye ulaştı. Boyun omurları, baş artık yana dönemeyecek kadar deforme olmuş. Ağrı kesiciler 8 ay önce etki etmeyi bıraktı.",
55: "Ev hanımı, 59 yaşında, Adana. Diz eklemleri o kadar aşınmış ki kıkırdak 1 mm'nin altına inmiş. Her adım eski bir kapının gıcırtısı gibi çıkıyor. Üç ortopedist ona tek çözümün çift protez olduğunu söyledi, 280.000 liranın üzerinde.",
56: "Eski maden işçisi, 68 yaşında, Zonguldak. Sağ dizindeki kıkırdak tamamen yok olmuş, kemik dokusu nekroz aşamasına girmiş. 4 aylık erteleme ona uzvuna mal oldu — diz üstü ampütasyon ve ömür boyu tekerlekli sandalyeye bağımlılık.",
57: "Hüseyin Dede Yılmaz:",
58: "102 yaşındayım ve size kendi deneyimimden söyleyebilirim: beden HER yaşta kendini yenileyebilir — yeter ki onu NASIL harekete geçireceğinizi bilin. Hayatımı tam da buna adadım.",
59: "VE EĞER 50–60 YAŞIN ÜZERİNDEYSENİZ, BİR SANİYE BİLE BEKLEMEYİN!",
60: "Sizde hasar neredeyse kesinlikle kritik aşamaya girdi — yok oluşu durdurmanız ve yeni kıkırdak, yeni kemik ve yeni doku üretimini harekete geçirmeniz acilen gerekiyor!",
61: "Doktorların umutsuz ilan ettiği vakalar!",
62: "Ayşe Kaplan, üç hastane onu geri çevirdikten sonra 86 yaşında yeniden yardımsız yürüyor. İşte onun hikâyesi…",
63: "Eskişehirli Ayşe Kaplan ağır diz artrozundan ve çoklu disk fıtığından muzdaripti. Üç ayrı hastane onu geri çevirdi — her yerde ona aynı şeyi söylediler: “Bu yaşta artık yapılacak bir şey yok.” Kızı, İstanbul'a yakın bir köyden bir tanıdıktan tesadüfen Hüseyin Dede'yi duydu ve onu aramaya karar verdi.",
64: "“Hapiste gibi yaşıyordum — kendi evim hücreme dönüşmüştü. Tuvalete kadar gidemiyordum, bir dakikadan fazla ayakta duramıyordum, kendime çay bile yapamıyordum. Çocuklarım çalışıyordu ve her gün gelemiyorlardı. Yatıp tavana bakıyordum. Doktorlar bu yaşta ameliyatın anlamı olmadığını söylediler ve bana sadece ağrı kesici verdiler.",
65: "Kızım beni Hüseyin Dede'ye götürdüğünde, bana baktı ve hiçbir doktorun söylemediği bir şey söyledi: “Ayşe Hanım, bedeniniz savaşmayı BIRAKMADI. Sadece kimse ona yardım etmedi.” Bana kendi hazırladığı şeyi verdi ve sabırlı olmamı söyledi. Üçüncü haftada, bir buçuk yıl sonra ilk kez, yataktan KENDİ BAŞIMA KALKTIM!",
66: "Bugün, beş ay sonra, markete gidiyorum, yemek yapıyorum, hatta apartmanın önündeki çiçek tarhıyla bile ilgileniyorum. 86 yaşında! Komşular beni bahçede gördüklerinde inanamadılar. Beni bir daha göremeyeceklerini sanıyorlardı. Hüseyin Dede bana hayatımı geri verdi — ve ona teşekkür edecek kelime bulamıyorum.”",
67: "Ayşe Kaplan, 86 yaşında, Eskişehir",
68: "Bir başka olağanüstü vaka ise Kadir Aslan — Kayserili 47 yaşında bir inşaat işçisi; 20 yıllık ağır bedensel çalışmanın ardından omurgasında ciddi bir hasar oluştu ve tekerlekli sandalyeyle hareket etmek zorunda kaldı.",
69: "Kadir, Hüseyin Dede'nin yöntemini denedi ve sonuçlar kendi aile hekimini bile şoke etti.",
70: "OMURGASI YENİLENMEYE BAŞLADI, AĞRI TAMAMEN GEÇTİ VE EN İNANILMAZI —",
71: "SADECE 4 HAFTA SONRA TEKERLEKLİ SANDALYEYİ BIRAKTI!",
72: "Kadir bize anlattı:",
73: "“Yirmi yıl bina yaptım, ama kendi omurgama hiç bakmadım. Bir sabah uyandım ve belimi kıpırdatamadım. Eşim ambulans çağırdı. Teşhis — üç fıtık ve sinir kökü üzerinde baskı. Doktorlar 175.000 liralık bir ameliyat önerdiler, ama garantisiz.",
74: "Aylarca evde tekerlekli sandalyede oturdum. Çocuklarım bana üzüntüyle bakıyordu, eşim her akşam ağlıyordu. Kendimi bir yük gibi hissediyordum. Yok olmayı diledim…",
75: "İşte o zaman kayınpederim, yardım ettiği bir adamdan Hüseyin Dede'yi duydu. Aradım, röntgenleri gönderdim ve yaşlı adam şöyle dedi: “Geç değil.” Bu üç kelime bana onlarca doktordan duyduğum her şeyden daha fazla umut verdi.",
76: "Dördüncü günde artık ayakta durabiliyordum. Tam kür 80 gün sürdü. Bugün yeniden çalışıyorum — şantiyede değil, ofiste, ama YÜRÜYORUM. Çocuklarımla parkta koşuyorum. Yaşıyorum. Röntgen disklerimin %90 oranında yenilendiğini gösteriyor. Hüseyin Dede beni geri çevirmeyen tek kişi — ve bana yardım eden tek kişi.”",
77: "Hüseyin Dede'nin yardım ettiği binlerce insanın hikâyesi de aynı derecede şaşırtıcı: doktorların “ağrıya alışın” dediği insanlar yeniden yürüdü, yeniden koştu, yeniden yaşadı. Bu nasıl mümkün olabilir?",
78: "Hüseyin Dede'nin 40 yılı aşkın süredir kendi elleriyle hazırladığı formül!",
79: "“Endojen doku reaktivasyonu” yönteminin sırrı — beden nasıl kendiliğinden yeni kıkırdak, yeni kemik ve yeni bağ üretmeye başlıyor!",
80: "Hüseyin Dede Yılmaz:",
81: "— İzin verin size geleneksel tıbbın kabul etmeyi reddettiği bir şeyi açıklayayım. Her insanın bedeninde — 90 yaşındaki birinde bile — “uyuyan” yenileyici hücreler bulunur. Gençliğinizde size kolayca kıkırdak, kemik ve bağ yapan hücrelerin aynısı. Yıllar geçtikçe ölmezler — sadece “uykuya dalarlar”, çünkü beden onlara doğru sinyalleri göndermeyi bırakır.",
82: "40 yıl önce, doğal maddelerin belirli bir bileşiminin — kesin olarak belirlenmiş oranlarda — bu uyuyan hücreler için bir “kontak anahtarı” gibi çalıştığını keşfettim. Yönteme şu adı verdim:",
83: "“Endojen doku reaktivasyonu”",
84: "— çünkü yapay hiçbir şey eklemez, bedenin kendi kaynaklarını harekete geçirir. Tam da bu yüzden bende YAN ETKİ YOK, organ hasarı YOK ve bağımlılık YOK.",
85: "Kırk yıl boyunca bu yöntemi eşiğime gelen herkese uyguladım — ve her birinde aynı sonucu kaydettim: yok oluşun durması, ağrının azalması ve eklem işlevinin kademeli olarak geri gelmesi. Bana “son şans” olarak gelen yüzlerce insan, evimden kendi ayakları üzerinde ayrıldı.",
86: "Formülün kendisi karmaşık değil — ama hassasiyet her şeydir. Her bileşen tam miktarda olmalı, miligramın yüzde birine kadar. Oranlara uyulmazsa etki basitçe kaybolur. Tam da bu yüzden yöntemi onlarca yıl bizzat uyguladım — çünkü onu eczanelere emanet edemezdim.",
87: "Aktar Yılmaz'ın tarifine göre jelin bileşimi (doz başına etken maddeler):",
88: "Omega-3",
89: "keten tohumu: 4500 mg",
90: "Glukozamin sülfat",
91: "kabuklular: 1100 mg",
92: "Magnezyum sitrat",
93: "deniz yosunu: 390 mg",
94: "Gingerol",
95: "zencefil: ekstre 4200 mg",
96: "AKBA",
97: "günlük ağacı reçinesi (Boswellia): ekstre 1100 mg",
98: "Silisyum",
99: "at kuyruğu otu: ekstre 320 mg",
100: "Kurkumin",
101: "zerdeçal: ekstre 2300 mg",
102: "Bu bileşenler basit görünüyor, ama onları uygun kalitede ve doğru kaynaktan bulmak son derece zor. Çoğu eczanelerde bulunmaz ve dünyanın farklı köşelerinden getirilmesi gerekir. Evde karıştırmak ise pratikte imkânsız — çünkü dozaj 0,1 mg'a kadar tam olmalıdır.",
103: "Tam da bu yüzden karışımı onlarca yıl bizzat, her insan için ayrı ayrı hazırladım. Ama oğlum Emre bütün resmi gördü.",
104: "Emre Yılmaz, babasının 40 yıllık tarifini herkesin ulaşabileceği bir jele nasıl dönüştürdü — Nautubone",
105: "Emre Yılmaz:",
106: "— Babamın bitki odasında büyüdüm. Her gün insanların ağrıdan iki büklüm içeri girip gülümseyerek çıktığını görüyordum. 14 yaşında tarifi ezbere biliyordum. Ben doktor olmadım — mesleği ondan öğrendim. Ama yıllarca onu ikna etmeye çalıştım: baba, bu tarif tek bir evde kapalı kalamaz. Binlerce insan senin rafta tuttuğun şeyi bekliyor.",
107: "Beş yıl boyunca İstanbul'daki ve Münih'teki laboratuvarları dolaştım; sonunda babamın tarifini ciddi biçimde incelemek isteyen insanları buldum. Aldığım cevap beni hayrete düşürdü: bu bileşenlerin kesin oranlardaki birleşimi, tip II kolajen ve proteoglikan üretimini harekete geçiriyor — kıkırdağın iki ana yapı taşını. Başka bir deyişle: beden yeni kıkırdağı nasıl inşa edeceğini kelimenin tam anlamıyla “hatırlıyor”, sadece doğru sinyale ihtiyacı var.",
108: "Laboratuvarla birlikte bir yöntem geliştirdik ve ona şu adı verdik:",
109: "“Gelişmiş biyoyararlanımlı nanodifüzyon teknolojisi”",
110: "— etken maddelerin özel nanopartiküllerin içine kapatıldığı bir yöntem; bu partiküller cildin derinliklerine nüfuz ediyor ve doğrudan hasarlı eklem dokusuna ulaşıyor. Bu, sıradan jellere ve merhemlere kıyasla emilimi yaklaşık %380 artırıyor. Ürüne şu adı verdim:",
111: "Nautubone",
112: "— cilde sürülen ve tam olarak gerekli yerde etki eden bir jel. Babamın ve onun 40 yıllık emeğinin şerefine bu adı verdim.",
113: "Nautubone jeli babamın orijinal tarifindeki 7 bileşenin tamamını içeriyor, ayrıca Münih'teki laboratuvar testlerinden sonra eklediğimiz 29 ek ekstre ve vitamin. Sonuç, babamın kendi elleriyle hazırladığı şey kadar İYİ çalışan bir jel — ama Türkiye'deki her eve teslim edilebilir. Günde iki kez eklemlerinize sürün, etken maddeler cilt yoluyla doğrudan etkilenen eklemlere ulaşsın.",
114: "“Nautubone babamın mirasıdır — onun 40 yıllık deneyimi, tek bir formülün içine kapatılmış. Her bileşen, kapısına gelen her insana gösterdiği titizlikle seçildi. Bu eczaneden alınan seri üretim bir ürün değil — bu, şifaya adanmış koca bir ömrün eseri.”",
115: "Nautubone'un en inanılmaz yanı, sadece ağrıyı hafifletmemesi — yıllarla birlikte uykuya dalmış yenilenme mekanizmasını harekete geçirmesi. Jel cilde sürülür ve nanopartiküller etken maddeleri eklem dokusunun derinliklerine taşır — sıradan hapların ve iğnelerin asla ulaşamadığı yere. Bileşenler arasındaki sinerji, etkiyi ayrı ayrı kullanıma kıyasla 20 kata kadar güçlendirir.",
116: "Nautubone ile iyileşmenin dört evresi — bedeninizde adım adım neler oluyor",
117: "Hüseyin Dede Yılmaz:",
118: "— Aktar olarak geçen bütün hayatım boyunca insanların aynı dört evreden geçtiğini gözlemledim. Oğlum bunları belgeledi ve Nautubone'a yerleştirdi; böylece herkes bu evreleri evinde geçebilir.",
119: "“Endojen doku reaktivasyonunun” dört evresi:",
120: "1. Evre — Ağrının ve iltihabın durdurulması:",
121: "Jelin ilk sürülmesinden itibaren nanopartiküller etken maddeleri cilt yoluyla doğrudan hasarlı dokulara taşır ve iltihap moleküllerini bloke eder. Ağrı 24–48 saat içinde gözle görülür biçimde azalır — karaciğeri ve böbrekleri yormadan, çünkü jel cilt yoluyla hedefe yönelik emilim teknolojisi kullanır ve geleneksel karaciğer metabolizmasından geçmez.",
122: "2. Evre — Yok oluşun durdurulması:",
123: "Üçüncü ile yedinci gün arasında beden kıkırdak ve kemik dokusunu parçalamayı bırakır. Eklem sıvısının — eklemlerin doğal “yağlayıcısının” — üretimi artar. Sürtünme azalır ve hareketler kolaylaşır.",
124: "3. Evre — Yenileyici hücrelerin uyandırılması:",
125: "Bu, yöntemin kalbidir. “Uyuyan” kondrositler ve osteoblastlar biyokimyasal bir sinyal alır ve yeni kıkırdak ile kemik dokusu üretmeye başlar. Nautubone'u eşsiz kılan tam da bu evredir — başka hiçbir ürün bu mekanizmayı harekete geçirmez.",
126: "4. Evre — Kalıcı koruyucu bariyer:",
127: "30–60 gün sonra yeni oluşan dokular sağlam bir koruyucu tabaka oluşturur; bu da eklemleri zorlanmaya karşı bile dayanıklı kılar. Hüseyin Dede buna “eklem bağışıklığı” diyor — bir kez elde edildiğinde etkisi yıllarca sürer.",
128: "Bu evrelerin her biri, tek bir insanın 40 yıllık deneyiminin ve 5 yıllık laboratuvar testlerinin sonucudur. Nautubone ağrının hızlıca “örtülmesini” sunmaz — derin, biyolojik bir yenilenme süreci başlatır ve eklemleri onlarca yıl önceki durumlarına geri döndürür.",
129: "Tıp camiasını şaşırtan sonuçlar — 38 ile 89 yaş arasındaki 2.340 kişinin izlenmesi",
130: "Emre Yılmaz:",
131: "— Laboratuvar testlerinin ilk sonuçlarını yayımladığımızda tepki yıldırım hızında oldu. İstanbul, Berlin ve Viyana'daki üniversite klinikleri kendi araştırmalarını yürütmek istediklerini bildirdi. Gerçek insanlardaki sonuçlar beklentilerimizi bile aştı — mevcut tedavi yöntemlerinin hiçbiri bu göstergelere yaklaşamıyor.",
132: "Eklem protezi takılmak üzere sıraya girmiş insanlar ameliyatlarını iptal etti. Aylarca yataktan kalkamayan insanlar yeniden yürümeye başladı. Ortopedistler kendi röntgenlerine inanamadı.",
133: "38 ile 89 yaş arasındaki 2.340 kişide “Nautubone” izleme sonuçları",
134: "Ağrının ve iltihabın tamamen giderilmesi",
136: "Tam hareket açıklığının geri kazanılması",
138: "Tendinit, bursit, periartrit",
140: "Dejeneratif değişimlerin durdurulması ve gerilemesi",
142: "Sinovit, ligamentit",
144: "Osteoartrit (tüm evreler)",
146: "Osteoporoz",
148: "Romatoid artrit, gut",
150: "Artroz, spondiloartrit",
152: "Belgelenmiş kıkırdak doku yenilenmesi",
154: "“Nautubone” ile kesin iyileşme süreleri:",
155: "Avrupa'daki diğer bilim ekipleri formülümüzü yeniden üretmeye çalışıyor, ama şimdiye kadarki sonuçlar bizimkilerden çok uzak. Laboratuvarımızla birlikte geliştirilen gelişmiş biyoyararlanımlı nanodifüzyon teknolojisi hâlâ taklit edilemiyor — jelin bileşenleri cilt yoluyla doğrudan ekleme ulaştırmasını, merhemler gibi cildin yüzeyinde kalmak yerine, tam da bu sağlıyor.",
156: "Tam iyileşme ne kadar sürer? Hüseyin Dede 70 yıllık deneyimine dayanarak açıklıyor",
157: "Hüseyin Dede Yılmaz:",
158: "— Önerdiğim asgari kür 30 gündür. Daha ağır hasarlarda — 60, bazen de 90 gün. Ama bütün kariyerim boyunca yöntemin sonuç vermediği TEK BİR VAKAM OLMADI. Bir tane bile. Üstelik 85, 90, hatta 94 yaşındaki insanları tedavi ettim.",
159: "Nautubone sadece ağrıyı durdurmaz — derin biyolojik bir yenilenme süreci başlatır. Jeli günde iki kez sürün ve daha ilk saatlerde rahatlama hissedin. Bir hafta içinde daha kolay hareket ettiğinizi fark edeceksiniz. Tam kürden sonra ise eklemleriniz 20–30 yıl önceki durumlarında olacak.",
160: "Ama en değerlisi başka bir şey: etki KALICIDIR. Bir kez “uyandırılan” yenileyici hücreler yıllarca çalışmaya devam eder!",
161: "“Nautubone” sayesinde Türkiye'de 48.000'den fazla insan hareket kabiliyetini geri kazandı. İşte Hüseyin Dede'nin yardım ettiklerinden yalnızca küçük bir bölümü:",
162: "Emekli, 66 yaşında, Samsun. Dört kaymış omur ve kronik radikülopati. Oğlu ona Nautubone jelini İstanbul'dan getiriyordu. İki ay sürme — omurganın normal konumuna tam olarak dönmesi. Ortopedisti ürünün adını sordu.",
163: "Muhasebeci, 41 yaşında, Denizli. İki gebelik ve kilo alımından sonra dizleri içe doğru deforme olmuştu. Ortopedist ona “alışın” dedi. Nautubone jeliyle — 30 gün sürme, günde iki kez — diz ekseni röntgende gözle görülür biçimde düzeldi.",
164: "Emekli, 73 yaşında, Malatya. Artroz ayak parmaklarını hiçbir ayakkabıyı giyemeyecek kadar deforme etmişti. Nautubone jelini her gün sürdü — 21 günde parmaklar düzeldi ve 5 yıl önceki ayakkabıları ona yeniden oldu.",
165: "Hüseyin Dede Yılmaz:",
166: "— Bu fotoğraflar mucize değil — doğa ve sabır. Bu insanların her biri, doktorların imkânsız dediği bir şeyi geri aldı: sağlıklı eklemler ve ağrısız bir hayat. Nautubone AKTAR OLARAK GEÇEN BÜTÜN HAYATIMIN TACIDIR — VE GELECEK KUŞAKLARA BIRAKTIĞIM MİRASTIR!",
167: "Hüseyin Dede neden artık insan kabul etmiyor — ve Nautubone onun tarifine ulaşmanın tek yolu nasıl oldu",
168: "“Sağlığım artık hastaları bizzat kabul etmeme izin vermiyor. Ama formülüm iyileştirmeye devam edecek — oğlumun elleriyle.”",
169: "Hüseyin Dede Yılmaz:",
170: "— Geçen yıl hayatımın en zor kararını verdim: artık insan kabul etmemek. Bekleme listesinde 2.000'den fazla isim vardı — ve onları yardımsız bırakamazdım. Bu yüzden oğlum Emre'ye tarifi, herkes için üretilecek yere götürmesine izin verdim. Şimdi içim rahat — Nautubone, bana gelen insanlara verdiğim şeyin tam olarak kendisi, sadece kullanışlı bir biçimde. Tarif emin ellerde.",
171: "Emre Yılmaz:",
172: "— Nautubone eczanelerde satılmıyor — üretim süreci karmaşık ve miktarlar sınırlı. Yalnızca çevrimiçi program aracılığıyla, yılda iki kez temin edilebiliyor. Ama program kapsamında indirimler şuna kadar çıkıyor:",
174: " — çünkü amacımız kâr değil, erişilebilirlik. Özellikle emekliler için; babam onlara en yüksek indirimin verilmesinde ısrar etti.",
175: "Kaydolmak için aşağıdaki resmî sipariş formunu kullanın — form doğrudan Emre Yılmaz'ın üretim ekibinden geliyor.",
176: "Bu yılın son fırsatını kaçırmayın — Nautubone program bitmeden tükenebilir!",
177: "Emre Yılmaz:",
178: "— Bu yıl Türkiye'deki insanlar için özel olarak 5&nbsp;000 paket Nautubone jeli üretmeyi başardık. Ancak talep göz önüne alındığında — ki bu talep muazzam — bu miktarlar hızla tükenecek. Bir sonraki parti ancak",
180: " yılının sonunda hazır olacak.",
181: "Destek programı şu tarihe kadar geçerli:",
182: "— Türkiye'de yaşayan 40 yaş üstü herkes",
183: "%50'ye varan indirim",
184: " alabilir. Bu tarihten sonra yeni bir fırsat için en az 6 ay beklemeniz gerekecek.",
185: "Ertelemeyin. Babam insanlara hep şunu söylerdi: “Eklemler sizi beklemez — her saniye yok oluyorlar.” Program devam ederken bundan yararlanın. Nautubone'un birikimli etkisi vardır — tek bir tam kür 5–6 yıllık sağlıklı eklemler için yeterlidir.",
186: "Formda adınızı ve telefon numaranızı yazmanız yeterli. Bir danışman sizi arayacak, durumunuza özel bir program hazırlayacak ve Türkiye'nin herhangi bir adresine teslimatı düzenleyecek — 2–3 gün içinde, posta veya kurye ile kapınıza kadar.",
187: "Herkese sağlık diliyorum! Yarın yürüyebilmek için bugün eklemlerinize sahip çıkın! Saygılarımla: Hüseyin Yılmaz ve oğlu Emre.",
188: "Güncellendi:",
190: "Son derece yüksek talep nedeniyle Nautubone stokları programın planlanan bitiminden önce tükenebilir! Bugün —",
191: "18.12.2025 — indirimli sipariş için son gün",
192: "veya stoklar tükenene kadar.",
193: "Dikkat! Sayfayı kapatmayın ve yenilemeyin — sizin için ayrılan Nautubone jeli bekleme listesindeki bir sonraki kişiye verilecek!",
194: "Programdaki ayrılmış yeriniz:",
195: "No.",
197: "Resmî sipariş formu",
198: "No.",
202: "Tam",
203: "%50 indirim",
204: " elde etmek için adınızı ve telefon numaranızı aşağıdaki alanlara girin ve “SİPARİŞ VER” düğmesine basın.",
205: "Kalan stok:",
208: "1.980 TL",
209: "990 TL",
210: "Ad Soyad",
211: "Telefon numarası",
212: "SİPARİŞ VER",
213: "✔️ Türkiye'nin her adresine 2–3 günde teslimat",
214: "posta veya kurye ile kapınıza kadar",
215: "YORUMLAR:",
216: "Gülten Şahin",
217: "Bu yazıyı aylardır bekliyordum! İstanbul'dan bir arkadaşım birkaç yıl önce bizzat Hüseyin Dede'ye gitmişti — insanın harikası diyordu. Artık kimseyi kabul etmemesi çok yazık, ama Nautubone'da aynı tarif varsa — hemen sipariş ediyorum. İndirimi yakaladığıma sevindim!",
218: "Sevgi Aydın",
219: "Kurye çarşamba günü getirdi. On gündür jeli sabah akşam sürüyorum — ve fark ÇOK BÜYÜK! O korkunç çıtırtı olmadan kalkıyorum! Eşim bakıyor ve inanamıyor. 60 günlük tam kürü tamamlayacağım, ama işe yaradığına şimdiden ikna oldum.",
220: "Fatma Öztürk",
221: "72 yaşındayım ve üç yıl kalça ağrısı çektim. Yürümek işkenceydi. Ortopedist “protez ya da katlanacaksınız” dedi. İkisini de istemiyordum. Nautubone iki ayda bana yardım etti — şimdi her gün bir buçuk kilometre yürüyorum! Röntgen ise doktorumun açıklayamadığı bir iyileşme gösteriyor. Teşekkürler Hüseyin Dede, oğluna da!",
222: "Serdar Koç",
223: "Eski bir sporcu olarak kıkırdağı yok olmuş halde yaşamanın ne demek olduğunu bilirim. Dizlerim 90 yaşında bir adamınki gibiydi — oysa daha 54 yaşındayım. Nautubone bana 10 yıldır yapamadığım hareketleri geri kazandırdı. Yeniden çömelebiliyorum! Bunu başaran başka bir ürün bilmiyorum.",
224: "Nurten Çelik",
225: "Biraz endişeliyim… Değer mi? 66 yaşındayım, her harekette eklemlerim çıtırdıyor ve sırtım rahat vermiyor. Ama türlü türlü “mucizevi” ilaçtan o kadar çok hayal kırıklığına uğradım ki artık inanmakta zorlanıyorum. Gerçekten yardımcı oluyor mu?",
226: "Bülent Kara",
227: "Nurten Hanım, şüphelerinizi çok iyi anlıyorum — bende de vardı. Ama Nautubone şimdiye kadar denediğim her şeyden farklı. Dizlerim ve belim için 5 haftadır kullanıyorum — ve size şunu söyleyebilirim, aradaki fark gece ile gündüz gibi.",
228: "Eskiden ayakkabımın bağını bağlamak için eğilemiyordum. Şimdi bunu düşünmeden yapıyorum. Hiç değilse bir paket sipariş edin ve kendiniz karar verin — kaybedecek bir şeyiniz yok!",
229: "Gülay Polat",
230: "Jeli sürmeye başladıktan üç gün sonra dizimdeki ağrı yarı yarıya azaldı! Şimdi 12. gün ve merdivenleri korkuluğa tutunmadan çıkıyorum. Tam kürü tamamlayacağım — iki ay sonra yeni gibi olacağıma inanıyorum!",
231: "Zeynep Arslan",
232: "Sırtımda iki aydır bir “kambur” büyümeye başlamıştı. Dehşete kapıldım! Eczaneden türlü türlü merhem denedim — hiçbir şey olmadı. Ama Nautubone jeli bambaşka bir şey — 40 günde kambur neredeyse tamamen kayboldu! Sürmeye devam ediyorum, ama şimdiden inanılmaz memnunum. İşte fark böyle görünüyor:",
233: "Perihan Doğan",
234: "Belimde sıkışmış bir sinir vardı — ağrıdan ne uyuyabiliyor ne ayakta durabiliyordum. Doktor bana güçlü ağrı kesiciler yazdı, onlardan da sürekli midem bulanıyordu. Nautubone jelini günde iki kez sürmeye başladım — bir hafta sonra ağrı birden azaldı, bir ay sonra ise — tamamen geçti! Küre devam ediyorum, ama hayatım şimdiden değişti!",
235: "Mehmet Balcı",
236: "79 yaşındayım ve üç yıldır zar zor yürüyordum. Oğlum Nautubone sipariş etti — bana sormadan, çünkü reddedeceğimi biliyordu. Jeli her sabah ve her akşam bana sürüyor. Peki sonuç? Bir buçuk ay sonra her gün parka kadar yürüyorum! Kendimi 60 yaşında hissediyorum! Teşekkürler Hüseyin Dede — 102 yaşında bugünün bütün doktorlarından daha bilgesin!",
237: "Tuncay Sezer",
238: "Nautubone'dan önce kollarımı başımın üstüne kaldıramıyordum — omzum çıtırdıyor ve korkunç ağrıyordu. İki yıl doktor doktor dolaştım — kimse yardım edemedi. Nautubone ile iki ay ve kollarım yeniden normal çalışıyor. İşte röntgenim — doktorun kendisi bile inanamadı:",
239: "Hatice Yavuz",
240: "Kayınvalidem için sipariş ettim — 81 yaşında ve neredeyse yataktan kalkamıyordu. Doktorlar hiçbir şey yapmayı reddediyordu — “bu yaşta artık hiçbir şey fayda etmez” diyorlardı. Nautubone ile 2 ayda bahçede yürüyor, hatta yemek bile yapıyor! İnanamadık.",
241: "Erdal Kurt",
242: "Eşim dört ay yatakta yattı — omurgası basitçe pes etti. Doktorlar hiçbir garanti vermeden 140.000 liralık bir ameliyat önerdiler. Nautubone jelini denemeye karar verdik — kaybedecek bir şeyimiz yoktu. Ona günde iki kez sürdüm. 5 hafta sonra kalktı. Dün birlikte pazara gittik — yarım yıl sonra ilk kez! Mutluluktan ağladım.",
243: "Nesrin Bulut",
244: "Geçen hafta sipariş ettim, üçüncü gün elime ulaştı. Hemen jeli sürmeye başladım — ve rahatlama ikinci gün geldi! Sanki biri eklemlerimi içeriden yağlıyor gibi. İki haftadır günde iki kez sürüyorum ve tam sonucu iple çekiyorum!",
245: "Rukiye Demir",
246: "74 yaşındayım. Beş yıl artrozdan ve sırt ağrılarından muzdarip oldum. Kelimenin tam anlamıyla her şeyi denedim — merhemler, haplar, iğneler, fizik tedavi. HİÇBİRİ uzun vadede işe yaramadı. Nautubone jeli bana GERÇEK BİR SONUÇ veren tek şey — günde iki kez sürüyorum ve bir buçuk ayda eklemlerim kökten değişti. Doktor röntgenlere inanmıyor!",
247: "Vildan Acar",
248: "Hüseyin Dede'yi şahsen tanıyorum — 12 yıl önce disk fıtığımda bana yardım etti. Üç haftada yeniden ayaktaydım! Adını İstanbul çevresindeki herkes bilir. Oğlunun bu işi sürdürmesine sevindim!",
249: "Gülsüm Taş",
250: "Babam 84 yaşında ve üç yıldır evden çıkmıyordu. Eklemleri, sırtı, dizleri — her yeri ağrıyordu. Gitmeyi beklediğini söylüyordu. Nautubone ile iki ay sonra — dün bahçeye çıktı ve bahçeyi suladı! Üç yıl sonra ilk kez! Ne hissettiğimi anlatamam. Yürekten teşekkür ederim!!!",
251: "Meral Duran",
252: "Alerji durumunda kullanılabilir mi, bilen var mı? Neredeyse her şeye tepki veriyorum — sıradan bir aspirinden bile parmaklarım şişiyor. Yeni bir şey denemeye korkuyorum…",
253: "Selim Karaca",
254: "Meral Hanım, ben dört çeşit ilaca alerjiğim. Nautubone jelini 50 gündür sürüyorum — hiçbir tahriş, hiçbir şişlik, hiçbir kızarıklık yok. Bileşimi tamamen doğal ekstrelerden oluşuyor — kimyasal içermiyor. Gönül rahatlığıyla sipariş edebilirsiniz!",
255: "Dilek Şen",
256: "Eskiden kalkacak gücüm yoktu — her hareket eziyetti, hayatımın bittiğini sanıyordum. Kızım Nautubone jelini sipariş etti ve denememi sağladı — sabah akşam bana sürdü. İki ay sonra? Torunumun düğününde dans ettim!!! Hayatım boyunca hiç bu kadar minnettar olmamıştım!",
257: "Sevda Barut",
258: "Annem için sipariş ettim. Sürekli boyun ağrıları vardı, baş dönmesi ve mide bulantısı yapıyordu — hayatı çekilmez olmuştu. Nautubone ile ikinci haftada ağrılar ciddi biçimde azaldı, baş dönmeleri ise tamamen kesildi! Annem yeniden gülüyor — onu uzun zamandır böyle görmemiştim.",
259: "Sema Yücel",
260: "Merak ediyorum — Hüseyin Dede bu kadar iyiyse, bu şeyler neden her yerde satılmıyor? Neden sadece internetten? Eczaneler neden sunmuyor?",
261: "Murat Aksoy",
262: "Çünkü eczaneler her ay ağrı kesici alan insanlardan kazanıyor! Herkes eklemlerini bir kez ve temelli iyileştirseydi — pahalı ilaçlarını kim satın alırdı? Mantıklı düşünün!",
263: "Özlem Kaya",
264: "Bütün yorumları okudum — ve içim ısındı. Şimdi sipariş ediyorum, kendim ve eşim için. Tam kür için üç paket jel aldım. İnsanların yazdığının yarısı kadar bile fayda ederse — mutlu olacağım!",
265: "Leyla Turan",
266: "Ortopedist bana 63 yaşında ağrıya alışmam gerektiğini söyledi — sözde çaresi yokmuş. Her şeye rağmen Nautubone sipariş ettim. Bakalım kim haklıymış!",
268: "Avatar yükle",
269: "Fotoğraf yükle",
270: "GÖNDER",
}

RAW = {}

ATTRS = {
"Numele dumneavoastră": "Adınız",
"Numărul dumneavoastră de telefon": "Telefon numaranız",
"Comentariul dumneavoastră": "Yorumunuz",
}
