# -*- coding: utf-8 -*-
# Uruguay / yuyero (forma: GEL)
U2 = {
70: "„Veinte años levanté edificios, pero no cuidé mi propia columna. Una mañana me desperté y no pude mover la cintura. Mi esposa llamó a la ambulancia. El diagnóstico — tres hernias y compresión de la raíz nerviosa. Los médicos propusieron una operación de 190.000 pesos, pero sin garantías.",
71: "Meses enteros pasé en la casa, en silla de ruedas. Mis hijos me miraban con tristeza, mi esposa lloraba todas las noches. Me sentía una carga. Deseaba desaparecer…",
72: "Entonces mi suegro escuchó de don Aníbal por un hombre al que él había ayudado. Llamé, mandé las radiografías, y el anciano dijo: „No es tarde.“ Esas tres palabras me dieron más esperanza que todo lo que había oído de decenas de médicos.",
73: "Al cuarto día ya podía estar de pie. El tratamiento completo duró 80 días. Hoy trabajo de nuevo — no en la obra, sino en la oficina, pero CAMINO. Corro con mis hijos en el parque. Vivo. La radiografía muestra que mis discos se recuperaron en un 90%. Don Aníbal es el único que no me rechazó — y el único que me ayudó.“",
74: "Las historias de los miles de personas a quienes ha ayudado don Aníbal son igual de asombrosas: gente a la que los médicos le decían „acostúmbrese al dolor“ volvió a caminar, volvió a correr, volvió a vivir. ¿Cómo es posible algo así?",
75: "¡La fórmula que don Aníbal preparó con sus propias manos durante más de 40 años!",
76: "El secreto del método „Reactivación tisular endógena“ — ¡cómo el organismo empieza solo a producir cartílago nuevo, huesos nuevos y ligamentos nuevos!",
77: "— Permítame explicarle algo que la medicina convencional se niega a reconocer. El organismo de toda persona — incluso el de alguien de 90 años — tiene células regenerativas „dormidas“. Las mismas células que en la juventud le construían con facilidad cartílago, huesos y ligamentos. Con los años no mueren — simplemente „se duermen“, porque el organismo deja de enviarles las señales correctas.",
78: "Hace 40 años descubrí que cierta combinación de sustancias naturales — en proporciones estrictamente definidas — funciona como una „llave de encendido“ para esas células dormidas. Al método lo llamé",
79: "„Reactivación tisular endógena“",
80: "— porque no introduce nada artificial, sino que activa los recursos propios del organismo. Precisamente por eso conmigo NO hay efectos adversos, NO hay daño a los órganos y NO hay dependencia.",
81: "Durante cuatro décadas apliqué este método a cada persona que cruzó mi puerta — y en todas anoté el mismo resultado: se detiene la destrucción, baja el dolor y vuelve poco a poco la función de las articulaciones. Cientos de personas que llegaban a mi casa „como última esperanza“ salían de mi casa por su propio pie.",
82: "La fórmula en sí no es complicada — pero la precisión lo es todo. Cada ingrediente debe estar en la cantidad exacta, hasta la centésima de miligramo. Si no se respetan las proporciones, el efecto simplemente desaparece. Justamente por eso durante décadas apliqué el método personalmente — porque no podía confiárselo a las farmacias.",
83: "Composición del gel según la receta del yuyero Silveira (sustancias activas por dosis):",
84: "Omega-3",
85: "semilla de linaza: 4500 mg",
86: "Sulfato de glucosamina",
87: "crustáceos: 1100 mg",
88: "Citrato de magnesio",
89: "algas marinas: 390 mg",
90: "Gingerol",
91: "jengibre: extracto 4200 mg",
92: "AKBA",
93: "resina de incienso (Boswellia): extracto 1100 mg",
94: "Silicio",
95: "cola de caballo: extracto 320 mg",
96: "Curcumina",
97: "cúrcuma: extracto 2300 mg",
98: "Estos ingredientes parecen simples, pero conseguirlos con la calidad adecuada y de la fuente correcta es sumamente difícil. La mayoría no se encuentra en las farmacias y hay que traerlos de distintas partes del mundo. Y mezclarlos en casa es prácticamente imposible — porque la dosificación debe ser exacta hasta 0,1 mg.",
99: "Precisamente por eso durante décadas preparé la mezcla personalmente, para cada persona por separado. Pero mi hijo Martín vio el cuadro completo.",
100: "Cómo Martín Silveira convirtió la receta de 40 años de su padre en un gel al alcance de cualquiera — Nautubone",
101: "Martín Silveira:",
102: "— Crecí en el cuarto de las hierbas de mi padre. Todos los días veía cómo la gente entraba doblada por el dolor — y salía sonriendo. A los 14 años ya me sabía la receta de memoria. No me hice médico — el oficio lo aprendí de él. Pero durante años lo convencí: papá, esta receta no puede quedarse encerrada en una sola casa. Miles de personas están esperando eso que tú tienes en el estante.",
103: "Cinco años recorrí laboratorios en Montevideo y en Múnich hasta encontrar gente que quisiera estudiar en serio la fórmula de mi padre. La respuesta que recibí me entusiasmó: la combinación de estos ingredientes en proporciones exactas activa la producción de colágeno tipo II y de proteoglicanos — los dos principales elementos con los que se construye el cartílago. En otras palabras: el organismo literalmente „recuerda“ cómo construir cartílago nuevo, solo necesita la señal correcta.",
104: "Junto con el laboratorio desarrollamos un proceso al que llamamos",
105: "„Tecnología de nanodifusión con biodisponibilidad avanzada“",
106: "— un método en el que las sustancias activas se encierran en nanopartículas especiales que penetran profundamente a través de la piel y llegan directamente al tejido articular dañado. Esto aumenta la absorción cerca de un 380% en comparación con los geles y pomadas comunes. Al producto lo llamé",
107: "Nautubone",
108: "— un gel que se aplica sobre la piel y actúa exactamente donde se lo necesita. Lo nombré así en honor a mi padre y a sus 40 años de trabajo.",
109: "El gel Nautubone contiene los siete componentes de la receta original de mi padre, más 29 extractos y vitaminas adicionales que agregamos después de los estudios de laboratorio en Múnich. El resultado es un gel que funciona EXACTAMENTE IGUAL DE BIEN que lo que mi padre preparaba con sus propias manos — pero que puede llegar a cada casa del Uruguay. Usted lo aplica sobre las articulaciones dos veces al día, y las sustancias activas atraviesan la piel directo hasta las articulaciones afectadas.",
110: "„Nautubone es la herencia de mi padre — sus 40 años de experiencia, encerrados en una sola fórmula. Cada ingrediente está elegido con la misma precisión con la que él se inclinaba sobre cada persona que llegaba a su puerta. Este no es un producto masivo de farmacia — es la obra de toda una vida dedicada a sanar.“",
111: "Lo más increíble de Nautubone es que no solo alivia el dolor — activa el mecanismo de regeneración que se durmió con los años. El gel se aplica sobre la piel, y las nanopartículas llevan las sustancias activas profundo dentro del tejido articular — allí donde las pastillas y las inyecciones comunes nunca llegan. La sinergia entre los ingredientes potencia el efecto hasta 20 veces en comparación con tomarlos por separado.",
112: "Las cuatro fases de la recuperación con Nautubone — qué ocurre en su organismo paso a paso",
113: "— A lo largo de toda mi vida como yuyero vi cómo la gente atraviesa las mismas cuatro fases. Mi hijo las documentó y las incorporó en Nautubone, para que cualquiera pueda recorrerlas en casa.",
114: "Las cuatro fases de la „Reactivación tisular endógena“:",
115: "Fase 1 — Detener el dolor y la inflamación:",
116: "Desde la primera aplicación del gel, las nanopartículas llevan las sustancias activas a través de la piel directo a los tejidos dañados, bloqueando las moléculas inflamatorias. El dolor baja de forma notoria en 24 a 48 horas — sin cargar el hígado ni los riñones, porque el gel usa una tecnología de absorción dirigida a través de la piel y no pasa por el metabolismo hepático tradicional.",
117: "Fase 2 — Detener la destrucción:",
118: "Entre el tercer y el séptimo día el organismo deja de degradar el tejido cartilaginoso y óseo. Aumenta la producción de líquido sinovial — el „lubricante“ natural de las articulaciones. La fricción disminuye y los movimientos se vuelven más fáciles.",
119: "Fase 3 — Despertar a las células regenerativas:",
120: "Este es el corazón del método. Los condrocitos y osteoblastos „dormidos“ reciben una señal bioquímica y empiezan a producir cartílago nuevo y tejido óseo nuevo. Justamente esta fase hace que Nautubone sea único — ningún otro producto enciende este mecanismo.",
121: "Fase 4 — Una barrera protectora duradera:",
122: "Después de 30 a 60 días, los tejidos recién formados construyen una capa protectora firme, que vuelve a las articulaciones resistentes incluso al esfuerzo. Don Aníbal llama a esto „la inmunidad de las articulaciones“ — una vez conseguida, el efecto se mantiene por años.",
123: "Cada una de estas fases es el resultado de 40 años de experiencia de un solo hombre y de 5 años de pruebas de laboratorio. Nautubone no ofrece un „enmascaramiento“ rápido del dolor — pone en marcha un proceso biológico profundo de regeneración, que devuelve las articulaciones al estado en el que estaban hace décadas.",
124: "Resultados que sorprendieron a la comunidad médica — seguimiento de 2 340 personas de entre 38 y 89 años",
125: "— Cuando publicamos los primeros resultados de los estudios de laboratorio, la reacción fue inmediata. Clínicas universitarias de Montevideo, Berlín y Viena pidieron realizar sus propias investigaciones. Los resultados en personas reales superaron incluso nuestras expectativas — ninguno de los métodos de tratamiento existentes se acerca a estos indicadores.",
126: "Personas que estaban programadas para la colocación de una prótesis articular cancelaron sus operaciones. Personas que llevaban meses sin levantarse de la cama volvieron a caminar. Los ortopedistas no daban crédito a sus propias radiografías.",
127: "Resultados del seguimiento de „Nautubone“ en 2 340 personas de entre 38 y 89 años",
128: "Eliminación completa del dolor y la inflamación",
129: "Recuperación del rango completo de movimiento",
130: "Tendinitis, bursitis, periartritis",
131: "Detención y reversión de los cambios degenerativos",
132: "Sinovitis, ligamentitis",
133: "Osteoartritis (todos los estadios)",
134: "Osteoporosis",
135: "Artritis reumatoide, gota",
136: "Artrosis, espondiloartritis",
137: "Regeneración documentada del tejido cartilaginoso",
138: "Tiempos exactos de recuperación con „Nautubone“:",
139: "Otros equipos científicos en Europa intentan reproducir nuestra fórmula, pero los resultados hasta ahora están lejos de los nuestros. La tecnología de nanodifusión con biodisponibilidad avanzada, desarrollada junto con nuestro laboratorio, todavía no se puede replicar — es precisamente ella la que le permite al gel entregar los ingredientes directamente dentro de la articulación a través de la piel, en lugar de que simplemente se queden en la superficie de la piel.",
140: "¿Cuánto tarda la recuperación completa? Don Aníbal lo explica basándose en 70 años de experiencia",
141: "— El tratamiento mínimo que recomiendo es de 30 días. En daños más graves — 60, y a veces hasta 90 días. Pero en toda mi práctica NO HE TENIDO NI UN SOLO CASO en el que el método no diera resultado. Ni uno. Y he curado a personas de 85, de 90, incluso de 94 años.",
142: "Nautubone no solo detiene el dolor — pone en marcha un proceso de regeneración biológica profunda. Aplique el gel dos veces al día y ya en las primeras horas sentirá alivio. En el transcurso de una semana notará que se mueve con más facilidad. Y después del tratamiento completo, sus articulaciones estarán en el estado en el que estaban hace 20 o 30 años.",
143: "Pero lo más valioso es otra cosa: el efecto es DURADERO. Una vez „despertadas“, las células regenerativas siguen trabajando durante años.",
144: "Gracias a „Nautubone“, más de 10 000 personas en el Uruguay recuperaron su movilidad. Esta es solo una pequeña parte de aquellos a quienes ayudó don Aníbal:",
145: "Jubilada, 66 años, Durazno. Cuatro vértebras desplazadas y radiculopatía crónica. Su hijo le traía el gel Nautubone desde Montevideo. Dos meses de aplicación — retorno completo de la columna a su posición normal. Su ortopedista le pidió el nombre del producto.",
146: "Contadora, 41 años, Colonia. Las rodillas se le deformaron hacia adentro después de dos embarazos y del aumento de peso. El ortopedista le dijo „acostúmbrese“. Con el gel Nautubone — 30 días de aplicación, dos veces al día — el eje de las rodillas se enderezó visiblemente en la radiografía.",
147: "Jubilado, 73 años, Mercedes. La artrosis le deformó los dedos de los pies al punto de no poder ponerse ningún par de zapatos. Se aplicó el gel Nautubone todos los días — en 21 días los dedos se enderezaron, y los zapatos de hace 5 años vuelven a quedarle.",
148: "— Estas fotografías no son milagros — son naturaleza y paciencia. Cada una de estas personas recuperó algo que los médicos le habían dicho que era imposible: articulaciones sanas y una vida sin dolor. ¡Nautubone ES LA CORONA DE TODA MI VIDA COMO YUYERO — Y MI HERENCIA PARA LAS GENERACIONES QUE VIENEN!",
149: "Por qué don Aníbal ya no recibe gente — y cómo Nautubone se volvió la única manera de llegar a su receta",
150: "„La salud ya no me permite recibir enfermos en persona. Pero mi fórmula seguirá curando — a través de las manos de mi hijo.“",
151: "— El año pasado tomé la decisión más difícil de mi vida: no recibir más gente. La lista de espera tenía más de 2 000 nombres — y no podía dejarlos sin ayuda. Por eso le permití a mi hijo Martín llevar la receta allí donde la van a preparar para todos. Ahora estoy tranquilo — Nautubone es exactamente lo que yo les daba a las personas que llegaban a mi casa, solo que en una forma cómoda. La receta está en buenas manos.",
152: "— Nautubone no se vende en farmacias — el proceso de producción es complejo y las cantidades son limitadas. Está disponible únicamente a través del programa en línea, dos veces al año. Pero dentro del programa los descuentos llegan hasta el",
153: "— porque nuestro objetivo no es la ganancia, sino que esté al alcance de todos. Especialmente de los jubilados, para quienes mi padre insistió en que hubiera el descuento máximo.",
154: "Para inscribirse, use el formulario oficial de pedido que está más abajo — llega directamente del equipo de producción de Martín Silveira.",
155: "No se pierda la última oportunidad de este año — ¡Nautubone puede agotarse antes del final del programa!",
156: "— Este año logramos producir 5&nbsp;000 envases del gel Nautubone especialmente para la gente del Uruguay. Pero considerando la demanda — que es enorme — estas cantidades se van a agotar rápido. La siguiente serie estará lista recién a finales de",
157: "El programa de apoyo está activo hasta el",
158: "— todo habitante del Uruguay mayor de 40 años puede recibir",
159: "hasta 50% de descuento",
160: ". Después de esa fecha tendrá que esperar por lo menos 6 meses para una nueva oportunidad.",
161: "No lo deje para después. Mi padre siempre les decía a las personas: „Las articulaciones no lo esperan — se están destruyendo a cada segundo.“ Mientras el programa esté activo, aprovéchelo. Nautubone tiene un efecto acumulativo — un solo tratamiento completo alcanza para 5 o 6 años de articulaciones sanas.",
162: "Simplemente escriba su nombre y su número de teléfono en el formulario. Un asesor lo llamará, armará un programa individual para su caso y organizará la entrega a cualquier dirección del Uruguay — en 2 a 3 días, por correo o con mensajero hasta su puerta.",
163: "¡Les deseo salud a todos! ¡Cuide hoy sus articulaciones, para caminar mañana! Con respeto: Aníbal Silveira y su hijo Andrés.",
164: "Actualizado:",
}
